### ISSUE TITLE
Node with `critical-components-not-ready` pod will be reported as `NodesScalingDown` in `EveryNodeReady` condition

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#10227]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
While trying to fix https://github.com/gardener/gardener/issues/10171 the message
```
condition type EveryNodeReady is not true yet, had message too many worker nodes are registered. Exceeding maximum desired machine count (4/3) with reason NodesScalingDown
```
was making me assume that there was a problem with the scaling down logic. But after deeper digging it was an error in a node-critical `apiserver-proxy` pod.

**What you expected to happen**:
The condition to be false with reason `NodesScalingUp`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a local shoot cluster with 1 machine
2. Deploy this to the shoot:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: busybox
  template:
    metadata:
      labels:
        name: busybox
        node.gardener.cloud/critical-component: "true"
    spec:
      tolerations:
      - key: node.gardener.cloud/critical-components-not-ready
        operator: Exists
        effect: NoSchedule
      containers:
      - name: busybox
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "exit 1" ]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - <shoot_node_name>
```

3. Update `.spec.kubernetes.version`
4. State of machines and nodes:
```
$ k get machine -A
NAMESPACE             NAME                                    STATUS    AGE     NODE
shoot--local--local   shoot--local--local-local-78c8b-lh2cc   Pending   5m34s   machine-shoot--local--local-local-78c8b-lh2cc
shoot--local--local   shoot--local--local-local-79987-w6bjj   Running   20m     machine-shoot--local--local-local-79987-w6bjj

$ k get nodes
NAME                                            STATUS   ROLES    AGE     VERSION
machine-shoot--local--local-local-78c8b-lh2cc   Ready    <none>   5m57s   v1.30.0
machine-shoot--local--local-local-79987-w6bjj   Ready    <none>   21m     v1.29.0

$ k get nodes machine-shoot--local--local-local-78c8b-lh2cc -o yaml | yq '.spec'
podCIDR: 10.3.1.0/24
podCIDRs:
  - 10.3.1.0/24
taints:
  - effect: NoSchedule
    key: node.gardener.cloud/critical-components-not-ready
```

Observe `EveryNodeReady `
```
$ k -n garden-local get shoot local -o yaml | yq '.status.conditions[3]'
lastTransitionTime: "2024-07-30T07:01:55Z"
lastUpdateTime: "2024-07-30T06:56:54Z"
message: too many worker nodes are registered. Exceeding maximum desired machine count (2/1)
reason: NodesScalingDown
status: "False"
type: EveryNodeReady
```

**Anything else we need to know?**:
Expected result:
```
$ k -n garden-local get shoot local -o yaml | yq '.status.conditions[3]'
lastTransitionTime: "2024-07-30T15:01:29Z"
lastUpdateTime: "2024-07-30T15:01:59Z"
message: 1 machine is provisioning and should join the cluster soon
reason: NodesScalingUp
status: Progressing
type: EveryNodeReady
```

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
