### ISSUE TITLE
Provide proper defaulting for `ManagedSeed`,s `gardenlet.config.seedConfig.spec.ingress.controller.kind`

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener#10396]
**How to categorize this issue?**

/area quality
/kind enhancement

**What would you like to be added**:
According to the documentation for [managed seeds](https://github.com/gardener/gardener/blob/master/docs/operations/managed_seed.md):
"You can omit practically everything from the gardenlet section, including all or most of the Seed spec fields. Proper defaults will be supplied in all cases, based either on the most common use cases or the information already available in the Shoot resource."
And when using the [example resource](https://github.com/gardener/gardener/blob/master/docs/operations/managed_seed.md#deploying-gardenlet-to-the-shoot) in a local kind cluster:
```
$ echo "
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: my-managed-seed
  namespace: garden
spec:
  shoot:
    name: local
  gardenlet: {}
" | kubectl apply -f -
The ManagedSeed "my-managed-seed" is invalid: spec.gardenlet.config.seedConfig.spec.ingress.controller.kind: Unsupported value: "": supported values: "nginx"
```
And the following works:
```
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: my-managed-seed
  namespace: garden
spec:
  shoot:
    name: local
  gardenlet:
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      seedConfig:
        spec:
          ingress:
            controller:
              kind: nginx
```

We can validate that the change works by checking if `k -n garden get managedseeds my-managed-seed -o yaml | yq .spec` return the same when run with and without specifying `gardenlet` configuration

**Note:** After https://github.com/gardener/gardener/issues/10349 we can even drop `gardenlet: {}` from the example

**Why is this needed**:
Consistency with documentation and easier to create managed seeds with default configurations
