### ISSUE TITLE
Nginx deprecation, first step.

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#1056]
Nginx controller is deprecated for a while. While it would no longer be deployed to end-users in the future, we must provide a escape hatch and backwards-compatible way for users to run their own Ingress controllers while keeping the `*.ingress.<shoot-name>.<project>.shoot.<domain>` as an entry point.

I would recommend the following additional field `DeployController` to be added to the Nginx ingress configuration in the Shoot specification:

```go
// NginxIngress describes configuration values for the nginx-ingress addon.
type NginxIngress struct {
	Addon `json:",inline"`
	// LoadBalancerSourceRanges is list of whitelist IP sources for NginxIngress
	// +optional
	LoadBalancerSourceRanges []string `json:"loadBalancerSourceRanges,omitempty"`
        // DeployController controls if the nginx-controller is deployed.
        // When set to "false" only the "addons-nginx-ingress-controller" Service is created.
        // Defaults to "true".
        // +optional
        DeployController *bool `json:"deployController,omitempty`
}
```
This new optional field `deployController` shall be defaulted to `true`, keeping the old behavior.
If end-user sets it to `false`, then only the `addons-nginx-ingress-controller` `Service` shall be deployed and correct NS record be created:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: addons-nginx-ingress-controller
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ingress
    component: controller
    release: addons
```

We'll change the reconciliation mode to `addonmanager.kubernetes.io/mode: EnsureExists`, allowing end-users to modify the service to their needs. 

Example - user wants to deploy Ingress controller called `foo`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: foo-ingress-controller
  template:
    metadata:
      labels:
        app: foo-ingress-controller
    spec:
      containers:
      - name: foo
        image: foo-ingress:v1
        ports:
        - containerPort: 443
```

After the controller is running, `addons-nginx-ingress-controller` is edited:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: addons-nginx-ingress-controller
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: foo-ingress-controller
```

The only down-side of this approach is that the end-user is required to run their ingress controller in the `kube-system` namespace.

Any feedback is welcomed.
