### ISSUE TITLE
GNA: Node bootstrap fails when registry config for an upstream defines a CA cert file and there is a file with imageRef from that upstream

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#10810]
**How to categorize this issue?**

/kind bug

**What happened**:
In https://github.com/gardener/gardener-extension-registry-cache/pull/245 we work on enabling TLS for the registries deployed in the Shoot cluster by the registry-cache extension.

Thanks to our e2e tests we discovered the following issue. ⬇

We have an [e2e test](https://github.com/gardener/gardener-extension-registry-cache/blob/v0.11.0/test/e2e/cache/create_enabled_delete_shoot_system_components.go) that adds caches for upstreams of Shoot system components (`europe-docker.pkg.dev`, `quay.io` and `registry.k8s.io`).

A Shoot with the a cache for upstream `europe-docker.pkg.dev` results in the following original OSC:

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: OperatingSystemConfig
metadata:
  name: gardener-node-agent-local-92b68a2635607a6f-original
  namespace: shoot--local--e2e-cache-ssc
# ...
spec:
  criConfig:
    cgroupDriver: systemd
    containerd:
      registries:
      # ...
      - hosts:
        - caCerts:
          - /etc/containerd/certs.d/ca-bundle.pem
          capabilities:
          - pull
          - resolve
          url: https://10.4.228.72:5000
        readinessProbe: true
        server: https://europe-docker.pkg.dev
        upstream: europe-docker.pkg.dev
  # ...
  files:
  # ...
  - content:
      imageRef:
        filePathInImage: /kubelet
        image: europe-docker.pkg.dev/gardener-project/releases/hyperkube:v1.31.1
    path: /opt/bin/kubelet
    permissions: 493
  # ...
  - content:
      inline:
        data: # ca-bundle.pem
        encoding: b64
    path: /etc/containerd/certs.d/ca-bundle.pem
    permissions: 420
```

In the above OSC we have:
1. A containerd registry for upstream `europe-docker.pkg.dev` with a CA cert file
2. The kubelet file that is extracted from the hyperkube image (from `europe-docker.pkg.dev`)
3. The CA cert file (`/etc/containerd/certs.d/ca-bundle.pem`)

For this OSC, GNA fails with:
```
Nov 07 07:52:30 machine-shoot--local--e2e-cache-ssc-local-c49c7-qpn4p gardener-node-agent[325]: {"level":"error","ts":"2024-11-07T07:52:30.205Z","msg":"Reconciler error","controller":"operatingsystemconfig","namespace":"kube-system","name":"gardener-node-agent-local-92b68a2635607a6f","reconcileID":"dd95843a-9c52-479b-8087-aa94d563d07a","error":"failed applying changed files: unable to copy file \"/kubelet\" from image \"europe-docker.pkg.dev/gardener-project/releases/hyperkube:v1.31.1\" to \"/opt/bin/kubelet\": error pulling image: failed to resolve reference \"europe-docker.pkg.dev/gardener-project/releases/hyperkube:v1.31.1\": unable to read CA cert \"/etc/containerd/certs.d/ca-bundle.pem\": open /etc/containerd/certs.d/ca-bundle.pem: no such file or directory","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.19.1/pkg/internal/controller/controller.go:224"}
```

In summary, GNA fails to pull the `europe-docker.pkg.dev/gardener-project/releases/hyperkube:v1.31.1` image because the `/etc/containerd/certs.d/ca-bundle.pem` does no exist.

The reason for this is in the GNA flow: https://github.com/gardener/gardener/blob/3c5d1de62eefb57fa06abef35cd318dd900c9f77/pkg/nodeagent/controller/operatingsystemconfig/reconciler.go#L97-L111

GNA:
1. First, applies containerd configuration
2. Second, applies containerd registries
3. Third, applies new or changed files

The creation of the kubelet file (which requires image pull) is before the corresponding registry CA bundle file.

A possible solution would be to apply new or changed files and then to apply containerd registries. Because a containerd registry can contain a CA cert file and the only way of providing files is adding the file to the `spec.files` field of the OSC.
Hence, it seems logical to me to first apply the new or changed files and afterwards to apply the containerd registries.

**What you expected to happen**:
GNA to do not fail in such manner.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.107.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
