### ISSUE TITLE
[Flaky Test] pull-gardener-e2e-kind-operator-seed

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#10868]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
pull-gardener-e2e-kind-operator-seed

**CI link**:
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10800/pull-gardener-e2e-kind-operator-seed/1857380861872181248
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10832/pull-gardener-e2e-kind-operator-seed/1856028741453484032
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind-operator-seed-release-v1-106/1854765804214554624
- https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/10703/pull-gardener-e2e-kind-operator-seed/1857371245184552960

**Reason for failure**:
`make operator-seed-up` fails with:
```
Starting post-deploy hooks...
⏳ Checking last operation state and conditions for garden/local...
[0;31m❌ ERROR: Last operation state not 'Succeeded' or VirtualComponentsHealthy not met for garden/local after 600 seconds.[0m
exit status 1
make[2]: *** [Makefile:404: operator-seed-up] Error 1
```

The Garden resource status:
```yaml
  status:
    conditions:
    - lastTransitionTime: "2024-11-15T11:20:59Z"
      lastUpdateTime: "2024-11-15T11:20:59Z"
      message: API server /healthz endpoint responded with success status code.
      reason: HealthzRequestSucceeded
      status: "True"
      type: VirtualGardenAPIServerAvailable
    - lastTransitionTime: "2024-11-15T11:19:54Z"
      lastUpdateTime: "2024-11-15T11:19:54Z"
      message: All runtime components are healthy.
      reason: RuntimeComponentsRunning
      status: "True"
      type: RuntimeComponentsHealthy
    - lastTransitionTime: "2024-11-15T11:25:59Z"
      lastUpdateTime: "2024-11-15T11:26:59Z"
      message: 'Deployment "virtual-garden-kube-controller-manager" is unhealthy:
        condition "Available" has invalid status False (expected True) due to MinimumReplicasUnavailable:
        Deployment does not have minimum availability.'
      reason: DeploymentUnhealthy
      status: "False"
      type: VirtualComponentsHealthy
    - lastTransitionTime: "2024-11-15T11:26:59Z"
      lastUpdateTime: "2024-11-15T11:26:59Z"
      message: 'Deployment "garden/kube-state-metrics-runtime" is progressing: there
        are still non-terminated old pods'
      reason: DeploymentProgressing
      status: Progressing
      type: ObservabilityComponentsHealthy
    gardener:
      id: 2z6GPxJkHOffN6aDbMHfJDlqZAb1DfBP8FmPF8izLys9jRfAKRPVuV9G7wCOsMK5
      name: gardener-operator-78bc6f7f49-pq8t6
      version: v1.109.0-dev
    lastOperation:
      description: Deploying Kubernetes Controller Manager
      lastUpdateTime: "2024-11-15T11:26:57Z"
      progress: 88
      state: Processing
      type: Reconcile
    observedGeneration: 2
```

From the events in the `garden` Namespace:
```
26s         Normal    EvictedByVPA                   pod/virtual-garden-kube-controller-manager-6c857bc7c7-f67cz                     Pod was evicted by VPA Updater to apply resource recommendation.

21s         Normal    Pulled                         pod/virtual-garden-kube-controller-manager-6c857bc7c7-vzwms                     Successfully pulled image "registry.k8s.io/kube-controller-manager:v1.31.1" in 1.696s (1.696s including waiting). Image size: 26221554 bytes.
21s         Normal    Started                        pod/virtual-garden-kube-controller-manager-6c857bc7c7-vzwms                     Started container kube-controller-manager
21s         Normal    Created                        pod/virtual-garden-kube-controller-manager-6c857bc7c7-vzwms                     Created container kube-controller-manager
```

The `virtual-garden-kube-controller-manager` Pod was evicted by VPA and just started.

There are in total 20 `EvictedByVPA` for Pods in the garden Namespace. This is one point for investigation and improvement.

Should we increase the timeout of the wait for the Garden resource? Currently it is set to 10mins (600s).

**Anything else we need to know**:
N/A
