### ISSUE TITLE
Forceful deletion of in-use SecretBinding and recreation of it breaks the SeedAuthorizer

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#10874]
**How to categorize this issue?**

/area quality
/area ops-productivity
/kind bug

**What happened**:
Forceful deletion of in-use SecretBinding and recreation of it breaks the SeedAuthorizer. See steps to reproduce.

**What you expected to happen**:
Either the forceful deletion (removal of the garden finalizer) to be forbidden for SecretBindings. Or the SeedAuthorizer to be able to handle this case.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Secret, SecretBinding and Shoot
2. Wait until the Shoot is successfully reconciled
3. Delete the SecretBinding. You have to remove the finalizer of the SecretBinding.
4. Recreate the SecretBinding
5. Reconcile the Shoot
6. Make sure that the reconciliation fails with:
```yaml
  lastOperation:
    description: >-
      Could not initialize a new operation for Shoot cluster: secrets
      "baz" is forbidden: User
      "gardener.cloud:system:seed:bar" cannot get resource "secrets" in
      API group "" in the namespace "garden-foo": no relationship found between
      seed 'bar' and this object Operation will be retried.
    lastUpdateTime: '2024-11-19T09:06:49Z'
    progress: 0
    state: Error
    type: Reconcile
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.108.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
