### ISSUE TITLE
Add quota for `project` resources

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardener#10878]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:
The ability to configure a quota for `project` resources.

**Why is this needed**:
Some customers use different projects for different separation purposes. The more advanced customers want to automate the `project` creation to ensure that they are uniformly setup and avoid unwanted differences due to manual creation.
Automatic creation however increases the risk of bugs that would e.g. endlessly create `projects` until ETCD is filled up.

A quota on `project` resources can help to avoid such issues.

**Comment by Kostov6** [comment]
With @tobschli and @theoddora we came up with the following possible approach:

# New `ProjectQuota` API

```yaml
kind: ProjectQuota
metadata:
  name: foo
spec:
  subject:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: foo
  limit: 10
```

- We considered using the `Garden` resource but that way users could not view the limit
- We considered using the k8s quota object but it does not seem to be a great candidate structure wise:
  - resource is namespaced
  - no clean way to add the subject
