### ISSUE TITLE
Dashboard OIDC setup fails when using `StructuredAuthentication`

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#10951]
**How to categorize this issue?**

/area security
/kind bug

**What happened**:

When configuring the `Garden` resource to use `structuredAuthentication` in `kubeAPIServer`, it's not possible to set up OIDC settings for the Gardener Dashboard. The Gardener Operator expects OIDC settings from `virtualCluster.kubernetes.kubeAPIServer.oidcConfig`, but this field is deprecated and incompatible with `structuredAuthentication`. As a result, the following validation error occurs:

```
must set .spec.virtualCluster.kubernetes.kubeAPIServer.oidcConfig when configuring OIDC config for dashboard
```

**What you expected to happen**:

I expected to configure OIDC settings for the Gardener Dashboard independently of `kubeAPIServer.oidcConfig`, especially when using `structuredAuthentication`. The Gardener Operator should allow setting up OIDC for the dashboard without requiring the deprecated `oidcConfig` field in the `kubeAPIServer`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a `Garden` resource with `structuredAuthentication` in `virtualCluster.kubernetes.kubeAPIServer`, omitting `oidcConfig`.
2. Configure the Gardener Dashboard's OIDC settings in `virtualCluster.gardener.gardenerDashboard.oidcConfig`.
3. Apply the `Garden` resource.
4. Observe the validation error stating that `.spec.virtualCluster.kubernetes.kubeAPIServer.oidcConfig` must be set.

Example `Garden` resource YAML:

```yaml
apiVersion: operator.gardener.cloud/v1alpha1
kind: Garden
metadata:
  name: local
spec:
  virtualCluster:
    kubernetes:
      kubeAPIServer:
        structuredAuthentication:
          configMapName: virtual-garden-auth-config
        # oidcConfig is omitted because it's deprecated
    gardener:
      gardenerDashboard:
        enableTokenLogin: false
        oidcConfig:
          secretRef:
            name: gardener-dashboard-oidc
          sessionLifetime: 12h
```

**Anything else we need to know?**:

The issue stems from validation logic in the Gardener Operator that requires `kubeAPIServer.oidcConfig` when OIDC is configured for the dashboard, conflicting with the deprecation of `oidcConfig` in favor of `structuredAuthentication`.

Relevant code snippets:

- **Validation forbidding `oidcConfig` when using `structuredAuthentication`**:
https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/pkg/apis/core/validation/shoot.go#L1371-L1386

- **Validation requiring `oidcConfig` for dashboard OIDC configuration**:
https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/pkg/apis/operator/v1alpha1/validation/validation.go#L410-L423

- **Operator reading OIDC settings from the deprecated `oidcConfig`** :
https://github.com/gardener/gardener/blob/e458bc02e5acbc06c736f60337efcd32b729f3bb/pkg/operator/controller/garden/garden/components.go#L1082-L1088

**Environment**:

- Gardener version: v1.108.1
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- Others: N/A
