### ISSUE TITLE
Restrict Ingress and Egress traffic by default

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/gardener#11140]
**How to categorize this issue?**

/area security
/area networking
/kind enhancement

**What would you like to be added**:
А default `NetworkPolicy` should be configured for each `Namespace` created from `Gardener` to default deny all ingress and egress traffic to the `Pods` in the `Namespace`.
``` yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  # select all pods in the namespace
  podSelector: {}
  # deny all traffic
  policyTypes:
  - Ingress
  - Egress
```

Additional `NetworkPolicy`s should also be configured to allow currently required Ingress and Egress traffic.

This issue is in sync with Diki's [Security Hardened Kubernetes Cluster Guide](https://github.com/gardener/diki/blob/main/docs/rulesets/security-hardened-k8s/ruleset.md). See rule [2000](https://github.com/gardener/diki/blob/main/docs/rulesets/security-hardened-k8s/ruleset.md#2000---ingress-and-egress-traffic-must-be-restricted-by-default) for more details.

/cc @ScheererJ Would such an enhancement be feasible? There would need to be an examination of the required traffic for all namespaces and the following maintenance of these `NetworkPolicy`s.

**Why is this needed**:
Restricting Ingress and Egress traffic by default to only the required traffic will increase security by denying unwanted traffic, which could have malicious intent.
