### ISSUE TITLE
Support to customize CoreDNS

### ISSUE THREAD

**Issue by vasu1124** [gardener/gardener#1115]
**What would you like to be added**:
We need the ability to add stub domains or change the CoreDNS configuration file without corrupting the DNS baseline of the shoot setup.

Currently any change to the CoreDNS configuration is reconciled and reset.

The Azure folks have a good extension mechanism described here:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/aks/coredns-custom.md

Maybe adding an initially empty cm "custom-coredns" and setting an [import](https://coredns.io/explugins/import/) directive in the main Configuration file is good enough (even though it could be a loophole for users to shoot themselves into the foot).

**Why is this needed**:
For Service Meshes and other applications that require internal DNS customizations.
In particular, the Istio and multi-cluster setup.

**Comment by rfranzke** [comment]
We already had a similar request in the past and we might allow customization of CoreDNS in the future (needs to be discussed how in detail that would look like/work).
As suggested by @mvladev, in the meantime, users can deploy their own CoreDNS deployment with their custom configuration. All the pods that require this custom CoreDNS can be started with a different DNS server than the default one (our CoreDNS): https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-config

**Comment by zanetworker** [comment]
@vasu1124 in the case of istio, the `istio-dns` service needs to get a pre-assigned cluster-ip and any pod that starts in an istio context needs to be assigned the `istio-dns` server ip via `dnsConfig`.

**Comment by vasu1124** [comment]
I understand it as workaround. 
@zanetworker @mvladev: Do you know if you can adjust the istio mutation controller to also inject/modify the Pod DNS configuration?
If not, then this puts the responsibility of setting the `istio-dns` link to whoever applies workloads. And that would not be satisfactory.

**Comment by mvladev** [comment]
@vasu1124  - it already does that - you can configure it as you like as you can provide an injection template:

https://github.com/istio/istio/blob/9bfe0c000ca299c338d2654844e77a074ec5e1e7/install/kubernetes/helm/istio/files/injection-template.yaml#L345-L351

**Comment by vasu1124** [comment]
@mvladev @zanetworker @rfranzke 
I tried out the workaround setup. 
What did we do?
a) adjusted istio-cordns to proxy to kubernetes-dns
```
    .:53 {
          errors
          health
          proxy global 127.0.0.1:8053 {
            protocol grpc insecure
          }
          prometheus :9153
          proxy . 100.64.0.10 <----- hard coded service ip
          cache 30
          reload
        }
```
b) adjusted the injection template to produce pods with
```
  dnsPolicy: None <----- necessary, as we can't merge with other resolver config
  dnsConfig:
    nameservers:
    - 100.65.87.98 <----- hard coded service ip of istio-coredns. chicken and egg problem!
    searches: <--- limited to 6 searches only
    - global
    - <namespace>.svc.cluster.local <---- how to inject dynamic namespace?
    - svc.cluster.local
    - cluster.local
    - ec2.internal <---- depends on platform
    options:
      - name: ndots
        value: "5"
```

These issues are making the proposed workaround unfeasible.
