### ISSUE TITLE
Allow to opt-out of automatic machine image upgrades until a forced update time

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#1117]
Currently every day in the maintenance time window, the  maintenance controller updates the shoots's image name and version to the version specified in the CloudPfrofile. This means every day there can be an update to the OsImage.

**What would you like to be added**:

- To give shoots the option to explicitly opt-out of the daily os update. Default is update os daily.

  - For Legacy shoots we assume default behaviour. 

- To set an expiration date on Os Images. When a shoot is still on this version after the expiration date, it forcefully upgrades to the latest (semver) version

- Semantic Versioning for OsIMage versions have to be mandatory. In the rare case that an OsImage has non-semVer versioning, we can still map it through the worker extensions  

- In case no explicit version is set, a new shoot will be created with the latest (semVer) version of the OsImage 

**Why is this needed**:

To give shoots planning/testing time for a specific version if they need to.

**Proposal** 

The CloudProfile resource would have a list of OsImages and versions:
```yaml
machineImages:
      - name: coreos
        version: 2023.7.0
        expirationDate: 2019-06-21T00:00:00-07:00
      - name: coreos
        version: 2023.6.0
        expirationDate: 2019-06-20T00:00:00-07:00
      - name: coreos
        version: 2023.5.0
        expirationDate: 2019-06-19T00:00:00-07:00
```
The Shoot Resource would have an additional flag similar to the auto update of kubernetes versions in the maintenance section

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      osVersion: false
```

**Scenarios**
We assume the following Cloud Profile

```yaml
machineImages:
      - name: coreos
        version: 2023.7.0
        expirationDate: 2019-06-21T00:00:00-07:00
      - name: coreos
        version: 2023.6.0
        expirationDate: 2019-06-20T00:00:00-07:00
      - name: coreos
        version: 2023.5.0
        expirationDate: 2019-06-19T00:00:00-07:00
```
**Scenario 1**
The shoot in our scenario is on version coreos-2023.5.0 on the date  2019-06-15.  The image version it is running is still valid until the 19.
The shoot specifies  autoUpdate of the Os Version ==  true (default)

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      osVersion: true
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-15  the shoots image version will be updated to 2023.7.0. This is the latest version.

**Scenario 2**

The shoot  is on version coreos-2023.5.0 on the date  2019-06-15.  The image version it is running is still valid until the 19.
The shoot specifies  autoUpdate of the Os Version ==  false (opt-out). This might be the case when the shoot still has to be tested for the new Os version ( 2023.7.0).

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      osVersion: false
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-15  the shoots image version remains the same. (Only the k8 Version will still be updated).

On the 2019-06-16 the testing of the shoot successfully completed. In the  shoot resource the OsImage version  2023.7.0 is being manually set to  2023.7.0. This triggers the reconcile.

**Scenario 3**

The shoot  is on version coreos-2023.5.0 on the date  2019-06-19.  The image version it is running expires at the same day at 00:00:00
The shoot specifies  autoUpdate of the Os Version ==  false (opt-out)

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
      osVersion: false
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-20  the shoots image version will be forcefully updated to 2023.7.0. This is the latest version.
