### ISSUE TITLE
[operator] Go Panic when utilizing new structuredAuthentication feature

### ISSUE THREAD

**Issue by benedikt-haug** [gardener/gardener#11227]
**How to categorize this issue?**

/area quality
/area dashboard
/kind bug
/kind discussion
/kind question

**What happened**:
When using structuredAuthentication with the new 1.111.0 release, the garden no longer reconciles for me:
```
...
    lastOperation:
      description: Reconciliation of Garden cluster initialized.
      lastUpdateTime: "2025-01-23T13:38:58Z"
      progress: 0
      state: Processing
      type: Reconcile
...
```

**What you expected to happen**:
I should be able to utilize the new structured authentication feature.

Is this working on your end? If yes, could you help me figure out what is wrong? The structured auth is working fine for our CAPI clusters.

**How to reproduce it (as minimally and precisely as possible)**:
The structured auth I'm testing with:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: structured-authentication
  namespace: garden
data:
  config.yaml: |
    apiVersion: apiserver.config.k8s.io/v1beta1
    kind: AuthenticationConfiguration
    jwt:
    - issuer:
        url: https://iam-staging.internal.cloud # Same as --oidc-issuer-url.
        audiences:
        - 12345678910@gardener # Same as --oidc-client-id.
        audienceMatchPolicy: MatchAny
      claimMappings:
        username:
          claim: "preferred_username"
          prefix: "ws#"
        groups:
          claim: "roles"
          prefix: "ws#"
          uid:
            claim: 'sub'
```

The relevant garden.yaml snippets:
```
...
        structuredAuthentication:
          configMapName: structured-authentication
...
        oidcConfig:
          issuerURL: https://iam-staging.internal.cloud
          clientIDPublic: 12345678910@gardener
          sessionLifetime: 12h
          additionalScopes: [ profile, offline_access, email, openid ]
          secretRef:
            name: gardener-dashboard-oidc
```

**Anything else we need to know?**:

Looking at the operator logs, it seems to run into a Go Panic:

`{"level":"error","ts":"2025-01-23T13:37:57.222Z","msg":"Observed a panic","controller":"garden","controllerGroup":"operator.gardener.cloud","controllerKind":"Garden","Garden":{"name":"dev"},"namespace":"","name":"dev","reconcileID":"afec9c67-090b-40dc-ac61-0b62c0917e32","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 358 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x3b4d930, 0xc0036a8c60}, {0x2a5e1c0, 0x564f2b0})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.31.5/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:105 +0x112\npanic({0x2a5e1c0?, 0x564f2b0?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).newGardenerDashboard(0xc0007bf208, 0xc00047ec08, {0x3b3dc30, 0xc0036ccc40}, 0x0)\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/components.go:1103 +0x4f9\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).instantiateComponents(_, {_, _}, {{_, _}, _}, _, {_, _}, 0xc003284410, ...)\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/components.go:252 +0xce5\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).reconcile(0xc0007bf208, {0x3b4d930, 0xc0036a8c60}, {{0x3b56f68?, 0xc0036a8c90?}, 0x3b4d930?}, 0xc00047ec08, {0x3b3dc30, 0xc0036ccc40}, 0xc003284410)\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/reconciler_reconcile.go:125 +0xb36\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).Reconcile(0xc0007bf208, {0x3b4d930, 0xc0036a8c60}, {{{0x0?, 0x2f251dc?}, {0xc00088c0dc?, 0x100?}}})\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/reconciler.go:115 +0x519\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0036a8bd0?, {0x3b4d930?, 0xc0036a8c60?}, {{{0x0?, 0x0?}, {0xc00088c0dc?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:116 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x3b75a40, {0x3b4d968, 0xc000846dc0}, {{{0x0, 0x0}, {0xc00088c0dc, 0x3}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:303 +0x3a5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x3b75a40, {0x3b4d968, 0xc000846dc0})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:263 +0x20e\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:224 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 154\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:220 +0x490\n","stacktrace":"runtime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:917\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).newGardenerDashboard\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/components.go:1103\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).instantiateComponents\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/components.go:252\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).reconcile\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/reconciler_reconcile.go:125\ngithub.com/gardener/gardener/pkg/operator/controller/garden/garden.(*Reconciler).Reconcile\n\t/go/src/github.com/gardener/gardener/pkg/operator/controller/garden/garden/reconciler.go:115\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:116\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:303\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.4/pkg/internal/controller/controller.go:224"}`

I think the feature came from https://github.com/gardener/gardener/pull/11080

**Environment**:

- Gardener version: v1.111.0
- Kubernetes version (use `kubectl version`): v1.31.3
- Cloud provider or hardware configuration: openstack
- Others:
