### ISSUE TITLE
Option to disable monitoring / logging stack in `operator`

### ISSUE THREAD

**Issue by tobschli** [gardener/gardener#11267]
**How to categorize this issue?**

/area quality
/kind discussion

**What would you like to be added**:

I think it should be configurable to disable or configure the monitoring / logging components, like `prometheus` and `vali` through the `Garden` resource.
An example could be:
```yaml
...
runtimeCluster:
  monitoring:
    prometheus:
      enabled: false
      replicas: 1
      storage: 40Gi
    vali:
      enabled: false
```

**Why is this needed**:

For some special use cases, like a Garden on a bare metal machine with just one node, it will not be needed to have multiple replicas of e.g. `prometheus`.
Sometimes it is not wanted to have such components deployed, so it should be possible to disable them.

What do others think about this idea?
