### ISSUE TITLE
ETCD Encryption Config: allow choosing a provider

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#11276]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
The ability to choose from different supported ETCD encryption providers ([reference](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#providers)). A good starting set would be `aescbc`, `aesgcm` (this requires automatic key rotation see https://github.com/gardener/gardener/issues/11275), `secretbox`, `kms v2`.

**Why is this needed**:
Crypto agility.

**Comment by plkokanov** [comment]
The first thought that comes to mind is to extend the `Shoot`'s `.spec.kubernetes.kubeApiServer.encryptionConfig` field to also contain the information about the key provider used. Changing this field could trigger an etcd key rotation which would take care of properly swapping the providers. 
To differentiated this from a normal etcd key rotation, the `Shoot`'s status field could also contain information about the currently used provider (similar to `status.encryptedResources`), so that the code that generates the `apiserverconfigv1.EncryptionConfiguration` knows the providers changed.

This is similar to what we did for the [Bring Your Own ETCD Encryption Key Via Key Management Systems](https://github.com/gardener-community/hackathon/blob/main/2024-12_Schelklingen/README.md#-bring-your-own-etcd-encryption-key-via-key-management-systems) topic during the gardener hackathon.

A quick suggestion for the api: 
```yaml
encryptionConfig:
  provider:
    aescbc: {}
  # aesgcm:
  #   rotation: 90d (if rotation can be supported)
  # secretbox: {}
  # kms:
  #   type: cloud-kms
  #   credentialsRef: ...
  #   providerConfig: ...
  #     apiVersion: kms.provider.extensions.gardener.cloud/v1alpha1
  #     kind: ControlPlaneEncryption
  #     key-uri: ....
  #     region: ...
```

**Comment by AleksandarSavchev** [comment]
With @plkokanov we discussed splitting the issues in parts and what to include in the first part. For the first part we should allow configuring the different local providers (aescbc|aesgcm|secretbox) for the ETCD encryption. This part can be done in 3 separate PRs:

- [x] Create new status field `.status.credentials.etcdEncryption` (similar to the [hackathon solution](https://github.com/plkokanov/gardener/blob/6276548b7cd2a24aea625e9f82641ac3d33a4206/pkg/apis/core/v1beta1/types_shoot.go#L257)) which would hold the currently encrypted resources, the used provider and config hash. https://github.com/gardener/gardener/pull/12894
- [x] Add field to set encryption provider for `Shoot` and `Garden`. https://github.com/gardener/gardener/pull/13732
- [x] Allow the configuration of local providers (aescbc|aesgcm|secretbox), leave provider type field immutable. https://github.com/gardener/gardener/pull/14034
- [x] Allow changing the provider type field (changing the field would trigger am etcd rotation key rotation)

For the `encryptionConfig` API we should choose between the one suggested in the upper comment:
``` yaml
encryptionConfig:
  resource: ...
  provider:
    aescbc: {}
  # aesgcm: {}
  # secretbox: {}
  # kms:
  #   type: cloud-kms
  #   version: v2
  #   credentialsRef: ...
  #   providerConfig: ...
  #     apiVersion: kms.provider.extensions.gardener.cloud/v1alpha1
  #     kind: ControlPlaneEncryption
  #     key-uri: ....
  #     region: ...
```
This one has the problem, where local provider currently do not have specific configurtions and would stay empty when configured. We can also take a cleaner approach with an API similar to the one [used in the hackathon](https://github.com/plkokanov/gardener/blob/6276548b7cd2a24aea625e9f82641ac3d33a4206/pkg/apis/core/v1beta1/types_shoot.go#L981-L992).
``` yaml
encryptionConfig:
  resource: ...
  provider:
    type: <aescbc|aesgcm|secretbox|kms>
    config: ...
```

There is also the question with the `Garden` API. Currently it uses 2x `encryptionConfig`, one for the standard [kube-apiserver](https://github.com/gardener/gardener/blob/3bcd2bfe088901313c97c69192d36fd68954ac22/pkg/apis/operator/v1alpha1/types_garden.go#L231) and the [gardener kube-apiserver](https://github.com/gardener/gardener/blob/3bcd2bfe088901313c97c69192d36fd68954ac22/pkg/apis/operator/v1alpha1/types_garden.go#L228). We would most likely not want to use different encryption providers for them, a validation to check if the same providers is used can be added.
