### ISSUE TITLE
One API Server LB per Seed for all Shoots

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#1135]
Replace `LoadBalancers` per Shoot kube-apiserver with SNI passthrough  proxy.

## Pros

- Greatly reduce IaaS provider costs. For example `network loadbalancer` on AWS costs at minimum 17 USD / month 
- No IaaS quota constraint.
- Support for better loadbalancing [algorithms than round-robin ](https://www.envoyproxy.io/docs/envoy/v1.10.0/intro/arch_overview/load_balancing/load_balancers#supported-load-balancers).
- Faster cluster provisioning time (no need to wait for `DNS`  and `LoadBalancer` to be provisioned) .
- Lower downtime as the proxy can be kubernetes-aware.

## Cons:

- Another component(s) to manage.
- Single point of failure (can be mitigated by running multiple different proxy instances in different namespaces with multiple `LoadBalancers`).
- https://github.com/gardener/aws-lb-readvertiser like controller must be ran next to every single cluster to reconcile `default/kubernetes` service of type `ExternalName`.

## Implementation detail:

After spending some time at possible solutions I think that the best part would be to run [Envoy proxy ](http://envoyproxy.io/) as it provides all the features we would like (no process reload being the most important one).

For Envoy configuration [Istio's Pilot](https://istio.io/docs/concepts/traffic-management/#pilot-and-envoy) could be a great as it offers a way to configure edge ingress traffic for Envoy via [Gateway](https://istio.io/docs/reference/config/networking/v1alpha3/gateway/) and [VirtualService](https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/).

A very rough architecture diagram:

```
+-------------------------------+
|                               |
|           Network LB          |
|                               |
|                               |
+-------------+-------+---------+                       +------------------+
              |       |                                 |                  |
              |       |            proxy + lb           | Shoot API Server |
              |       |    +-------------+------------->+                  |
              |       |    |                            | Cluster A        |
              |       |    |                            |                  |
              |       |    |                            +------------------+
              |       |    |
     +----------------v----+--+
     |        |               |
   +-+--------v----------+    |                         +------------------+
   |                     |    |                         |                  |
   |                     |    |       proxy + lb        | Shoot API Server |
   |    Envoy Proxy      |    +-------------+---------->+                  |
   | (ingress Gateway)   |    |                         | Cluster B        |
   |                     |    |                         |                  |
   |                     +----+                         +------------------+
   +-----+----------+----+
         ^          |
         |          |
         |          |                                   +------------------+
         |          |                                   |                  |
         |          |             proxy + lb            | Shoot API Server |
         |          +-------------------+-------------->+                  |
         |                                              | Cluster C        |
         | configure                                    |                  |
         |                                              +------------------+
         |
         |                                                  Configure
      +--+--------------+         +---------------------+   via Istio
      |                 |         |                     |   Custom Resources
      |     Pilot       +-------->+   Seed API Server   +<------------------+
      |                 |         |                     |
      |                 |         |                     |
      +-----------------+         +---------------------+
```

The resources which needs to be created per Shoot clusters are the following:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kube-apiserver-gateway
  namespace: shoot-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    tls:
      mode: PASSTHROUGH
    hosts:
    - api.<shoot>.<seed>.<domain>
    - api.internal.<shoot>.<seed>.<domain>
```

and correct `VirtualService` pointing to the correct API server:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kube-apiserver
spec:
  hosts:
  - api.<shoot>.<seed>.<domain>
  - api.internal.<shoot>.<seed>.<domain>
  gateways:
  - kube-apiserver-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - api.<shoot>.<seed>.<domain>
      - api.internal.<shoot>.<seed>.<domain>
    route:
    - destination:
        host: kube-apiserver
        port:
          number: 443
```

After this, and accessing the gateway at port `1500` we see that all instances of your API server are there:

<details>
<summary>curl http://localhost:15000/clusters click me</summary>

```
outbound|443||kube-apiserver.test.svc.cluster.local::default_priority::max_connections::1024
outbound|443||kube-apiserver.test.svc.cluster.local::default_priority::max_pending_requests::1024
outbound|443||kube-apiserver.test.svc.cluster.local::default_priority::max_requests::1024
outbound|443||kube-apiserver.test.svc.cluster.local::default_priority::max_retries::1024
outbound|443||kube-apiserver.test.svc.cluster.local::high_priority::max_connections::1024
outbound|443||kube-apiserver.test.svc.cluster.local::high_priority::max_pending_requests::1024
outbound|443||kube-apiserver.test.svc.cluster.local::high_priority::max_requests::1024
outbound|443||kube-apiserver.test.svc.cluster.local::high_priority::max_retries::3
outbound|443||kube-apiserver.test.svc.cluster.local::added_via_api::true
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::cx_active::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::cx_connect_fail::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::cx_total::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::rq_active::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::rq_error::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::rq_success::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::rq_timeout::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::rq_total::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::health_flags::healthy
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::weight::1
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::region::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::zone::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::sub_zone::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::canary::false
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.205:443::success_rate::-1
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::cx_active::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::cx_connect_fail::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::cx_total::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::rq_active::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::rq_error::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::rq_success::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::rq_timeout::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::rq_total::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::health_flags::healthy
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::weight::1
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::region::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::zone::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::sub_zone::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::canary::false
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.206:443::success_rate::-1
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::cx_active::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::cx_connect_fail::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::cx_total::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::rq_active::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::rq_error::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::rq_success::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::rq_timeout::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::rq_total::0
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::health_flags::healthy
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::weight::1
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::region::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::zone::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::sub_zone::
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::canary::false
outbound|443||kube-apiserver.test.svc.cluster.local::10.1.0.207:443::success_rate::-1
```

</details>

<details>
<summary>curl http://localhost:15000/config_dump click me</summary>

```json
{
 "configs": [
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.BootstrapConfigDump",
   "bootstrap": {
    "node": {
     "id": "router~10.1.0.213~istio-ingressgateway-5cdb6847f9-mdbkg.istio-system~istio-system.svc.cluster.local",
     "cluster": "istio-ingressgateway",
     "metadata": {
      "ISTIO_META_INSTANCE_IPS": "10.1.0.213,10.1.0.213",
      "POD_NAME": "istio-ingressgateway-5cdb6847f9-mdbkg",
      "istio": "sidecar",
      "CONFIG_NAMESPACE": "istio-system",
      "ISTIO_PROXY_VERSION": "1.1.3",
      "ISTIO_PROXY_SHA": "istio-proxy:7767d3a6fd8def76b44f5c03283ba3f2f9dd74a9",
      "ISTIO_VERSION": "1.2.0",
      "ROUTER_MODE": "sni-dnat"
     },
     "locality": {},
     "build_version": "7767d3a6fd8def76b44f5c03283ba3f2f9dd74a9/1.11.0-dev/Clean/RELEASE/BoringSSL"
    }
   },
   "last_updated": "2019-06-23T06:34:12.370Z"
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ClustersConfigDump",
   "version_info": "2019-06-23T06:34:56Z/3",
   "static_clusters": [
    {
     "cluster": {
      "name": "prometheus_stats",
      "type": "STATIC",
      "connect_timeout": "0.250s",
      "hosts": [
       {
        "socket_address": {
         "address": "127.0.0.1",
         "port_value": 15000
        }
       }
      ]
     },
     "last_updated": "2019-06-23T06:34:12.374Z"
    },
    {
     "cluster": {
      "name": "xds-grpc",
      "type": "STRICT_DNS",
      "connect_timeout": "10s",
      "hosts": [
       {
        "socket_address": {
         "address": "istio-pilot",
         "port_value": 15010
        }
       }
      ],
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 100000,
         "max_pending_requests": 100000,
         "max_requests": 100000
        },
        {
         "priority": "HIGH",
         "max_connections": 100000,
         "max_pending_requests": 100000,
         "max_requests": 100000
        }
       ]
      },
      "http2_protocol_options": {},
      "dns_refresh_rate": "300s",
      "dns_lookup_family": "V4_ONLY",
      "upstream_connection_options": {
       "tcp_keepalive": {
        "keepalive_time": 300
       }
      }
     },
     "last_updated": "2019-06-23T06:34:12.375Z"
    },
    {
     "cluster": {
      "name": "zipkin",
      "type": "STRICT_DNS",
      "connect_timeout": "1s",
      "hosts": [
       {
        "socket_address": {
         "address": "zipkin",
         "port_value": 9411
        }
       }
      ],
      "dns_refresh_rate": "300s",
      "dns_lookup_family": "V4_ONLY"
     },
     "last_updated": "2019-06-23T06:34:12.375Z"
    }
   ],
   "dynamic_active_clusters": [
    {
     "version_info": "2019-06-23T06:34:53Z/2",
     "cluster": {
      "name": "outbound_.443_._.kube-apiserver.test.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s"
       },
       "service_name": "outbound_.443_._.kube-apiserver.test.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      }
     },
     "last_updated": "2019-06-23T06:34:55.055Z"
    },
    {
     "version_info": "2019-06-23T06:34:53Z/2",
     "cluster": {
      "name": "outbound|443||kube-apiserver.test.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s"
       },
       "service_name": "outbound|443||kube-apiserver.test.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      }
     },
     "last_updated": "2019-06-23T06:34:55.051Z"
    }
   ]
  },
  {
   "@type": "type.googleapis.com/envoy.admin.v2alpha.ListenersConfigDump",
   "version_info": "2019-06-23T06:34:56Z/3",
   "dynamic_active_listeners": [
    {
     "version_info": "2019-06-23T06:34:53Z/2",
     "listener": {
      "name": "0.0.0.0_443",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 443
       }
      },
      "filter_chains": [
       {
        "filter_chain_match": {
         "server_names": [
          "api.127.0.0.1.nip.io",
          "api.internal.127.0.0.1.nip.io"
         ]
        },
        "filters": [
         {
          "name": "envoy.tcp_proxy",
          "config": {
           "cluster": "outbound|443||kube-apiserver.test.svc.cluster.local",
           "stat_prefix": "outbound|443||kube-apiserver.test.svc.cluster.local"
          }
         }
        ]
       }
      ],
      "listener_filters": [
       {
        "name": "envoy.listener.tls_inspector"
       }
      ]
     },
     "last_updated": "2019-06-23T06:34:55.168Z"
    }
   ]
  }
 ]
}
```
</details>

And client `x509` authentication works without a problem.

## Prerequisites

At this moment the master `default/kubernetes` service doesn't support services of type `ExternalName`.

- relevant issue https://github.com/kubernetes/kubernetes/issues/79280
- PR in master https://github.com/kubernetes/kubernetes/pull/79312

**Comment by marwinski** [comment]
There is one challenge: the kubelet uses the ip address and not the host name so SNI will not work here. You probably need to set a up proxies in the shoot cluster (possibly one per host) that captures the requests and redirects them to a FQDN. 

Anyway, I have closed the internal issue so this is the master issue now.

**Comment by mvladev** [comment]
> There is one challenge: the kubelet uses the ip address and not the host name so SNI will not work here. You probably need to set a up proxies in the shoot cluster (possibly one per host) that captures the requests and redirects them to a FQDN.

Where are you getting this from?

I've the following kubeconfig:

```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.M.Y.I.P.nip.io
  name: local-sni-cluster
contexts:
- context:
    cluster: local-sni-cluster
    user: local-sni-cluster
  name: local-sni-cluster
current-context: local-sni-cluster
kind: Config
preferences: {}
users:
- name: local-sni-cluster
  user:
    client-certificate-data: SOME-CERT
    client-key-data: SOME-CERT-KEY
```

And I'm running kubelet with 

```console
./kubelet \
    --kubeconfig /mnt/hgfs/kubernetes/sni-kubeconfig \
    --fail-swap-on=false \
    --register-node \
    --pod-cidr=10.10.5.0/24 \
    --hostname-override=MY-NODE-IP.nip.io \
    --container-runtime=remote \
    --container-runtime-endpoint=unix:///run/containerd/containerd.sock
```

And after that kubelet runs successfully:

```
E0624 11:46:01.966807   49351 controller.go:194] failed to get node MY-NODE-IP.nip.io" when trying to set owner ref to the node lease: nodes MY-NODE-IP.nip.io" not found
E0624 11:46:02.040823   49351 kubelet.go:2248] node MY-NODE-IP.nip.io" not found
I0624 11:46:02.040881   49351 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
I0624 11:46:02.054414   49351 kubelet.go:1822] skipping pod synchronization - container runtime status check may not have completed yet
I0624 11:46:02.056022   49351 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
I0624 11:46:02.125439   49351 cpu_manager.go:155] [cpumanager] starting with none policy
I0624 11:46:02.125460   49351 cpu_manager.go:156] [cpumanager] reconciling every 10s
I0624 11:46:02.125469   49351 policy_none.go:42] [cpumanager] none policy: Start
I0624 11:46:02.131164   49351 kubelet_node_status.go:72] Attempting to register node MY-NODE-IP.nip.io
E0624 11:46:02.146845   49351 kubelet.go:2248] node MY-NODE-IP.nip.io" not found
I0624 11:46:02.162865   49351 kubelet_node_status.go:75] Successfully registered node MY-NODE-IP.nip.io
I0624 11:46:02.166351   49351 plugin_manager.go:116] Starting Kubelet Plugin Manager
W0624 11:46:02.166763   49351 container_manager_linux.go:818] CPUAccounting not enabled for pid: 49351
W0624 11:46:02.166782   49351 container_manager_linux.go:821] MemoryAccounting not enabled for pid: 49351
W0624 11:46:02.254668   49351 pod_container_deletor.go:75] Container "162b03ec8e779f74460ed95a8abee79eb576eefd46f22e273ada50a02a60a0ae" not found in pod's containers
I0624 11:46:02.361842   49351 reconciler.go:150] Reconciler: start to sync state
```

Are you referring to https://github.com/kubernetes/kubernetes/issues/79280 ?

**Comment by vlerenc** [comment]
👍

If this works reliably (also for horizontally scaled shoot API servers), this would be a huge win for Gardener. Thank you! You can add to your pro points also that then Gardener would be "compatible" also with infrastructures with poor LBaaS implementations. We have some demand in this regard and such a solution - if we in addition/later solve also the VPN question elegantly - greatly reduces said LBaaS requirements. That is just another advantage, but the/your listed ones like cost and quota are even more important (cost always is and quota determines how far we can go with our seeds and scale-out).

**Comment by marwinski** [comment]
@mvladev, sorry the hint with the kubelet was wrong. The real problem appears to be the Kubernetes service as requests will not contain a valid api server domain name but ```kubernetes``` or ```kubernetes.default```.

**Comment by mvladev** [comment]
@marwinski have a look at https://github.com/kubernetes/kubernetes/pull/79312 
Hopefully I'll be able to backport it to other versions

**Comment by marwinski** [comment]
wow, I am impressed

**Comment by mvladev** [comment]
# In-cluster communication to the API server

Even if the master service (`kubernetes` in `default` namespace) is of type `ExternalName` and kubelet [supports](https://github.com/gardener/gardener/issues/1135#issuecomment-505317932) this configuration the problem still exists for older K8S versions where this functionality is not available.

## Workaround

SNI works only if the client sets the server name in the hello TLS handshake phase.
Due to this limitation TLS termination proxy in the Shoot cluster is required.

To make things easier, Envoy is going to be used:

```text
                                              +------------------+
                                              |                  |
                                              | Shoot API Server |
                                              |                  |
                                              | Cluster A        |
                                              |                  |
                                              +------------------+
                                                        ^
                                                        |
                                                        |
                                                        |
                                                        |
  +-----------------------------------------------------------------------+
                                                        |   Shoot Cluster
                                                        |
                                                        |
                                                        |
                                                        |
                                                        |
                                                        |
   +---------------------+                   +---------------------+
   |                     |                   |                     |
   |  Pod talking to     |                   |                     |
   |  the kubernetes     |                   |    Envoy Proxy      |
   |  service            +------------------>+  TLS termination    |
   |                     |                   |                     |
   |                     |                   |                     |
   +---------------------+                   +---------------------+
```

The configuration bellow starts Envoy, running on port `443`, terminates TLS and sends all traffic to `api.M.Y.I.P.nip.io`.

```yaml
static_resources:
  listeners:
  - name: listener_https
    address:
      socket_address:
        address: 192.168.0.1 # kubernetes service IP
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          forward_client_cert_details: APPEND_FORWARD
          set_current_client_cert_details:
            subject: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: upstream-apiserver
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: kube_apiserver
                  timeout:
                    seconds: 300
          http_filters:
          - name: envoy.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              # The filter bellow handles client x509 TLS authentication.
              # It filters and removes all headers prefixed with `X-Remote-Extra-` and uses
              # the 'x-forwarded-client-cert' header which contains the subject and cert has. e.g.
              # Hash=add402ba275bb59b9e234e3f5699bd526752a;Subject="CN=system:cluster-admin,O=system:masters
              # It gets the Subject value (which is always quoted)
              # https://www.envoyproxy.io/docs/envoy/v1.11.2/configuration/http_conn_man/headers#x-forwarded-client-cert
              # then splits the value by "," and sets the individual `X-Remote-User` and `X-Remote-Group` headers
              # if applicable
              inline_code: |
                local function starts_with(str, start)
                  return str:sub(1, #start) == start
                end
                local p = require("etc.envoy.lib.parser")

                function envoy_on_request(request_handle)
                  local headers = request_handle:headers()
                  local headersToRemove = {}
                  -- it's explicitly mentioned in the Envoy 1.11.2 docs that no modification of the headers
                  -- should be done while looping through them. We are forced to create
                  for key, value in pairs(headers) do
                    if starts_with(key, "x-remote-extra-") then
                      table.insert(headersToRemove, key)
                    end
                  end

                  for i, value in ipairs(headersToRemove) do
                    headers:remove(value)
                  end

                  headers:remove("x-remote-user")
                  headers:remove("x-remote-group")

                  local cert = headers:get("x-forwarded-client-cert")
                  if cert ~= nil then
                    local certheaders = p.parse(cert)
                    local cn = certheaders["CN"]
                    if cn ~= nil then
                      headers:replace("X-Remote-User", cn)
                    end
                    local org = certheaders["O"]
                    if org ~= nil then
                      headers:replace("X-Remote-Group", org)
                    end
                    headers:remove("x-forwarded-client-cert")
                  end
                end

                function envoy_on_response(handle) end
          - name: envoy.router
            config: {}
      tls_context:
        require_client_certificate: false
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: /etc/envoy/apiserver-proxy.pem
              private_key:
                filename: /etc/envoy/apiserver-proxy-key.pem
          validation_context:
            trusted_ca:
              filename: /etc/envoy/apiserver-ca.crt

  clusters:
  - name: kube_apiserver
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: kube_apiserver
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: api.M.Y.I.P.nip.io
                port_value: 443
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
    tls_context:
      sni: api.M.Y.I.P.nip.io
      common_tls_context:
        tls_certificates:
          - certificate_chain:
              filename: /etc/envoy/apiserver-proxy.pem
            private_key:
              filename: /etc/envoy/apiserver-proxy-key.pem

```

Code of `parser.lua`:

```lua
M = {}

--[[
  Parses a XCFF header send via envoy and returns a table with
  key the subject name and it's value. For example if you pass
  Hash=ca62b277e66008c;Subject="CN=MyCompany,O=MyOrg"
  it returns:
  t = {
    "CN": "MyCompany",
    "O":  "MyOrg"
  }
]]--
function M.parse(header)
  local t = {}

  if header == nil then return t end

  local res = string.match(header, 'Subject="([^"]+)')
  if res~= nil then
      local buffer = ""
      -- split the subject by ','
      for subject, i in string.gmatch(res, [[([^,]+)]]) do
          -- in the subjects you can have ',' but those are escaped by envoy `\,`
          -- so we must sure to concat those comas and then unescape it
          if string.sub(subject, #subject, #subject) == [[\]] then
            buffer = buffer .. string.sub(subject, 0, #subject-1) .. ","
          else
            local bs = buffer .. subject
            local i = string.find(bs, "=")
            if i ~= nil then
              t[string.sub(bs,0, i-1)] = string.sub(bs,i+1,#bs)
            end
            buffer = ""
          end
      end
  end
  return t
end

return M
```

`kube-apiserver` is configured with disabled master service controller.

To avoid chicken and egg problem (as calico/CNI might need access to the apiserver), that proxy must be ran as `Daemonset` and in the host network.
The `Daemonset` will have a sidecar container which will create a `dummy` network interface and set it's ip address to the kubernetes master service IP (`192.168.0.1`).
It'll also add additional `iptables` rules which will allow traffic to that IP and disable contrack (`kube-proxy` sets iptables rules which reject all traffic if the service has no endpoints).

The serving certificate used for this proxy must have the correct SANs:

- `kubernetes`
- `kubernetes.default`
- `kubernetes.default.svc`
- `kubernetes.default.svc.cluster`
- `kubernetes.default.svc.cluster.local`
- `192.168.0.1`

The entire flow will look like this:

- Pod talks to the IP address for the kubernetes service `192.168.0.1`
- the proxy will terminate the TLS connection and open/reuse TLS connection to the FQDN of the apiserver - `api.M.Y.I.P.nip.io`, setting the SNI string to `api.M.Y.I.P.nip.io`
- if a valid certificate is presented by the client, envoy will use it and add `X-Remote-User` and `X-Remote-Group` Headers
- istio-ingress-gateway will select the correct Shoot kube-apiserver using the SNI string

## Problems

The problem with this approach is that if a `Node` is compromised, then an attacker can access the proxy certificate and use it to make requests to the API server and impersonate users. Today if an attacker gets full access to a `Node` it can read the `Secrets` and `ConfigMaps` associated with it, which could lead to the same result if a secret for `ServiceAcccount` bound to the `cluster-admin` `ClusterRole`, is used by `Pod` on this `Node`.

<del>
One big problem with this approach is the TLS termination.
Due to this, client TLS authentication cannot work. To overcome this problem, a new custom filter should be added to envoy which reads the x509 certificate's `CN` and `CO` to set the `user` and `groups` and then send them as `X-Remote-User` and `X-Remote-Group` flags.</del>

<del>
A better alternative would be to build a stripped down version of [kube-aggregator](https://github.com/kubernetes/kube-aggregator), which only proxies the connection and sets the `X-Remote-User` and `X-Remote-Group` if TLS authentication.
</del>

## Workaround 2 reuse VPN tunnel

Another possibility would be invert the VPN tunnel. In this case the VPN (server) endpoint would be exposed on the `Seed` cluster and all `Nodes` would be a client.
Then the VPN connection can be used as a two-way tunnel.

## <del>Workaround 3 - XDP</del>

<del>
Another alternative would be to use [XDP](https://www.iovisor.org/technology/xdp) to [modify](https://github.com/torvalds/linux/blob/505a8ec7e11ae5236c4a154a1e24ef49a8349600/samples/bpf/xdp_tx_iptunnel_kern.c) the TLS client hello handshake packet.

This XDP program could be loaded on every single Node in the cluster and when a packet is send to the kube-service's IP address, it would modify the TLS client hello packet and insert sni extension.

This workaround offers the best performance solution where no additional hops are required and no security handling is needed / re-implemented.

More info

- https://github.com/xdp-project/xdp-tutorial
- https://cilium.readthedocs.io/en/v1.6/bpf/
</del>

This doesn't work due to https://github.com/gardener/gardener/issues/1135#issuecomment-531176831

/cc @zanetworker
