### ISSUE TITLE
Override OS updateStrategy per shoot resource

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#11520]
**How to categorize this issue?**

/area os ops-productivity security usability
/kind enhancement

**What would you like to be added**:
To configure OS update strategy per shoot that overrides the one set in the cloudprofile, the goal is the worker pools in the cluster get the latest supported OS version no matter the update strategy of the given OS in the CloudProfile.

**Why is this needed**:
Some shoot owners are not concerned with breaking or incompatible changes introduced with the OS major version upgrade, instead they want to always stay up-to-date with the latest supported version.

**Comment by LucaBernstein** [comment]
A good place for implementing this could be the `NamespacedCloudProfile`.
Currently, we do not allow overriding the `updateStrategy` of machine images.
We could agree on dropping this constraint.
Example could then look like this:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: NamespacedCloudProfile
metadata:
  name: early-adopter-profile
  namespace: garden-local
spec:
  parent:
    kind: CloudProfile
    name: local
  machineImages:
    - name: gardenlinux
      updateStrategy: patch
```
/cc @timuthy @voelzmo
