### ISSUE TITLE
[operator] Garden reconciliation fails if etcd backup is configured

### ISSUE THREAD

**Issue by benedikt-haug** [gardener/gardener#11531]
**How to categorize this issue?**

/area robustness
/area delivery
/area quality
/area backup
/kind bug

**What happened**:
If the garden object is created containing etcd backup configuration code (example below), the garden never reconciles:
![Image](https://github.com/user-attachments/assets/4fcd3f87-9bf8-4f79-a01b-5adfada299fd)

This is caused by the virtual-garden-etcd-main pods not working correctly:
```
garden                                 virtual-garden-etcd-main-0                                             1/2     Running     0              47m
garden                                 virtual-garden-etcd-main-1                                             1/2     Running     0              47m
garden                                 virtual-garden-etcd-main-2                                             1/2     Running     0              47m
```
```
kubectl --context oidc-wavecon-staging@garden-runtime-dev -n garden describe pods virtual-garden-etcd-main-0
...
Containers:
  etcd:
    Container ID:  containerd://9339c6944c135e43cdaa1e1c82bcd9f4382791087d991c1f1bd987d37bd3f75a
    Image:         europe-docker.pkg.dev/gardener-project/public/gardener/etcd-wrapper:v0.4.1
    Image ID:      europe-docker.pkg.dev/gardener-project/public/gardener/etcd-wrapper@sha256:2ff43ea2768786aa31cc489ec2c521bd5129dab1f166c1d3d0bd5bdbb5613937
    Ports:         2380/TCP, 2379/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      start-etcd
      --backup-restore-host-port=virtual-garden-etcd-main-local:8080
      --etcd-server-name=virtual-garden-etcd-main-local
      --backup-restore-tls-enabled=true
      --backup-restore-ca-cert-bundle-path=/var/etcdbr/ssl/ca/bundle.crt
      --etcd-client-cert-path=/var/etcd/ssl/client/tls.crt
      --etcd-client-key-path=/var/etcd/ssl/client/tls.key
    State:          Running
      Started:      Wed, 26 Feb 2025 14:16:39 +0100
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:        300m
      memory:     1G
    Readiness:    http-get https://:9095/readyz delay=15s timeout=1s period=5s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/etcd/data from main-virtual-garden-etcd (rw)
      /var/etcd/ssl/ca from etcd-ca (rw)
      /var/etcd/ssl/client from etcd-client-tls (rw)
      /var/etcd/ssl/peer/ca from etcd-peer-ca (rw)
      /var/etcd/ssl/peer/server from etcd-peer-server-tls (rw)
      /var/etcd/ssl/server from etcd-server-tls (rw)
      /var/etcdbr/ssl/ca from backup-restore-ca (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gardener (ro)
...
  Warning  Unhealthy  91s (x1276 over 101m)  kubelet  Readiness probe failed: Get "https://10.192.1.157:9095/readyz": dial tcp 10.192.1.157:9095: connect: connection refused
```

The logs of that service look like this (Deduplicated log lines in the following example for better readability):
```
kubectl logs -n garden statefulsets/virtual-garden-etcd-main --all-pods
...
[pod/virtual-garden-etcd-main-2/etcd] {"level":"info","ts":"2025-02-26T13:16:43.830Z","caller":"app/app.go:39","msg":"Initializing application","config":{"BackupRestore":{"HostPort":"virtual-garden-etcd-main-local:8080","TLSEnabled":true,"CaCertBundlePath":"/var/etcdbr/ssl/ca/bundle.crt"},"EtcdClientTLS":{"ServerName":"virtual-garden-etcd-main-local","CertPath":"/var/etcd/ssl/client/tls.crt","KeyPath":"/var/etcd/ssl/client/tls.key"}}}
...
[pod/virtual-garden-etcd-main-2/etcd] {"level":"info","ts":"2025-02-26T13:16:43.830Z","caller":"etcd-wrapper/main.go:67","msg":"Running with flags: backup-restore-ca-cert-bundle-path: /var/etcdbr/ssl/ca/bundle.crt, backup-restore-host-port: virtual-garden-etcd-main-local:8080, backup-restore-tls-enabled: true, etcd-client-cert-path: /var/etcd/ssl/client/tls.crt, etcd-client-key-path: /var/etcd/ssl/client/tls.key, etcd-ready-timeout: 0s, etcd-server-name: virtual-garden-etcd-main-local"}
[pod/virtual-garden-etcd-main-2/etcd] {"level":"info","ts":"2025-02-26T13:16:43.830Z","caller":"app/app.go:39","msg":"Initializing application","config":{"BackupRestore":{"HostPort":"virtual-garden-etcd-main-local:8080","TLSEnabled":true,"CaCertBundlePath":"/var/etcdbr/ssl/ca/bundle.crt"},"EtcdClientTLS":{"ServerName":"virtual-garden-etcd-main-local","CertPath":"/var/etcd/ssl/client/tls.crt","KeyPath":"/var/etcd/ssl/client/tls.key"}}}
...
[pod/virtual-garden-etcd-main-2/etcd] {"level":"error","ts":"2025-02-26T13:16:44.832Z","caller":"bootstrap/bootstrap.go:65","msg":"error while fetching initialization status","error":"Get \"https://virtual-garden-etcd-main-local:8080/initialization/status\": dial tcp 127.0.0.1:8080: connect: connection refused","stacktrace":"github.com/gardener/etcd-wrapper/internal/bootstrap.(*initializer).Run\n\t/go/src/github.com/gardener/etcd-wrapper/internal/bootstrap/bootstrap.go:65\ngithub.com/gardener/etcd-wrapper/internal/app.(*Application).Setup\n\t/go/src/github.com/gardener/etcd-wrapper/internal/app/app.go:57\ngithub.com/gardener/etcd-wrapper/cmd.InitAndStartEtcd\n\t/go/src/github.com/gardener/etcd-wrapper/cmd/etcd.go:66\nmain.main\n\t/go/src/github.com/gardener/etcd-wrapper/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
...
[pod/virtual-garden-etcd-main-1/etcd] {"level":"error","ts":"2025-02-26T14:07:45.335Z","caller":"bootstrap/bootstrap.go:136","msg":"error in checking if exitCodeFile exists, assuming full-validation to be done.","exitCodeFilePath":"/var/etcd/data/exit_code","error":"stat /var/etcd/data/exit_code: no such file or directory","stacktrace":"github.com/gardener/etcd-wrapper/internal/bootstrap.determineValidationMode\n\t/go/src/github.com/gardener/etcd-wrapper/internal/bootstrap/bootstrap.go:136\ngithub.com/gardener/etcd-wrapper/internal/bootstrap.(*initializer).Run\n\t/go/src/github.com/gardener/etcd-wrapper/internal/bootstrap/bootstrap.go:69\ngithub.com/gardener/etcd-wrapper/internal/app.(*Application).Setup\n\t/go/src/github.com/gardener/etcd-wrapper/internal/app/app.go:57\ngithub.com/gardener/etcd-wrapper/cmd.InitAndStartEtcd\n\t/go/src/github.com/gardener/etcd-wrapper/cmd/etcd.go:66\nmain.main\n\t/go/src/github.com/gardener/etcd-wrapper/main.go:47\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
...
```

The backup bucket seems to have been created successfully:
```
$ kubectl --context oidc-wavecon-staging@garden-runtime-dev get backupbuckets.extensions.gardener.cloud -A
NAME                 TYPE        REGION   STATE       AGE
dev-virtual-garden   openstack   MUC5     Succeeded   55m
```

The etcds look like this:
``` 
kubectl get etcds -n garden virtual-garden-etcd-main -o yaml
```
![Image](https://github.com/user-attachments/assets/609c89b8-027b-4747-9a21-a77f2d971777)

**What you expected to happen**:
Currently we have to deploy the garden in a two step process: Comment out the etcd backup config block, reconcile the garden, un-comment it and reconcile again. I want to be able to just configure the garden correctly from the get go without manual intervening.

**How to reproduce it (as minimally and precisely as possible)**:

Create an garden object on openstack with the backup configuration option enabled and let the operator try to reconcile it:
```
      etcd:
        events:
          storage:
            capacity: 10Gi
        main:
          backup:
            bucketName: dev-virtual-garden
            provider: openstack
            secretRef:
              name: garden-etcd-backup
          storage:
            capacity: 25Gi
```

**Anything else we need to know?**:

If you ask me, this is quite similar to the issue we had with the bootstrapping not working if dns was defined: https://gardener-cloud.slack.com/archives/CAPMD6DCG/p1734082143558929

**Environment**:

- Gardener version: v1.113.0 
- Kubernetes version (use `kubectl version`): v1.31.5
- Cloud provider or hardware configuration: 
```
apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-openstack
  namespace: garden
spec:
  deployment:
    admission:
      runtimeCluster:
        helm: 
          ociRepository: 
            repository: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/admission-openstack-runtime
            tag: v1.45.1
      virtualCluster:
        helm: 
          ociRepository: 
            repository: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/admission-openstack-application
            tag: v1.45.1
    extension:
      helm: 
        ociRepository: 
          repository: europe-docker.pkg.dev/gardener-project/releases/charts/gardener/extensions/provider-openstack
          tag: v1.45.1
  resources:
  - kind: BackupBucket
    type: openstack
  - kind: BackupEntry
    type: openstack
  - kind: Bastion
    type: openstack
  - kind: ControlPlane
    type: openstack
  - kind: DNSRecord
    type: openstack-designate
  - kind: Infrastructure
    type: openstack
  - kind: Worker
    type: openstack
```
- Others:
