### ISSUE TITLE
Prevent accidental deletion of infrastructure shoot/seed clusters

### ISSUE THREAD

**Issue by RaphaelVogel** [gardener/gardener#1157]
**What would you like to be added**:
If rbac is disabled in the garden cluster, users could accidental delete seed clusters.
To prevent this, garden API server should not start, if a call to `SubjectAccessReview` with an arbitrary user trying to delete the seed cluster succeeds.   

**Why is this needed**:
Prevent accidental deletion if infrastructure shoot clusters

**Comment by mvladev** [comment]
Gardener API server should not be aware of such authorization assumptions. 

`RBAC` is not a requirement for running K8S - it's recommended in most of times, but not a requirement.

> users could accidental delete seed clusters.

Such setup issues should be enforced via `Webhook` Authorization or dynamic admission controls.

**Comment by rfranzke** [comment]
Technically it's not required, true, but some installations (like ours) want to enforce that it's enabled. We can make it configurable whether the gardener-apiserver should crash if RBAC is not enabled (and default it to `false`).

**Comment by mvladev** [comment]
RBAC can be enabled / disabled at any given time. Check during API server start is not sufficient.

The proper way is to add `ValidatingWebhookConfiguration` and have a dedicated dynamic admission which can actually check for `RBAC`.

**Comment by rfranzke** [comment]
> RBAC can be enabled / disabled at any given time.

Yes, true, but this requires a restart of the kube-apiserver. The gardener-apiserver probably won't restart in this case but just re-establish the connection.

> The proper way is to add ValidatingWebhookConfiguration and have a dedicated dynamic admission which can actually check for RBAC.

Can you explain in detail how this should look like? Which rules should the webhook have? What should it do? How does it deal with the dynamic enable/disable behaviour of RBAC?

**Comment by mvladev** [comment]
> Can you explain in detail how this should look like? Which rules should the webhook have? What should it do? How does it deal with the dynamic enable/disable behaviour of RBAC?

It should probably be something like 

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: valdiate-rbac
webhooks:
- name: rbac.gardener.cloud
  rules:
  - apiGroups:
    - garden.sapcloud.io
    - core.gardener.cloud
    apiVersions:
    - v1beta1
    - v1beta1
    operations:
    - "*"
    resources:
    - "*"
    scope: "*"
  clientConfig:
    service:
      namespace: some-namespace
      name: rbac-validator
    caBundle: some-bundle
  admissionReviewVersions:
  - v1beta1
  timeoutSeconds: 2
```

It'll periodically execute

```yaml
apiVersion: authorization.k8s.io/v1
kind: SubjectAccessReview
spec:
  resourceAttributes:
    group: garden.sapcloud.io
    verb: delete
    namespace: garden
    resource: seeds
  groups:
  - system:authenticated
```

and store the result in a global variable. That variable is going to be checked later on on every single admission request. If it's false, then the admission requests is going to be denied.
