### ISSUE TITLE
[Flaky Test] Registry Cache Extension Tests [It] [BETA] [SERIAL] [SHOOT] should enable extension, rotate CA, disable extension [cache]

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#11615]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
`Registry Cache Extension Tests [It] [BETA] [SERIAL] [SHOOT] should enable extension, rotate CA, disable extension [cache]`

**CI link**:
N/A

**Reason for failure**:
```
2025-03-04T09:46:40.482068587Z stdout F • [FAILED] [2946.133 seconds]
• [FAILED] [2946.133 seconds]
Registry Cache Extension Tests  [It] [BETA] [SERIAL] [SHOOT] should enable extension, rotate CA, disable extension [cache]
/go/pkg/mod/github.com/gardener/gardener@v1.110.4/test/framework/gingko_utils.go:16

  [FAILED] Expected success, but got an error:
      <*retry.Error | 0xc000c8a900>: 
     retry failed with context deadline exceeded, last error: shoot "foo" was not successfully reconciled
     {
         ctxError: <context.deadlineExceededError>{},
          err: <*errors.errorString | 0xc000314b30>{
              s: "shoot \"foo\" was not successfully reconciled",
         },
     }
 In [It] at: /src/test/testmachinery/shoot/enable_rotate_ca_disable_test.go:61 @ 03/04/25 09:26:33.259

  There were additional failures detected.  To view them in detail run ginkgo -vv
------------------------------

Summarizing 1 Failure:
 [FAIL] Registry Cache Extension Tests  [It] [BETA] [SERIAL] [SHOOT] should enable extension, rotate CA, disable extension [cache]
  /src/test/testmachinery/shoot/enable_rotate_ca_disable_test.go:61

Ran 3 of 3 Specs in 4816.887 seconds
FAIL! -- 2 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestShoot (4816.89s)
FAIL
FAIL	github.com/gardener/gardener-extension-registry-cache/test/testmachinery/shoot	4816.953s
FAIL
```

The Shoot fails to be reconciled with:

```yaml
lastErrors:
- codes:
  - ERR_CONFIGURATION_PROBLEM
  description: "task \"Waiting until shoot worker nodes have been reconciled\" failed:
    Error while waiting for Worker shoot--it--foo/foo to become ready:
    error during reconciliation: Error reconciling Worker: failed while waiting
    for all machine deployments to be ready: machine(s) failed: 1 error occurred:
    \"shoot--it--foo-worker-1-z1-55f98-86zgj\": Cloud provider message - machine
    codes error: code = [Internal] message = [InvalidParameterValue: User data is
    limited to 16384 bytes\n\tstatus code: 400, request id: <omitted>]"
  lastUpdateTime: "2025-03-04T09:28:01Z"
  taskID: Waiting until shoot worker nodes have been reconciled
lastOperation:
  description: "Flow \"Shoot cluster reconciliation\" encountered task errors: [task
    \"Waiting until shoot worker nodes have been reconciled\" failed: Error while
    waiting for Worker shoot--it--foo/foo to become ready: error during
    reconciliation: Error reconciling Worker: failed while waiting for all machine
    deployments to be ready: machine(s) failed: 1 error occurred: \"shoot--it--foo-worker-1-z1-55f98-86zgj\":
    Cloud provider message - machine codes error: code = [Internal] message = [InvalidParameterValue:
    User data is limited to 16384 bytes\n\tstatus code: 400, request id: <omitted>]]"
  lastUpdateTime: "2025-03-04T09:28:01Z"
  progress: 87
  state: Failed
  type: Reconcile
```

**Anything else we need to know**:

The registry-cache should not be adding something to the init OSC. Hence, it is less likely the flake is related to the extension itself.

Gardener version: v1.113.0
