### ISSUE TITLE
Introduce a new OpenID Connect configuration resource(s)

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#1161]
# Introduce new OpenID Connect configuration resource(s)

Gardener offers clusters with OpenID Connect (OIDC) not configured by default.

Offering a way to (optionaly) inject OIDC configuration on `Shoot` on creation can dramatically improve the secutity, and it can be used to limit the need for `kubeconfigs` with client x509 certificates and the admin (`system:masters`) certificate.

The solution should be:

- 100% backwards compatible.
- 100% customizable by cluster administrators on `cluster-scope`.
- 100% customizable by project administrators on `project-scope`.
- 100% side-effects free.
- `Shoot` configuration should be mutated on `CREATE` and not on `UPDATE`/`DELETE` (this behavior can be achieved with an additional (admission)controller, but not a requirement).

> Note: This is NOT a policy designed to enforce OpenID Configurations.

## Implementation

Two new API resources should be added to the `Gardener` - `OpenIDConnectConfiguration` and `ClusterOpenIDConnectConfiguration`

### OpenIDConnectConfiguration

`OpenIDConnectConfiguration` is a namespaced resource which holds a temple of OpenID Connect configuration, `Shoot` selector, and weight:

```yaml
apiVersion: settings.gardener.cloud/v1alpha1
kind: OpenIDConnectConfiguration
metadata:
  name: default
  namespace: some-namespace
spec:
  selector: {} # selects every Shoot in the default namespace.
  weight: 1 # Weight associated with matching the Shoot selector, in the range 1-100.
  config:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      Li4u
      -----END CERTIFICATE-----
    clientID: client-id
    clientSecret: some-secret
    groupsClaim: groups-claim
    groupsPrefix: groups-prefix
    issuerURL: https://identity.example.com
    usernameClaim: username-claim
    usernamePrefix: username-prefix
    signingAlgs: RS256,some-other-algorithm
```

Fields in this spec include:

- `selector` a standard [label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors), selecting to which `Shoot` this configuration is applied to.
- `weight` a value in the `1-100` range, controlling priority for selecing `OpenIDConnectConfiguration` for the same `Shoot`.
- `config` a template for `Shoot`'s `spec.kubernetes.kubeAPIServer.oidcConfig`.

### ClusterOpenIDConnectConfiguration

`ClusterOpenIDConnectConfiguration` is the cluster-scoped version of `OpenIDConnectConfiguration`, normally reserverd for cluster administrators:

```yaml
apiVersion: settings.gardener.cloud/v1alpha1
kind: ClusterOpenIDConnectConfiguration
metadata:
  name: default
spec:
  selector: {} # selects every Shoot in matched namespaces.
  namespaceSelector: {} # selects every namespace.
  weight: 1 # Weight associated with matching the Shoot selector, in the range 1-100.
  config:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      Li4u
      -----END CERTIFICATE-----
    clientID: client-id
    clientSecret: some-secret
    groupsClaim: groups-claim
    groupsPrefix: groups-prefix
    issuerURL: https://identity.example.com
    usernameClaim: username-claim
    usernamePrefix: username-prefix
    signingAlgs: RS256,some-other-algorithm
```

Fields in this spec are the same as in `OpenIDConnectConfiguration`, but also include:

- `namespaceSelector` a standard [label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors), selecting `Namespaces/Projects` to which this configuration is applied to.

### Garden API server admission controller

A new mutating admission controller should be added and enabled by default when a new `Shoot` admission request is recieved it should:

- Work only `CREATE` calls
- Mutate only Shoots without `spec.kubernetes.kubeAPIServer.oidcConfig`.
- Mutate `spec.kubernetes.kubeAPIServer.oidcConfig` with correct configuration.

## Ordering

When `Shoot` clusters are matched by multiple configuration the following ordering should take place:

1. `OpenIDConnectConfiguration` is selected over `ClusterOpenIDConnectConfiguration`.
1. `(Cluster)OpenIDConnectConfiguration` with the highest `spec.weight` is selected..
1. The first `(Cluster)OpenIDConnectConfiguration`(orderd by name) is selected.

## About clientSecret

While not needed / configurable on the API server, in order for the [kubectl's OIDC Authenticator](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator) to work `clientSecret` must be known for generating `kubeconfigs`.

This new optional field shall be added to the [OpenIDConfig](https://github.com/gardener/gardener/blob/5ab1e291b3cd4fb0a10346c73e39d649832b9e94/pkg/apis/garden/v1beta1/types.go#L1279-L1310) spec.

In both `ClusterOpenIDConnectConfiguration` and `OpenIDConnectConfiguration` this value should be required.

## Additional benefits

This new resources can also be used in https://github.com/gardener/dashboard/issues/419.

## Unknowns

- Wouldn't it make more sense to expose the entire [KubeAPIServer configuration](https://github.com/gardener/gardener/blob/5ab1e291b3cd4fb0a10346c73e39d649832b9e94/pkg/apis/garden/v1beta1/types.go#L1246-L1262) as a standalone resource?

**Comment by vlerenc** [comment]
Can you please motivate a bit more. We have not disabled OIDC. It's just not configured. How will the additional resources help? It's about defaults, right? So `ClusterOpenIDConnectConfiguration` in combination with the mutating web hook are already sufficient, aren't they? So why `OpenIDConnectConfiguration`? In case someone wants to do that on project level for all shoots there, right?

**Comment by mvladev** [comment]
> We have not disabled OIDC.

It was a wrong wording - I meant "not configured by default".

> How will the additional resources help? It's about defaults, right?

Yes - it'll mutate the Shoot entity on creation:

If you have 

```yaml
apiVersion: settings.gardener.cloud/v1alpha1
kind: OpenIDConnectConfiguration
metadata:
  name: default
  namespace: some-namespace
spec:
  selector: {} # selects every Shoot in the default namespace.
  weight: 1 # Weight associated with matching the Shoot selector, in the range 1-100.
  config:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      Li4u
      -----END CERTIFICATE-----
    clientID: client-id
    clientSecret: some-secret
    groupsClaim: groups-claim
    groupsPrefix: groups-prefix
    issuerURL: https://identity.example.com
    usernameClaim: username-claim
    usernamePrefix: username-prefix
    signingAlgs: RS256,some-other-algorithm
```

and the following Shoot entity send to the API server

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-aws
  namespace: some-namespace
spec:
  cloud:
    profile: aws
    region: eu-west-1
    secretBindingRef:
      name: foo
    aws:
      networks:
          cidr: 10.250.0.0/16
        internal: ['10.250.112.0/22']
        public: ['10.250.96.0/22']
        workers: ['10.250.0.0/19']
      workers:
      - name: cpu-worker
        machineType: m5.large
        volumeType: gp2
        volumeSize: 20Gi
        autoScalerMin: 2
        autoScalerMax: 2
        maxSurge: 1
        maxUnavailable: 0
  kubernetes:
    version: 1.15.0
```

after the mutating admission control, the Shoot entity will have the following spec:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-aws
  namespace: garden-dev
spec:
  cloud:
    profile: aws
    region: eu-west-1
    secretBindingRef:
      name: foo
    aws:
      networks:
          cidr: 10.250.0.0/16
        internal: ['10.250.112.0/22']
        public: ['10.250.96.0/22']
        workers: ['10.250.0.0/19']
      workers:
      - name: cpu-worker
        machineType: m5.large
        volumeType: gp2
        volumeSize: 20Gi
        autoScalerMin: 2
        autoScalerMax: 2
        maxSurge: 1
        maxUnavailable: 0
  kubernetes:
    version: 1.15.0
    kubeAPIServer:
      oidcConfig:
        caBundle: |
        -----BEGIN CERTIFICATE-----
        Li4u
        -----END CERTIFICATE-----
        clientID: client-id
        clientSecret: some-secret
        groupsClaim: groups-claim
        groupsPrefix: groups-prefix
        issuerURL: https://identity.example.com
        usernameClaim: username-claim
        usernamePrefix: username-prefix
        signingAlgs: RS256,some-other-algorithm
```

> So why OpenIDConnectConfiguration? In case someone wants to do that on project level for all shoots there, right?

Exactly - its the same reason why you have `ClusterRole` and `Role` in K8S - cluster-scoped and namespace-scoped permissions.
