### ISSUE TITLE
Add virtualCapacity field to extensions/v1alpha1.NodeTemplate for WorkerConfig

### ISSUE THREAD

**Issue by elankath** [gardener/gardener#11691]
**How to categorize this issue?**

/area control-plane
/kind api-change

**What would you like to be added**:

In order to support an extension requirement. See https://github.com/gardener/gardener-extension-provider-aws/issues/1238 we would like `NodeTemplate` in `pkg/apis/extensions/v1alpha1/types_worker.go` to have an additional map used to specify *virtual* resources of a Node that don't require rollout as opposed to *real* provisionable resources

```yaml
providerConfig:
    nodeTemplate:
        capacity:
            cpu: 123
        virtualCapacity: #PROPOSED API CHANGE
             hc.hana.com/memory: 1234567
```

**Why is this needed**:

This is to disambiguate *real* capacity attributes that indicate provision-able resources that necessitate rollout versus *virtual* capacity attributes that are applied on existing Nodes to affect workload scheduling and scaling.
