### ISSUE TITLE
Last operation state not properly updated

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1223]
I observe some Shoots with the following strange `.status.lastOperation`:
```yaml
lastOperation:
  description: Shoot cluster state has been successfully reconciled.
  lastUpdateTime: '2019-07-17T10:42:10Z'
  progress: 100
  state: Failed
  type: Reconcile
```

Checking the `progress` and `description` it looks like the `Reconcile` was successful but the state is `Failed`.
