### ISSUE TITLE
ETCD Encryption Config: insufficient validation

### ISSUE THREAD

**Issue by AleksandarSavchev** [gardener/gardener#12338]
**How to categorize this issue?**

/area security
/kind bug

**What happened**:
I tried encrypting encrypting all `ConfigMaps` in my `Shoot` cluster by adding them to the `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` field:
``` yaml
spec:
  kubernetes:
    kubeAPIServer:
      encryptionConfig:
        resources:
          - ConfigMaps
```

The `Shoot` reconciliation failed on waiting the kube-apiserver to get ready. The apiserver pods were in errored state with logs:
```
E0617 07:10:33.024360       1 run.go:72] "command failed" err="error while parsing file: resources[0].resources[0]: Invalid value: \"ConfigMaps\": resource name should not contain capital letters"
```

Removing the `ConfigMaps` resource from `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` is not allowed by validation:
```
Shoot.core.gardener.cloud "foo" is invalid: spec.kubernetes.kubeAPIServer.encryptionConfig.resources: Forbidden: resources cannot be changed because a previous encryption configuration change is currently being rolled out
```

You need to edit the `Shoot` status to mend the cluster.

**What you expected to happen**:
The `Shoot` API to not allow me to apply changes that would bring the cluster to an errored state.

**How to reproduce it (as minimally and precisely as possible)**:
Add string with capital letters to the `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` field as shown above.

**Anything else we need to know?**:
We should adapt to the validation from [kubernetes](https://github.com/kubernetes/kubernetes/blob/8adc0f041b8e7ad1d30e29cc59c6ae7a15e19828/staging/src/k8s.io/apiserver/pkg/apis/apiserver/validation/validation_encryption.go#L122-L284).

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by AleksandarSavchev** [comment]
There is also a bug with the validation of encryption config validation. If I have an `encryptionConfig` with similar configuration:
``` yaml
spec:
  kubernetes:
    kubeAPIServer:
      encryptionConfig:
        resources:
          - configmaps
```

When I edit the core resource with `.` at the end:
``` yaml
spec:
  kubernetes:
    kubeAPIServer:
      encryptionConfig:
        resources:
          - configmaps.
```

Then try to edit `spec.kubernetes.kubeAPIServer.encryptionConfig.resources` I get:
```
Shoot.core.gardener.cloud "foo" is invalid: spec.kubernetes.kubeAPIServer.encryptionConfig.resources: Forbidden: resources cannot be changed because a previous encryption configuration change is currently being rolled out
```

This is because in the `status.encryptedResources` it is written without the `.`:
``` yaml
status:
  encryptedResources:
    - configmaps
```
