### ISSUE TITLE
Shoot Spec: hibernation.enabled should be optional 

### ISSUE THREAD

**Issue by Fabian-K** [gardener/gardener#1251]
**What would you like to be added**:
The field hibernation.enabled of the Shoot spec should be optional

**Why is this needed**:
I want to add a hibernation schedule to a cluster. Currently, I have to supply a value for `enabled`. As a result, the cluster is hibernated or woken up whenever the config is applied (depending on the value of enabled). This leads e.g. to an unexpected wake up of the cluster when enabled is set to false and the config is applied during hibernation time.

```
hibernation:
    schedules:
      - start: '0 15 * * 1,2,3,4,5'
        end: '0 8 * * 1,2,3,4,5'
        location: Europe/Berlin
```
