### ISSUE TITLE
Please support Kubernetes version expiration date

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#1325]
**What would you like to be added**:
When managing could profiles and Kubernetes versions, we tend to drop versions with security vulnerabilities rather instantly, replacing them with the latest safe one. This causes issues with stakeholders that first want to validate the update process, but have no means anymore to create an "old" cluster and run through the update process. While this is more of a process issue (not strictly relevant to Gardener code), it should be possible to specify expiration dates on Kubernetes versions and the API server should reject shoot resources with expired Kubernetes versions (this, on the other hand, would be relevant to Gardener code).

**Why is this needed**:
To have enough time to validate Kubernetes version updates before they are forcefully executed.

**Comment by ialidzhikov** [comment]
I would also vote to "officialize" the k8s version support policy and add it under `/docs` or in `g/documentation`. For me now it is not clear when a given k8s version reaches its end of life in g/gardener.

**Comment by ialidzhikov** [comment]
I just mean something like [AKS Kubernetes version support policy](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#kubernetes-version-support-policy):
> AKS supports four minor versions of Kubernetes:
> - The current minor version that is released in AKS (N)
> - Three previous minor versions. Each supported minor version also supports two stable patches.
>
> This is known as "N-3" - (N (Latest release) - 3 (minor versions)).

Having a similar rule/policy would mean that when a new Kubernetes version support is added, the oldest minor version is deprecated (marked with an expiration date if we talk in the context of this issue).

Linking also [EKS Kubernetes support policy](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#kubernetes-version-support-policy) which is similar.

**Comment by vlerenc** [comment]
That is service-specific and up to the owner of the Gardener deployment, but not really something that can be implemented in Gardener or be mentioned in the docs as every owner can handle it differently. For instance, if AKS offers that, they will have to back-port patches that the community doesn't. It's their specific rule. Gardener per se, doesn't have any rules, because it's just a tool, but not a service. An owner can support only the last version or all versions there ever were or anything in the middle. The general rule is to follow what Kubernetes does, which is basically to support the current and the last two versions.

The issue above is primarily to introduce technical means into the cloud profile so that people a.) know when something gets deprecated in advance and can react and b) prevent cluster creation when a version is indeed expired, but the policy is really up to the owner of the Gardener installation and will vary.

**Comment by rfranzke** [comment]
Still, the question of @ialidzhikov is still relevant. Today we are supporting 1.10 - 1.15, but 1.16 is coming in a few weeks and with every version the complexity in our code increases (sometimes more, sometimes less).

I guess what @ialidzhikov wanted to clarify is whether we want to setup a general rule for the open-source tool Gardener itself in regards to which version support is implemented.

**Comment by rfranzke** [comment]
From #1333 
@danielfoehrKn :

**Currently** 

The cloud profile can contain multiple supported kubernetes versions.  A shoot can specify in the spec.Maintenance.AutoUpdate section if its kubernetes version should be upated to the latest version on a daily basis.

If a shoot is on an old kubernetes version (no auto update) and the admin decides to drop this version from the cloud profile due to any reason (e.g security) the shoot needs to be updated ->  shoot admission plugin enforces that shoot's kubernetes version is in the CloudProfile -> no update to shoot possible any more (reconcile might still work - not tested though)

**What would you like to be added**:
-  add an expiration date on the kubernetes version in the cloud profile. An expiration date on the latest defined version is not allowed.

- In maintenance time window: when a shoot is on a kubernetes version with an expiration date in the past, forcefully upgrade to the latest kubernetes version 

- In maintenance time window: when a shoot's kubernetes version cannot be found in the CloudProfile (any more), update to latest kubernetes version 

**Why is this needed**:
Draft for #1325 

To give shoots planning/testing time before a kubernetes version update. 
Enables setting an expiration time on kubernetes versions instead of just dropping them rather instantaneously from the CloudProfile.

**Proposal** 

The CloudProfile resource has a list of Kubernetes versions  with optional expiration dates:
```yaml
  gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
#        expiration date not allowed on latest
        - version: 1.15.2
        - version: 1.14.5
           expirationDate: 2019-06-21T00:00:00-07:00
```

**Scenarios**
The Gardener CloudProfile has three supported versions: 1.15.2, 1.14.2 & 1.13.9.
Then there is a security vulnerability at the date 15.06.2019 in version 1.13.9. The responsible person is setting an expiration date on the version 1.13.9 to the 21.06.2019.

We assume the following Cloud Profile

```yaml
  gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
#        expiration date not allowed on latest version
        - version: 1.15.2
        - version: 1.14.5
        - version: 1.13.9
          expirationDate: 2019-06-21T00:00:00-07:00
```

**Scenario 1**
Our shoot is on Kubernetes version 1.13.9 on the date  of the security incident. The shoots Kubernetes version has an expiration date set and will expire on the 21.06.
The shoot specifies  autoUpdate of the Kubernetes Version ==  false

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: false
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-15  the shoot's kubernetes version will remain the same.  

The shoots manifest can be updated in the normal fashion (no admission errors -  the kubernetes version is still valid in the CloudProfile). 
Necessary test operations can be conducted to prepare for a kubernetes update & ensure that the workload on the shoot can run on a higher Kubernetes version. 

On the date 2019-06-19 all testings  are complete and the shoots kubernetes version is being manually updated to 1.14.5 (has no expiration date).

**Scenario 2**
The shoot in our scenario is still on kubernetes version 1.13.9 on the date  2019-06-22.  The kubernetes version it is running is expired (only valid until the 21.06).
The shoot specifies  autoUpdate of the Kubernetes Version ==  false

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: false
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-22  the shoot's kubernetes version will be forcefully updated to 1.15.2. This is the latest version.

**Scenario 3**
The shoot is on kubernetes version 1.13.9 on the 2019-06-16.
The CloudProfile drops Kubernetes version 1.13.9  on the 2019-06-17.

This is the CloudProfile after dropping support for version 1.13.9.
```yaml
   gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
#        expiration date not allowed on latest version
        - version: 1.15.2
        - version: 1.14.5
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-17  the shoot's kubernetes version will be forcefully updated to 1.15.2. This is the latest version.

**Comment by vlerenc** [comment]
@rfranzke Are you saying, you would vote for dropping older versions faster? That was also the proposal by @ialidzhikov quite some time ago. Back then I argued why we don't want to do that, but if the complexity in maintaining the older versions is hurting us, then of course we can drop older versions faster.

So far this was on the pro side:
- More versions leave more time to our end users to adapt and they can do so less frequently
- Also we as maintainers of an internal service don't have to drop Kubernetes versions that often, but only with severe security vulnerabilities and then we drop multiple versions at once (less work)
- That also helps in motivating the end users to accept that we do that (less communication, because in the light of security vulnerabilities everybody complies immediately without arguing)

However, if maintenance becomes a burden, sure. Then let's define a clear contract (cc @RaphaelVogel @hoeltcl @ThormaehlenFred). In that case, since we have only access to the official Kubernetes releases, we can only offer the current and the last two versions. Before we finalise that, please present and inform the community and our internal stakeholders, so that people have enough time to react.

**Comment by vlerenc** [comment]
@danielfoehrKn I don't think we should forcefully update shoot clusters. Is there a mandatory reason to do that? Even if, we can only update one version at a time. We should never update to the latest, because that is a.) not possible and b.) bears an even greater risk to break the cluster. We should only update to the highest patch version of the oldest permitted minor version.

Still, I am not sure we should update forcefully. Is there a technical necessity to do so? On the other hand, if because of the above, there is no reconciliation code anymore in Gardener for that version, then we have no choice, I guess. The only other option, is to completely cease activities and switch off reconciliation, which is likewise ugly.

So, I guess, we have to update, but to the next = oldest version only (highest patch level of lowest minor version).

**Comment by rfranzke** [comment]
> @rfranzke Are you saying, you would vote for dropping older versions faster? That was also the proposal by @ialidzhikov quite some time ago. Back then I argued why we don't want to do that, but if the complexity in maintaining the older versions is hurting us, then of course we can drop older versions faster.

I have no strong opinion against or for dropping older versions faster. Currently, the maintenance effort is manageable. I just wanted to raise the awareness again whether we want to setup such rule (because currently there is nothing, we simply decide at a specific date to drop something, but nobody knows when). This might make it difficult to plan for end-users, especially if they don't have influence on the deployed Gardener version of their landscapes.
Let's not hijack this ticket now, nothing to be decided immediately, but something that maybe should be considered. @RaphaelVogel @hoeltcl @ThormaehlenFred probably have a clearer view on that and might want to setup such rules. I guess they should drive the topic if they see need.

**Comment by vlerenc** [comment]
OK, thanks @rfranzke. Indeed, this ticket is about technical support for the `expirationDate`, not the process itself. The purpose is to exactly avoid sudden removals of Kubernetes versions in the future and make the deprecation of a Kubernetes version accessible to end users via our programmatic interface, so that they can alert themselves or even automate a migration procedure.

What about the other topic, forceful updates? None (but how would reconciliation then work? not at all?) or to the highest patch version of the lowest minor version?

**Comment by rfranzke** [comment]
> @danielfoehrKn I don't think we should forcefully update shoot clusters. Is there a mandatory reason to do that? Even if, we can only update one version at a time. We should never update to the latest, because that is a.) not possible and b.) bears an even greater risk to break the cluster. We should only update to the highest patch version of the oldest permitted minor version.

+1, we can't do that. Let's keep the current behaviour which is only updating to the latest patch version for the respective minor version (if auto update is `true`, or if it's `false` and the currently used version's `expirationDate` is expired). I don't see a new to forcefully update minor versions. This would potentially break a lot of users as with most minor version updates there may be manual actions that need to be performed (depending on the users' workloads).

So, let's please keep everything as it is today and simply add the possibility to add expiration dates for Kubernetes versions.

**Comment by rfranzke** [comment]
@danielfoehrKn How do you plan to realize this in a backwards compatible way?

Today, the list of supported Kubernetes versions is just a `[]string`:

```yaml
kubernetes:
  versions:
  - 1.15.0
```

We cannot change the `versions` object, unfortunately. What do you think about

```yaml
kubernetes:
  versions: # deprecated
  - 1.15.0
  - 1.14.1
  - 1.14.0
  offeredVersions: # new
  - version: 1.15.0
  - version: 1.14.1
  - version: 1.14.0
    expirationDate: 2019-09-09T14:22:32Z # optional
```

Every version in the `.versions[]` must be in the `.offeredVersions[]`, and vice versa. But what if a version in the `.offeredVersions[]` has an expiration date that is expired? Should we built a mechanism that removes it from `.versions[]` if a shoot tries to use it? Or should the operator be responsible for removing it out of the `CloudProfile` after expiration?

**Comment by danielfoehrKn** [comment]
@rfranzke yes, providing backwards compatibility like this makes sense.
I would say removing expired kubernetes versions from the CloudProfile is up to the Operator.  This way a kubernetes version does not suddenly disappear from the CloudProfile.
Also maybe some people would like to have a "history" of their used versions, but thats speculation... in any case it is a trivial operation for the operator.
What do you think?

**Comment by rfranzke** [comment]
+1, makes it easier for us and is not a huge problem for operators (it doesn't make any sense to keep expired versions in the list anyways).

**Comment by vlerenc** [comment]
What a pity. It was almost consistent for a brief moment in time. Soon:

```
      kubernetes:
        offeredVersions:
        - version: 1.15.0
        - version: 1.14.1
        ...
      machineImages:
      - name: coreos
        versions:
        - version: 1234.5.0
      ...
```

Such is life. ;-)
