### ISSUE TITLE
Draft: Kubernetes version expiration date

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#1333]
**Currently** 

The cloud profile can contain multiple supported kubernetes versions.  A shoot can specify in the spec.Maintenance.AutoUpdate section if its kubernetes version should be upated to the latest version on a daily basis.

If a shoot is on an old kubernetes version (no auto update) and the admin decides to drop this version from the cloud profile due to any reason (e.g security) the shoot needs to be updated ->  shoot admission plugin enforces that shoot's kubernetes version is in the CloudProfile -> no update to shoot possible any more (reconcile might still work - not tested though)

**What would you like to be added**:
-  add an expiration date on the kubernetes version in the cloud profile. An expiration date on the latest defined version is not allowed.

- In maintenance time window: when a shoot is on a kubernetes version with an expiration date in the past, forcefully upgrade to the latest kubernetes version 

- In maintenance time window: when a shoot's kubernetes version cannot be found in the CloudProfile (any more), update to latest kubernetes version 

**Why is this needed**:
Draft for #1325 

To give shoots planning/testing time before a kubernetes version update. 
Enables setting an expiration time on kubernetes versions instead of just dropping them rather instantaneously from the CloudProfile.

**Proposal** 

The CloudProfile resource has a list of Kubernetes versions  with optional expiration dates:
```yaml
  gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
#        expiration date not allowed on latest
        - version: 1.15.2
        - version: 1.14.5
           expirationDate: 2019-06-21T00:00:00-07:00
```

**Scenarios**
The Gardener CloudProfile has three supported versions: 1.15.2, 1.14.2 & 1.13.9.
Then there is a security vulnerability at the date 15.06.2019 in version 1.13.9. The responsible person is setting an expiration date on the version 1.13.9 to the 21.06.2019.

We assume the following Cloud Profile

```yaml
  gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
#        expiration date not allowed on latest version
        - version: 1.15.2
        - version: 1.14.5
        - version: 1.13.9
          expirationDate: 2019-06-21T00:00:00-07:00
```

**Scenario 1**
Our shoot is on Kubernetes version 1.13.9 on the date  of the security incident. The shoots Kubernetes version has an expiration date set and will expire on the 21.06.
The shoot specifies  autoUpdate of the Kubernetes Version ==  false

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: false
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-15  the shoot's kubernetes version will remain the same.  

The shoots manifest can be updated in the normal fashion (no admission errors -  the kubernetes version is still valid in the CloudProfile). 
Necessary test operations can be conducted to prepare for a kubernetes update & ensure that the workload on the shoot can run on a higher Kubernetes version. 

On the date 2019-06-19 all testings  are complete and the shoots kubernetes version is being manually updated to 1.14.5 (has no expiration date).

**Scenario 2**
The shoot in our scenario is still on kubernetes version 1.13.9 on the date  2019-06-22.  The kubernetes version it is running is expired (only valid until the 21.06).
The shoot specifies  autoUpdate of the Kubernetes Version ==  false

```yaml
 maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: false
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-22  the shoot's kubernetes version will be forcefully updated to 1.15.2. This is the latest version.

**Scenario 3**
The shoot is on kubernetes version 1.13.9 on the 2019-06-16.
The CloudProfile drops Kubernetes version 1.13.9  on the 2019-06-17.

This is the CloudProfile after dropping support for version 1.13.9.
```yaml
   gcp:
    constraints:
      dnsProviders:
      - name: unmanaged
      kubernetes:
        versions:
#        expiration date not allowed on latest version
        - version: 1.15.2
        - version: 1.14.5
```

In the daily maintenance window of the shoot at 22:00 - 23:00 on  2019-06-17  the shoot's kubernetes version will be forcefully updated to 1.15.2. This is the latest version.
