### ISSUE TITLE
Improve core.gardener.cloud.CloudProfile validation

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1407]
The following cases could be improved:
- Prevent `.spec.kubernetes.versions` with duplicating version. Example of invalid spec section:

```yaml
spec:
  kubernetes:
    versions:
    - expirationDate: "2020-04-05T08:00:00Z"
      version: 1.10.13
    - expirationDate: "2007-04-05T08:00:00Z"
      version: 1.10.13
```

- Prevent `.spec.regions` with duplicating name. Example of invalid spec section:
```yaml
spec:
  regions:
  - name: us-east-2
    zones:
    - name: us-east-2a
  - name: us-east-2
    zones:
    - name: bar
```
