### ISSUE TITLE
Browser-trusted certificates for kube-apiservers

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#1413]
**What would you like to be added**:
If a certificate can be requested because a certificate service is available, e.g. `cert-management` for shoots, make use of [`--tls-sni-cert-key`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) flag to pass a browser-trusted certificate to the kube-apiserver of shoot clusters.

> --tls-sni-cert-key namedCertKey     Default: []
> --
> A pair of x509 certificate and private key file paths, optionally suffixed with a list of domain patterns which are fully qualified domain names, possibly with prefixed wildcard segments. If no domain patterns are provided, the names of the certificate are extracted. Non-wildcard matches trump over wildcard matches, explicit domain patterns trump over extracted names. For multiple key/certificate pairs, use the --tls-sni-cert-key multiple times. Examples: "example.crt,example.key" or "foo.crt,foo.key:*.foo.com,foo.com".
> 
> 

**Why is this needed**:
For the [web terminals feature](https://github.com/gardener/dashboard/pull/450) of the dashboard we open a websocket connection to the kube-apiserver and need a browser-trusted certificate. This would be the most elegant solution, without the need of another component in between.

**Comment by mvladev** [comment]
I would not do this:

- Let’s Encrypt (LE) CA issuer takes a while to be processed during this time, the API server cannot start, slowing cluster creation.
- With the Gardener API you can create clusters without DNS and LE won’t issue certificates for IP addresses only. So this won't work for the dashboard.
- You can provide your own DNS and let Gardener create the `api.<your-domain>` DNS record, however there is no guarantee that `<your-domain>` will have quota for LE or the issuer.
- All existing Nodes must be rotated as the workload would only trust a public certificate signed by the kubernetes CA and not LE’s CA.

**Comment by petersutter** [comment]
The flag should be added in addition to the current `--tls-cert-file` and `--tls-private-key-file` kube-apiserver flags.

Example:
```yaml
...
    spec:
      containers:
      - command:
        - /usr/local/bin/kube-apiserver
...
        - --tls-cert-file=/srv/kubernetes/apiserver/kube-apiserver.crt
        - --tls-private-key-file=/srv/kubernetes/apiserver/kube-apiserver.key
        - --tls-sni-cert-key=foo-le.crt,foo-le.key:makesomethingup.external.example.com
```

> - All existing Nodes must be rotated as the workload would only trust a public certificate signed by the kubernetes CA and not LE’s CA.

When accessing `makesomethingup.external.example.com` you will get the browser trusted certificate presented for the kube-apiserver. This should not affect the cluster internal communication, e.g. for myservice.ns.svc.local I would still get the self signed certificate of the custom root ca, so no need to rotate any Nodes. Or do I oversee something here?
