### ISSUE TITLE
Enhance backup handling

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1428]
The current shared backup bucket solution aims to automatically reschedule `core.gardener.cloud/v1alpha1.BackupBucket` resources in case the active `Seed` is offline or has problems. However, as of today there is no mechanism to decide which new `Seed` has access to the backup infrastructure environment (e.g., consider the `openstack` case where multiple OpenStack installations might be active with the same Gardener).

Consequently, the proposal we discussed with @swapnilgm @timuthy @mandelsoft is to enhance our current APIs to support these scenarios. These APIs will also "for free" open up for new features, e.g. using an existing bucket for backups, or using the very same bucket for all seeds, if desired.

```yaml
apiVersion: core.gardener.cloud/v1alpha1
kind: BackupInfrastructure
metadata:
  name: environment1
spec:
  provider: openstack
  secretRef:
    name: backup-openstack
    namespace: garden

---
apiVersion: core.gardener.cloud/v1alpha1
kind: Seed
metadata:
  name: seed1-in-environment1
spec:
  provider:
    type: openstack
    region: eu1
  backup:
    infrastructureName: environment1                       # creates new bucket in `eu1` region
  # region: eu3                                            # only possible to specify if new bucket shall be created (in another region)
  # bucketName: e7032be0-ceea-11e9-aa66-acde48001122       # use existing bucket
  ...

---
apiVersion: core.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: e7032be0-ceea-11e9-aa66-acde48001122
spec:
  backupInfrastructureName: environment1
  region: eu1
  seed: seed1-in-environment1
```

**Comment by amshuman-kr** [comment]
> However, as of today there is no mechanism to decide which new Seed has access to the backup infrastructure environment (e.g., consider the openstack case where multiple OpenStack installations might be active with the same Gardener).

I see this as a topology problem. The [above](https://github.com/gardener/gardener/issues/1428#issue-493992716) approach with `BackupInfrastructure` seeks to solve it by explicitly encoding the topology (provider, region etc.).

How about solving it a bit more informally similar to the topology-aware scheduling using labels and selectors? The topology can be encoded in the labels of `seeds` similar to the [built-in](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#built-in-node-labels) topology labels in `nodes`. The constraint for the scheduler can be captured in a selector in the `BackupBucket` spec similar to the [`nodeSelector`](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#step-two-add-a-nodeselector-field-to-your-pod-configuration) or `topologyKey` in the [`podAffinity`](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity) in `pods`.

```yaml
apiVersion: core.gardener.cloud/v1alpha1
kind: Seed
metadata:
  name: seed1-in-environment1
  labels:
    backup.garden.sapcloud.io/provider: openstack
    backup.garden.sapcloud.io/region: eu1
spec:
  provider:
    type: openstack
    region: eu1
  ...

---
apiVersion: core.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: e7032be0-ceea-11e9-aa66-acde48001122
spec:
  seedSelector:
    matchLabels:
      backup.garden.sapcloud.io/provider: openstack
      backup.garden.sapcloud.io/region: eu1
  region: eu1
  seed: seed1-in-environment1
status:
  seed: seed1-in-environment1
```

**Comment by swapnilgm** [comment]
@amshuman-kr Since backupBucket is not created manually and created at the time of seed creation. Mostly your idea leads to putting seedSelector to all the label values from first assigned seed. But all labels need not be useful for categorising seeds which has access  to object store/backup provider. So, when the event of rescheduling occurs the new seed need not be expected to have all labels as previous seed. So, this approach won't work.

**Comment by amshuman-kr** [comment]
> Mostly your idea leads to putting seedSelector to all the label values from first assigned seed.

This is not a valid assumption. The selector could be on a subset of values. Hence, the rest of the chain of logic is invalid too.

**Comment by swapnilgm** [comment]
>This is not a valid assumption. The selector could be on a subset of values. Hence, the rest of the chain of logic is invalid too.

Yes. but then we will have to hardcode it in code the set of label to be choose from seed for which backupBucket is being created. 

@rfranzke @timuthy @mandelsoft Any comment on approach suggested by @amshuman-kr ?

**Comment by amshuman-kr** [comment]
> but then we will have to hardcode it in code the set of label to be choose from seed for which backupBucket is being created.

Or pick it from somewhere in the landscape configuration which is the right place for such information, isn't it?

**Comment by rfranzke** [comment]
@swapnilgm @amshuman-kr what's the plan here?

**Comment by swapnilgm** [comment]
I'm fine with seedSelector approach suggested by @amshuman-kr.  But before going forward, just need one more clarification. With `seedSelector` approach it's hard rather not possible to specify that the single seed can have access to multiple backup object store provider. On other hand, with backupInfrastructure resource, we can extend it to array i.e. we can make either `seed.spec.backup.Infrastructure` as list rather than string.

**Comment by amshuman-kr** [comment]
> With `seedSelector approach` it's hard rather not possible to specify that the single seed can have access to multiple backup object store provider.

Well... not impossible ;-)
The assumption above seems driven by the labels I have specified in the example [above](https://github.com/gardener/gardener/issues/1428#issuecomment-532160595). But the whole point of the `seedSelector` approach is that the landscape admins can choose their own labels to describe their topology of seeds and backup infrastructures.

For example, a set of labels like the following could address the use-case of a single seed accessing multiple backup infrastructures.
```yaml
...
metadata:
  labels:
    backup.garden.cloud/provider/s3: 'true'
    backup.garden.cloud/provider/gcs: 'true'
...
```

The advantage is that this need not have any changes to the spec. This is the intended advantage of the `seedSelector` approach that the spec remains unaffected and can support many different kinds of mapping between the `seeds`, `backupbuckets` and the backup infrastructure not only during the creation use-case but also during the migration use-case.

The downside, of course, is that the explicit mapping between the `seeds`, `backupbuckets` and the backup infrastructure is not clear from the spec and emerges from how the labels and the selectors are used.
