### ISSUE TITLE
Gardener does not respect machineImage on shoot level

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#1496]
**What happened**:
When a shoot cluster is created with this manifest(only relevant fields are show)
```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: foo
  namespace: garden-bar
spec:
  ...
  cloud:
    aws:
      machineImage:
        name: non-default-os
        version: 1.2.3
      workers:
      - autoScalerMax: 2
        autoScalerMin: 2
        machineType: m4.xlarge
        maxSurge: 1
        maxUnavailable: 0
        name: worker-coreos
        volumeSize: 50Gi
        volumeType: standard
...
```

The API defaulting sets the worker pool level os to be the default from the cloud profile, not the default defined on shoot level. So if I get the manifest of the created shoot, I will see this:
```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  annotations:
    migration.shoot.gardener.cloud/globalMachineImage: '{"Name":"non-default-os","ProviderConfig":null,"Version":"1.2.3"}'
    migration.shoot.gardener.cloud/workers: '{"worker-coreos":{"ProviderConfig":null,"Volume":null,"Zones":null}}'
  name: foo
  namespace: garden-bar
spec:
  ...
  cloud:
    aws:
      machineImage:
        name: non-default-os
        version: 1.2.3
      workers:
      - autoScalerMax: 2
        autoScalerMin: 2
        machineImage:
          name: coreos
          version: 2135.6.0
        machineType: m4.xlarge
        maxSurge: 1
        maxUnavailable: 0
        name: worker-coreos
        volumeSize: 50Gi
        volumeType: standard
...
```

**What you expected to happen**:
I expect the shoot level defined machine image to be respected.

**How to reproduce it (as minimally and precisely as possible)**:
It is standard Gardener landscape with support for at least 2 operating systems, for example `coreos` and `ubuntu`.

**Anything else we need to know?**:
Most probably this was caused because of the conversions between the old and new API, for reference #1430. 

**Environment**:

- Gardener version: 0.30.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
