### ISSUE TITLE
Publish Ingress LB Address 

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#154]
The nginx-ingress controller doesn't report the LB IP anymore with v0.12.0 https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.12.0. Should we set `--publish-status-address` to get the IP back. Vora was expecting it/checking it, just to see whether everything worked out.

**Comment by rfranzke** [comment]
I don't get it.. can you please explain what exactly you mean? 
Where should the ingress-controller report the IP?

The `.status` object of an `Ingress` resource does still contain it, e.g.:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
  ...
spec:
  rules:
  - host: g.<host>
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - g.<host>
    secretName: grafana-tls
status:
  loadBalancer:
    ingress:
    - ip: 35.123.124.125
```
