### ISSUE TITLE
Implement versioning policy contract (GEP-5)

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1577]
GEP-5 (https://github.com/gardener/gardener/blob/master/docs/proposals/05-versioning-policy.md) is a proposal for making the Kubernetes and operating system versioning policy more predictable for operators and end-users.

Mainly, it classifies versions into four categories, `preview`, `supported`, `deprecated`, and `expired`.

As the proposal has been accepted we should implement it now.

**Comment by danielfoehrKn** [comment]
As I am currently implementing the proposal, I am also reiterating over the MaintenanceController.

Currently, if the shoots's K8 version does not exist in the cloudprofile (any more) and the K8AutoUpdate is not enabled, then the K8 version will not be bumped. 
This can lead to a Shoot being permanently on a version that does not exist any more.

I would therefore suggest:
- Forcefully migrate Shoot (inclusive minor upgrade if already highest patch) if the Version does not exist in the CloudProfile -> this is more aligned with the GEP that specifies forceful upgrades for expired & highest patch versions for a minor version
- Introduce a check in the admissionplugin that forbids deletion of a K8Version that are still referenced by a Shoot.  This would make it more safe to delete a version in the cloudprofile, as there are now forceful migration of Clusters involved. Rather than deletion the version right away, the operator would have to expire a version first (has to be done manually for latest-patch version of each minor version). Then wait until the K8 version of every Shoot gets updated during Maintenance to eventually delete the version manually.

This Two-Step approach in my opinion would make it more safe for operator to use.
WDYT @rfranzke  @vlerenc @timuthy 

@rfranzke said he would rather like to be able to delete the version from the CloudProfile right away.

**Comment by vpnachev** [comment]
> Currently, if the shoots's K8 version does not exist in the cloudprofile (any more) and the K8AutoUpdate is not enabled, then the K8 version will not be bumped.

This has been clarified as a desired behavior in https://github.com/gardener/gardener/issues/1419.

> Forcefully migrate Shoot (inclusive minor upgrade if already highest patch)

Please, do not do this. The downgrade is a manual effort and we've already seen couple of broken patch releases.

**Comment by rfranzke** [comment]
@vpnachev what @danielfoehrKn describes is what was agreed on in [GEP5](https://github.com/gardener/gardener/blob/master/docs/proposals/05-versioning-policy.md). Of course, this GEP assumes proper output qualification is in place and broken patch versions are not even added in the first place.

**Comment by vlerenc** [comment]
❗️Please note that our internal wiki Versioning-Policy contains the **actual agreed-upon truth**. 

I am saying that, because I am not sure, whether all changes were reflected in the GEP5 (was it updated)?

Forceful updates are described there. If we don't do/include that, we can't rid us of these versions and that is in our very interest. Since we do that only with expired versions, likelihood is high, that the versions to which we upgrade are actually working.

@danielfoehrKn also asks about securing the versioning policy process with admission webhooks. That's actually a good idea and I would see that as part of the automation this issue is about, i.e. it's not only about the implementation of the actual steps, but also about making any modification/updates as safe as possible.

> Rather than deletion the version right away, the operator would have to expire a version first (has to be done manually for latest-patch version of each minor version). Then wait until the K8 version of every Shoot gets updated during Maintenance to eventually delete the version manually. Introduce a check in the admissionplugin that forbids deletion of a K8Version that are still referenced by a Shoot.

Yes, that's a good idea. We need at a minimum (mandated by the contract):
* Only versions that have an expiration date that lies in the past can be removed from the cloud profile. Versions that neither have an expiration date or have one that hasn't lapsed yet, can't be removed from the cloud profile.

In addition (better/safer/covers all versions/clusters in general, but also more work), we could:
* Allow to remove expired versions only if no clusters are using it anymore.

**Comment by danielfoehrKn** [comment]
Please review [this PR](https://github.com/gardener/gardener/pull/2105) first.

**Comment by vlerenc** [comment]
As discussed out-of-band, we agreed to first document our "ideal versioning policy" (technical representation) and break down the functionality into 3 components:
1. CloudProfileHelper: A binary that uses the policy and helps an operator to manipulate a cloud profile as file/stream (**not as Kubernetes resource**).
2. CloudProfileAdmissionController: An admission controller that uses the policy and that, if switched on/configured, prevents mistakes in the live system from happening.
3. ShootMaintenanceController: Modifications to the Gardener shoot maintenance controller that implements general (**not policy-sensitive**) operations.

E.g. a document with these 4 sections (content is just an example/not a proposal/final/matching the https://github.tools.sap/kubernetes/kube-docs/wiki/Versioning-Policy):
```
# VersioningPolicy
kubernetesVersionManagement:
  maintainedKubernetesVersions: 3
  expirationDurationForMaintainedVersions: 2880h
  expirationDurationForUnmaintainedVersions: 720h
machineImageVersionManagement:
  expirationDuration: 2880h

# CloudProfileHelper Tasks
- When a preview patch version is marked as supported, the until then latest patch version turns deprecated with 4 months expiration
- ...

# CloudProfileAdmissionController Tasks
- Previews only newer than latest supported minor/patch versions
- Expiration dates within allowed timerange according to policy
- ...

# ShootMaintenanceController Tasks
- Do not roll into preview OS versions (even if previews newer than supported versions)
- Roll expired OS into latest supported OS version
- Do not roll into preview K8s versions (even if previews newer than supported versions)
- Roll expired K8s into oldest supported or deprecated minor Kubernetes version and latest patch version
- ...
```
