### ISSUE TITLE
Enhance validation for core.gardener.cloud.Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1585]
**What would you like to be added**:
Currently it is possible to create a Shoot with the following spec section (only relevant fields are shown):
```yaml
spec:
  provider:
    infrastructureConfig:
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
        - internal: 10.250.112.0/26
          name: eu-central-1a
          public: 10.250.96.0/26
          workers: 10.250.0.0/26
```

The Shoot reconciliation will fail with
```
Flow "Shoot cluster reconciliation" encountered task errors: [task
      "Waiting until shoot infrastructure has been reconciled" failed: failed to create
      infrastructure: retry failed with context deadline exceeded, last error: extension
      encountered error during reconciliation: Error reconciling infrastructure: could
      not render Terraform chart: render error in "aws-infra/templates/main.tf": template:
      aws-infra/templates/main.tf:20:29: executing "aws-infra/templates/main.tf" at
      <required "vpc.cidr is required" .Values.vpc.cidr>: error calling required:
      vpc.cidr is required]'
```

The valid spec should be
```yaml
spec:
  provider:
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
        - internal: 10.250.112.0/26
          name: eu-central-1a
          public: 10.250.96.0/26
          workers: 10.250.0.0/26
```
