### ISSUE TITLE
Quota for user facing resources

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#1650]
**What would you like to be added**:
Gardener should have configurable, project scoped quotas for resources that end users (specifically project members) are permitted to create:

```
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - serviceaccounts

- apiGroups:
  - garden.sapcloud.io
  - core.gardener.cloud
  resources:
  - shoots
  - secretbindings
  - quotas
  - plants

- apiGroups:
  - settings.gardener.cloud
  resources:
  - openidconnectpresets

- apiGroups:
  - garden.sapcloud.io
  - core.gardener.cloud
  resources:
  - projects
```

The list above contains all possible resources, although some of them might be negligible or aren't critical for the system stability (tbd).

A quota could look like:

```
apiVersion: core.gardener.cloud/v1alpha1
kind: ResourceQuota
metadata:
  name: standard-quota
  namespace: garden-project
spec:
- apiGroups:
  - garden.sapcloud.io
  - core.gardener.cloud
  resources:
  - shoots
  - secretbindings
  - quotas
  - plants
  limits:
    maxObjects: 200
    maxSizePerObject: 1m 
```

Unfortunately, k8s native `ResourceQuotas` don't cover all necessary API objects and uses cases:
https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object/

**Why is this needed**:
Quotas are one countermeasure to prevent the Gardener- and Kube-Apiserver, it's backing etcds as well as involving controllers from being flooded.

/cc @petersutter @ThormaehlenFred
