### ISSUE TITLE
Editing infrastructureConfig does not reconcile the Infrastructure

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1653]
Steps to reproduce:
1. Create a Shoot
2. Edit the `spec.provider.infrastructureConfig`. For example for GCP add a new property `spec.provider.infrastructureConfig.networks.cloudNAT.minPortsPerVM`.

```yaml
infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        cloudNAT:
          minPortsPerVM: 512
        worker: 10.250.0.0/19
```

3. Ensure that the Shoot reconciliation fails at step `Waiting until shoot infrastructure has been reconciled`

```
Last Error
Flow "Shoot cluster reconciliation" encountered task errors: [task "Waiting until shoot infrastructure has been reconciled" failed: failed to create infrastructure: retry failed with context deadline exceeded, last error: observed generation outdated (2/3)]
```

The `metadata.generation` of the Infrastructure is updated, but the there is no `reconcile` annotation.
