### ISSUE TITLE
Cluster upgrades may cause downtime for workloads with multiple AZs

### ISSUE THREAD

**Issue by georgi-lozev** [gardener/gardener#1673]
Hey friends.

This is not the typical enhancement request, but still it's a strange behaviour we observed while using cluster managed by Gardener, so I think it's worth sharing.

**Description of the problematic behaviour observed**
We have a relatively small cluster running on GCP with worker nodes distributed over 3 AZs.

Here is the worker setup:
```yaml
      workers:
        - name: worker-c92jz
          machineType: n1-standard-4
          machineImage:
            name: coreos
            version: 2135.6.0
          autoScalerMin: 3
          autoScalerMax: 6
          maxSurge: 1
          maxUnavailable: 0
          volumeType: pd-standard
          volumeSize: 50Gi
      zones:
        - us-west2-a
        - us-west2-b
        - us-west2-c
```

Currently we have 3 worker nodes, 1 node per AZ and our workloads have `PodDisruptionBudget`, `PodAffinity` and `HorizontalPodAutoscaler` configured.

When we roll out a new k8s version to the cluster we observe a downtime of the workloads running on top. The behaviour we see is that all 3 worker nodes seem to start updating all at the same time and in parallel. 

**What would you like to be added**:
Is it possible to alter this behaviour and not trigger a parallel deploy for all zones, but do it one by one or at some configurable value/`%`. Pretty much the same as when we have in a single zone cluster.
If it's not possible at least have it explicitly stated and document what are the preferred adjustments that needs to be done in order to prevent similar misinterpretations from users in future.
The mitigation mechanism we thought may help is that if we increase the nodes to be at least 2 per zone and also scale out our pods to distribute a bit more evenly between the nodes. Any recommendations from your side will be welcome.

**Comment by rfranzke** [comment]
@hardikdr @prashanth26 - we have three `MachineClass`es and three `MachineDeployment`s, one per zone. When updating the version then we create three new `MachineClass`es and update the references in all `MachineDeployment`s in parallel. Wasn't your statement that PDBs will ensure that MCM does not start draining all of the nodes at the same time?

**Comment by vlerenc** [comment]
It should block, according to my understanding, but maybe that's a parallelisation issue/race condition since draining will start together, because these are three different machine deployments, but the code that does the PDB planning is not within the API server, but the client, I believe.

**Comment by prashanth26** [comment]
@ggaurav10 tried this the following - 

```
i tried to reproduce this in my cluster. Details:
setup: 2 nodes, deployment with 5 replicas, pdb with minAvailable: 4
Exp1 - To check client side parallelism:
*   All pods are created on same node of of the 2
*  use cmd k drain --pod-selector=run=resource-consumer ip-10-250-30-120.eu-west-1.compute.internal to drain it
* Expectation and observation: PDB was respected
Exp2 - To check server side parallelism:
• All pods are created on same node out of the 2
• use the same cmd but run it in parallel 5 times
• Expectation and observation: PDB was respected
```

But we are yet to test it with the multi-zone setup as mentioned above. Maybe something isn't working there.  Ideally, this shouldn't be happening. I shall check this case out. We might need a couple of days' time. I will keep you posted on this thread.

**Comment by hardikdr** [comment]
I believe PDBs should be respected with the above setup. 
- MCM respects the `maxSurge`, `maxUnavailable` but that's per MachineDeployment. With the setup mentioned above by @rfranzke , it is expected that the replacement of all the machines will initiate simultaneously.  
- Before actually deleting/replacing the machine, MCM always drains it. And drain basically evicts the pods on the node using `EvictionAPI`.
   - The [EvictionAPI](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#the-eviction-api) ensures to not delete the given pod if any PDBs are violated due to its deletion. Hence, even though the drain has been simultaneously initiated for all machines above, the actual deletion of the PDB-backed-pods should be blocked by `EvictionAPI`.
 
Though the catch here is, we have certain timeouts. If a drain isn't successful in a given timeout-period, we simply force-delete the machines and hence also the pods running on them. I believe such a timeout is large enough atm[~2hrs] [cc @prashanth26 ]. This is just a theoretical explanation and it would be nice to reproduce the case if possible, we shall do a few experiments. 

Although I am curious, what is the size of the docker image? How much time does your pod generally take in getting started on the fresh machine? Was your observation only about the machines being rolled together or was there actually a downtime observed for the workload-pods as well?

**Comment by amshuman-kr** [comment]
There is code to block already but I when I tried with multi-az cluster, `PDB` was indeed violated as described above.

There could be a general `PDB` violation issue for pods with affinity/antiaffinity even in single-az clusters.

![image](https://user-images.githubusercontent.com/32157254/69950773-fbbc2a80-1519-11ea-8090-5919f0a95460.png)

**Comment by amshuman-kr** [comment]
The `PDB` violation in single-az clusters was transient and was not reproducible. But it is consistently reproducible in multi-az clusters.

**Comment by vlerenc** [comment]
OK, so even though we use a central coordinator (Kubernetes eviction API), PDBs are not respected. Do we already know whether that's an upstream bug or works as intended?

**Comment by amshuman-kr** [comment]
Not sure. Couldn't make out from the available MCM logs. Could be an internal issues as well. We should to check with more logging (especially, the eviction API response).

**Comment by georgi-lozev** [comment]
Hey @hardikdr .

Some of the docker images are around 30-40 MB and others  80-100 MB. In general no more  than 100MB. Implementation is Go based if it matters.

I don't have a concrete metrics about the starting time, but in general it doesn't take more than a couple of seconds, so nothing noticeable or too big.

There was an actual downtime for the workloads running on top.

We tried the upgrades with both `maxUnavailable` set to 0 and 1, but the observed behaviour was pretty much the same.

**Comment by georgi-lozev** [comment]
Any thoughts on this one?

Does the option to just scale the clusters to have more than one VM/node per region sounds like a viable thing to do in order to mitigate the downtime problem in the short term?

Is the PDB going to be taken in consideration if we have this setup and scale out both our machines and pods ?

**Comment by hardikdr** [comment]
Sorry for not updating this thread. We are looking into it further. We have a possible improvement at hand in MCM, where we plan to increase the number of eviction retries before force-fully deleting the pods. This should better the roll-outs, at least initial experiments have been suggesting so.

> Does the option to just scale the clusters to have more than one VM/node per region sounds like a viable thing to do in order to mitigate the downtime problem in the short term?

Any possible mitigations from your side are always good to have in my opinion. Having more machines leaves space for pods to be quickly scheduled on other machines. 

> Is the PDB going to be taken in consideration if we have this setup and scale out both our machines and pods ?

We have identified a fixed number of eviction-retries in drain function, which were exhausted and hence pods were getting deleted forcefully - violating PDBs. With fix on the way, the PDBs should be respected in the setup you described above.

**Comment by mvladev** [comment]
@rfranzke another problem is that both fields `maxSurge` and `maxUnavailable` are applied to ALL `MachineDeployments` which is really contra-intuitive:

```yaml
workers:
- name: worker-c92jz
  autoScalerMin: 3
  autoScalerMax: 6
  maxSurge: 1
  maxUnavailable: 0
zones:
- us-west2-a
- us-west2-b
- us-west2-c
```

When I have the above specification I would expect that only ONE node should be updated at all times. 

End-user might also be tricked into putting `maxUnavailable` and `maxSurge` to 3, expecting that there should always be at least `6` nodes UP, which would result in ALL Nodes of the cluster to be rolled in the same time:

```yaml
workers:
- name: worker-c92jz
  autoScalerMin: 9
  autoScalerMax: 9
  maxSurge: 3
  maxUnavailable: 3
zones:
- us-west2-a
- us-west2-b
- us-west2-c
```

**Comment by mvladev** [comment]
A more sane representation would be to have 

```yaml
workers:
- name: worker-a
  autoScalerMin: 3
  autoScalerMax: 3
  maxSurge: 1
  maxUnavailable: 1
  zone: us-west2-a
- name: worker-b
  autoScalerMin: 3
  autoScalerMax: 3
  maxSurge: 1
  maxUnavailable: 1
  zone: us-west2-b
- name: worker-c
  autoScalerMin: 3
  autoScalerMax: 3
  maxSurge: 1
  maxUnavailable: 1
  zone: us-west2-c
```

or something on the line of:

```yaml
workers:
- name: worker-a
  taints: 
  - foo: bar
  kubernetes:
    kubelet: ....
  zones:
  - name: us-west2-a
    maxSurge: 1
    maxUnavailable: 1
    autoScalerMin: 3
    autoScalerMax: 3
  - name: us-west2-b
    maxSurge: 1
    maxUnavailable: 1
    autoScalerMin: 3
    autoScalerMax: 3
  - name: us-west2-c
    maxSurge: 1
    maxUnavailable: 1
    autoScalerMin: 3
    autoScalerMax: 3
```
