### ISSUE TITLE
Volume type overridden for multiple worker pools

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener#1713]
**What happened**:
If we have a Shoot cluster with several worker pools and the pools have different volume types configured than it seems that the volume types will be overridden.

```
spec:
  provider:
    workers:
    - name: worker-1
      machine:
        type: <machine-type>
      volume:
        size: 20Gi
        type: STANADARD
      ...
    - name: worker-2
      machine:
        type: <machine-type>
      volume:
        size: 20Gi
        type: PREMIUM
      ...
```

After creating the shoot resource the worker sections looks like this:
```
spec:
  provider:
    workers:
    - name: worker-1
      machine:
        type: <machine-type>
      volume:
        size: 20Gi
        type: STANDARD
      ...
    - name: worker-2
      machine:
        type: <machine-type>
      volume:
        size: 20Gi
        type: STANDARD
      ...
```

**What you expected to happen**:
Volume type information are applied correctly for each worker pool.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster with two or more worker pools which have each different volume types

**Anything else we need to know?**:
We see this for Azure shoot clusters, but have reproduced it also for other infrastructures like aws.

**Environment**:

- Gardener version: 0.33.0
- Kubernetes version (use `kubectl version`): v1.15.6
- Cloud provider or hardware configuration: multiple, azure, aws for sure
- Others:
