### ISSUE TITLE
SeedAuthorizer restricting gardenlet permission in garden cluster

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#1723]
With #1601 we have introduced the gardenlet, a component comparable with the kubelet in Kubernetes.

Kubernetes has a dedicated [`NodeAuthorizer` admission plugin](https://github.com/kubernetes/kubernetes/tree/master/plugin/pkg/auth/authorizer/node) which ensures that a kubelet responsible for node `X` may only touch resources (like `Pod`s, `Secret`s, etc.) that are related to node `X`.

In our first introduction of the Gardenlet we haven't implemented such mechanism yet.
Instead, similar to Gardener v0 (where the gardener-controller-manager was bound to the `cluster-admin` role), the gardenlet gets full administrator privileges in the garden cluster.

Let's follow Kubernetes' approach and implement a `SeedAuthorizer` admission plugin which ensures that gardenlets only touch resources related to the `Seed`s they are responsible for.

| | Status |
| --- | --- |
| ✅| completed |
| 🚧| in progress |
| ❔| to be clarified |
| ℹ️| interesting, but not relevant (yet) |
| ❌| incomplete |

Prerequisites:
- ✅ Copy secrets into separate and seed dedicated namespace (see https://github.com/gardener/gardener/issues/1725)
- ✅ Transfer Gardener-Admission-Controller into Controller-Runtime handler (see https://github.com/gardener/gardener/issues/3109)

To-Dos:
- ✅ Skeleton for "SeedAuthorizer"  [authorization webhook](https://kubernetes.io/docs/reference/access-authn-authz/webhook/) ➡️ #3571
- ✅ Skeleton for "SeedRestriction" [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) ➡️ #3571
- ✅ Resource Dependency Graph ➡️ #3631 
- ✅ Functionality for identifying seed identity from a user info ➡️ #3671
- ✅ Adapt gardenlet to properly read global secrets from its seed namespace (see #1725)
- ✅ Implementation for various and involved kinds (`CloudProfiles`, `Shoots`, `Secrets`, etc.).
- ✅ Prevent that a gardenlet can issue a certificate for a seed it is not responsible for

**Comment by rfranzke** [comment]
Due to the fact that the `ControllerRegistration` resource may contain sensitive data in its `.spec.deployment.providerConfig` we want to restrict the gardenlet to only access those that are relevant for its own `Seed`.
While looking into implementing this handling in the seed authorizer, I encountered some conceptual issues blocking me from proceeding at the moment.

At the moment, there are several occasions where the gardenlet lists all `ControllerRegistration` resources:

1. Federated seed controller (https://github.com/gardener/gardener/blob/03794c4fab012f16625540cd2989ab8f328be93d/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L96-L102)
   Theoretically, this could be reworked and the listing could be replaced by explicit `GET` requests with the API reader here: https://github.com/gardener/gardener/blob/03794c4fab012f16625540cd2989ab8f328be93d/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L128

1. Shoot controller (https://github.com/gardener/gardener/blob/9f7e1e38dbae4a6466377ecbd68724b0e8221516/pkg/operation/botanist/botanist.go#L156-L159)
   Theoretically, this check could be changed in a way that the gardenlet does only list the `ControllerInstallation`s for its `Seed` before checking that all of them are ready. Obviously, this has the downside that a not yet installed extension might be missed (maybe the cache of the gardenlet wasn't populated yet).

1. Shoot controller (https://github.com/gardener/gardener/blob/9f7e1e38dbae4a6466377ecbd68724b0e8221516/pkg/operation/botanist/extension.go#L32-L35)
   As an alternative, I was thinking about an admission plugin that populates the `Shoot`'s `.spec.extensions[]` with the "globally enabled" extensions. This would prevent the complete necessity for the listing.

For all three occasions, the only reason for the listing is to fetch the information about the `.spec.resources[]`.

I'm not very happy with the proposed alternatives above. Especially, the one for 1. could result in a lot of API calls stressing the Gardener API server.
@timebertt proposed to extract the sensitive information from the `ControllerRegistration` so that the gardenlet is allowed to simply list/watch/get them all and only restricted to access the sensitive information for those which are installed on its `Seed`. I would go one step further and extract the entire deployment section (also including the chart) as this is enlarging the resource anyways and has downsides when controllers watch this resource.

Today, the `ControllerRegistration` looks like this:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  # primary: true|false
  # globallyEnabled: true|false # only valid if kind=Extension
  # reconcileTimeout: 30s # only valid if kind=Extension
  deployment:
    type: helm
    providerConfig:
      chart: |
        H4sIFAAAAAAA/yk...
      values:
        foo: bar
  # policy: OnDemand|Always|AlwaysExceptNoShoots
  # seedSelector:
  #   matchLabels:
  #     foo: bar
```

Concretely, the proposal is now to add a new `ExtensionDeployment` resource to the `core.gardener.cloud/v1beta1` API group:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ExtensionDeployment
metadata:
  name: os-coreos
spec:
  type: helm
  providerConfig:
    chart: |
      H4sIFAAAAAAA/yk...
    values:
      foo: bar
```

This allows to change the `ControllerRegistration` as follows:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
  # primary: true|false
  # globallyEnabled: true|false # only valid if kind=Extension
  # reconcileTimeout: 30s # only valid if kind=Extension
  deploymentRef:
    name: os-coreos
  # policy: OnDemand|Always|AlwaysExceptNoShoots
  # seedSelector:
  #   matchLabels:
  #     foo: bar
```

Like today, the gardenlet's `ControllerInstallation` controller ships a default implementation for `.spec.type=helm`.

Above proposal would allow to keep most of the code as it is.
The only thing that would require adaptation would be the `ControllerInstallation` controller when it fetches the deployment information.
Obviously, a downside is that there are now two resources that must be maintained for an extension registration.

/cc @gardener/gardener-maintainers
