### ISSUE TITLE
Support `metadata.generateName` as alternative to `metadata.name`

### ISSUE THREAD

**Issue by loewenstein** [gardener/gardener#1783]
**What happened**:
I tried to create a shoot with generated name and got an error.
```
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  generateName: prefix  <-------------
  annotations:
    garden.sapcloud.io/purpose: evaluation
spec: <shoot spec>
```

```
error: error when retrieving current configuration of:
Resource: "garden.sapcloud.io/v1beta1, Resource=shoots", GroupVersionKind: "garden.sapcloud.io/v1beta1, Kind=Shoot"
Name: "", Namespace: "<project-namespace>"
Object: ...
from server for: "generate-shoot-name/shoot.yml": resource name may not be empty
```

**What you expected to happen**:
I expected to get a Shoot whose name is generated with "prefix" as a prefix.

**How to reproduce it (as minimally and precisely as possible)**:
1. Login to the Gardener Dashboard
1. Click the "+" sign to create a Shoot
1. Switch to YAML tab
1. remove `metadata.name` and replace it with a `metadata.generateName` key

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.35.4
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: n/a
- Others:
