### ISSUE TITLE
Project deletion can be blocked by BackupEntry

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1784]
**How to reproduce it (as minimally and precisely as possible)**:
1. Create new project `foo`

2. Create Shoot in this project and ensure that the Shoot is created

3. Delete the Shoot

4. Delete the project

5. Ensure that the Project hangs in `Terminating`

```
kubectl api-resources --verbs=list --namespaced -o name \
                                                          | xargs -n 1 kubectl get --show-kind --ignore-not-found -n garden-foo
NAME                                                                                                 BUCKET                                 SEED         OPERATION   PROGRESS   AGE
backupentry.core.gardener.cloud/shoot--foo--bar--25907222-017c-11ea-b7d2-0a580af18e19   22ffba84-9673-11e9-81e7-0a580af18af0   foo-seed   Pending     1          61d
```

The backup entry is with status
```
status:
    lastOperation:
      description: Deletion of backup entry is scheduled for 2020-01-10 13:44:04 +0000
        UTC
      lastUpdateTime: "2020-01-07T23:29:15Z"
      progress: 1
      state: Pending
      type: Delete
    observedGeneration: 318
```

So currently the project deletion will pass after `gardenlet.config.controllers.backupEntry.deletionGracePeriodHours`.

**Environment**:

- Gardener version: 0.33.x
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
