### ISSUE TITLE
Set elasticsearch logging VPA to auto

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener#1789]
**What happened**:
`elasticsearch-logging-0` entered a crashloop backoff due to the `metrics-exporter` sidecar crashing and getting OOM killed. The `metrics-exporter` sidecar has static resources and does not get scaled. We should switch VPA to `auto` for this component to prevent situations like this in the future.
/cc @AndreasBurger

**Comment by rfranzke** [comment]
@wyb1 any progress?

**Comment by vpnachev** [comment]
After a whole day with enabled VPA and `kube-controller` running with flag `-v=10` I got the following resources by the VPA:
```yaml
...
    name: elasticsearch-logging
    resources:
      limits:
        cpu: 7640m
        memory: 2821291347656m
      requests:
        cpu: 163m
        memory: "2407501950"
...
    name: metrics-exporter
    resources:
      limits:
        cpu: 110m
        memory: "47149996"
      requests:
        cpu: 11m
        memory: "23574998"
...
```

The main container `elasticsearch-logging` does not benefit so much - only the cpu limit is increased while the memory is pretty stable. Note, the real usage of cpu is double digit mCPU, so the number  `7640m` seems wrong and too high.

The `metrics-exporter` benefits more, but its resources are pretty low either way.

There is huge disadvantage - the VPA scaling requires pod recreation while the start-up times of the pod is taking a lot of time - between 2 and 4 minutes and this is the expected behavior because of the nature of the elastic search.

My opinion is that VPA must not be enabled for this component, but I would just increase the limits for the `metrics-exporter` here https://github.com/gardener/gardener/blob/7b9b7b98f772fd5d27380d0015c5698df7351076/charts/seed-bootstrap/charts/elastic-kibana-curator/values.yaml#L87-L93
