### ISSUE TITLE
Token volume projection cannot be used to authenticate agains the apiserver

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#1792]
**What happened**:

ID tokens from the ServiceAccount Token Volume projection cannot be used to authenticate against the API server.

**What you expected to happen**:

- Out of the box to be able to create projected volumes with tokens signed by the same key which is used to sign the service account tokens (used in `kube-controller-manager`)
- Said token can be used to authenticate against the `kube-apiserver` and checked against the `TokenReview` API.

**How to reproduce it (as minimally and precisely as possible)**:

Create the following Pod on `1.16` gardener cluster:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: some-token
  volumes:
  - name: some-token
    projected:
      sources:
      - serviceAccountToken:
          path: some-token
          expirationSeconds: 7200
```

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    5m15s                 default-scheduler  Successfully assigned default/nginx to some-node
  Warning  FailedMount  65s (x10 over 5m15s)  kubelet, some-node  MountVolume.SetUp failed for volume "some-token" : failed to fetch token: the server could not find the requested resource
```

Even if the API server is configured correctly https://github.com/gardener/gardener/blob/e796be149ae18fc38768b2888f8610c2b5f9af61/example/90-deprecated-shoot-alicloud.yaml#L120-L123 because the end-user provides the signing key, it cannot be used for authentication as the apiserver is using another public key to check the service account token.

To resolve this, I'll recommend the following:

- out of the box configure the API server with 
  - `--service-account-issuer=https://<SHOOT-DOMAIN>`
  - `--service-account-signing-key-file` to point to the private key used by `kube-controller-manager` to sign SAs.
- deprecate the [signing-key](https://github.com/gardener/gardener/blob/0e1e3eb1925e62515b81cc3b0c4a03b7449190dd/pkg/operation/common/types.go#L464-L465) key and use the standard `cert.key` and `cert.pem` in the ServiceAccountSigningKey data.
- use this public `cert.pem` key as an additional flag `--service-account-key-file`. This will still allow the existing service accounts to work without a problem and the projected ones can be used to authenticate against the `kube-apiserver` or the other system which can check those keys.

**Anything else we need to know?**:

Related issues:
#1073 
#1288

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: n/a
- Others: n/a
