### ISSUE TITLE
shoot.garden.sapcloud.io/expirationTimestamp can be extended to infinity

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1837]
**What happened**:
According to #81, lifetime of a Shoot can be extended only up to `.spec.clusterLifetimeDays` from the current date,  but never more.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create `Quota`
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Quota
metadata:
  name: my-quota
  namespace: garden-dev
spec:
  clusterLifetimeDays: 7
  metrics:
    cpu: "200"
    gpu: "20"
    loadbalancer: "100"
    memory: 4000Gi
    storage.premium: 2000Gi
    storage.standard: 8000Gi
  scope:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Project
```

2. Create `SecretBinding`
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    cloudprofile.garden.sapcloud.io/name: gcp
  name: my-secretbinding
  namespace: garden-dev
quotas:
- name: my-quota
  namespace: garden-dev
secretRef:
  name: my-secret
  namespace: garden-dev
```

3. Create `Shoot` with that `SecretBinding` and ensure that the Shoot gets the annotation `shoot.garden.sapcloud.io/expirationTimestamp="2020-01-29T16:30:57+02:00"`

4. Run `./to-infinity.sh`

```sh
#/bin/bash +e

[[ -z "$1" ]] && echo "no namespace passed" && exit 1
[[ -z "$2" ]] && echo "no shoot name passed" && exit 1

while :
do
  oldExpirationTimestamp=$(kubectl get shoot -n $1 $2 -o jsonpath='{.metadata.annotations.shoot\.garden\.sapcloud\.io/expirationTimestamp}')
  newExpirationTimestamp=$(date --rfc-3339=seconds -d "$oldExpirationTimestamp + 6 day" | sed 's/ /T/')

  kubectl annotate shoot -n $1 $2 shoot.garden.sapcloud.io/expirationTimestamp="$newExpirationTimestamp" --overwrite > /dev/null
  echo "Set the expiration timestamp to $newExpirationTimestamp"

  sleep 1
done
```

```
./to-infinity.sh garden-dev crazy-botany
Set the expiration timestamp to 2020-02-04T16:30:57+02:00
Set the expiration timestamp to 2020-02-10T16:30:57+02:00
Set the expiration timestamp to 2020-02-16T16:30:57+02:00
Set the expiration timestamp to 2020-02-22T16:30:57+02:00
Set the expiration timestamp to 2020-02-28T16:30:57+02:00
Set the expiration timestamp to 2020-03-05T16:30:57+02:00
Set the expiration timestamp to 2020-03-11T16:30:57+02:00
Set the expiration timestamp to 2020-03-17T16:30:57+02:00
Set the expiration timestamp to 2020-03-23T16:30:57+02:00
Set the expiration timestamp to 2020-03-29T17:30:57+03:00
Set the expiration timestamp to 2020-04-04T17:30:57+03:00
Set the expiration timestamp to 2020-04-10T17:30:57+03:00
Set the expiration timestamp to 2020-04-16T17:30:57+03:00
Set the expiration timestamp to 2020-04-22T17:30:57+03:00
Set the expiration timestamp to 2020-04-28T17:30:57+03:00
Set the expiration timestamp to 2020-05-04T17:30:57+03:00
Set the expiration timestamp to 2020-05-10T17:30:57+03:00
Set the expiration timestamp to 2020-05-16T17:30:57+03:00
Set the expiration timestamp to 2020-05-22T17:30:57+03:00
Set the expiration timestamp to 2020-05-28T17:30:57+03:00
Set the expiration timestamp to 2020-06-03T17:30:57+03:00
Set the expiration timestamp to 2020-06-09T17:30:57+03:00
```

And ensure that the expirationTimestamp is delayed in the future not respecting the `Quota` `.spec.clusterLifetimeDays=7`

**Environment**:

- Gardener version: v0.35.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
