### ISSUE TITLE
Add validation about spec.kubernetes.kubeAPIServer.oidcConfig

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1878]
**What would you like to be added**:
1. Create Shoot with the following partial spec included:
```yaml
spec:
  kubernetes:
    kubeAPIServer:
      oidcConfig:
        groupsClaim: groups
        issuerURL: 'https://example.com'
        usernameClaim: email
```

2. Ensure that the kube-apiserver will fail to start with:
```
Error: oidc-issuer-url and oidc-client-id should be specified together
```

Basically the same Shoot will fail to delete as it will wait `kube-apiserver` to report readiness.

We could add validation to check whether `oidcConfig.clientID` is set. Probably the same applies also to the other fields.
