### ISSUE TITLE
Cannot deploy kube-apiserver when HVPA feature gate is false

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#1922]
**What happened**:
To be able to create Shoot with 
```yaml
featureGates:
  HVPA: false
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot

2. Ensure that the creation fails with

```yaml
  lastErrors:
  - description: 'task "Deploying Kubernetes API server" failed: retry failed with
      context deadline exceeded, last error: HorizontalPodAutoscaler.autoscaling "kube-apiserver"
      is invalid: [spec.metrics[0].resource.target.averageUtilization: Required value:
      must set either a target raw value or a target utilization, spec.metrics[1].resource.target.averageUtilization:
      Required value: must set either a target raw value or a target utilization]'
    lastUpdateTime: "2020-02-12T08:14:50Z"
    taskID: Deploying Kubernetes API server
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
