### ISSUE TITLE
Ingress hostname very long, little space for service names left

### ISSUE THREAD

**Issue by schulzh** [gardener/gardener#199]
The default hostname generated for the ingress controller is quite long, in our case 55 characters: `ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com`
As TLS certificates only allow for 63 characters long hosts, this leaves in our case only 7 characters of usable length for the service name.
While in theory it should be possible to use SANs for longer names, Letsencrypt for example does not allow that either:
```
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: long-tls-test
spec:
  secretName: vault-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dummy.ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com
  dnsNames:
  - a-really-long-name.ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dummy.ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com
      - a-really-long-name.ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com
```
results in
```
Error preparing issuer for certificate: error presenting acme authorization for domain "a-really-long-name.ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com": error ensuring http01 challenge
service: Service "cm-long-tls-test-2-jqxqk" is invalid: [metadata.labels: Invalid value: "a-really-long-name.ingress.ngom-eu.ngom.shoot.canary.k8s-hana.ondemand.com": must be no more than 63 characters, spec.selector: Invalid value: "a-really-long-name.ingress.ngom-eu.ngom.sho
ot.canary.k8s-hana.ondemand.com": must be no more than 63 characters]
```

One solution would be to have a wildcard certificate for the ingress domain (which itself still needs to be shorter than 61 characters in that case), but for Letsencrypt this needs to be created using the DNS-01 challenge, which requires the modification of the zonefile which is not managed in the consumer AWS account.

So it would be easiest to just have a shorter ingress name overall. While users can influence the account and cluster name, the following improvements could be made from Gardeners side:
* Replace "ingress" by "ing" or something similar.
* Remove the "shoot" part from the hostname.
* Remove the "-hana" from the hostname. It is misleading anyways.
