### ISSUE TITLE
Allow fine-granular configuration of multi-zone worker pools

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2014]
**What would you like to be added**:
As of today, when a worker pool is split across multiple zones, then Gardener/the `Worker` extension does automatically calculate the respective `minimum`, `maximum`, `maxSurge`, and `maxUnavailable` values in a balancing manner:

```yaml
workers:
- name: worker-c92jz
  minimum: 9
  maximum: 9
  maxSurge: 3
  maxUnavailable: 3
  zones:
  - us-west2-a
  - us-west2-b
  - us-west2-c
```

However, some users want to have more fine-granular configuration.

See related thread: https://github.com/gardener/machine-controller-manager/issues/400

[@mvladev suggested](https://github.com/gardener/machine-controller-manager/issues/400#issuecomment-562624529) the following adaptation to allow this:

```yaml
workers:
- name: worker-a
  taints: 
  - foo: bar
  kubernetes:
    kubelet: ....
  zoneConfig:
  - name: us-west2-a
    maxSurge: 1
    maxUnavailable: 1
    minimum: 3
    maximum: 3
  - name: us-west2-b
    maxSurge: 1
    maxUnavailable: 1
    minimum: 3
    maximum: 3
  - name: us-west2-c
    maxSurge: 1
    maxUnavailable: 1
    minimum: 3
    maximum: 3
```

The `zoneConfig[].{maxSurge,maxUnavailable,minimum,maximum}` fields should be optional. If they are present for ALL zones then they should be considered instead of applying above-mentioned balancing logic. If they are only added for a few zones then a validation error should happen, i.e., the following should not be allowed:

```yaml
workers:
- name: worker-a
  taints: 
  - foo: bar
  kubernetes:
    kubelet: ....
  zoneConfig:
  - name: us-west2-a
    maxSurge: 1
    maxUnavailable: 1
    minimum: 3
    maximum: 3
  - name: us-west2-b
  - name: us-west2-c
```

**Why is this needed**:
Give users more control.

**Comment by hardikdr** [comment]
I am curious, what value does [2] bring over [1].
- [1] being already available in Gardener. 

1. Worker-pool per zone.
```
workers:
- name: worker-a
  autoScalerMin: 3
  autoScalerMax: 3
  maxSurge: 1
  maxUnavailable: 1
  zone: us-west2-a
- name: worker-b
  autoScalerMin: 3
  autoScalerMax: 3
  maxSurge: 1
  maxUnavailable: 1
  zone: us-west2-b
- name: worker-c
  autoScalerMin: 3
  autoScalerMax: 3
  maxSurge: 1
  maxUnavailable: 1
  zone: us-west2-c
```

2. Multi-zonal worker-pools. 
```
workers:
- name: worker-a
  taints: 
  - foo: bar
  kubernetes:
    kubelet: ....
  zoneConfig:
  - name: us-west2-a
    maxSurge: 1
    maxUnavailable: 1
    minimum: 3
    maximum: 3
  - name: us-west2-b
  - name: us-west2-c
```

One important benefit I could think of is, better UX. 
- The user doesn't need to really replicate the taints/labels/maxSurge info all across.

Wondering if technically, it would make any difference in respecting PDBs.
- In multi-zonal worker-pools, I would still expect all the MachineDeployments to be rolled-out simultaneously. Though the parallel drain will ensure that PDBs are not violated if set appropriately.

Asking just to understand, if MCM/CA is expected to behave any different with this change mainly wrt maintaining the PDBs. :)

**Comment by rfranzke** [comment]
I think the main benefit is that the settings (taints, kubelet flags, labels, etc.) don't need to be replicated "just because" the pool shall be distributed across zones.

Regarding PDBs, you are the expert. Technically, for each zone a dedicated machine deployment must be created no matter how we change the worker spec.

**Comment by mvladev** [comment]
There must also be rollout of `MachineDeployments`. If specify 3 zones = 3 `MachineDeployments`. If I specify 

```
- name: worker-c92jz
  minimum: 9
  maximum: 9
  maxSurge: 3

**Comment by mvladev** [comment]
There must also be rollout of `MachineDeployments`. If specify 3 zones = 3 `MachineDeployments`. If I have the following

```yaml

- name: worker-a
   maxSurge: 1
   maxUnavailable: 1
  taints: 
  - foo: bar
  kubernetes:
    kubelet: ....
  zoneConfig:
  - name: us-west2-a
  - name: us-west2-b
  - name: us-west2-c
```

I would expect that only *one* machine from this entire worker set is unavailable at all time. This means that I update the machine image in it, gardener would first update the `MachineDeployment` for `us-west2-a`, and after it succeeds, `us-west2-b` and so...
