### ISSUE TITLE
addons-kyma ManagedResource is with condition ResourcesApplied=False

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2033]
**What happened**:
addons-kyma ManagedResource is with condition ResourcesApplied=False.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot with annotation `experimental.addons.shoot.gardener.cloud/kyma: enabled` and all kyma requirements configured - `shoot-dns-service` enabled, `shoot-cert-service` enabled, `.spec.allowPrivilegedContainers=true`.]

2. Ensure that the `addons-kyma` ManagedResource is with condition ResourcesApplied=False

```yaml
status:
  conditions:
  - lastTransitionTime: "2020-03-11T09:44:22Z"
    lastUpdateTime: "2020-03-11T09:46:22Z"
    message: All resources are healthy.
    reason: ResourcesHealthy
    status: "True"
    type: ResourcesHealthy
  - lastTransitionTime: "2020-03-11T09:45:22Z"
    lastUpdateTime: "2020-03-11T09:46:47Z"
    message: Could not apply all new resources
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
```

gardener-resource-manager logs:

```
{"level":"error","ts":"2020-03-11T09:46:06.327Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"resource-controller","request":"shoot--foo--bar/addons-kyma","error":"Errors occurred during applying: [error during apply of object \"batch/v1/Job/kyma-installer/kyma-initializer-tiller-1.10.0\": Job.batch \"kyma-initializer-tiller-1.10.0\" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{\"app\":\"kyma-initializer\", \"shoot.gardener.cloud/no-cleanup\":\"true\"}: `selector` does not match template `labels`, spec.selector: Invalid value: \"null\": field is immutable, spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"kyma-initializer-tiller\",
```

Actually the above log fails to apply job `kyma-initializer-tiller-1.10.0` which is already applied and present on the Shoot:
```
$ k get jobs -n kyma-installer
NAME                                   COMPLETIONS   DURATION   AGE
kyma-initializer-installation-1.10.0   0/1           10m        11m
kyma-initializer-tiller-1.10.0         0/1           10m        11m
```

That makes me think that the initial apply is successful but the subsequent are not. From the gardener-resource-manager the initial apply is successful but the next ones are not.

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
