### ISSUE TITLE
Use PodSecurityPolicies for enabling/disabling privileged containers

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#211]
We allow to specify in the [`Shoot` resource](https://github.com/gardener/gardener/blob/master/pkg/apis/garden/v1beta1/types.go#L963-L965) whether to enable/disable privileged containers. Until Kubernetes v1.13.0 the way to enable/disable them is to provide the `--allow-privileged` flag to the kubelet. However, this flag is already deprecated will be removed in v1.13.0: https://github.com/kubernetes/kubernetes/blob/v1.11.0-beta.2/cmd/kubelet/app/options/options.go#L427-L429

We have to move to [`PodSecurityPolicies`](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) to keep the behaviour. However, we need to make sure that the user experience keeps the same like now, that the Kubernetes controllers are not blocked and that we can keep deploying our (privileged) system components into the Shoot.

@mvladev You have already looked into the topic some months back, could you help here?

**Comment by mvladev** [comment]
The idea is to have at least 2 PSPs - one _privileged_ (full permissions) and _restricted_ (limited to the absolute minimum).

By default we should grant the _privileged_ PSP to all authenticated users + administrators (not breaking existing users and administrators)
By default we should grant the _restricted_ PSP to all authenticated users + administrators (not breaking existing users and administrators)

If administrators want to enforce restrictive permissions, then they should edit the _privileged_ PSP `ClusterRoleBinding` and remove the all authenticated users from `subject`.

**Comment by rfranzke** [comment]
@thormaehlenfred maybe you could work together with Martin here?

**Comment by ThormaehlenFred** [comment]
@mvladev so your proposal is the following if I understand you correctly. 
Given a privileged PSP `ClusterRoleBinding` would look like this:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:privileged
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user
subjects:
- kind: Group
  # All authenticated users are allowed to use this.
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io

```
then you would simply advise the administrator via documentation to comment or delete the last lines from the `subject`
```
subjects:
- kind: Group
  # All authenticated users are allowed to use this.
  # name: system:authenticated
  # apiGroup: rbac.authorization.k8s.io
```
The consequence would be: 

1. privileged PSP ([example](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/privileged.yaml)) is granted only to administrators (potentially breaking existing users but not administrators)
2. restricted PSP ([example](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/podsecuritypolicies/unprivileged-addon.yaml)) is still granted to all authenticated users + administrators (not breaking existing users and administrators)

Is my understanding correct?
