### ISSUE TITLE
Shoot cannot be deleted if the InfrastructureConfig is mis-configured

### ISSUE THREAD

**Issue by aylei** [gardener/gardener#2139]
**What happened**:
Shoot cannot be deleted if the InfrastructureConfig is mis-configured, the error is:

```
Last Error
task "Waiting until shoot infrastructure has been reconciled" failed: failed to create infrastructure: retry failed with context deadline exceeded, last error: extension encountered error during reconciliation: Error reconciling infrastructure: no kind "InfrastructureConfig" is registered for version "aws.provider.extensions.gardener.cloud/v1alpha1" in scheme "github.com/gardener/gardener-extension-provider-gcp/pkg/apis/gcp/helper/scheme.go:45"
```

**What you expected to happen**:
The shoot is deleted successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot with mis-configured `InfrastructureConfig` and delete the shoot.
```
....
  provider:
    type: gcp
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      networks:
        worker: ''
        workers: 10.250.0.0/16
```

**Anything else we need to know?**:
We use a go client to create shoots (the error would not have happened if we use the gardener UI), and a code bug causes the GCP shoots are created with the aws `InfrastructureConfig`

**Environment**:

- Gardener version: `v1.0.4`
- Kubernetes version (use `kubectl version`): `v1.16.7`
- Cloud provider or hardware configuration: GCP
