### ISSUE TITLE
Workers count is limited by cloud-config Secret size limit

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2168]
**What happened**:
Currently it is not possible to have more than 20-25 (depending on the OS) workers in `.spec.provider.workers`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with 25 Worker entries under `.spec.provider.workers`.

2. Ensure that the `Deploying managed resources` step fails with:

```yaml
status:
  lastErrors:
  - description: 'task "Deploying managed resources" failed: retry failed with context
      deadline exceeded, last error: Secret "managedresource-shoot-cloud-config-execution"
      is invalid: data: Too long: must have at most 1048576 characters'
    lastUpdateTime: "2020-04-09T11:08:27Z"
    taskID: Deploying managed resources
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.2.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
