### ISSUE TITLE
Allow better control for extension controller deployment

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2180]
**What would you like to be added**:
1. Let's lift the restriction that there is only exactly one registered extension for each `kind/type` combination.
1. Allow to not specify any `.spec.resources` (if not yet allowed)
1. Let's enhance the `ControllerRegistration` specification to allow better control for how/when extensions are deployed:

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: os-coreos
spec:
  resources:
  - kind: OperatingSystemConfig
    type: coreos
    primary: true # new
  deployment:
    policy: OnDemand # new
    seedSelector: # new
      matchLabels:
        foo: bar
    type: helm
    providerConfig:
      chart: |
        H4sIFAAAAAAA/yk...
      values:
        foo: bar
```

* The `.spec.resources[].primary` field defaults to `true`. The validation should ensure that there is only exactly one registration with `primary=true` for each `kind/type` combination.
* The `.spec.deployment.policy` defaults to `OnDemand` and controls the policy for the deployment. `OnDemand` is what is currently implemented. Another allowed value is `Always` that tells that extension shall be deployed to each seed independent of whether it's needed for the particular reconciliation of a `BackupBucket`/`BackupEntry`/`Shoot`. 
* The `.spec.deployment.seedSelector` field controls which seeds are targeted. By default all seeds are targeted as the field is optional.

**Why is this needed**:
With #1993 the extension controllers registered via `ControllerRegistration` resources are no longer deployed by default to every seed cluster. Instead, the needed extensions for the reconciliation of a `BackupBucket`/`BackupEntry`/`Shoot` are computed and (un-)installed on-demand.
Also, currently the code is assuming that for each `kind/type` combination there is exactly one registration. While there should only be exactly one controller responsible for the reconciliation of an extension resource this breaks scenarios where secondary controllers (that just listen for example `Infrastructure` resource) can be installed as well.
We should allow better control so that more use-cases can be implemented.

Also interesting/related in this context: #1581
