### ISSUE TITLE
Replace the `use-as-seed` annotation with a `spec` field

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2181]
**What would you like to be added**:
In order to mark shoots to be used as seed we have the `shoot.gardener.cloud/use-as-seed` annotation. It allows a historically grown, meanwhile awkward, comma-separated list of options.
Let's replace this annotation with a field in the `ShootSpec` where we embed the `SeedSpec` and which will allow to set/control every field of the seed configuration:

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: crazy-botany
  namespace: garden-dev
spec:
  secretBindingName: my-provider-account
  cloudProfileName: cloudprofile1
  region: europe-central-1
  shootedSeed:
    metadata:
      labels:
        foo: bar
    spec:
      provider:
        providerConfig:
          foobar
      taints:
      - key: seed.gardener.cloud/protected  
  ...
```

The `.spec.shootedSeed` field should probably be of `runtime.RawExtension` so that the OpenAPI generation is bypassed. Otherwise, if we would simply inline the `SeedSpec`, several fields would be required to set which don't make sense to set in the shooted-seed case. The other option, not preferred option, is to duplicate the `SeedSpec` and make all fields optional.

It should only be possible to set this field if the `Shoot`'s `namespace` is `garden`.

**Why is this needed**:
Cleaner and easier configuration.

/kind cleanup
