### ISSUE TITLE
Just upgrade the machine-controller-manager component

### ISSUE THREAD

**Issue by qiffang** [gardener/gardener#2186]
I use gardener to manage our kubernetes clusters.
I seems that this PR (
#414) support local ssd for GCP. I just want to upgrade machine-controller-manager and i have build the image with machine-controller-manager latest code. But how should i update the image version of machine-controller-manager in gardener?

Thanks

**Comment by vpnachev** [comment]
You can [overwrite images](https://github.com/gardener/gardener-extension-provider-gcp/blob/2029a82003ed2b533143ab0db77e464e5572d0c7/charts/gardener-extension-provider-gcp/values.yaml#L32-L43) deployed by the provider extension, e.g. you can provide your own build of the MCM.  Here is the default list of images used by the provider https://github.com/gardener/gardener-extension-provider-gcp/blob/master/charts/images.yaml

**Comment by vpnachev** [comment]
I am closing now the issue, if you need - please re-open it.

**Comment by qiffang** [comment]
Hi @vpnachev 
I try to edit `gardener-extension-provider-gcp ` deployment to add overwrite images, but it always be modified back.
```
kubectl edit deploy gardener-extension-provider-gcp -n extension-provider-gcp-2x6xs 
```

**Comment by timebertt** [comment]
Hi @qiffang 

the provider extension resources (specified in the provided chart of the `ControllerRegistration`) are deployed via a `ManagedResource` and reconciled back by [gardener-resource-manager](https://github.com/gardener/gardener-resource-manager).
You can overwrite chart values directly in the `ControllerRegistration` like this, which will be propagated to all `ControllerInstallations`/`Seeds`:

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: provider-gcp
spec:
  resources:
  - kind: BackupBucket
    type: gcp
  - kind: BackupEntry
    type: gcp
  - kind: ControlPlane
    type: gcp
  - kind: Infrastructure
    type: gcp
  - kind: Worker
    type: gcp
  deployment:
    type: helm
    providerConfig:
      chart: "<base64 encoded chart>"
      values:
        image:
          tag: v1.5.1
        imageVectorOverwrite: |
          images:
          - name: machine-controller-manager
            repository: your-repo/machine-controller-manager
            sourceRepository: github.com/gardener/machine-controller-manager
            tag: your-image-tag
```
