### ISSUE TITLE
Shoot deletion flow fails to delete VolumeSnapshot CRDs

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2227]
**What happened**:
Currently during Shoot deletion we delete resources such as Services, Deployments, PVCs, etc. The user may also have `VolumeSnapshot`s as we already have multiple provider extensions supporting CSI and `VolumeSnapshot`s.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot.

2. Create a `VolumeSnapshot`.

3. Delete the Shoot.

4. As the `volumesnapshots.snapshot.storage.k8s.io` CRD is triggered for deletion, the `VolumeSnapshot` CR deletion fails with:
```yaml
  status:
    boundVolumeSnapshotContentName: snapcontent-e12bf34c-a377-44ce-9873-0b0b74670252
    creationTime: "2020-04-23T19:33:59Z"
    error:
      message: Failed to get snapshot class with error volumesnapshotclass.snapshot.storage.k8s.io
        "default-snapshot-class" not found
      time: "2020-04-23T19:52:31Z"
    readyToUse: false
    restoreSize: 6Gi
```

```
$ k get crds
NAME                                             CREATED AT
volumesnapshotcontents.snapshot.storage.k8s.io   2020-04-23T18:38:11Z
volumesnapshots.snapshot.storage.k8s.io          2020-04-23T18:38:11Z
```

As you can see, the `volumesnapshotclass.snapshot.storage.k8s.io` CRD is already deleted.

5. Ensure that the `volumesnapshots.snapshot.storage.k8s.io` CRD will be finalized after 1h and the respective VolumeSnapshot will leak.

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
