### ISSUE TITLE
Controller restart in maintenance time window does not work

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2228]
**What happened**:
With #2098, #2116 a feature was contributed that enables auto-restart of controllers in the shoot maintenance time window. However, it seems that there is a bug. I'm having a shoot that was reconciled `8h` ago: 

```yaml
  lastOperation:
    description: Shoot cluster state has been successfully reconciled.
    lastUpdateTime: '2020-04-23T21:01:23Z'
    progress: 100
    state: Succeeded
    type: Reconcile
```

However, the {kube,cloud}-controller-managers run since 31h:

```shell
$ kubectl -n shoot--foo--bar get pod | grep controller-m
cloud-controller-manager-749ccfc56f-ndjt7     1/1     Running     0          31h
kube-controller-manager-84d47674b6-4w8pw      1/1     Running     0          31h
```

**What you expected to happen**:
The controller-managers should have been restarted `8h` ago. The 

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot and enable the `enableShootControlPlaneRestarter` flag in GCM config:

```yaml
    apiVersion: controllermanager.config.gardener.cloud/v1alpha1
    kind: ControllerManagerConfiguration
    controllers:
      shootMaintenance:
        concurrentSyncs: 200
        enableShootControlPlaneRestarter: true
```

**Anything else we need to know?**:
/cc @timuthy 

**Environment**:

- Gardener version: v1.3.0
- Kubernetes version (use `kubectl version`): v1.14.0
- Cloud provider or hardware configuration: AWS

**Comment by rfranzke** [comment]
It seems that this issue not related to the controller-restart feature but to the maintenance in general. The `lastOperation` of the `Infrastructure` is:

```yaml
status:
    lastOperation:
      description: Successfully reconciled infrastructure
      lastUpdateTime: "2020-04-22T21:13:45Z"
      progress: 100
      state: Succeeded
      type: Reconcile
```

However, it should be `2020-04-23`. Investigating further...
