### ISSUE TITLE
recent secrets are still not picked up by Admission controllers #223

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#227]
This is a followup after "Admission controllers don't pick up recent secrets in k8s cluster #223".

As indicated by @rfranzke in #223, I deployed gardener-apiserver and gardener-contoller-manager with the image `0.7.0-d0f1fda30b679c730680af3355bfa1424fe4f37e`.

# Steps to repeat the problem

Crate a test project:

```yaml
cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: secret-test
  labels:
    garden.sapcloud.io/role: project
    project.garden.sapcloud.io/name: secret-test
EOF
```

Prepare test manifest just with a `Secret` and a `SecretBinding`

```yaml
cat << EOF > secret-test-manifest.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: testN
  namespace: secret-test
  labels:
    cloudprofile.garden.sapcloud.io/name: azure
type: Opaque
data:
  key: dmFs
---
apiVersion: garden.sapcloud.io/v1beta1
kind: SecretBinding
metadata:
  name: testN
  namespace: secret-test
  labels:
    cloudprofile.garden.sapcloud.io/name: azure # label is only meaningful for Gardener dashboard
secretRef:
  name: testN
quotas: []
EOF
```

Re-run this command as much as you want, all will fail:

```bash
let i++; sed "s/testN/test$i/" secret-test-manifest.yaml | kubectl apply -f -
```

Here is an example output:

```bash
$ let i++; sed "s/testN/test$i/" secret-test-manifest.yaml | kubectl apply -f -
secret "test11" created
Error from server (Forbidden): error when creating "STDIN": secretbindings.garden.sapcloud.io "test11" is forbidden: secret "test11" not found
```

For more details about how we deploy gardener, you can see the gardener chart values file in this gist: https://gist.github.com/bergerx/794957a55a315d5038db9f03c3a89413

And this is how we deploy/update gardener:

```
helm upgrade --install \
  -f gardener-values.yaml \
  -f gardener-values-secrets.yaml \
  --namespace garden \
  garden ~/git/gardener/charts/gardener
```
