### ISSUE TITLE
Do not pardon False ConditionStatus for recently created Shoots

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2295]
**What happened**:
We currently pardon transition to False ConditionStatus (set it back to Progressing) when Shoot `.status.lastOperation.type=Create`.

**What you expected to happen**:
We should not pardon similar transition when  `.status.lastOperation.type=Create` and `.status.lastOperation.state=Succeeded`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot.

2. Scale the kube-apiserver to 0 replicas to simulate condition fail.

```
$ k -n shoot--foo--bar scale deploy kube-apiserver --replicas=0
deployment.extensions/kube-apiserver scaled
```

3. Ensure that the condition won't switch to False after threshold duration and will stay in Progressing.

```yaml
status:
  conditions:
    - type: APIServerAvailable
      status: Progressing
      lastTransitionTime: '2020-05-06T21:03:32Z'
      lastUpdateTime: '2020-05-06T21:03:32Z'
      reason: APIServerDown
      message: Could not reach API server during client initialization.
# ...
  lastOperation:
    description: Shoot cluster state has been successfully reconciled.
    lastUpdateTime: '2020-05-06T20:21:38Z'
    progress: 100
    state: Succeeded
    type: Create
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.3.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
