### ISSUE TITLE
Integrate essential secondary controllers into the Gardener extension reconciliation flow

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2302]
**What would you like to be added**:
Make it possible to register extension-controllers that can "hook" into the reconciliation flow of Extension CRDs of the Gardenlet. Secondary controllers that are essential for the Shoot reconcile can then be included in an extensible way / registered at runtime trough ControllerRegistrations.

**Why is this needed**:

In certain cases, in addition to the standard Gardener extension reconciliation, there can be another (secondary) extension that is required for the Shoot to be successfully created / deleted / reconciled.

This is for instance the case when deploying Gardener in an environment that relies on private DNS zones that need to be associated with the Shoot VPC and Seed VPC. The secondary controllers would also reconcile the infrastructure CRD. If this VPC assignment is missing because the reconcile of the secondary controller errors, the worker nodes cannot join in a later step. Hence there are use-cases for (secondary) extension controllers that are essential to the Shoot flow.

The above mentioned use case is only one, and we do not know in which environment people want to operate Gardener in.

This is why I think we need to have a way of integration essential secondary controllers into the Gardener extension reconciliation flow. 

**Possible solution**

Extension controllers could write a certain condition.Type in the status of the Extension CRD,  that if exist, needs to indicate success, in order for the Gardenlet to continue the reconcile.

``` yaml
    lastTransitionTime: "xx"
    lastUpdateTime: "xx"
    message: VPC 'xy' successfuly attached to private hosted zone 'xyz'.
    reason: xxx
    status: "True"
    type:  PrivateZoneAttached
```

In order for the Gardenlet to know which condition.type to consider, the controller could be registered as a ["secondary" controller for the kind/type combination](https://github.com/gardener/gardener/pull/2278#pullrequestreview-407388628) (for instance aws-infrastructure).
The Registration then could also contain an additional field

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: private-zone-controller
spec:
  resources:
  - kind: Infrastructure
     type: aws
     primary: false
     isEssential: true # new
     conditionTypes:   # new
        - PrivateZoneAttached
  - kind: DNSProvider
     type: aws
     primary: false
  deployment:
    type: helm
    providerConfig:
      chart: |
        H4sIFAAAAAAA/yk...
    policy: Always  # essential for the Shoot flow, so always install it on each Seed
```

@AndreasBurger @ThormaehlenFred this helps for the AWS gov-cloud use-case in case the private-zone-controller is not working.
