### ISSUE TITLE
`.spec.seedSelector` for `Shoot` resources

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#2306]
**What would you like to be added**:
Give users the ability to select access restrictions (for gardener operators) for their shoot, depending on the selected region.
E.g. on the UI it could look like the following (texts are just an example and for better understanding of the requested feature and will be configurable in the Dashboard)
<img width="1751" alt="Screenshot 2020-05-08 at 15 35 43" src="https://user-images.githubusercontent.com/5526658/81410806-a7108180-9141-11ea-8c72-ab1888fc65ad.png">
https://github.com/gardener/dashboard/issues/689

**UPDATE**: see https://github.com/gardener/gardener/issues/2306#issuecomment-626781778 for latest proposal

~~The selected options should be added to the shoot spec as following:~~
```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-bar
  name: foo
spec:
  accessRestrictions:
    eu-access-standard:
    - eu-access-24-7-node
    foo: []
```

~~In addition, the `region` of the `CloudProfile` has to be extended with an `accessRestrictions` field.~~
- ~~This way we can validate the shoot resource and only allow the change if the region has a corresponding accessRestrictions field in the CloudProfile~~
- ~~On the UI the checkboxes would only appear only for the respective regions.~~

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
name: aws
regions:
  - name: ca-central-1
    zones:
    - name: ca-central-1a
    - name: ca-central-1b
  - name: eu-central-1
    accessRestrictions:
      - eu-access-standard
      - foo
    zones:
    - name: eu-central-1a
    - name: eu-central-1b
    - name: eu-central-1c
  - name: eu-north-1
    accessRestrictions:
      - eu-access-standard
    zones:
    - name: eu-north-1a
    - name: eu-north-1b
    - name: eu-north-1c
```

~~As described above the shoot validation needs to be extended so that in case an `accessRestriction` is set, it ensures that the selected region has a corresponding accessRestrictions field in the corresponding `CloudProfile`~~

**Why is this needed**:
In order to fulfil GDPR requirements, shoot owners should have the possibility to restrict access to their shoots in order to protect personal data.

**Comment by vlerenc** [comment]
Thank you, great! If you want to be open for the future and the taints/tolerations idea makes no sense/cannot be put into action, then maybe `annotations` instead of `accessRestrictions` would be more flexible. Also, why is it `eu-access-standard` and not `eu-access`? And how would the shoot spec look in more details in regards to the 8x5 bullet points? BTW, I would call them rather ...`-cluster-addons` and ...`-cluster-nodes`. WDYT?

**Comment by petersutter** [comment]
see reply here https://github.com/gardener/dashboard/issues/689#issuecomment-625982838

**Comment by rfranzke** [comment]
Please see https://github.com/gardener/dashboard/issues/689#issuecomment-626716750 for the latest and signed-off proposal how to implement it.

For gardener/gardener, we concretely need to

1. add `.spec.seedSelector` to the `Shoot` specification which allows to provide a label selector for seeds (similar to how `.spec.nodeSelector` in the `Pod` specification allows to provide a label selector for nodes):
```yaml
spec:
  seedSelector:
    matchLabels:
      seed.gardener.cloud/eu-access: true
```

2. add `.spec.regions[].labels` to the `CloudProfile` specification that shows end-users which regions are eligible for EU access (from gardener’s API PoV it’s just a `map[string]string`):
```yaml
spec:
 regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    labels:
      seed.gardener.cloud/eu-access: true
```

3. enhance the gardener-scheduler to evaluate the `seedSelector` if present and find an appropriate seed based on the label selector

See also: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
