### ISSUE TITLE
Allow configuration of load balancer service annotations per seed

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2318]
**What would you like to be added**:
Let's enhance the `gardencorev1beta1.Seed` object and allow to configure a list of annotations that Gardener will add to every `Service` of type `LoadBalancer` in this seed (e.g., the kube-apiserver services, ingresses load balancers, VPN load balancers, etc.).

#2315 will introduce a new `.spec.settings` field that can be enhanced:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Seed
metadata:
  name: my-seed
spec:
  provider:
    type: <provider-name> # e.g., aws, azure, gcp, ...
    region: europe-1
  ...
  settings:
    ...
    loadBalancerServices:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:xx-xxxx-x:xxxxxxxxx:xxxxxxx/xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx #replace this value
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
```

The seed and shoot controller will simply add the given annotations to all load balancer services.

**Why is this needed**:
Any existing Kubernetes cluster can be connected to a Gardener system by either providing the kubeconfig or by deploying the Gardenlet into it. However, based on the underlying infrastructure it is sometimes required to deviate from the default load balancer configuration, e.g. in order to make them accessible or to configure certain properties in a different way.
