### ISSUE TITLE
"Deploying Kubernetes API server" fails

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2319]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot

2. Ensure `.status.lastErrors`:
```yaml
  lastErrors:
  - description: 'task "Deploying Kubernetes API server" failed: retry failed with
      context deadline exceeded, last error: failed to apply manifests: 1 error occurred:
      could not apply object of kind "Deployment" "shoot--foo--bar/kube-apiserver":
      Deployment.apps "kube-apiserver" is invalid: [spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight:
      Invalid value: 0: must be in the range 1-100, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey:
      Required value: can not be empty, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey:
      Invalid value: "": name part must be non-empty, spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.topologyKey:
      Invalid value: "": name part must consist of alphanumeric characters, ''-'',
      ''_'' or ''.'', and must start and end with an alphanumeric character (e.g.
      ''MyName'',  or ''my.name'',  or ''123-abc'', regex used for validation is ''([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'')]'
```
**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
