### ISSUE TITLE
Extend the Shoot API so that users can provide secret data to extension configurations via references

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#2321]
**What would you like to be added**:
Extend the `Shoot` API to support adding secrets data required by various `Shoot` components (dns, provider configurations, extension configurations) via secret references.
 
**Why is this needed**:
Currently some extension configurations could require secret data which has to be specified directly in the `Shoot`'s spec. For example:
```
apiVersion: shoot-cert-service.extensions.config.gardener.cloud/v1alpha1
kind: Configuration
issuerName: gardener
restrictIssuer: true # restrict issuer to any sub-domain of shoot.spec.dns.domain (default)
acme:
  email: john.doe@example.com
  server: https://acme-v02.api.letsencrypt.org/directory
# privateKey: | # Optional key for Let's Encrypt account.
#   -----BEGIN BEGIN RSA PRIVATE KEY-----
#   ...
#   -----END RSA PRIVATE KEY-----
```
To avoid this, references to secrets should be used instead. This means that the way it is currently done for the `dns` configuration should be changed so that required secrets are defined in a homogeneous way.

**Proposal**:
The `Shoot` spec has a new field similar to `Pod`'s `Volumes` which lists all the secrets that can be used by `Shoot` components. The example below shows how this could look for the certificate service extension and dns configuration:

```
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
spec:
  dns:
    domain: crazy-botany.core.my-custom-domain.com
    providers:
    - type: aws-route53
       secretName: domain-secret
  extensions:
  - type: shoot-cert-service
    providerConfig:
      apiVersion: shoot-cert-service.extensions.config.gardener.cloud/v1alpha1
      kind: Configuration
      issuerName: gardener
      restrictIssuer: true # restrict issuer to any sub-domain of shoot.spec.dns.domain (default)
      acme:
        email: john.doe@example.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeyRef:
          secretName: private-key
  kubernetes:
    version: 1.18.2
  ...
  Secrets:
  - name: private-key
    secretName: my-lets-encrypt-private-key
  - name: domain-secret
    secretName: my-domain-secret
```

The secrets are created by the user and stored in the `project`'s namespace on the garden cluster. During reconciliation they are copied to the `Shoot`'s namespace on the seed cluster.

**Note**
If we need to provide other objects then we could change the name of the spec.`Secrets` field and it could look like this
```
resources:
- name: private-key
  secret:
    secretName: my-lets-encrypt-private-key
```

**Comment by timebertt** [comment]
Thanks for the proposal, sounds promising FMPOV.
I would probably go with `resources` directly to have a more generic concept to keep our options open for other resources, a Shoot might need. Though, I have no strong opinion regarding the naming of this new section.
If we decide to do so, we should probably also name the referencing fields (e.g. `acme.privateKeyRef.secretName` in your proposal) to something more generic like `resourceName`/`resourceRef` or even `resourceMount`.

**Comment by rfranzke** [comment]
What about

```yaml
resources:
- name: <some-name>
  apiVersion: v1
  kind: Secret
  name: my-lets-encrypt-private-key
```

> If we decide to do so, we should probably also name the referencing fields (e.g. acme.privateKeyRef.secretName in your proposal) to something more generic like resourceName/resourceRef or even resourceMount.

+1, with `resourceRef` it'd be more generic.

**Comment by timebertt** [comment]
> What about
> 
> ```yaml
> resources:
> - name: <some-name>
>   apiVersion: v1
>   kind: Secret
>   name: my-lets-encrypt-private-key
> ```

Hmm, you have a duplicated key `name` in your list entry, so this won't work, at least in this exact form :)

Still, I rather tend to use something like @plkokanov suggested (with `resources[].secret.secretName`), as we will most probably have a very limited number of resource types we want to support and this could indeed be done very similarly to `v1/Pod.spec.volumes[].secret.secretName`.

**Comment by rfranzke** [comment]
Yeah, we can rename the second `name` to `resourceName` or so. I'm still in favour with this solution because we don't have to adapt our code (maybe only the validation, but not our API/controller) if we want to add a new resource (other than secrets). The `.spec.volumes` field in the `Pod` looks like this for legacy reasons, I'd assume. They cannot change it anymore now, but I'm pretty sure that if they'd redesign it they'd do it like above (see also newer resources like HPA with their `.spec.targetRef`, etc.).

**Comment by timebertt** [comment]
> because we don't have to adapt our code [...] see also newer resources like HPA with their .spec.targetRef, etc.

Good point, agreed. So the respective golang type will look something like this, right?
```go
type ShootResource struct {
	corev1.CrossVersionObjectReference `json:",inline"`

	ResourceName string `json:"resourceName"`
}
```

**Comment by stoyanr** [comment]
@rfranzke @tim-ebert I would propose a minor change:

```yaml
resources:
- name: <some-name>
  resourceRef:
    apiVersion: v1
    kind: Secret
    name: my-lets-encrypt-private-key
```

It makes more explicit which name is which, as well as easier to reuse `autoscalingv1.CrossVersionObjectReference` in the implementation. Otherwise it might result in confusion - the `CrossVersionObjectReference` name must be the resource (secret) name, and so we would need to rename the other name, which is counterintuitive.

See also my comment to #2327 for the same structure to be used in the ShootState and the Status of extension CRs.
