### ISSUE TITLE
Persist secrets required by extension controllers so that they can be used during Control Plane Migration

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener#2327]
**What would you like to be added**:
Extend the ShootState, ShootState Sync Controller and the Status of Extension CRs so that secret resources required by extension controllers can be persisted in the ShootState and migrated from the source seed to the destination seed.

**Why is this needed**:
Currently extension controllers can save their state in the `status.state` field of the corresponding extension resource. This is synced by the `ShootState Sync Controller` to the `ShootState` and used to restore the state of the extension controller on the destination seed during control plane migration. However, if the extension controller has to persist a secret, it cannot be directly saved to the `status.state` as it contains confidential information. 

**Proposal**:
To handle such cases an additional field is added to the `status` of extension CRs similar to Pod `Volumes` - `status.Secrets` (if it is required to handle other resources similarly then we could change the name to e.g. `status.Resources`) 

- The `ShootState Sync Controller` will read the new field, copy the data of the corresponding secrets and add them to the `ShootState` resource. 
- The control plane migration's restoration phase has an additional step which gets all such secrets from the `ShootState` and deploys them on the `Seed` in the `Shoot`'s namespace.

Here's an example with the `Extension` CR used by the certificate extension controller
```
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: "extension-certificate-service"
  namespace: shoot--project--abc
spec:
  type: shoot-cert-service
  providerConfig:
    apiVersion: shoot-cert-service.extensions.config.gardener.cloud/v1alpha1
    kind: Configuration
    issuerName: gardener
    restrictIssuer: true # restrict issuer to any sub-domain of shoot.spec.dns.domain (default)
    acme:
      email: john.doe@example.com
      server: https://acme-v02.api.letsencrypt.org/directory
      privateKeyRef:
        name: private-key
status:
  observedGeneration: 2
  state:
    # some data
    privateKeySecretRef: my-lets-encrypt-private-key
  secretReferences:
  - name: private-key
     secretName: my-lets-encrypt-private-key
```

**Comment by rfranzke** [comment]
Thanks for opening the issue!
We should be in line with https://github.com/gardener/gardener/issues/2321#issuecomment-628417974

**Comment by rfranzke** [comment]
/assign @stoyanr 
/status/in-progress
/area/control-plane-migration
/priority/normal
/component/gardener

**Comment by stoyanr** [comment]
The example should actually look as follows (in sync with #2321):

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: "extension-certificate-service"
  namespace: shoot--project--abc
spec:
  type: shoot-cert-service
status:
  observedGeneration: 2
  state:
    # some data
    privateKeyRef: private-key
  resources:
  - name: private-key
    resourceRef:
      apiVersion: v1
      kind: Secret
      name: my-secret
```

This should result in a `ShootState` similar to the following:

```yaml
apiVersion: core.gardener.cloud/v1alpha1
kind: ShootState
metadata:
  name: abc
  namespace: project
spec:
  gardener:
    ...
  extensions:
  - kind: Extension
    name: shoot-cert-service
    state:
      # some data
      privateKeyRef: private-key
    resources:
    - name: private-key
      resourceRef:
        apiVersion: v1
        kind: Secret
        name: my-secret
  resources:
  - apiVersion: v1
    kind: Secret
    name: my-secret
    data:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: my-secret
        namespace: shoot--project--abc
      data:
        test: dGVzdA==
```
