### ISSUE TITLE
Event logs for maintenance and hibernation operations

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#2390]
**How to categorize this issue?**

/area operations
/area usability
/kind enhancement
/priority normal

**What would you like to be added**:

Add an "event-log" of performed maintenance operations as well as hibernation / wake-up operations.

Below I listed three options that I could think of how to realize this. 

Option (1)

Add an events (or otherwise named field) into the Shoot.Status containing arbitrary Shoot events identified by the type field.

``` yaml
status:
  conditions: <>
  hibernated: true
  events:
    - type: MachineImageVersionMaintenance
      timestamp: "2020-05-25T14:47:54Z"
      status: "Successful"
      message: "Updated image of worker-pool 'coreos-1' from 'coreos' version 'xy' to version 'abc'."
      reason: "AutoUpdate of MachineImage configured"
    - type: MachineImageVersionMaintenance
      timestamp: "2020-05-25T14:47:53Z"
      status: "Successful"
      message: "Updated image of worker-pool 'coreos-2' from 'coreos' version 'xy' to version 'abc'."
      reason: "Machine image version is expired"
    - type: KubernetesVersionMaintenance
      timestamp: "2020-05-25T14:47:52Z"
      status: "Successful"
      message: "Updated Kubernetes version '0.0.1' to version '0.0.5'. This is an increase in the patch level."
      reason: "AutoUpdate of Kubernetes version configured"
    - type: KubernetesVersionMaintenance
      timestamp: "2020-05-25T14:47:53Z"
      status: "Successful"
    - type: KubernetesVersionMaintenance
      timestamp: "2020-05-24T14:47:53Z"
      status: "Successful"
    - type: Hibernation
      timestamp: "2020-05-24T14:47:53Z"
    - type: WakeUp
      timestamp: "2020-05-26T14:47:53Z"
```

Option (2)
To have a separation between Maintenance and Hibernation, this would be another option.
This would also group events that happened during the same maintenace time window.
``` yaml
status:
  conditions: <>
  hibernated: true
  maintenance:
    - lastSuccessfulMaintenance: "2020-05-25T14:47:53Z"
      events:
      - timestamp: "2020-05-25T14:47:53Z"
        status: "Successful"
        messages:
          - message: Updated image of worker-pool 'coreos-1' from 'coreos' version 'xy' to version 'abc'.
            reason: AutoUpdate of MachineImage configured
            type: MachineImageVersion
          - message: Updated Kubernetes version '0.0.1' to version '0.0.5'. This is an increase in the patch level.
            reason: AutoUpdate of Kubernetes version configured.
            type: KubernetesVersion
  hibernation:
    - timestamp: "2020-05-25T14:47:53Z"
      type: "Hibernation"
    - timestamp: "2020-05-26T14:47:53Z"
      type: "WakeUp"
```

Another option (3) would be to have a dedicated resource in the core.gardener-cloud API group 

``` yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ShootOperation
metadata:
  name: <shoot-name>
  namespace: shoot--dev--<>
  ownerReferences:
    - kind: Shoot
      name: <shoot-name>
spec:
  type: Maintenance / Hibernation
status:
  lastOperation: "2020-05-21T00:00:12Z"
  events: # only contain actual changes
    - type: MachineImageVersionMaintenance
      timestamp: "2020-05-25T14:47:54Z"
      status: "Successful"
      message: "Updated image of worker-pool 'coreos-1' from 'coreos' version 'xy' to version 'abc'."
      reason: "AutoUpdate of MachineImage configured"
    - type: MachineImageVersionMaintenance
      timestamp: "2020-05-25T14:47:53Z"
      status: "Successful"
      message: "Updated image of worker-pool 'coreos-2' from 'coreos' version 'xy' to version 'abc'."
      reason: "Machine image version is expired"
    - type: KubernetesVersionMaintenance
      timestamp: "2020-05-25T14:47:52Z"
      status: "Successful"
      message: "Updated Kubernetes version '0.0.1' to version '0.0.5'. This is an increase in the patch level."
      reason: "AutoUpdate of Kubernetes version configured"
```

I tend to favour option (3) to not pollute the already quite large Shoot resource with Hibernation and Maintenance event logs. @vpnachev also suggested to restrict the TTL of an event to 14 days.
The same TTL could also be done if we store the event log in the external resource.

Another issue that I see is how to deal with failed Shoot operations e.g a Shoot using an expired Kubernetes version cannot be updated because of a `CloudProfile` misconfiguration.
It would be handy if the controller could persist this information without writing a new event for each re-tried operation. There are several ways to achieve this.

**Why is this needed**:

There is no place to properly store a log of automatically performed maintenance operations.
For instance for Maintenance, the Gardener Controller manager just writes events on the Shoot resource stating the reason for a performed update operation.
The problem is that Kubernetes events are Garbage collected after a certain amout of time ([configurable in the Kube-Apiserver](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). 
Usually this is somewhere between 1 - 24 hours.

This is problematic because
- Users want to be able to see which maintenance operation Gardener automatically performed, when, why and if it was successful. 
- In case of unwanted update behaviour / problems, operators cannot easily determine what was the reason for the update operation.

In addition Gardener does currently only persist the current and desired state of the Hibernation.
Shoot owners might also want to see a log of the manually & automatically triggered Hibernations.

Integrators like the gardener Dashboard could read this information and display an operations log for both the Hibernation and the Maintenance operations.
