### ISSUE TITLE
metrics-server unable to scrape kubelet

### ISSUE THREAD

**Issue by dergeberl** [gardener/gardener#2455]
**How to categorize this issue?**

/area metering
/kind bug
/priority normal

**What happened**:
In our setup with openstack the metrics-server runs into the following error:
```
E0615 12:41:12.158755       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:shoot--core--ab7vxtoulk-worker-gnvyr-z1-5c4dc9599b-kdq4j: unable t 
 o fetch metrics from Kubelet shoot--core--ab7vxtoulk-worker-gnvyr-z1-5c4dc9599b-kdq4j (shoot--core--ab7vxtoulk-worker-gnvyr-z1-5c4dc9599b-kdq4j): Get https://shoot--core--ab7vxtoulk-worker-gnvyr-z1-5c4dc9 
 599b-kdq4j:10250/stats/summary?only_cpu_and_memory=true: dial tcp: lookup shoot--core--ab7vxtoulk-worker-gnvyr-z1-5c4dc9599b-kdq4j on 100.64.0.10:53: no such host
```
The default setting for the kubelet-preferred-address in the master branch from the matrics server is documented as `[Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP]`. In the tags/v0.3.6 there is no documentation about the default.

In our setup is the hostname not resolvable, so the metrics-server should fallback to the InternalIP. 

We try following settings in the metrics-server chart (/charts/shoot-core/components/charts/metrics-server/templates/deployment.yaml)

Set the kubelet-preferred-address (see [README.md from metrics-server](https://github.com/kubernetes-sigs/metrics-server/blob/master/README.md) direct to InternalIP
```yaml
...
      containers:
      - name: metrics-server
        image: {{ index .Values.images "metrics-server" }}
        imagePullPolicy: Always
        command:
        - /metrics-server
        - --profiling=false
        - --kubelet-preferred-address-types=InternalIP
        # nobody user only can write in home folder
        - --cert-dir=/home/certdir
        - --secure-port=8443
...
```
-> with this setting the metric-server works like expected

Set the kubelet-preferred-address (see [README.md from metrics-server](https://github.com/kubernetes-sigs/metrics-server/blob/master/README.md) to the "default" order ([Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP]).
```yaml
...
      containers:
      - name: metrics-server
        image: {{ index .Values.images "metrics-server" }}
        imagePullPolicy: Always
        command:
        - /metrics-server
        - --profiling=false
        - --kubelet-preferred-address-types=[Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP]
        # nobody user only can write in home folder
        - --cert-dir=/home/certdir
        - --secure-port=8443
...
```
-> that works, this should be the default but without this setting the metrics-server isn`t able to scrape the kubelet.

**What you expected to happen**:

The metrics-server is able to scrape the kubelet.

**How to reproduce it (as minimally and precisely as possible)**:

The hostname from the worker nodes is unresolvable in the kubernetes cluster. 

**Anything else we need to know?**:

**Environment**:

- Gardenlet version: 1.6.1
- Kubernetes version (use `kubectl version`): 1.18.0
- Cloud provider or hardware configuration: OpenStack
- Metrics-Server: 0.3.6
