### ISSUE TITLE
Document how autoUpdate in Shoots are handled

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#249]
After having a chat in slack I learned that if a shoot has `.spec.maintenance.autoUpdate.kubernetesVersion: true` in the definition then kubernetes patch releases will be automatically updated during the `.spec.maintenance.timeWindow`

E.g. if you have a shoot cluster with:

```
spec:
  kubernetes:
    version: 1.10.0
  maintenance:
    timeWindow:
      begin: 220000+0000
      end: 230000+0000
    autoUpdate:
      kubernetesVersion: true
```

And if you update Cloud profile and add `1.10.5` and `1.11.0` to the `.spec.<provider>.constraints.kubernetes.versions` list, the Shoot will be upgraded to `1.10.5` (not `1.11.0`) between 22:00-23:00 UTC.

This should be documented under the docs.
