### ISSUE TITLE
Enabling KonnectivityTunnel feature gate breaks shoot-core managed resource

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2498]
**How to categorize this issue?**

/area networking
/kind bug
/priority normal

**What happened**:
When the `KonnectivityTunnel` feature gate is enabled then the `shoot-core` `ManagedResource` breaks and cannot apply the resources/deploy the `konnectivity-agent`:

```
$ k -n shoot--dev--d065849-a1 get mr shoot-core -o yaml
apiVersion: resources.gardener.cloud/v1alpha1
kind: ManagedResource
...
status:
  conditions:
  - lastTransitionTime: "2020-06-23T06:28:00Z"
    lastUpdateTime: "2020-06-24T07:50:28Z"
    message: Missing required Secret with name "vpn-shoot".
    reason: SecretMissing
    status: "False"
    type: ResourcesHealthy
  - lastTransitionTime: "2020-06-23T06:27:57Z"
    lastUpdateTime: "2020-06-24T07:42:56Z"
    message: Deletion is still pending
    reason: DeletionPending
    status: "False"
    type: ResourcesApplied
```

**What you expected to happen**:
GRM deletes VPN resources and deploys konnectivity resources.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a 1.18 shoot with `KonnectivityTunnel=false`.
1. Enable `KonnectivityTunnel=true`.

- Gardener version: `master`
- Kubernetes version (use `kubectl version`): `v1.18.0`
- Cloud provider or hardware configuration: AWS

**Comment by rfranzke** [comment]
/kind regression
cc @zanetworker @DockToFuture

**Comment by zanetworker** [comment]
I didn't observe this before, how did you trigger it?

**Comment by rfranzke** [comment]
I simply enabled the feature gate.

**Comment by zanetworker** [comment]
Tested locally the conditions look healthy: 

```
status:
  conditions:
  - lastTransitionTime: "2020-06-24T09:52:14Z"
    lastUpdateTime: "2020-06-24T09:55:15Z"
    message: All resources are healthy.
    reason: ResourcesHealthy
    status: "True"
    type: ResourcesHealthy
  - lastTransitionTime: "2020-06-24T09:51:20Z"
    lastUpdateTime: "2020-06-24T09:55:21Z"
    message: All resources are applied.
    reason: ApplySucceeded
    status: "True"
    type: ResourcesApplied
```
