### ISSUE TITLE
Last responsible extension controller remains on seed after getting obsolete

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#2519]
**How to categorize this issue?**

/area quality
/area cost
/kind bug
/priority normal

**What happened**:
Gardener offers on-demand `ControllerRegistration`s which are only deployed to the seed cluster if a related extension Kind/Type is found on the seed. Likewise, once extensions are gone, Gardener checks if the extension controller is still required and deletes it if necessary.

Unfortunately, this hehavior doesn't work for the very last extension Kind/Type that is deleted from the seed, i.e. the infrastructure resource.

**What you expected to happen**:
The provider extension to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a cluster on a seed w/o backup configuration
- Delete the cluster again
- `ControllerInstallation` for the provider extension is not gone

**Anything else we need to know?**:
You can find the related exit condition here: https://github.com/gardener/gardener/blob/f120f2c74a503ab4a388aa055cd08d4081eaf5ed/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L174-L177

The comment correctly says that it cannot decide if the extension is required or not but unfortunately it misses the following case:
- The controller registration is responsible for resources which are **not required** at all by the shoot, e.g. because you disabled the backup feature (`controllerRegistration.Spec.Resources`)
```
resources:
  - kind: BackupBucket     <--- not required in this scenario
    primary: true
    type: gcp
  - kind: BackupEntry        <--- not required in this scenario
    primary: true
    type: gcp
  - kind: ControlPlane
    primary: true
    type: gcp
  - kind: Infrastructure
    primary: true
    type: gcp
  - kind: Worker
    primary: true
    type: gcp
```
- `c.kindToRequiredTypes` has no required types **after** the `Infrastructure` extension is deleted, hence we never enter this block https://github.com/gardener/gardener/blob/f120f2c74a503ab4a388aa055cd08d4081eaf5ed/pkg/gardenlet/controller/federatedseed/extensions/controllerinstallation_control.go#L166-L169
- Eventually the early exit is taken because `required == nil`

/cc @rfranzke

**Environment**:

- Gardener version: `master` with #2517
