### ISSUE TITLE
Expired machine image version of worker is not forcefully updated

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2604]
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:
Currently expired machine image version of worker is not forcefully updated when Shoot has other workers with non-expired machine image versions.

**What you expected to happen**:
Expired machine image version of worker to be forcefully updated. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Ensure that you have a Shoot with 1 worker that has expired machine image version (requires forceful update) and 1 worker which machine image version is for example supported.

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: crazy-botany
  namespace: garden-dev
spec:
  cloudProfileName: aws
  provider:
    type: aws
# ...
    workers:
    - name: worker1
      machine:
        image:
          name: suse-jeos
          version: 15.1.20200220
# ...
    - name: worker2
      machine:
        image:
          name: coreos
          version: 2512.3.0
# ...
```

The corresponding CloudProfile looks like:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: aws
spec:
# ...
  machineImages:
  - name: coreos
    versions:
    - classification: supported
      version: 2512.3.0
  - name: suse-jeos
    versions:
    - classification: deprecated
      expirationDate: "2020-07-15T23:59:59Z"
      version: 15.1.20200220
    - classification: deprecated
      version: 15.1.20200406
# ...
```

2. Maintain the Shoot and ensure that `worker1` won't be forcefully updated to non-expired version.

```
$ k -n garden-dev annotate shoot crazy-botany gardener.cloud/operation=maintain
$ k -n garden-dev describe shoot crazy-botany

Events:
  Type    Reason             Age                From                         Message
  ----    ------             ----               ----                         -------

  Normal  MaintenanceDone    15m                gardener-controller-manager  No action required.
  Normal  Reconciled         13m                gardenlet                    Reconciled Shoot cluster state
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.7.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
