### ISSUE TITLE
Bootstrap Tokens Piling Up

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#264]
An end user reported that our clusters pile up `bootstrap-token-*` secrets in the `kube-system` NS.

```
apiVersion: v1
data:
  description: <base64-decoded: "A bootstrap token generated by Gardener.">
  expiration: <redacted>
  token-id: <redacted>
  token-secret: <redacted>
  usage-bootstrap-authentication: <redacted>
  usage-bootstrap-signing: <redacted>
kind: Secret
metadata:
  name: bootstrap-token-<redacted>
  namespace: kube-system
type: bootstrap.kubernetes.io/token
```

Please note: When we fix the issue, we also need to take care of the amassed secrets in the shoots and clean them out if that's not a side effect of the fix already.
