### ISSUE TITLE
Ability to restrict addons-nginx-ingress LoadBalancer Source Ranges

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#269]
In many of our Shoots, our customers are deploying test systems and mostly want to limit access to the exposed applications from certain ip ranges.

This seems to be implemented using the `loadBalancerSourceRanges` field in Service definition: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/

Example:
```
kind: Service
metadata:
  name: addons-nginx-ingress-controller
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 1.1.1.0/24
```
