### ISSUE TITLE
All aws ebs volumes are deleted when deleting shoot

### ISSUE THREAD

**Issue by qiffang** [gardener/gardener#2729]
**How to categorize this issue?**

When i deleted a shoot, all aws ebs volumes are deleted.
![image](https://user-images.githubusercontent.com/7285248/90240518-f90d2580-de5b-11ea-8610-91ef5f1780e4.png)
Actually, some pv policies are `retain`.

**What happened**:

**What you expected to happen**:
The `retain` pv does not deleted and aws ebs volume also does not deleted

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
But the deletion flow does not delete PVs. Ref https://github.com/gardener/gardener/blob/5de026e5116e250e3ed80f97cdd6d9bec48f47a2/pkg/operation/botanist/cleanup.go#L228-L240

Can you share the output of `k get pv`? They should be `Released`.

**Comment by ialidzhikov** [comment]
I now double-checked and PV with `reclaimPolicy: Retain` was not deleted as part of the Shoot deletion flow.

My setup:

1. Create PVC

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: custom
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: custom
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

2. PV is first bound:

```
$ k get pv
NAME                                                                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM               STORAGECLASS   REASON   AGE
pv-shoot--foooooo--baaaaaaar-aa514882-cf07-4542-adb6-a9a163cd6f01   4Gi        RWO            Retain           Bound    default/ebs-claim   custom                  3m59s
```

3. When the PVC is deleted as part of the deletion flow, the PV is `Released`:
```
$ k get pv
NAME                                                                CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM               STORAGECLASS   REASON   AGE
pv-shoot--fooooooo--baaaaaar-aa514882-cf07-4542-adb6-a9a163cd6f01   4Gi        RWO            Retain           Released   default/ebs-claim   custom                  8m6s
```

4. After the Shoot deletion, the EBS volume is not deleted:
```
$ aws ec2 describe-volumes --volume-ids=vol-03f23bd74c1c26foo --output=json
{
    "Volumes": [
        {
            "Attachments": [],
            "AvailabilityZone": "eu-west-1a",
            "CreateTime": "2020-08-14T10:54:58.884Z",
            "Encrypted": false,
            "Size": 4,
            "SnapshotId": "",
            "State": "available",
            "VolumeId": "vol-03f23bd74c1c26foo",
            "Iops": 100,
            "Tags": [
                {
                    "Key": "CSIVolumeName",
                    "Value": "pv-shoot--fooooooo--baaaaaar-aa514882-cf07-4542-adb6-a9a163cd6f01"
                }
            ],
            "VolumeType": "gp2"
        }
    ]
}
```
