### ISSUE TITLE
Improve worker status summary during rolling update

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#2734]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:
I have observed the following error message during a rolling update:

```
task "Waiting until shoot worker nodes have been reconciled" failed: Error while waiting for Worker shot--foo--bar/az-us2 to become ready: extension encountered error during reconciliation: Error reconciling worker: Failed while waiting for all machine deployments to be ready: 'retry failed with context deadline exceeded, last error: Waiting until all desired machines are available (18/18 machine objects available, 1/1 machinedeployments available)...'
```

`MachineDeployment` and `Machine` objects:

```
$ k -n shot--foo--bar get machdeploy,mach
NAME                                                                        READY   DESIRED   UP-TO-DATE   AVAILABLE   AGE
machinedeployment.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1   18      18        5            18          8d

NAME                                                                               STATUS        AGE
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-5dd85bf44d-776h2                 7s
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-5dd85bf44d-9jb42   Running       19m
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-5dd85bf44d-fpdqt   Running       12m
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-5dd85bf44d-jlvwz   Running       3m53s
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-5dd85bf44d-l7tsw   Running       16m
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-2bz6k   Running       2d1h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-2vj6x   Running       7d1h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-4t9mn   Running       6d12h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-57jx5   Running       6d12h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-9qzj2   Running       2d9h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-dfflj   Running       2d8h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-fcf7j   Running       12h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-gw8b9   Running       12h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-gwfbs   Running       2d2h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-kdldv   Running       12h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-l47zd   Running       2d4h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-npp54   Terminating   7d11h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-rlw94   Running       2d12h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-td5dn   Running       8h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-wr9n7   Terminating   7d3h
machine.machine.sapcloud.io/shot--foo--bar-cpu-worker-z1-66bd876549-zsdpj   Running       12h
```

`MachineDeployment` spec & status:

```yaml
  spec:
    replicas: 18
  status:
    availableReplicas: 18
    conditions:
    - lastTransitionTime: "2020-08-05T06:31:30Z"
      lastUpdateTime: "2020-08-05T06:31:30Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 45
    readyReplicas: 18
    replicas: 21
    unavailableReplicas: 1
    updatedReplicas: 5
```

We should improve the status message and probably incorporate the number of updated replicas to provide better and fine-grained information.

/cc @danielfoehrKn 

**Why is this needed**:
Improve ops-productivity, less confusion
