### ISSUE TITLE
NodeLocalDNS Feature lacks DNS network policy for control-plane components

### ISSUE THREAD

**Issue by zanetworker** [gardener/gardener#2745]
**How to categorize this issue?**

/area networking
/kind bug
/priority normal

**What happened**:
Without the `NodeLocalDNS` feature enabled,  a network policy to allow DNS traffic from the shoots control-plane components is defined as follows: 
```yaml 
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
     ....
    to:
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchExpressions:
        - key: k8s-app
          operator: In
          values:
          - kube-dns
          - coredns
```
This policy basically blocks DNS traffic destined anywhere else other than the CoreDNS pods in the `kube-system` namespace. 

With `NodeLocalDNS` we need to enable DNS traffic to the `node-cache` process running on the nodes. There are two ways to go about this: 
1. <s> Use a podSelector for `node-local-dns` pods -> that won't work because these pods are running on `hostNetwork`.</s> 
2. Use ipBlocks to the DNS service ClusterIP which is fixed, as well as the `node-local-dns` IP (in case IPVS is used `169.254.20.10`) -> this is the suggested fix. 

Suggested solution: 
```yaml
  egress:
  - ports:
    - port: 53
      protocol: UDP
    ....
    to:
    - ipBlock:
        cidr: 100.64.0.10/32
    - ipBlock:
        cidr: 169.254.20.10/32
```
 
**What you expected to happen**:
Shoot controlplanee traffic would be able to access DNS. 

**How to reproduce it (as minimally and precisely as possible)**:
Enable `NodeLocalDNS` on the seeds.

cc @ialidzhikov
