### ISSUE TITLE
Shoot deletion can fail if the Infrastructure is deleted but kube-apiserver deployment is not

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2778]
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:
I was now checking a Shoot stuck in deletion. 

Its `status.lastOperation`:

```yaml
status:
  lastOperation:
    description: >-
      Flow "Shoot cluster deletion" encountered task errors: [task "Deploying
      Kubernetes controller manager" failed: retry failed with context deadline
      exceeded, last error: failed to apply manifests: 1 error occurred: could
      not apply object of kind "Deployment"
      "shoot--foo--bar/kube-controller-manager": admission webhook
      "controlplane.azure.extensions.gardener.cloud" denied the request: could
      not get configmap 'shoot--foo--bar/cloud-provider-config':
      ConfigMap "cloud-provider-config" not found]
    lastUpdateTime: '2020-08-25T00:25:31Z'
    progress: 31
    state: Failed
    type: Delete
```

Checking in the event history I see that the Shoot was successfully created:

```yaml
- apiVersion: events.k8s.io/v1beta1
  deprecatedCount: 1
  deprecatedFirstTimestamp: '2020-08-24T10:22:55Z'
  deprecatedLastTimestamp: '2020-08-24T10:22:55Z'
  deprecatedSource:
    component: gardenlet
  eventTime: null
  kind: Event
  metadata:
    name: foo.162e2d29ee729633
    namespace: garden-bar
  note: Reconciled Shoot cluster state
  reason: Reconciled
  regarding:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    name: foo
    namespace: garden-bar
    resourceVersion: '2147461051'
    uid: bf2a3487-4ebc-4fe7-ac25-4d463d160a01
```

Control plane:

```
$ k -n shoot--foo--bar get po
NAME                                         READY   STATUS              RESTARTS   AGE
etcd-events-0                                2/2     Running             0          13h
etcd-main-0                                  2/2     Running             0          24h
gardener-resource-manager-745b6ffbc6-f7m68   1/1     Running             2          6h43m
kube-apiserver-6c94f94b49-qt6m7              2/2     Running             0          24h
kube-controller-manager-6495c9dbf9-mnvqj     0/1     ContainerCreating   0          12h
kube-scheduler-77fdb6c7d8-sbxbw              1/1     Running             0          11h

$ k -n shoot--foo--bar get infra
No resources found in shoot--foo--bar namespace.

$ k -n shoot--foo--bar get cp
NAME           TYPE    PURPOSE    STATUS      AGE
foo-exposure   azure   exposure   Succeeded   24h
```

kube-controller-manager fails to start with:

```
$k -n shoot--foo--bar describe po kube-controller-manager-6495c9dbf9-mnvqj

  Warning  FailedMount  4m10s (x362 over 12h)  kubelet, shoot--garden--baz-cpu-worker-z1-6d778bf59-wd7xv  MountVolume.SetUp failed for volume "cloud-provider-config" : secret "cloud-provider-config" not found
```

As part of the ControlPlane deletion the `cloud-provider-config` Secret is deleted. We see that the kube-apiserver is still present, but the Infrastructure is deleted -> the ControlPlane does not get redeployed -> kube-controller-manager hangs forever in `ContainerCreating`.

The dependencies between the steps are:

https://github.com/gardener/gardener/blob/72ccc6de4352107a7b6e9e1d60e35b6df60f06bb/pkg/gardenlet/controller/shoot/shoot_control_delete.go#L394-L431

Generally the issue can occur when `DeleteKubeAPIServer` step fails for some reason and in the same time the Infrastructure gets deleted (receives deletionTimestamp) or gardenlet is restarted before `DeleteKubeAPIServer` step succeeds. We don't have a guarantee that `DeleteKubeAPIServer` will succeed when delete infra step also succeeds.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Locally I applied the following "mocking" to be able to reproduce the issue:

```diff
func (b *Botanist) DeleteKubeAPIServer(ctx context.Context) error {
	// invalidate shoot client here before deleting API server
	if err := b.ClientMap.InvalidateClient(keys.ForShoot(b.Shoot.Info)); err != nil {
		return err
	}
	b.K8sShootClient = nil

-	deploy := &appsv1.Deployment{
-		ObjectMeta: metav1.ObjectMeta{
-			Name:      v1beta1constants.DeploymentNameKubeAPIServer,
-			Namespace: b.Shoot.SeedNamespace,
-		},
-	}
-
-	return client.IgnoreNotFound(b.K8sSeedClient.Client().Delete(ctx, deploy, kubernetes.DefaultDeleteOptions...))
+       return fmt.Errorf("mock error")
}
```

1. Create an Azure Shoot

2. Delete the Shoot and ensure after `DeleteKubeAPIServer` step failure, the Shoot deletion gets stuck as described above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.9.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
