### ISSUE TITLE
Support AdmissionPlugin to reference other files

### ISSUE THREAD

**Issue by bellwest** [gardener/gardener#2879]
**What would you like to be added**:

Currently [Admission Plugin](https://gardener.cloud/api-reference/core/#core.gardener.cloud/v1beta1.AdmissionPlugin) does not support referencing other files(in api-server pod). I'd like this to be supported.

**Why is this needed**:

Some Admission Configuration might require other files and their locations, e.g.
```yaml
apiVersion: apiserver.k8s.io/v1alpha1
kind: AdmissionConfiguration
plugins:
- name: ValidatingAdmissionWebhook
  configuration:
    apiVersion: apiserver.config.k8s.io/v1alpha1
    kind: WebhookAdmission
    kubeConfigFile: /var/lib/minikube/certs/kube-config.yaml
```
(reference : https://github.com/open-policy-agent/kube-mgmt/blob/master/docs/admission-control-secure.md)
