### ISSUE TITLE
Seed .spec.settings.scheduling.visibility is flapping when it is set to false

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#2953]
**How to categorize this issue?**

/area quality
/kind bug
/priority normal

**What happened**:
Currently `.spec.settings.scheduling.visibility` is flapping between true and false when ShootedSeed `shoot.gardener.cloud/use-as-seed` annotation contains the `unvisible` identifier.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Add `unvisible` to the `shoot.gardener.cloud/use-as-seed` annotation

2. Ensure that the corresponding gardenlet seedConfig in the gardenlet configmap looks like:

```yaml
  spec:
    settings:
      scheduling:
        visible: false
```

Note that there are no taints.

3. Ensure that with Seed registration the Seed is set to visible=false and the invisible taint is added:

```yaml
  spec:
    settings:
      scheduling:
        visible: false
    taints:
    - key: seed.gardener.cloud/invisible
```

4. Ensure that with next Seed registration, visible is set to true and invisible taint is removed.

```yaml
  spec:
    settings:
      scheduling:
        visible: true
```

Note that the invisible taint is not present in the seedConfig in the gardenlet configmap.
This will cause gardenlet to send Update with the missing invisible Seed. Ref https://github.com/gardener/gardener/blob/v1.10.2/pkg/gardenlet/controller/shoot/seed_registration_control.go#L369-L400

The migrateSettings logic on apiserver side will thread the missing invisible taint as taint removal and will set the .spec.settings.visible=true. Ref https://github.com/gardener/gardener/blob/v1.10.2/pkg/registry/core/seed/strategy.go#L156-L173

**Anything else we need to know?**:

**Environment**:

- Gardener version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
