### ISSUE TITLE
Shoot's `.status.lastOperation` set to `Failed` too early

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#3018]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:
`gardener-apiserver` was put under load (and got scaled up very fast), however, until new apiserver pods were available, it sometimes returned

  ```text
  the server has received too many requests and has asked us to try again later (get controllerregistrations.core.gardener.cloud)
  ```

  The gardenlet sets the `.status.lastOperation.state` to `Failed` when trying to initialize a new operation without waiting for the configured retry period.

**What you expected to happen**:
The `Failed` status is only set after the configured period in the gardenlet component config.

**How to reproduce it (as minimally and precisely as possible)**:
n/a yet, sorry

- Gardener version: v1.11.3
- Kubernetes version (use `kubectl version`): 1.17.8

**Comment by ialidzhikov** [comment]
I managed to reproduce this one. The full error is like:

```
Could not initialize a new operation for Shoot reconciliation: cannot calculate required extensions for shoot my-shoot: the server has received too many requests and has asked us to try again later (get controllerregistrations.core.gardener.cloud)
```

The problematic part seems to be https://github.com/gardener/gardener/blob/v1.12.3/pkg/gardenlet/controller/shoot/shoot_control.go#L595. 

The `utils.TimeElapsed(shoot.Status.RetryCycleStartTime, c.config.Controllers.Shoot.RetryDuration.Duration)` part will always evaluate to true as `shoot.Status.RetryCycleStartTime` is nil -> `willNotRetry` is set to true in the first occurrence of such failure -> `status.lastOperation.status` is set to `Failed`.
I will check whether I can improve that.

**Comment by rfranzke** [comment]
Nice digging @ialidzhikov, thank's so much.
Shall we move https://github.com/gardener/gardener/blob/566a736b7bbd1ddccada371c9d4ba38bc943dd31/pkg/gardenlet/controller/shoot/shoot_control.go#L436-L439 up to https://github.com/gardener/gardener/blob/566a736b7bbd1ddccada371c9d4ba38bc943dd31/pkg/gardenlet/controller/shoot/shoot_control.go#L396?

The `updateShootStatusOperationStart` function ensures that the `retryCycleStarTime` is never `nil`.
/cc @timuthy - WDYT?

**Comment by timuthy** [comment]
> The `updateShootStatusOperationStart` function ensures that the `retryCycleStarTime` is never `nil`.
> /cc @timuthy - WDYT?

A side effect of a plain move would be a constant retry for shoots for which an `operation` could not be initialized (usually configuration problems). Might not be critical for a handful of invalid shoots but might be if some automation creates plenty if such.

**Comment by rfranzke** [comment]
Hm, yes, but if we can detect this and assign the `ERR_CONFIGURATION_PROBLEM` error code to it then it won't be retried, right? Is this possible?

**Comment by timuthy** [comment]
Sounds good to me.

**Comment by ialidzhikov** [comment]
@timuthy , I checked now and it seems that we have in place the handling for incomplete dns config. Ref https://github.com/gardener/gardener/blob/v1.12.5/pkg/gardenlet/controller/shoot/shoot_control.go#L626-L638
Creation of such Shoot is flagged with ERR_CONFIGURATION_PROBLEM and set to Failed immediately:

```yaml
status:
  lastErrors:
  - codes:
    - ERR_CONFIGURATION_PROBLEM
    description: unable to figure out which secret should be used for dns
    taskID: initializeOperation
  lastOperation:
    description: 'Could not initialize a new operation for Shoot reconciliation: unable
      to figure out which secret should be used for dns'
    lastUpdateTime: "2020-11-06T13:36:03Z"
    progress: 0
    state: Failed
    type: Create
  observedGeneration: 1
```

> I think generally every case that leads to an error when initializing the operation.

This confused me a little bit. 😅   For example the error `cannot calculate required extensions for shoot my-shoot: the server has received too many requests and has asked us to try again later (get controllerregistrations.core.gardener.cloud)` can be also returned from the `initializeOperation` func and we rather want to retry on such error. My understanding is that we introduce errors like `IncompleteDNSConfigError` for known user configuration problems and add handling for them with error code. Otherwise on generic error we allow retry for `retryDuration`. That's why I also asked whether there are other cases that need such handling.
