### ISSUE TITLE
Spot / Low-Priotity / Preemptible VM Support

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#31]
**Issue by [kubernetes-jenkins](https://github.com/kubernetes-jenkins)**
_Wednesday Jul 19, 2017 at 18:45 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/49_

----

# Story
* As operator I want to use AWS spot, Azure Low-Priotity or GCP Preemptible VM instances, so that my landscape runs at lower costs.

# Motivation
Money, sure, but also some form of chaos monkey that should help train the application developers that all resources will eventually fail.

# Acceptance Criteria
- [ ] Additional instance group with this machine type possible to create
  - https://aws.amazon.com/en/ec2/spot/
  - https://cloud.google.com/compute/docs/instances/preemptible
  - https://azure.microsoft.com/en-gb/blog/announcing-public-preview-of-azure-batch-low-priority-vms/ (seems not to be general purpose?)
- [ ] Nodes are either (at least) labelled or maybe even tainted so that only tolerating pods (with strict replication onto multiple nodes) are scheduled onto them

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://git.infra.removed/kubernetes/kube-docs/wiki/Operations%20Guide)?

:information_source: Migrated from Jira issue [KUBE-95](https://jtrack.removed/browse/KUBE-95)

**Comment by gardener-robot-ci-1** [comment]
**Comment by [vlerenc](https://github.com/vlerenc)**
_Wednesday Nov 29, 2017 at 07:38 GMT_

----

Looks like Bosh had the same idea (well, everybody can if they have cattle VMs): http://www.starkandwayne.com/blog/save-85-on-your-cloud-foundry-hosting-bill-with-this-one-simple-trick/amp

**Comment by gardener-robot-ci-1** [comment]
**Comment by [mvladev](https://github.com/mvladev)**
_Wednesday Nov 29, 2017 at 14:12 GMT_

----

With our current Shoot specification this cannot be achieved easily (just looking at the types).
The worker specification is too generic, but this feature for spot instances is AWS specific. Making changes to the specification for every similar feature can't scale well in the future.

I would suggest the following (similar to what ClusterAPI is doing):

```yaml
apiVersion: garden.sapcloud.io/v1alpha1
kind: Shoot
metadata:
  name: foo-aws
  namespace: bar
  finalizers:
  - garden.sapcloud.io/operator
spec:
  seed: # this is now reference
    name: foo-bar-seed
    namespace: foo-bar-seed-namespace
  infrastructure:
    apiVersion: infra.garden.sapcloud.io/v1alpha1
    kind: AWS
    region: eu-west-1
    secretRef:
      name: foo-secret
      namespace: baz
    vpc:
      cidr: 10.250.0.0/16
    networks:
      workers:
      - 10.250.0.0/19
      public:
      - 10.250.96.0/22
      internal:
      - 10.250.112.0/22
    workers:
    # this is InstanceSet/InstanceDeployment replica set
    - replicas: 5
      class:
        value: # it can be litteral value
          # some fields are auto-populated by garden-oprator
          apiVersion: node.sapcloud.io/v1alpha1
          kind: AWSSInstanceClass
          availabilityZone: eu-west-1
          instanceType: t2.xlarge
          spotPrice: "0.5" # spot instance
          blockDevices:
            volumeType: gp2
            volumeSize: 20
    - replicas: 2 # regular instances
      class:
        value:
          apiVersion: node.sapcloud.io/v1alpha1
          kind: AWSSInstanceClass
          availabilityZone: eu-west-1
          instanceType: t4.xlarge
          blockDevices:
            volumeType: gp2
            volumeSize: 40
    - replicas: 5
      class:
        ref: # or class reference
          name: default-aws-ifra-class
          namespace: bar
  dns:
    apiVersion: dns.garden.sapcloud.io/v1alpha1
    kind: AWS
    domain: d012345-1.d012345.k8s.sapcloud.io     
  kubernetesVersion: 1.8.2
```
