### ISSUE TITLE
Nginx Ingress Configuration Returns HTTP-400 on AWS

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#310]
We've been observing an issue with the Nginx Ingress Controller in Shoot clusters **on AWS**:

**Failure description:**
Whenever a Ingress resource with a corresponding URL is created, a request against it ends up with a HTTP 400 error message.
In addition, a request to a non existing Ingress URL or to the AWS load balancer directly also returns HTTP 400 instead of being redirected to the default backend.

**Expected behavior:**
The request is forwarded to the configured Service or the default backend respectively.

**Steps to reproduce:**

1. Create a Shoot cluster on AWS / take an existing one
2. Apply Yaml file (please adjust Host information)

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <Your Host>
    http:
      paths:
      - backend:
          serviceName: nginx-service
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
---
```
