### ISSUE TITLE
Detect webhooks that are potentially problematic for maintenance activities and place a constraint on shoots

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3122]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority normal

**What would you like to be added**:
We should detect webhooks that are potentially problematic for maintenance activities and place a constraint on shoots of type `MaintenancePossible` to forbid maintenance similarly to how we currently forbid hibernation for similar reasons. The constraint could look like this:

```yaml
    constraints:
    - type: MaintenancePossible
      status: 'False'
      lastTransitionTime: '2020-11-05T02:43:34Z'
      lastUpdateTime: '2020-10-29T07:32:57Z'
      reason: ProblematicWebhooks
      message: >-
        Maintenance activities cannot be performed on this shoot because of 
        MutatingWebhookConfiguration "sen-webhooks-shoot": webhook 
        "vpn-service-webhook.sen.sap.com" with failurePolicy "Fail" will probably 
        cause the maintenance activities to fail.
```

Alternatively, we may refrain from forbidding maintenance, but still add a constraint and a visual cue in the dashboard based on this constraint, e.g. a red "Schedule Maintenance" button with a popup that displays the constraint message.

**Why is this needed**:
During DoD activities, we noticed errors where the shoot reconciliation during maintenance activities failed due to a user webhook modifying `kube-system` pods. If the webhook is not reachable from `kube-apiserver` for whatever reason (e.g. no running `vpn-shoot` pods, or webhook pods), calling the webhook may fail with `context deadline exceeded` even if the failure policy is set to `Fail`, or even if it's set to `Ignore` and the timeout is long enough (30s or more). This in turn prevents `kube-system` pods from being created, which may prevent `calico` from properly initializing and cause the nodes to fail to join the cluster due to kubelet reporting `NetworkPluginNotReady`.

The issue is partially mitigated by https://github.com/gardener/gardener/pull/3100, but not prevented entirely.

The solution proposed above was suggested in the DoD sync.
