### ISSUE TITLE
Deletion deadlock with invalid primary domain

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener#3159]
**How to categorize this issue?**

/area usability
/kind bug
/priority normal

**What happened**:

Gardener is unable to delete shoot clusters, with a invalid primary dns domain.

Gardener tries to redeploy dns entries before starting the deletion flow, which will result in a deadlock if the dns configuration is invalid.

```
   task "Deploying external domain DNS record" failed: Failed to create "external" DNS record: "DNS record \"external\" is not ready (status=Error, message=No responsible provider found)" (status=Error, message=No responsible provider found)
```

The only possible fix is to patch the etcd as the primary dns field is immutable.

**What you expected to happen**:

Gardener should be able to delete cluster if a wrong dns was specified.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot cluster with a invalid primary dns:
  ```
  dns:
    domain: invalid.exampl.com
    providers:
      - domains:
          include:
            -  invalid.example.com
        primary: true
        secretName: my-secret
        type: cloudflare-dns
  ```
2. Delete the cluster

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.12.8
