### ISSUE TITLE
Make the check for stale extension healthchecks enabled by default

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#3169]
For backwards compatibility reasons https://github.com/gardener/gardener/pull/2266 made the check for stale extension healthchecks disabled by default. This was done back in `gardener/gardener@v1.4.0` and now it is time to make this check enabled by default.

Initially there was no idea to make this check configurable (like enabled or disabled) but I think to make sense to have this configurable.

Currently we have:
```yaml
---
apiVersion: gardenlet.config.gardener.cloud/v1alpha1
kind: GardenletConfiguration
# ...
  shootCare:
    staleExtensionHealthCheckThreshold: 5m
```

And when `staleExtensionHealthCheckThreshold` is not specified, then the check for stale extension healthchecks is disabled.

My proposal:

```yaml
---
apiVersion: gardenlet.config.gardener.cloud/v1alpha1
kind: GardenletConfiguration
# ...
  shootCare:
    staleExtensionHealthChecks:
      enabled: true
      threshold: 5m
```

@gardener/gardener-maintainers wdyt?

/kind cleanup
/priority normal
