### ISSUE TITLE
Cilium DNS-based egress rules (toFQDN) not working reliably

### ISSUE THREAD

**Issue by anbrsap** [gardener/gardener#3274]
### How to categorize this issue?

/area networking
/kind bug
/priority normal

### What happened

A shoot cluster with [__Cilium networking__](https://github.com/gardener/gardener-extension-networking-cilium) is used.

A pod is restricted by a CiliumNetworkPolicy using [DNS-based L3 rules](https://docs.cilium.io/en/v1.9/policy/language/#dns-based) (`toFQDN`).

The pod is unable to resolve DNS names.

### What you expected to happen

The pod should be able to resolve DNS names.

### How to reproduce it (as minimally and precisely as possible)

Create a shoot cluster with _Cilium networking_ and _two nodes_.

Example shoot manifest for AWS (see comments for values to be adapted):

```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: your-project-name # replace by your Gardener project name
  name: testcase-1
spec:
  provider:
    type: aws
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - name: eu-central-1c
            workers: 10.250.0.0/19
            public: 10.250.32.0/20
            internal: 10.250.48.0/20
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    workers:
      - name: worker1
        minimum: 2  # ensure we have two nodes
        maximum: 2
        maxSurge: 1
        machine:
          type: m5.large
          image:
            name: gardenlinux
            version: 184.0.0
        zones:
          - eu-central-1c # adapt if necessary
        volume:
          type: gp2
          size: 50Gi
  networking:
    type: cilium
    nodes: 10.250.0.0/16
  cloudProfileName: aws
  secretBindingName: your-aws-secret-name # replace by your AWS secret name
  region: eu-central-1 # adapt if necessary
  purpose: evaluation
  kubernetes:
    version: 1.19.3
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: false
  maintenance:
    timeWindow:
      begin: 020000+0000
      end: 030000+0000
    autoUpdate:
      kubernetesVersion: false
      machineImageVersion: false
  hibernation:
    schedules: []
```

For the following commands use a shell where `kubectl` accesses the cluster with admin privileges.

Gardener configures CoreDNS as the cluster DNS server. It runs with two replicas. For a stable reproduction of the issue ensure that both replicas run on the first cluster node (just scaling down to 1 replica doesn't work as Gardener will revert any modification to the controlling Deployment resource object):

```sh
# used by subsequent commands
NODE1=$(kubectl get nodes -o jsonpath='{.items[0].metadata.name}')
NODE2=$(kubectl get nodes -o jsonpath='{.items[1].metadata.name}')
```

```sh
kubectl cordon "$NODE2"
kubectl -n kube-system scale deployment coredns --replicas=0
kubectl -n kube-system scale deployment coredns --replicas=2
# wait until pods have been scheduled
kubectl uncordon "$NODE2"
```

Check that all CoreDNS pods are running on `NODE1` now:

```sh
echo "$NODE1"; kubectl -n kube-system get pods -o wide | grep coredns
```

Result (example):

```
ip-10-250-14-108.eu-central-1.compute.internal
coredns-6c4f754f4b-6nmwp            1/1     Running   0          11m   100.96.1.91     ip-10-250-14-108.eu-central-1.compute.internal   <none>           <none>
coredns-6c4f754f4b-h2fmm            1/1     Running   0          11m   100.96.1.173    ip-10-250-14-108.eu-central-1.compute.internal   <none>           <none>
```

Create a namespace `testcase` containing a CiliumNetworkPolicy using [DNS-based L3 rules](https://docs.cilium.io/en/v1.9/policy/language/#dns-based) (`toFQDN`):

```sh
kubectl create -f - <<EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: testcase
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: dns-based-l3-rules
  namespace: testcase
spec:
  endpointSelector:
    matchLabels:
      affected-by-dns-based-l3-rules: "true"
  egress:
  - toFQDNs:
    - matchPattern: "*"
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "8053"
        protocol: ANY
      - port: "53"
        protocol: ANY
      rules:
        # enable DNS proxy to enable toFQDN egress rules
        dns:
        - matchPattern: "*"
EOF
```

Open a remote shell in a pod on the _second_ node that is affected by CiliumNetworkPolicy `dns-based-l3-rules`:

```sh
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE2"'"}}' \
  --image arunvelsriram/utils \
  -it --rm \
  restricted--node2 \
  -- bash
```

Within that remote shell, try to resolve a DNS name both via UPD and TCP:

```
root@restricted--node2:/# dig heise.de +notcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +notcp
;; global options: +cmd
;; connection timed out; no servers could be reached
```

```
root@restricted--node2:/# dig heise.de +tcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +tcp
;; global options: +cmd
;; connection timed out; no servers could be reached
```

The DNS resolution failed because there was no answer from the DNS server!

Run a remote shell in a similar pod, but this time on the _first_ node:

```sh
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE1"'"}}' \
  --image arunvelsriram/utils \
  -it --rm \
  restricted--node1 \
  -- bash
```

Within that remote shell, try to resolve a DNS name both via UPD and TCP:

```
root@restricted--node1:/# dig heise.de +notcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +notcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14006
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 8a9db8963e5c579f (echoed)
;; QUESTION SECTION:
;heise.de.			IN	A

;; ANSWER SECTION:
heise.de.		30	IN	A	193.99.144.80

;; Query time: 3 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Mon Dec 07 13:30:07 UTC 2020
;; MSG SIZE  rcvd: 73
```

```
root@restricted--node1:/# dig heise.de +tcp

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54001
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;heise.de.			IN	A

;; ANSWER SECTION:
heise.de.		30	IN	A	193.99.144.80

;; Query time: 4 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Mon Dec 07 13:30:11 UTC 2020
;; MSG SIZE  rcvd: 61
```

Here it works!

### Analysis

With DNS-based egress rules in Cilium network policies the affected pods' DNS traffic is transparently routed through Cilium's _DNS proxy_ on the local node. The DNS proxy in turn queries the Cluster DNS server. DNS proxy routing gets enabled by the `dns` L7 rule in the CiliumNetworkPolicy:

```yaml
spec:
  egress:
  - toEndpoints:
    - matchLabels:
        "k8s:io.kubernetes.pod.namespace": kube-system
        "k8s:k8s-app": kube-dns
    toPorts:
    - ports:
      - port: "8053"
        protocol: ANY
      - port: "53"
        protocol: ANY
      rules:
        # enable DNS proxy to enable toFQDN egress rules
        dns:
        - matchPattern: "*"
```

In the failure case described above, the DNS proxy runs on a different node than the DNS server. In the working case both DNS proxy and DNS server run on the same node.

_Theory_: DNS traffic from Cilium DNS proxies to a cluster DNS server is blocked if both endpoints reside on different cluster nodes. If the endpoints reside on the same cluster node, the traffic is not blocked.

_Note_: The following steps continue what has been described in _How to reproduce it_ above.

Use `cilium monitor` to inspect dropped network traffic on the two cluster nodes. Start monitoring on the first node (use a separate shell):

```sh
NODE1=$(kubectl get nodes -o jsonpath='{.items[0].metadata.name}') && \
NODE1_CILIUM_POD=$(kubectl -n kube-system get pod --selector k8s-app=cilium \
    --field-selector spec.nodeName="$NODE1" -o jsonpath='{.items[0].metadata.name}') && \
kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium monitor -t drop
```

Then start monitoring on the second node (use a separate shell):

```sh
NODE2=$(kubectl get nodes -o jsonpath='{.items[1].metadata.name}') && \
NODE2_CILIUM_POD=$(kubectl -n kube-system get pod --selector k8s-app=cilium \
    --field-selector spec.nodeName="$NODE2" -o jsonpath='{.items[0].metadata.name}') && \
kubectl -n kube-system exec "$NODE2_CILIUM_POD" -- cilium monitor -t drop
```

Now reproduce the failure case again:

```sh
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE2"'"}}' \
  --image arunvelsriram/utils \
  -it --rm --restart=Never \
  restricted--node2--dig \
  -- dig heise.de
```

Output (failing as before):

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Now look at the output of the network monitors. On the _second_ node no traffic was dropped. But on the _first_ node DNS traffic (port 8053) was dropped:

```
xx drop (Policy denied) flow 0xaa59aa59 to endpoint 1272, identity 6->9560: 100.96.0.217:57536 -> 100.96.1.91:8053 udp
xx drop (Policy denied) flow 0xdc51dc51 to endpoint 1272, identity 6->9560: 100.96.0.217:47925 -> 100.96.1.91:8053 udp
xx drop (Policy denied) flow 0x46c946c9 to endpoint 1272, identity 6->9560: 100.96.0.217:41670 -> 100.96.1.91:8053 udp
```

Before further analyzing the packet drops, test the good case (a pod on the first node) for comparison:

```sh
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE1"'"}}' \
  --image arunvelsriram/utils \
  -it --rm --restart=Never \
  restricted--node1--dig \
  -- dig heise.de
```

Output (succeeding as before):

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30567
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 9f527802197e81b9 (echoed)
;; QUESTION SECTION:
;heise.de.			IN	A

;; ANSWER SECTION:
heise.de.		30	IN	A	193.99.144.80

;; Query time: 4 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Mon Dec 07 15:47:53 UTC 2020
;; MSG SIZE  rcvd: 73
```

The network monitor on the first node shows blocked traffic, but this time it's only L2 traffic which seems not to be important here:

```
xx drop (Unsupported L2 protocol) flow 0x3e6550b7 to endpoint 0, identity 16063->0: 11:ff:fe:80:00:00 -> 60:0e:b7:50:00:2a LLC
level=info msg="Initializing dissection cache..." subsys=monitor
xx drop (Unsupported L2 protocol) flow 0x3e6550b7 to endpoint 0, identity 16063->0: 11:ff:fe:80:00:00 -> 60:0e:b7:50:00:2a LLC
xx drop (Unsupported L2 protocol) flow 0x3e6550b7 to endpoint 0, identity 16063->0: 11:ff:fe:80:00:00 -> 60:0e:b7:50:00:2a LLC
```

The network monitors can be stopped now.

Continuing the analysis of dropped DNS traffic.

Remember the pod names of Cilium agents on the nodes:

```sh
NODE1_CILIUM_POD=$(kubectl -n kube-system get pod --selector k8s-app=cilium \
    --field-selector spec.nodeName="$NODE1" -o jsonpath='{.items[0].metadata.name}') && \
NODE2_CILIUM_POD=$(kubectl -n kube-system get pod --selector k8s-app=cilium \
    --field-selector spec.nodeName="$NODE2" -o jsonpath='{.items[0].metadata.name}')
```

Find out what the source (100.96.0.217) and destination (100.96.1.91) endpoints are:

```sh
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium ip list
IP                 IDENTITY   SOURCE
...
100.96.0.217/32    6
...
100.96.1.91/32     9560       k8s
...

$ kubectl -n kube-system exec "$NODE2_CILIUM_POD" -- cilium ip list
IP                 IDENTITY   SOURCE
...
100.96.0.217/32    1
...
100.96.1.91/32     9560       k8s
...

$ # check identities
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium identity list
ID         LABELS
...
6          reserved:remote-node
...
9560       k8s:garden.sapcloud.io/role=system-component
           k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system
           k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true
           k8s:io.cilium.k8s.policy.cluster=default
           k8s:io.cilium.k8s.policy.serviceaccount=coredns
           k8s:io.kubernetes.pod.namespace=kube-system
           k8s:k8s-app=kube-dns
           k8s:origin=gardener
           k8s:shoot.gardener.cloud/no-cleanup=true
...

$ kubectl -n kube-system exec "$NODE2_CILIUM_POD" -- cilium identity list
ID         LABELS
1          reserved:host
...
9560       k8s:garden.sapcloud.io/role=system-component
           k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system
           k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true
           k8s:io.cilium.k8s.policy.cluster=default
           k8s:io.cilium.k8s.policy.serviceaccount=coredns
           k8s:io.kubernetes.pod.namespace=kube-system
           k8s:k8s-app=kube-dns
           k8s:origin=gardener
           k8s:shoot.gardener.cloud/no-cleanup=true
...
```

The _source_ (100.96.0.217) is not a K8s identity and seems to be located on the second host. This is the Cilium DNS proxy on the second node.

The _destination_ (100.96.1.91) is a CoreDNS pod.

Now let Cilium explain why it blocked the DNS traffic:

```
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium policy trace --src-identity 6 --dst-identity 9560 --dport 8053/UDP
----------------------------------------------------------------

Tracing From: [reserved:remote-node] => To: [k8s:garden.sapcloud.io/role=system-component, k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system, k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=coredns, k8s:io.kubernetes.pod.namespace=kube-system, k8s:k8s-app=kube-dns, k8s:origin=gardener, k8s:shoot.gardener.cloud/no-cleanup=true] Ports: [8053/UDP]

Resolving ingress policy for [k8s:garden.sapcloud.io/role=system-component k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=coredns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=kube-dns k8s:origin=gardener k8s:shoot.gardener.cloud/no-cleanup=true]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
      No label match for [reserved:remote-node]
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
1/9 rules selected
Found no allow rule
Ingress verdict: denied

Final verdict: DENIED
```

For the CoreDNS pods there's an ingress rule which does not allow this particular traffic. It comes from network policy `gardener.cloud--allow-dns` in namespace `kube-system`:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows CoreDNS to lookup DNS records, talk to the API Server. Also allows
      CoreDNS to be reachable via its service and its metrics endpoint.
    resources.gardener.cloud/description: |-
      DO NOT EDIT - This resource is managed by gardener-resource-manager.
      Any modifications are discarded and the resource is returned to the original state.
  labels:
    shoot.gardener.cloud/no-cleanup: "true"
  name: gardener.cloud--allow-dns
  namespace: kube-system
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector: {}
    - ipBlock:
        cidr: 100.96.0.0/11
    ports:
    - port: 9153
      protocol: TCP
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
  podSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-dns
      - coredns
  policyTypes:
  - Egress
  - Ingress
```

The ingress rule specifies an `ipBlock` and UDP port which should allow the traffic that has been blocked. Maybe the existence of `namespaceSelector` and `podSelector` lead to the rule not matching our traffic. Lets try to define a additional policy without those:

```sh
kubectl create -f - <<EOF
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: maybe-allow-dns-traffic-from-cilium-dns-proxy
  namespace: kube-system
spec:
  ingress:
  - from:
    # only this
    - ipBlock:
        cidr: 100.96.0.0/11
    ports:
    - port: 9153
      protocol: TCP
    - port: 8053
      protocol: TCP
    - port: 8053
      protocol: UDP
  podSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-dns
      - coredns
  policyTypes:
  - Ingress
EOF
```

```
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium policy trace --src-identity 6 --dst-identity 9560 --dport 8053/UDP
----------------------------------------------------------------

Tracing From: [reserved:remote-node] => To: [k8s:garden.sapcloud.io/role=system-component, k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system, k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=coredns, k8s:io.kubernetes.pod.namespace=kube-system, k8s:k8s-app=kube-dns, k8s:origin=gardener, k8s:shoot.gardener.cloud/no-cleanup=true] Ports: [8053/UDP]

Resolving ingress policy for [k8s:garden.sapcloud.io/role=system-component k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=coredns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=kube-dns k8s:origin=gardener k8s:shoot.gardener.cloud/no-cleanup=true]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
      No label match for [reserved:remote-node]
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
2/10 rules selected
Found no allow rule
Ingress verdict: denied

Final verdict: DENIED
```

Even with this additional network policy the traffic is blocked. It may be a bug in Cilium.

Now try with an additional CiliumNetworkPolicy, which allows DNS server pods to receive traffic from `remote-node` entities:

```sh
kubectl create -f - <<EOF
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-dns-from-remote-nodes
  namespace: kube-system
spec:
  description: |
    Enables access from non-pod remote node IPs, in particular
    Cilium DNS proxies, to the cluster's DNS resolvers.
  endpointSelector:
    matchExpressions:
    - key: k8s-app
      operator: In
      values:
      - kube-dns
      - coredns
  ingress:
  - fromEntities:
    - remote-node
    toPorts:
    - ports:
      - port: "8053"
        protocol: TCP
      - port: "8053"
        protocol: UDP
EOF
```

```
$ kubectl -n kube-system exec "$NODE1_CILIUM_POD" -- cilium policy trace --src-identity 6 --dst-identity 9560 --dport 8053/UDP
----------------------------------------------------------------

Tracing From: [reserved:remote-node] => To: [k8s:garden.sapcloud.io/role=system-component, k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system, k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true, k8s:io.cilium.k8s.policy.cluster=default, k8s:io.cilium.k8s.policy.serviceaccount=coredns, k8s:io.kubernetes.pod.namespace=kube-system, k8s:k8s-app=kube-dns, k8s:origin=gardener, k8s:shoot.gardener.cloud/no-cleanup=true] Ports: [8053/UDP]

Resolving ingress policy for [k8s:garden.sapcloud.io/role=system-component k8s:io.cilium.k8s.namespace.labels.gardener.cloud/purpose=kube-system k8s:io.cilium.k8s.namespace.labels.shoot.gardener.cloud/no-cleanup=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=coredns k8s:io.kubernetes.pod.namespace=kube-system k8s:k8s-app=kube-dns k8s:origin=gardener k8s:shoot.gardener.cloud/no-cleanup=true]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Enforcing requirements [{Key:k8s.io.kubernetes.pod.namespace Operator:Exists Values:[]}]
      No label match for [reserved:remote-node]
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"k8s:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Allows from labels {"matchLabels":{"cidr:100.96.0.0/11":""}}
      No label match for [reserved:remote-node]
* Rule {"matchLabels":{"k8s:io.kubernetes.pod.namespace":"kube-system"},"matchExpressions":[{"key":"any:k8s-app","operator":"In","values":["kube-dns","coredns"]}]}: selected
    Allows from labels {"matchLabels":{"reserved:remote-node":""}}
      Found all required labels
      Allows port [{8053 TCP} {8053 UDP}]
3/11 rules selected
Found allow rule
Ingress verdict: allowed

Final verdict: ALLOWED
```

This rule seems to allow the traffic!

Lets verify with a pod that failed before:

```sh
kubectl run -n testcase \
  --labels="affected-by-dns-based-l3-rules=true" \
  --overrides='{"spec":{"nodeName":"'"$NODE2"'"}}' \
  --image arunvelsriram/utils \
  -it --rm --restart=Never \
  restricted--node2--dig \
  -- dig heise.de
```

Output (now succeeding):

```
; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> heise.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30316
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: db6841d129a11118 (echoed)
;; QUESTION SECTION:
;heise.de.			IN	A

;; ANSWER SECTION:
heise.de.		30	IN	A	193.99.144.80

;; Query time: 4 msec
;; SERVER: 100.64.0.10#53(100.64.0.10)
;; WHEN: Mon Dec 07 17:07:09 UTC 2020
;; MSG SIZE  rcvd: 73
```

### Anything else we need to know?

With a cluster of only one node the problem does not occur.

With a cluster of two nodes the problem _may_ occur, depending on how the DNS server replicas are distributed across nodes and whether a cross-node communication from proxy to server is involved. If DNS server replicas run on different nodes, load balancing leads to the effect that sometimes DNS requests succeed and sometimes not. As DNS clients retry if a DNS request times out, chances are high that a DNS server on the local node will be used. Nevertheless DNS resolution is slow in average due to retries after timeout.

With a cluster of more than two nodes the problem occurs always for pods on nodes that do not run a DNS server replica.

### Environment

- Gardener version: 1.13.2
- Kubernetes version (use `kubectl version`): 1.19.3 (others are affected, too)
- Cloud provider or hardware configuration: AWS
- Others:
