### ISSUE TITLE
shoot.status.conditions are removed

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#343]
I'd expect shoots' `.status.conditions` fields not to be empty ever once they have successfully provisioned, but we regularly see as reconciliation fails the conditions field is removed.  I'm not sure about the best practices here but we expect to see a value for the rest of the shoot's lifecycle if once there was any value.

For reconciliation failures there should be dedicated reason (e.g. Stale) to be place into the corresponding conditions rather than removing the conditions field at all.

This is a regular issue for shoots on Azure since we have reconciliations failing regularly due to Azure API not being as fast as Gardener expects. (e.g. volume detach/attach or LB creations for services could take up to an hour, or VM provisioning taking longer in some regions)

Example shoot status on one of our gardener installations:
```
[msa-dev-garden:garden]~ $ kubectl get --all-namespaces shoots | sed 's/dub.*io/<cropped>/'
NAMESPACE   NAME        CLOUDPROFILE   VERSION   SEED              DOMAIN                OPERATION    PROGRESS   CONTROL     NODES       SYSTEM      AGE
cloud-9     cloud-9     azure          1.10.5    azure-eastus-01   cloud-9.<cropped>     Processing   84         <unknown>   <unknown>   <unknown>   65d
consus      axeda       azure          1.10.5    azure-eastus-01   axeda.<cropped>       Failed       84         False       False       False       14d
consus      consus      azure          1.10.5    azure-eastus-01   consus.<cropped>      Processing   80         <unknown>   <unknown>   <unknown>   65d
flow        flow        azure          1.10.5    azure-eastus-01   flow.<cropped>        Processing   80         <unknown>   <unknown>   <unknown>   65d
ipa         ipa         azure          1.10.5    azure-eastus-01   ipa.<cropped>         Processing   80         <unknown>   <unknown>   <unknown>   39d
man         man         azure          1.10.5    azure-eastus-01   man.<cropped>         Processing   80         <unknown>   <unknown>   <unknown>   66d
studio      studio      azure          1.10.5    azure-eastus-01   studio.<cropped>      Processing   84         <unknown>   <unknown>   <unknown>   1d
wnc         windchill   azure          1.10.5    azure-eastus-01   windchill.<cropped>   Processing   80         <unknown>   <unknown>   <unknown>   62d
[msa-dev-garden:garden]~ $ 
```

consus shoot status field doesn't have a`conditions` field:
```
[msa-dev-garden:garden]~ $ kubectl get shoot -n consus consus -o yaml
...
status:
  gardener:
    id: 2166589d48b6804b9da69e7d2ae2a33f6901aae1a8bff6579f48e8f764cf0408
    name: gardener-controller-manager-587bd55dfc-8cqcw
    version: 0.10.0-dev
  lastError:
    description: 'Failed to reconcile Shoot cluster state: Errors occurred during
      flow execution: ''(*HybridBotanist).ReconcileMachines'' returned ''Failed while
      waiting for all machine deployments to be ready: ''timed out waiting for the
      condition'''''
  lastOperation:
    description: Executing ReconcileMachines.
    lastUpdateTime: 2018-08-29T10:55:38Z
    progress: 80
    state: Processing
    type: Reconcile
  observedGeneration: 10
  retryCycleStartTime: 2018-08-28T11:18:18Z
  seed: azure-eastus-01
  technicalID: shoot--consus--consus
  uid: 9e488c58-77c4-11e8-8af0-5635bb14771b
```

axeda shoot has the `.status.conditions` field (included just as an example):
```  conditions:
  - lastTransitionTime: 2018-08-29T11:17:57Z
    message: Deployment machine-controller-manager has not yet the desired number
      of available pods.
    reason: DeploymentUnavailable
    status: "False"
    type: ControlPlaneHealthy
  - lastTransitionTime: 2018-08-29T09:21:11Z
    message: Node shoot--consus--axeda-cpu-worker-69fc66b955-gfk74 is not ready.
    reason: NodeNotReady
    status: "False"
    type: EveryNodeReady
  - lastTransitionTime: 2018-08-29T09:21:11Z
    message: Deployment addons-heapster-e3b0c has not yet the desired number of available
      pods.
    reason: DeploymentUnavailable
    status: "False"
    type: SystemComponentsHealthy
```
