### ISSUE TITLE
Reset failed Shoots when a new Gardener version gets deployed

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#355]
Today, Gardener does retrying an operation (create/reconcile/delete) on `Shoot` resources in case it keeps failing for a [given maximum duration](https://github.com/gardener/gardener/blob/master/example/20-componentconfig-gardener-controller-manager.yaml#L13). If the operation did still not succeed after the duration was exceeded, Gardener will set the `.status.lastOperation.state=Failed` and will never start the same operation on it again, unless:
* the `.spec` of the `Shoot` is changed
* another operation is triggered (e.g., `Reconcile` operation was failing but now `Delete` is triggered)
* the end-user [manually triggers](https://github.com/gardener/gardener/blob/master/hack/retry-shoot-operation) Gardener to retry the same operation.

This behaviour is problematic as it requires manual interaction to let Gardener restart the operation again.

The first thing we should do is to automatically reset the failed Shoots when a new Gardener version takes over (meaning setting `.status.lastOperation.state=Error` and `.status.retryCycleStartTime=<current-timestamp>`). Gardener already writes its own version into the `Shoot` status, so it's relatively easy to find these Shoots:

```yaml
...
status:
  gardener:
    id: 4a659427e1953356dcf30faf651b8f9554bc9676f12810102fe5d67b596d69e4
    name: gardener-controller-manager-74c484b898-9v648
    version: 0.10.1
```

The next step would be to have an automatic unfreeze also within the same Gardener version, e.g. with an exponential backoff or similar means (same problem like https://github.com/gardener/machine-controller-manager/issues/75). Anyway, this is just to mention it and should be discussed/handled separately.
