### ISSUE TITLE
Dedicated Member/Admin resources

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#357]
Now that we have [dedicated `Project` resources](https://github.com/gardener/gardener/blob/master/example/05-project-dev.yaml) we also want to get rid of the implicit/unversioned logic of adding members to projects and administrators to the whole Garden cluster.

Currently, Gardener relies on the [`garden.sapcloud.io:system:project-member` `ClusterRole`](https://github.com/gardener/gardener/blob/master/charts/gardener/templates/rbac.yaml#L161-L210) in the Garden cluster.
* A project member is any `User`/`Group`/`ServiceAccount` that is part of a `RoleBinding` named `garden-project-members` that was labelled with `garden.sapcloud.io/role=members` and binds to the mentioned `ClusterRole` (the `RoleBinding` must have exactly this name and label so that the Gardener dashboard can understand and work with it).
* An administrator is any `User`/`Group`/`ServiceAccount` that is part of a `ClusterRoleBinding` named `garden-administrators` that was labelled with `garden.sapcloud.io/role=admins` and binds to the mentioned `ClusterRole` (again, same conditions apply due to the Gardener dashboard).

Both ways are hard to understand, too implicit and unversioned. We want to have a better way of binding members to projects and defining administrators.

One approach could be to introduce dedicated `Member` or `Admin` resources in the Garden API, together with corresponding controllers which would be responsible for the underlying RBAC logic. It could look like that:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Member
metadata:
  name: john-doe
  namespace: garden-my-project
spec:
  subject:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  project: my-project
---
apiVersion: garden.sapcloud.io/v1beta1
kind: Admin
metadata:
  name: alice
spec:
  subject:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
```

Another approach could be to include the list of members into the now existing `Project` resources, e.g. like that:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Project
metadata:
  name: my-project
spec:
  owner:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
# description: "This is my first project"
# purpose: "Experimenting with Gardener"
  members:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: alice@example.com
```

However, how would be administrators realised? We would still need a dedicated resource like in the first proposal.

Both approaches would be easier to implement a) for the Gardener dashboard or b) for any client that wants to talk to the Gardener.

Do we have other ideas or general comments/suggestions?

/cc @holgerkoser @petersutter @grolu @mvladev

**Comment by bergerx** [comment]
Wow this issue tells a o lot to digest for me about how the authz works on garden cluster. The information in this issue hasn't been documented anywhere (so thanks for the detailed description in the issue :+1:) and i didn't have time to go through the code to deduct the flow you explained here.

In our case, we host gardener on AKS and we still can't run a gardener dashboard due to unknown auth config used for apiserver control plane hosted on AKS (the AAD oauth client that AKS uses can't be used for gardener-dashboard due to several incompatible configuration parameters).

Partly as a result of not having a dahboard, and partly because we prefer shoot creations and changes to be handled by PRs (as result of our infra-as-code approach), we don't let any non-garden-admin users to access to the garden clusters yet (this part is still not final). We have our own pipelines that applies project/shoot resources on our garden clusters.

We were also planning about putting some RBAC roles and bindings around the project namespaces to allow shoot users to be able to at least see (no change) status of their own resources.

We need to go through the Role and RoleBinding changes introduced in #330 to have a better understanding and provide helpful feedback here, but i don't think we'll have any time soon :(. I just wanted to provide what we have, so you can have an idea about at least one other Gardener project user's point of view.

**Comment by luisdavim** [comment]
I like the second approach better, even though we'd have to manage admis separately, it makes it easier to manage users from a shoot centric perspective. I can see pros and cons in both approaches but we definitely need these dedicated resources.

**Comment by rfranzke** [comment]
@luisdavim that's true, it makes it little easier. The "problem" with the second approach is that anyone who may write the `Project` resource does now also have privileges for adding/removing members. In case we would like to control that separately (who may add/remove members) this won't be possible with this approach.

**Comment by luisdavim** [comment]
That's a good point @rfranzke, I agree.

**Comment by rfranzke** [comment]
FYI: We decided to go with the second approach for now (see #480):

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Project
metadata:
  name: my-project
spec:
  owner:
    apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
# description: "This is my first project"
# purpose: "Experimenting with Gardener"
  members:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: john.doe@example.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: alice@example.com
```

We won't introduce dedicated `Admin` resources now either. A Gardener administrator is a user that is bound to the [`garden.sapcloud.io:admin` ClusterRole](https://github.com/gardener/gardener/blob/master/charts/gardener/templates/rbac.yaml#L1-L11) via a `ClusterRoleBinding`.
