### ISSUE TITLE
Sane minimum resource requests for Seed's metrics server

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#3619]
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/priority normal

**What would you like to be added**:

Provide sane minimum resource requests for Seed's metrics server to prevent it from being CPU throttled.
If it is throttled it cannot provide the necessary metrics for its own VPA and any Shoot cluster in the Seed.
This leads to horizontal scaling not working for Shoot kube-apiservers.
cc @mvladev 

**Why is this needed**:

We have seen cases when the metrics server of a Shooted / ManagedSeed cluster got CPU throttled.
It could not serve the Metrics API any more.

```
k describe hpa kube-apiserver-fdjl
  Warning  FailedGetResourceMetric  99s (x744 over 6h16m)  horizontal-pod-autoscaler  missing request for cpu
```

In turn, the vpa recommendations for the deployment of the metrics server itself were also not adjusted. 
So it never scaled up.

The CPU limits for the metrics server in the kube-system ns of the Seed were very low:

```
kubectl -n kube-system describe vpa metrics-server
RecommendationProvided
  Recommendation:
    Container Recommendations:
      Container Name:  metrics-server
      Lower Bound:
        Cpu:     22m
        Memory:  225354966
      Target:
        Cpu:     23m
        Memory:  225384266
      Uncapped Target:
        Cpu:     23m
        Memory:  225384266
      Upper Bound:
        Cpu:     24m
        Memory:  240035464
```

In comparison to another Seed of similar size:

```
  recommendation:
    containerRecommendations:
    - containerName: metrics-server
      lowerBound:
        cpu: 22m
        memory: "203680514"
      target:
        cpu: 35m
        memory: "203699302"
      uncappedTarget:
        cpu: 35m
        memory: "203699302"
      upperBound:
        cpu: 36m
        memory: "213093882"
```

**Comment by timebertt** [comment]
> Provide sane minimum resource requests for Seed's metrics server to prevent it from being CPU throttled.

I guess, this is not only related to Seed clusters but to Shoot clusters in general, right?

In the particular case you observed, was the VPA enabled for the Shoot?

**Comment by danielfoehrKn** [comment]
> In the particular case you observed, was the VPA enabled for the Shoot?

Not at first, but we enabled it. 

I am just thinking that we need higher minimum resource requests for metric servers of Seed clusters because they'll have a higher load.

**Comment by vpnachev** [comment]
Actually, the `minAllowed` is not set for the `metrics-server` VPA https://github.com/gardener/gardener/blob/5a13e6b11a5452e51c0f010c3839319b8f8b67e6/pkg/operation/botanist/systemcomponents/metricsserver/metrics_server.go#L393-L408.

**Comment by plkokanov** [comment]
Just to add an additional cause for the same error:

When sni is enabled an `apiserver-proxy-pod-mutator` container is added to the `kube-apiserver` pod. This container is missing the `resources` field:

```
- args:
    ...
    image: ...
    imagePullPolicy: IfNotPresent
    name: apiserver-proxy-pod-mutator
    resources: {}
``` 

This basically prevents the hpa from reading the full CPU/Memory requests.
