### ISSUE TITLE
Network policy allow-to-seed-apiserver is not updated on time when APIServerSNI is enabled

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#3717]
**How to categorize this issue?**

/kind bug
/priority normal
/assign @mvladev 

**What happened**:
The APIServerSNI feature gate was enabled for a seed cluster that hosts managed seeds.
When this has happened the managed seed was not in its maintenance time window, thus it did not get a shoot reconciliations, just the SHOOTEDSEED controller has reconciled it, i.e. re-deployed and re-configured the gardenlet. 
Later, during the maintenance time window, the managed seed got the mutating webhook `apiserver-proxy.networking.gardener.cloud` and its kube-apiserver deployment was extended with a sidecar `apiserver-proxy-pod-mutator` which will be responsible to inject `KUBERNETES_SERVICE_HOST` in the pods of the managed seed, i.e. in the gardenlet pod. However, there is nothing to re-restart the gardenlet and it did not get the environment variable, hence the 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: Allows Egress from pods labeled with 'networking.gardener.cloud/to-seed-apiserver=allowed'
      to Seed's Kubernetes API Server endpoints in the default namespace.
  name: allow-to-seed-apiserver
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.0.12.241/32 # the address of the default/kubernetes endpoint
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-seed-apiserver: allowed
  policyTypes:
  - Egress
```

While, it must be extended also with the address of the SNI ingress LoadBalancer 
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: Allows Egress from pods labeled with 'networking.gardener.cloud/to-seed-apiserver=allowed'
      to Seed's Kubernetes API Server endpoints in the default namespace.
  name: allow-to-seed-apiserver
spec:
  egress:
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 10.0.12.241/32
  - ports:
    - port: 443
      protocol: TCP
    to:
    - ipBlock:
        cidr: 1.2.3.4/32 # this is the IP address of the SNI Ingress LB. It is set by the gardenlet based on the KUBERNETES_SERVICE_HOST env var
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-seed-apiserver: allowed
  policyTypes:
  - Egress
```

Due to the misconfigured network policy, a lot of control plane components of normal shoots hosted in the managed seed cannot connect to the API of the seed as they have been injected with `KUBERNETES_SERVICE_HOST`.

**What you expected to happen**:
The gardenlet pods to be updated on time when the SNI is enabled/disabled.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a seed and managed seed initially with APIServerSNI=false.
1. Enable APIServerSNI while the managed seed is outside of its maintenance time window.
1. Create a shoot scheduled on the managed seed.
1. Check that some of the controllers are failing to connect to the API of the managed seed, for example the Gardener Resource Manager.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.18.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
