### ISSUE TITLE
Validate extension resources (`Infrastructure`, etc.) using strict validation

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener#3787]
**How to categorize this issue?**

/area control-plane
/kind enhancement
/priority 3

**What would you like to be added**:

Extension resources such as `Infrastructure` should be properly validated using the so-called "strict validation" that was introduced recently. In this validation mode, validation should fail if there is any data that is not part of the API definition.

**Why is this needed**:

We recently had the case where the infrastructure creation failed because the user did not indent `natGateway` properly in an infrastructure resource :

```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
spec:
  provider:
    type: azure
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      networks:
        ...
      natGateway: # <--- nat gateway should be under networks
        ...
```

Changing the validation as described would enable us to detect and report such mistakes earlier, e.g. when the Shoot resource is created, rather than much later when the infrastructure creation fails.
