### ISSUE TITLE
Support SecretBinding for DNS Providers

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#3846]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 3

**What would you like to be added**:
The `Shoot` API should be extended by an optional `secretBindingName` field which can be used as an alternative for `shoot.spec.dns.providers[].secretName` to set up DNS providers:

```yaml
spec:
  dns:
    domain: foo.bar
    providers:
      - secretBindingName: gcp-secret-binding
        type: google-clouddns
      - secretName: aws-secret
        type: aws-route53
```

**Why is this needed**:
Today, DNS providers for shoot clusters refer to `Secrets` that reside in the very same namespace as the `Shoot`.
In addition, users might want to refer to `Secrets` in other project namespaces where they have access to.

/cc @grolu
