### ISSUE TITLE
Proposal: Expose Extension Provider Status in Gardener cluster 

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#3873]
**How to categorize this issue?**

/area quality
/kind enhancement
/priority 3

**What would you like to be added**:

I'd like to propose a way to expose the **ProviderStatus**  of an extension resource ("lives" in the Seed) to a resource in the Garden cluster.

Generally, there are three ways how to accomplish this

1. Put the information into the Shoot status 
2. Use config map or secret to store the information
3. Create a dedicated resource in the project accessible by shoot owners (raw.Config type for the state, can be used for any extension)

The downside of 1) is that it further bloats the Shoot resource, we want to avoid this especially because a provider status can be large.

For 2) 
 - advantage: less code needed because we reuse an existing type. We only need to store information, not actively reconcile it.
 - disadvantage:   
      - Gardener internal consumers (admission webhooks etc.) need to deal with an awkward format parsed from a config map.
      - provider status itself is generic, but there is general information that is not (extension kind (Infrastructure), type (aws), associated shoot that is not. This information would have to be either included in the naming of the config map resource, put into untyped fields in the cm or as annotations.

I propose to use 3) and create a new resource `ExtensionProviderStatus`.  
This has the advantage of an API with well-defined format  (besides the generic provider status) and easier handling for consumers (possibly e.g use field-selector).

**Concretely**

The Gardenlet creates & updates the resource **ExtensionProviderStatus** (namespace: project-ns, name <shoot-name>-<extension-kind>) in the garden cluster with the  **ProviderStatus** field of the particular extension resources in the Seed.
This can be done similar to the `ShootState` resource in the federated-seed-controller.

```
apiVersion: core.gardener.cloud/v1beta1
kind: ExtensionProviderStatus
metadata:
  # e.g <shoot>-infrastructure  | <shoot>-worker
  name: <shoot-name>-<extension-kind>
  namespace: garden--myproject
spec:
  kind: Infrastructure
  type: aws
  shootName: my-shoot
status:
  # provider status type raw.Extension
  apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
  ec2:
    keyName: shoot--xx-publickey
  iam:
    instanceProfiles:
      - name: shoot----seed-aws-boot-nodes
        purpose: nodes
    roles:
      - arn: arn:aws:iam::802691470131:role/shoot----seed-aws-boot-nodes
        purpose: nodes
  kind: InfrastructureStatus
  vpc:
    id: vpc-xx
    securityGroups:
      - id: sg-xx
        purpose: nodes
    subnets:
      - id: subnet-xx
        purpose: public
        zone: eu-west-1a
      - id: subnet-xx
        purpose: nodes
        zone: eu-west-1a
```

Extensions that want their `providerStatus` to be synced,  need to set the field `syncProviderStatus` in the `ControllerRegistration`.
A predicate in the federated-seed-controller of the gardenlet would make sure that only extension resources are enqueued 
where the `ControllerRegistration` has `syncProviderStatus = true` (default: false) set.

```
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: provider-aws
spec:
  resources:
    - kind: Infrastructure
      type: aws
      # primary: true
      syncProviderStatus: true

  deployment:
    type: helm
    providerConfig:
      chart: |
        H4sIFAAAAAAA/yk...
      values:
        foo: bar
```

**Why is this needed**:

 - However, Shoot owners want to know via Gardener API which (provider/cloud) resources have been created for a Shoot (Shoot owners typically do not have access to the Seed cluster, so they cannot check the status of the Extension 
   resource  (e.g Infrastructure CRD) in the Seed).
   This enables to build custom functionality on top e.g VPC peerings,.... . 

 - Can be used for admission decisions on the Shoot resource.
  For example,  
 - By gardener-extension-admission webhook to allow deletion of a zone whose subnets have not been created yet.
 - First step to zone deletion that has already been created (in addition to not create workers  index-based & remove leftovers in the zone)
