### ISSUE TITLE
Health check messages with strong types

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener#3899]
**How to categorize this issue?**

/area quality
/kind enhancement
/priority 3

**What would you like to be added**:

At the moment, health check messages (from the Gardenlet & the extensions) are aggregated into one field of type `string`.

```
- lastTransitionTime: "2021-04-19T17:03:27Z"
    message: API server /healthz endpoint responded with success status code.
    reason: HealthzRequestSucceeded
    status: "True"
    type: APIServerAvailable
  - lastTransitionTime: "2021-04-19T17:05:52Z"
    message: "1) deployment “cloud-controller-manager” in namespace “shoot--d060239--garden”
        is unhealthy: Deployment does not have minimum availability (MinimumReplicasUnavailable).
        2) deployment “csi-snapshot-controller” in namespace “shoot--d060239--garden”
        is unhealthy: Deployment does not have minimum availability (MinimumReplicasUnavailable)".
    reason: ControlPlaneRunning
    status: "True"
    type: ControlPlaneHealthy
  - lastTransitionTime: "2021-04-19T17:03:27Z"
    message: All nodes are ready.
    reason: EveryNodeReady
    status: "True"
    type: EveryNodeReady
  - lastTransitionTime: "2021-04-19T17:03:27Z"
    message: All system components are healthy.
    reason: SystemComponentsRunning
    status: "True"
    type: SystemComponentsHealthy
```

I propose strong API types for health check messages in the Shoot's `Status`.
To give an example, this is how the Shoot's conditions could look like: 

```
-   lastTransitionTime: "2021-04-19T17:05:52Z"
    reason: FailingHealthChecks
    status: "False"
    type: ControlPlaneHealthy
    healthchecks: 
    - origin: Extension
      area: "Infrastructure provisioning"
      code: "ERR_INFRA_UNAUTHORIZED"
      target:
        -  kind: Deployment
           name: cloud-controller-manager
           namespace: shoot--xyz--garden
      reason: "MinimumReplicasUnavailable"
      message: "There are only (0/1) available replicas."
      status: "False"
      lastUpdateTime: xxx
      lastTransitionTime: xxx
    
    - origin: Extension
      area: "Logging"
      target:
        -  kind: StatefulSet
           name: loki
           namespace: shoot--xyz--garden
      reason: "MinimumReplicasUnavailable"
      message: "There are only (0/3) available replicas."
      status: "False"
      lastUpdateTime: xxx
      lastTransitionTime: xxx
    
    - origin: Gardenlet
      area: "Tunnel Connection"
      reason: "NoTunnelDeployed"
      message: "no tunnels are currently deployed to perform health-check on"
      status: "False"
      lastUpdateTime: xxx
      lastTransitionTime: xxx
```
The detailed health checks could also be externalized into a dedicated resource to reduce the Shoot `status` size.

Strong types for the Health checks messages should consequently also be used for the aggregated health check reports on the **Extension resources**. 

**Why is this needed**:

- More meaningful health check reports 
- Better human readability possible. Especially in conjunction with the Dashboard.
- Better machine parseable for consumers of the Shoot API.
  
E.g the Dashboard can only display the error as a `string` field. 
Having strong types could have following advantages for the dashboard.
- Properly display a list of failing health checks for one condition type instead of awkwardly parsing a string or dumping the whole error message containing multiple errors into one window.
- More exact status report: "There are 3 problems with the  readiness concerning the Shoot’s control plane”
