### ISSUE TITLE
Generate kubeconfig secret with shoot-login credential plugin

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#3949]
**How to categorize this issue?**
/area security
/area dev-productivity
/kind enhancement
/priority 3

## What would you like to be added:
The `gardener` should generate a `kubeconfig` `secret`, similar to the (to-be-deprecated) `<shoot-name>.kubeconfig` `secret` in the project namespace with the difference, that it does not contain any user credentials but rather uses a [client-go credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) to receive the credentials.
It can then be downloaded by the `gardener/dashboard`, `gardenctl` or by user's calling the API directly to fetch the `secret`.

### Motivation

With [GEP-16](https://github.com/gardener/gardener/blob/master/docs/proposals/16-adminkubeconfig-subresource.md), users are able to generate kubeconfigs for `Shoot` clusters with short-lived certificates, to access the cluster as `cluster-admin`.
@mvladev suggested to have a client-go credential plugin, similar to [kubelogin](https://github.com/int128/kubelogin) to receive the client credentials and make use of the API introduced with GEP-16. Let's call this plugin `shoot-login` for now.

### Example

A `Shoot` cluster `kubeconfig` with the `shoot-login` credential plugin could look like the following:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: shoot--myproject--mycluster
  cluster:
    server: 'https://api.mycluster.myproject.shoot.dev.k8s-hana.ondemand.com'
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    extensions:
    - name: client.authentication.k8s.io/exec # reserved extension name for per cluster exec config
      extension:
        shootRef:
          namespace: garden-myproject
          name: mycluster
        gardenClusterIdentity: landscape-dev # from garden cluster's `kube-system/cluster-identity` ConfigMap
contexts:
- name: shoot--myproject--mycluster
  context:
    cluster: shoot--myproject--mycluster
    user: shoot--myproject--mycluster
current-context: shoot--myproject--mycluster
users:
- name: shoot--myproject--mycluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      provideClusterInfo: true # To enable the exec plugin to obtain cluster-specific information
      command: kubectl
      args:
      - shoot-login
      - get-client-certificate
```

The configuration file of the `shoot-login` credential plugin is configured by the user in advance (similar to `gardenctl`) and could look like the following:
```yaml
gardenClusters:
  - clusterIdentity: landscape-dev
    kubeconfig: ~/local/path/garden-kubeconfig.yaml
```

### Flow

To authenticate against the `Shoot` cluster, the flow could look like the following:

1. The user would either download the `Shoot` cluster `kubeconfig` 
    - using the `gardener/dashboard` 
    - by targeting the cluster with `gardenctl`
    - or using the `API` to fetch the `secret`
2. `kubectl` is then configured to use the downloaded `kubeconfig` for the shoot cluster
3. A `kubectl` command is executed, e.g. `kubectl get namespaces`
4. The `shoot-login` credential plugin is called to print the `ExecCredential` to `stdout`, see [input and output formats](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats) for more information.
5. In case a valid credential is already cached locally it can be returned directly. Otherwise a new credential has to be requested
6. According to the garden cluster identity under `clusters[].cluster.extensions[].extension.gardenClusterIdentity`, the `shoot-login` plugin searches a matching garden cluster in it's configuration file (`gardenClusters[].clusterIdentity`) to get the `kubeconfig` of the garden cluster
7. The `shoot-login` plugin calls `shoots/adminkubeconfig` resource with an `AdminKubeConfigRequest` for the `Shoot` cluster referenced under `clusters[].cluster.extensions[].extension.shootRef`
8. The `shoot-login` plugin takes the x509 client certificate from the returned `AdminKubeConfigRequest` under `status.kubeconfig` and prints it as `ExecCredential` to `stdout`

### Why not call the `shoots/adminkubeconfig` resource directly?

The following reasons speak against using the `shoots/adminkubeconfig` resource directly.

Instead, a `kubeconfig` with the `shoot-login` credential plugin should be used:
1. The `kubeconfig` does does not impose the risk of leaking credentials in case it shown during a Demo or in case it was accidentally pushed to a `git` repository, etc.
2. The `kubeconfig` can be shared with team members as it does not contain any user identity
3. The `shoot-login` plugin transparently refreshes the credentials in case they expire
