### ISSUE TITLE
Missing log line when KAS is configured with unsupported feature gate

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4010]
**How to categorize this issue?**

/area ops-productivity quality robustness
/kind bug
/priority 3

**What happened**:
https://github.com/gardener/gardener/pull/3353 has improved a lot the ops experience by providing the latest log lines. 
Sometimes, it misses the log line about the misconfigured feature gate (maybe it is even not logged, changed log format or no more logging it).

**What you expected to happen**:
The logs from the kube-apiserver to contain the message what was wrongly configured and prevents successful start-up.

**How to reproduce it (as minimally and precisely as possible)**:
Not very clear, but try with shoot running k8s 1.20 and feature gate `ConfigurableFSGroupPolicy`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.21.x
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vpnachev** [comment]
I finally succeeded to reproduce this issue with shoot running k8s 1.16 (It did not happen with 1.15 and 1.18).
The shoot manifest is:
<details>
  <summary>Shoot manifest:</summary>

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: foo
spec:
  addons:
    kubernetesDashboard:
      authenticationMode: basic
      enabled: false
    nginxIngress:
      enabled: false
      externalTrafficPolicy: Cluster
  cloudProfileName: aws
  hibernation:
    enabled: false
  kubernetes:
    allowPrivilegedContainers: false
    kubeAPIServer:
      featureGates:
        ConfigurableFSGroupPolicy: true
    kubeControllerManager:
      nodeCIDRMaskSize: 24
    kubeProxy:
      mode: IPTables
    version: "1.16"
    verticalPodAutoscaler:
      enabled: true
  maintenance:
    autoUpdate:
      kubernetesVersion: false
      machineImageVersion: false
    timeWindow:
      begin: 010000+0000
      end: 020000+0000
  networking:
    nodes: 10.250.0.0/16
    pods: 100.96.0.0/11
    services: 100.64.0.0/13
    type: calico
  provider:
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
        - internal: 10.250.112.0/22
          name: eu-west-1a
          public: 10.250.96.0/22
          workers: 10.250.0.0/19
    type: aws
    workers:
    - machine:
        image:
          name: gardenlinux
        type: c5.large
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 1
      labels:
        shell: "1"
      name: gardenlinux
      volume:
        size: 50Gi
        type: gp2
      zones:
      - eu-west-1a
  region: eu-west-1
  secretBindingName: shoot-operator-aws
  purpose: development
```

</details>

The `kube-apiserver` reports the wrong configuration but on the first line 
```bash
$ k logs kube-apiserver-6b7c6b6c8b-nd7lp kube-apiserver | head
Error: invalid argument "ConfigurableFSGroupPolicy=true" for "--feature-gates" flag: unrecognized feature gate: ConfigurableFSGroupPolicy
Usage:
  hyperkube kube-apiserver [flags]

Generic flags:

      --advertise-address ip                         The IP address on which to advertise the apiserver to members of the cluster. This address must be reachable by the rest of the cluster. If blank, the --bind-address will be used. If --bind-address is unspecified, the host's default interface will be used.
      --cors-allowed-origins strings                 List of allowed origins for CORS, comma separated.  An allowed origin can be a regular expression to support subdomain matching. If this list is empty CORS will not be enabled.
      --default-not-ready-toleration-seconds int     Indicates the tolerationSeconds of the toleration for notReady:NoExecute that is added by default to every pod that does not already have such a toleration. (default 300)
      --default-unreachable-toleration-seconds int   Indicates the tolerationSeconds of the toleration for unreachable:NoExecute that is added by default to every pod that does not already have such a toleration. (default 300)
```

While gardenlet is looking only in the last 10 log lines which are
```
$ k logs kube-apiserver-6b7c6b6c8b-nd7lp kube-apiserver | tail
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --logtostderr                      log to standard error instead of files (default true)
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --version version[=true]           Print version information and quit
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

A quick solution would be to also get the first 10 log lines.
