### ISSUE TITLE
Grafana NetworkPolicy does not match Ingress controller in kube-system

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#4108]
**How to categorize this issue?**

/area monitoring
/area security
/kind bug
/priority 2

**What happened**:

The shoot's Grafana deploys a NetworkPolicy which does not match the Nginx Ingress Controller in `kube-system`. Hence it's not accessable:

The NetworkPolicy
```yaml
Name:         allow-grafana
Namespace:    shoot--garden--hm4vihjqoz
Created on:   2021-05-25 13:02:05 +0200 CEST
Labels:       <none>
Annotations:  gardener.cloud/description: Allows Ingress to the Grafana from the nginx controller and Egress to Prometheus.
Spec:
  PodSelector:     component=grafana,garden.sapcloud.io/role=monitoring
  Allowing ingress traffic:
    To Port: 3000/TCP
    From:
      NamespaceSelector: role=garden
      PodSelector: app=nginx-ingress,component=controller
    From:
      NamespaceSelector: role=kube-system
      PodSelector: app=nginx-ingress,component=controller
  Allowing egress traffic:
    To Port: 9090/TCP
    To:
      PodSelector: app=prometheus,garden.sapcloud.io/role=monitoring,role=monitoring
  Policy Types: Egress, Ingress 

```

The nginx-ingress controller:
```yaml
Name:                 nginx-ingress-controller-dbb74974-bdsl5
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Start Time:           Sat, 22 May 2021 16:49:17 +0200
Labels:               app.kubernetes.io/component=controller
                           app.kubernetes.io/instance=nginx-ingress
                           app.kubernetes.io/name=ingress-nginx
                           pod-template-hash=dbb74974e
```

as can be seen the labels don't match the label selectors

**What you expected to happen**:

Labels matching the selectors and traffic being allowed.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Gardener 1.23.1 to GCP and create a shoot. Then try to access the Grafana Dashbaord of that Shoot

**Environment**:

- Gardener version: 1.23.1
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: GCP
