### ISSUE TITLE
Shoot fails to be reconciled after enabling ManagedIstio and APIServerSNI feature gates

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4127]
/kind bug
/priority 3

**What happened**:

Shoot fails to be reconciled after enabling ManagedIstio and APIServerSNI feature gates

**How to reproduce it (as minimally and precisely as possible)**:

1. Start gardenlet with APIServerSNI and ManagedIstio feature gates disabled

```yaml
featureGates:
  APIServerSNI: false
  ManagedIstio: false
```

2. Create Shoot and make sure that it is successfully created

3. Start gardenlet with APIServerSNI and ManagedIstio feature gates enabled

```yaml
featureGates:
  APIServerSNI: true
  ManagedIstio: true
```

4. Make sure that the reconciliation of the existing Shoot fails with:

```yaml
status:
  lastErrors:
  - description: 'task "Finishing Kubernetes API server service SNI transition" failed:
      retry failed with context deadline exceeded, last error: Service "kube-apiserver"
      is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is
      ''ClusterIP'''
    lastUpdateTime: "2021-05-28T13:33:42Z"
    taskID: Finishing Kubernetes API server service SNI transition
  lastOperation:
    description: 'Flow "Shoot cluster reconciliation" encountered task errors: [task
      "Finishing Kubernetes API server service SNI transition" failed: retry failed
      with context deadline exceeded, last error: Service "kube-apiserver" is invalid:
      spec.ports[0].nodePort: Forbidden: may not be used when `type` is ''ClusterIP'']
      Operation will be retried.'
    lastUpdateTime: "2021-05-28T13:33:42Z"
    progress: 98
    state: Error
    type: Reconcile
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v1.24.0-dev-8256a360c1e17102a084c849027d120df0a26605`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
