### ISSUE TITLE
CIDRs for default networks are not written to Seed from ManagedSeed

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#4323]
**How to categorize this issue?**

/area networking
/area usability
/kind bug
/priority 3

**What happened**:

When creating a `ManagedSeed` for an existing shoot cluster, Gardener does not write the `shootDefaults` CIDRs to the resulting `Seed` resource.
The effect is, that Gardener will not auto-populate the `pods` and `services` CIDRs for newly created `Shoot` clusters, which especially breaks the `Shoot` creation from the Dashboard. 
Manually adding those fields to a `Shoot` still works. 

Error when creating a `Shoot` from the Dashboard: 

```shell
Warning  SchedulingFailed  68s (x4 over 2m53s)  gardener-scheduler  Failed to schedule shoot 'pmsfesky8i' : 0/1 seed cluster candidate(s) are eligible for scheduling: {me-south-1 => invalid networks: [Required value: services is required Required value: pods is required]}
```

Example ManagedSeed:

```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: myseed
  namespace: garden # Must be garden
spec:
  shoot:
    name: myshoot
  gardenlet:
    config:
      seedConfig:
        networks:
          nodes: 10.242.0.0/16
          pods: 10.243.128.0/17
          services: 10.243.0.0/17
          shootDefaults:
            pods: 100.96.0.0/11
            services: 100.64.0.0/13
```

Resulting Shoot snippet:

```yaml
(...)
spec:
  dns:
    ingressDomain: <redacted>
  networks:
    nodes: 10.242.0.0/16
    pods: 10.243.128.0/17
    services: 10.243.0.0/17
(...)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Create a ManagedSeed and observe the Seed manifest for said fields.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.24.1
- Kubernetes version (use `kubectl version`): 1.20.7
- Cloud provider or hardware configuration: GCP and AWS
- Others:
