### ISSUE TITLE
OS version for a shoot is defaulted to newer but deprecated version when older but supported is available.

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#4324]
**How to categorize this issue?**

/kind bug
/priority 2
/assign

**What happened**:
A shoot cluster was created with empty OS version. The gardener API has defaulted it to newer but deprecated version when older and supported one is available.

**What you expected to happen**:
To not default worker pool to a deprecated OS version.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cloud profile with the following machineImages spec
```yaml
  machineImages:
  - name: gardenlinux
    versions:
    - classification: preview
      version: 318.8.0
    - classification: deprecated
      expirationDate: '2021-08-31T23:59:59Z'
      version: 318.4.0
    - classification: supported
      version: 184.0.0
```

Create a shoot or add a worker pool to existing shoot with the following spec
```yaml
    - machine:
        image:
          name: gardenlinux
```

Check that the worker os version for this worker pool is set to use the deprecated `318.4.0` instead of the supported `184.0.0`.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.26.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
