### ISSUE TITLE
Additional DNS provider Secret is not updated on Shoot deletion

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4333]
**How to categorize this issue?**
/area quality
/kind bug
/priority 3

**What happened**:

Additional DNS provider Secret is not updated on Shoot deletion.

**What you expected to happen**:

Similar to the `cloudprovider` Secret, during the Shoot deletion flow gardenlet should also sync the additional DNS provider Secret. This is to allow end users to update their invalid Secret data with valid one.

**How to reproduce it (as minimally and precisely as possible)**:

1. Prepare a correct && valid secret for DNS provider

2. Create a Shoot with additional DNS provider

```yaml
spec:
  dns:
    domain: testy.ialidzhikov.shoot.dev.example.com
    providers:
      - domains:
          include:
            - testy2.ialidzhikov.shoot.staging.example.com
        primary: false
        secretName: my-secret
        type: aws-route53
```

Make sure that the corresponding DNSProvider in the Seed is `Ready`.

3. Create a DNS record with the additional DNS provider

In the Shoot cluster apply the following Service:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: "test.testy2.ialidzhikov.shoot.staging.example.com"
  name: dns
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
```

Make sure that the DNSEntry in the Seed is `Ready`:

4. Change the secret for DNS provider with invalid one (to simulate credentials that got invalid)

5. Delete the Shoot

6. Make sure that as expected the Shoot deletion fails with

```yaml
status:
  lastErrors:
    - description: "task \"Waiting until extension resources have been deleted\" failed: 1 error occurred:\n\t* Failed to delete Extension shoot--foo--testy/shoot-dns-service: Error deleting Extension resource: waiting until shoot DNS entries have been deleted\n\n"
      taskID: Waiting until extension resources have been deleted
      lastUpdateTime: '2021-07-08T13:03:50Z'
```

7. Update the secret for DNS provider with correct && valid one

8. Make sure that the Shoot deletion still fails with the same error and that the DNSProvider secret in the Seed is not updated with the new Secret data (still contains the data of the old && invalid one).

**Environment**:

- Gardener version: v1.26.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

/cc @MartinWeindel
