### ISSUE TITLE
gardenlet fails to delete Shoot when ssh-keypair is missing in the ShootState

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4393]
/kind bug
/kind regression
/priority 2

**What happened**:
Currently gardenlet may fail to create Shoot in the early steps of the Shoot reconcile flow (or simply gardenlet can be in CrashloopBackoff because of any other reason). In such case depending of the problematic step the ShootState can be empty. Deletion of such failed Shoot fails with:

```yaml
  lastOperation:
    description: 'Flow "Shoot cluster deletion" encountered task errors: [task "Generating
      secrets and saving them into ShootState" failed: no Secret named ssh-keypair
      loaded] Operation will be retried.'
```

**What you expected to happen**:
The deletion of such Shoot to succeed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot and simulate a failure in the Shoot reconciliation flow before the step `Generating secrets and saving them into ShootState`

2. Maintain the Shoot

This will also lead to ssh key rotation - the `gardener.cloud/operation: rotate-ssh-keypair` annotation will be added to the Shoot

3. Delete the Shoot

4. Make sure that the deletion fails with:

```yaml
  lastOperation:
    description: 'Flow "Shoot cluster deletion" encountered task errors: [task "Generating
      secrets and saving them into ShootState" failed: no Secret named ssh-keypair
      loaded] Operation will be retried.'
    lastUpdateTime: "2021-07-20T07:52:48Z"
    progress: 17
    state: Error
    type: Delete
```

- Gardener version: v1.28.0-dev-3806079d4e35dca8064e39ce0e69a0912aa02778
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
