### ISSUE TITLE
SSH keypair rotation does not work for Alicloud Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4395]
/kind bug
/priority 3

**What you expected to happen**:
SSH keypair rotation to work for Alicloud Shoot.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an Alicloud Shoot

2. Maintain the Shoot (annotate it gardener.cloud/operation=maintain)

Currently the maintain operation also performs SSH key pair rotation.

3. Make sure that the Shoot fails to reconcile with:

```yaml
  lastErrors:
    - description: >-
        task "Waiting until shoot infrastructure has been reconciled" failed:
        Error while waiting for Infrastructure
        shoot--foo--bar/bar to become ready: error during
        reconciliation: Error reconciling infrastructure: failed to apply the
        terraform config: Terraform execution for command 'apply' could not be
        completed:


        * [ERROR]
        terraform-provider-alicloud/alicloud/resource_alicloud_ecs_key_pair.go:249:
        Resource shoot--foo--bar-ssh-publickey DeleteKeyPairs
        Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:

        SDKError:
           Code: InvalidParameter.KeypairAlreadyAttachedInstance
           Message: code: 400, The specified parameter "KeyPairNames" attached to instances can not be deleted. request id: <omitted>
           Data: {"Code":"InvalidParameter.KeypairAlreadyAttachedInstance","HostId":"ecs.eu-central-1.aliyuncs.com","Message":"The specified parameter \"KeyPairNames\" attached to instances can not be deleted.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidParameter.KeypairAlreadyAttachedInstance\u0026source=PopGw","RequestId":"<omitted>"}
      taskID: Waiting until shoot infrastructure has been reconciled
      codes:
        - ERR_CONFIGURATION_PROBLEM
      lastUpdateTime: '2021-07-20T13:32:33Z'
```

**Environment**:

- Gardener version: v1.28.0-dev-3fd2bce9b3e743c0586fe8dc80daac7525193184
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
provider-alicloud: v1.25.0
