### ISSUE TITLE
project member has no permission to list controllerregistrations as required by gardener dashboard

### ISSUE THREAD

**Issue by lotharbach** [gardener/gardener#4477]
**How to categorize this issue?**

/area user-management
/kind bug
/priority 3

**What happened**:
Gardener dashboard 1.51.0 is not able to show available Network Types and DNS Providers, which it tries to look up in the controllerregistrations. (unless logged in with an global admin account). With kubectl and a project-admin serviceaccount I get:
```
# kubectl get controllerregistration
Error from server (Forbidden): controllerregistrations.core.gardener.cloud is forbidden: User "system:serviceaccount:garden-23t-test:default" cannot list resource "controllerregistrations" in API group "core.gardener.cloud" at the cluster scope
```

**What you expected to happen**:
Be able to list the controllerregistration, as the dashboard depends on it for important functionality.

**How to reproduce it (as minimally and precisely as possible)**:
`# kubectl get controllerregistrations`
with a serviceaccount with gardener.cloud:system:project-member permissions

**Anything else we need to know?**:
As a quick workaround I allowed access to controllerregistrations with
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controllerregistration-reader
rules:
- apiGroups: ["core.gardener.cloud"]
  resources: ["controllerregistrations"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-controllerregistration-global
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
roleRef:
  kind: ClusterRole
  name: controllerregistration-reader
  apiGroup: rbac.authorization.k8s.io
```

It is possible that this gardener installation is missing some RBAC by accident, but I did not find anything relating to reading controllerregistration anywhere, so I'm unsure how the dashboard wound up to be dependent on being able to read them.

Maybe this is also more of an issue for g/dashboard and it needs to change there, but if list access on the controllerregistrations is considered uncritical it is easier fixed in g/g.
 
**Environment**:

- Gardener version: 1.28.2
- Gardener dashboard 1.51.0
