### ISSUE TITLE
Configuring Backups in a ManagedSeed with Gardenlet does not work

### ISSUE THREAD

**Issue by christianhuening** [gardener/gardener#4587]
**How to categorize this issue?**

/area backup
/area control-plane-migration
/kind bug
/priority 1

**What happened**:
I am deploying `ManagedSeeds` with the `GardenletConfig` in it. I also configure the `spec.backup` part of it. However, the resulting `Seed` does not get the required `Backup` entries created. As a consequence, the `BackupBucket` is not created and no `Shoot` is backed up.

**What you expected to happen**:
`Seed`gets `Backup` entry from `ManagedSeed` configuration.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: seed-test
  namespace: garden # Must be garden
spec:
  shoot:
    name: seed-test
  gardenlet:
    mergeWithParent: true 
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      featureGates:
        APIServerSNI: true
        Logging: true
        ManagedIstio: true
        ReversedVPN: true
        MountHostCADirectories: true
      seedConfig:
        provider:
          type: aws
          region: me-south-1
        backup:
          provider: aws
          region: me-south-1
          secretRef:
            name: seed-test-seed-backup
            namespace: garden
```

results in this `Seed`:

```yaml
Name:         seed-test
Namespace:    garden
Labels:       gardener.cloud/role=seed
Annotations:  seed.gardener.cloud/ingress-class: nginx
API Version:  core.gardener.cloud/v1beta1
Kind:         Seed
Metadata:
  Creation Timestamp:  2021-08-27T10:50:05Z
  Finalizers:
    core.gardener.cloud/controllerregistration
    gardener
  Generation:  1
    Manager:         gardenlet
    Operation:       Update
    Time:            2021-08-27T10:55:28Z
  Resource Version:  16985963
  UID:               84e15c2b-68b2-4cdd-8bf6-e536696953e8
Spec:
  Dns:
    Ingress Domain:  <redacted>>
  Networks:
    Nodes:     10.0.0.0/16
    Pods:      10.243.128.0/17
    Services:  10.243.0.0/17
  Provider:
    Region:  me-south-1
    Type:    aws
  Settings:
    Excess Capacity Reservation:
      Enabled:  true
    Scheduling:
      Visible:  true
    Shoot DNS:
      Enabled:  true
    Vertical Pod Autoscaler:
      Enabled:  false
Status:
  Allocatable:
    Shoots:  250
  Capacity:
    Shoots:          250
  Cluster Identity:  <redacted>
  Conditions:
    Last Transition Time:  2021-08-27T10:53:56Z
    Last Update Time:      2021-08-27T10:53:56Z
    Message:               Gardenlet is posting ready status.
    Reason:                GardenletReady
    Status:                True
    Type:                  GardenletReady
    Last Transition Time:  2021-08-31T14:22:19Z
    Last Update Time:      2021-08-31T14:22:19Z
    Message:               Seed cluster has been bootstrapped successfully.
    Reason:                BootstrappingSucceeded
    Status:                True
    Type:                  Bootstrapped
    Last Transition Time:  2021-08-27T11:02:33Z
    Last Update Time:      2021-08-27T11:02:33Z
    Message:               All extensions installed into the seed cluster are ready and healthy.
    Reason:                AllExtensionsReady
    Status:                True
    Type:                  ExtensionsReady
  Gardener:
    Id:                 96c6fef83bdee5d8559cd4e87a842ac485a840dfb0cfd24cf58247ec0ee51781
    Name:               gardenlet-5d76cffc6-bj29s
    Version:            v1.29.0
  Kubernetes Version:   v1.20.10
  Observed Generation:  1
Events:                 <none>
```

only after editing the `Seed`and manually adding the backup section from above, it does pick it up:

```yaml
Name:         seed-test
Namespace:    garden
Labels:       gardener.cloud/role=seed
Annotations:  seed.gardener.cloud/ingress-class: nginx
API Version:  core.gardener.cloud/v1beta1
Kind:         Seed
Metadata:
  Creation Timestamp:  2021-08-27T10:50:05Z
  Finalizers:
    core.gardener.cloud/controllerregistration
    gardener
  Generation:  2
    Manager:         gardener-controller-manager
    Operation:       Update
    Time:            2021-08-31T17:41:43Z
  Resource Version:  17089085
  UID:               84e15c2b-68b2-4cdd-8bf6-e536696953e8
Spec:
  Backup:
    Provider:  aws
    Region:    me-south-1
    Secret Ref:
      Name:       seed-test-seed-backup
      Namespace:  garden
  Dns:
    Ingress Domain:  <redacted>
  Networks:
    Nodes:     10.0.0.0/16
    Pods:      10.243.128.0/17
    Services:  10.243.0.0/17
  Provider:
    Region:  me-south-1
    Type:    aws
  Settings:
    Excess Capacity Reservation:
      Enabled:  true
    Scheduling:
      Visible:  true
    Shoot DNS:
      Enabled:  true
    Vertical Pod Autoscaler:
      Enabled:  false
Status:
  Allocatable:
    Shoots:  250
  Capacity:
    Shoots:          250
  Cluster Identity:  shoot--garden--seed-test-40f3bbef-4dd0-4741-9dcf-8f061e303abe-finleap-cloud-garden
  Conditions:
    Last Transition Time:  2021-08-27T10:53:56Z
    Last Update Time:      2021-08-27T10:53:56Z
    Message:               Gardenlet is posting ready status.
    Reason:                GardenletReady
    Status:                True
    Type:                  GardenletReady
    Last Transition Time:  2021-08-31T21:14:58Z
    Last Update Time:      2021-08-31T21:14:58Z
    Message:               Seed cluster has been bootstrapped successfully.
    Reason:                BootstrappingSucceeded
    Status:                True
    Type:                  Bootstrapped
    Last Transition Time:  2021-08-27T11:02:33Z
    Last Update Time:      2021-08-27T11:02:33Z
    Message:               All extensions installed into the seed cluster are ready and healthy.
    Reason:                AllExtensionsReady
    Status:                True
    Type:                  ExtensionsReady
    Last Transition Time:  2021-08-31T17:41:42Z
    Last Update Time:      2021-08-31T17:41:42Z
    Message:               Backup Buckets are available.
    Reason:                BackupBucketsAvailable
    Status:                True
    Type:                  BackupBucketsReady
  Gardener:
    Id:                 96c6fef83bdee5d8559cd4e87a842ac485a840dfb0cfd24cf58247ec0ee51781
    Name:               gardenlet-5d76cffc6-bj29s
    Version:            v1.29.0
  Kubernetes Version:   v1.20.10
  Observed Generation:  2
Events:                 <none>
```

Only then a BackupBucket is created and backups are written. 

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.28.x and 1.29.0
- Kubernetes version (use `kubectl version`): 1.20.10
- Cloud provider or hardware configuration: AWS
- Others:
