### ISSUE TITLE
AKS doesn't play well with controllers

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener#462]
We have both our garden and seed clusters running on AKS.

Apparently AKS doesn’t play well with controllers running inside the cluster due to VPN issues between AKS control plane (apiserver) and nodes, you can find the details in https://github.com/Azure/AKS/issues/676

This is causing lots of noise both in gardener and machine controller manager logs and could be causing some other unpredictable issues since it regularly break watches.

Both component logs (gcm and mcm) are full of these errors:
```E1017 09:12:18.882096       1 streamwatcher.go:109] Unable to decode an event from the watch stream: stream error: stream ID 989; INTERNAL_ERROR```

The suggested solution from Azure is to inject these environment values to the pods which runs controllers:

```yaml
      env:
        - name: KUBERNETES_PORT_443_TCP_ADDR
          value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
        - name: KUBERNETES_PORT
          value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
        - name: KUBERNETES_PORT_443_TCP
          value: tcp://<your-fqdn-prefix>.hcp.<region>.azmk8s.io:443
        - name: KUBERNETES_SERVICE_HOST
          value: <your-fqdn-prefix>.hcp.<region>.azmk8s.io
```

The gardener chart would be as easy as allowing to pass extra env values to the pods, so i think that would be covered easily.

But for `charts/seed-controlplane/charts/machine-controller-manager` I’m not sure about adding hosting provider specific logic, for which we also need to eventually update the `pkg/operation/botanist/controlplane.go` to discover if the shoot's seed is operating on AKS and pass it to the mcm chart.

But I can't see any other solution since there is no way we'd be moving out of AKS. Any suggestions?
