### ISSUE TITLE
ManagedSeed sets `debugging.*=false`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#4654]
**How to categorize this issue?**

/area dev-productivity ops-productivity
/kind bug

**What happened**:

When creating a simple `ManagedSeed` object like this
```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: gcp
  namespace: garden # Must be garden
spec:
  shoot:
    name: seed-gcp
  gardenlet: {}
```

the newly added `debugging` fields (see https://github.com/gardener/gardener/issues/4567, https://github.com/gardener/gardener/pull/4568) in the gardenlet config will be set to `false,false`:
```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
  name: gcp
  namespace: garden
spec:
  gardenlet:
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      debugging:
        enableContentionProfiling: false
        enableProfiling: false
      kind: GardenletConfiguration
# ...
    mergeWithParent: true
  shoot:
    name: seed-gcp
```

Because of this, the gardenlet that is deployed for the `ManagedSeed` will be configured with profiling handlers disabled even though the parent gardenlet has profiling handlers enabled and `mergeWithParent=true`.
Config of parent gardenlet:
```yaml
debugging:
  enableProfiling: true
  enableContentionProfiling: true
```

Config of `ManagedSeed` gardenlet:
```yaml
debugging:
  enableProfiling: false
  enableContentionProfiling: false
```

**What you expected to happen**:

I expected that if I create a `ManagedSeed` object without setting the `debugging` fields, the settings in the parent gardenlet are propagated down to the child gardenlet.

**Environment**:

- Gardener version: `v1.31.0`
