### ISSUE TITLE
Sequential ControllerInstallation deletion and creation can cause issues

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4694]
**How to categorize this issue?**

/area quality
/kind bug
/priority 3

**What happened**:
gardener-controller-manager and gardenlet do not handle properly sequential ControllerInstallation deletion and creation.

**What you expected to happen**:
- [x] GCM to do not try to update ControllerInstallation when the resource has deletionTimestamp -> https://github.com/gardener/gardener/pull/4718
- [x] gardenlet to handle properly sequential deletion and creation of ControllerInstallation with the same name (see more details below) -> https://github.com/gardener/gardener/pull/4704

**How to reproduce it (as minimally and precisely as possible)**:

Let's use the runtime/gvisor extension in our steps to reproduce.

1. Create a Shoot with gvisor enabled.

```yaml
    cri:
     name: containerd
     containerRuntimes:
      - type: gvisor
```

Make sure that a gvisor ControllerInstallation is installed in the system.

2. Remove the gvisor as part of the worker pool spec

Once the Shoot is reconciled, gardener-controller-manager will delete the gvisor ControllerInstallation (because it is no longer needed):

```
{"controllerregistration-seed":"foo","level":"info","msg":"Deleting unneeded ControllerInstallation \"runtime-gvisor-k45f5\"","time":"2021-09-20T17:51:28+03:00"}
```

The ControllerInstallation deletion usually takes ~1min as the corresponding ManagedResource in the Seed has to be deleted.

3. Once you see that GCM deleted the ControllerInstallation, immediately add gvisor once again to the worker pool

```yaml
    cri:
     name: containerd
     containerRuntimes:
      - type: gvisor
```

Make sure that afterwards this update is causing issues to GCM. Because of this update, GCM tries to deploy the ControllerInstallation but the update itself fails with

```
{"level":"info","msg":"Error syncing ControllerRegistration-Seed foo: ControllerInstallation.core.gardener.cloud \"runtime-gvisor-k45f5\" is invalid: spec: Invalid value: core.ControllerInstallationSpec{RegistrationRef:v1.ObjectReference{Kind:\"\", Namespace:\"\", Name:\"runtime-gvisor\", UID:\"\", APIVersion:\"\", ResourceVersion:\"119134\", FieldPath:\"\"}, SeedRef:v1.ObjectReference{Kind:\"\", Namespace:\"\", Name:\"foo\", UID:\"\", APIVersion:\"\", ResourceVersion:\"121408\", FieldPath:\"\"}, DeploymentRef:(*v1.ObjectReference)(0xc004153e30)}: field is immutable","time":"2021-09-20T17:51:40+03:00"}

{"level":"info","msg":"Error syncing ControllerRegistration-Seed foo: ControllerInstallation.core.gardener.cloud \"runtime-gvisor-k45f5\" is invalid: spec: Invalid value: core.ControllerInstallationSpec{RegistrationRef:v1.ObjectReference{Kind:\"\", Namespace:\"\", Name:\"runtime-gvisor\", UID:\"\", APIVersion:\"\", ResourceVersion:\"119134\", FieldPath:\"\"}, SeedRef:v1.ObjectReference{Kind:\"\", Namespace:\"\", Name:\"foo\", UID:\"\", APIVersion:\"\", ResourceVersion:\"121408\", FieldPath:\"\"}, DeploymentRef:(*v1.ObjectReference)(0xc003b74620)}: field is immutable","time":"2021-09-20T17:51:42+03:00"}
```

because the ControllerInstallation is still in deletion. It is not allowed to update the spec of ControllerInstallation when it has deletionTimestamp set. This issue itself seems not that critical for GCM as GCM will succeed to create the new ControllerInstallation when the old one is deleted.

While reproducing this issue for GCM, I noticed that gardenlet does not properly handle sequential ControllerInstallation deletion and deployment. On ControllerInstallation deletion, gardenlet waits until the corresponding ManagedResource is deleted, but it does not wait until the corresponding Namespace is deleted.

After the old ControllerInstallation was deleted and the new one was created, the new one failed get ready with reason that the corresponding ManagedResource is not ready:

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-09-20T14:51:58Z"
    lastUpdateTime: "2021-09-20T14:51:58Z"
    message: The health checks have not yet been executed for the current set of resources.
    reason: HealthChecksPending
    status: Unknown
    type: ResourcesHealthy
  - lastTransitionTime: "2021-09-20T14:52:39Z"
    lastUpdateTime: "2021-09-20T14:52:39Z"
    message: 'Could not apply all new resources: 3 errors occurred: [error during
      apply of object "v1/ServiceAccount/extension-runtime-gvisor-k45f5/gardener-extension-runtime-gvisor":
      namespaces "extension-runtime-gvisor-k45f5" not found, error during apply of
      object "autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler/extension-runtime-gvisor-k45f5/gardener-extension-runtime-gvisor-vpa":
      namespaces "extension-runtime-gvisor-k45f5" not found, error during apply of
      object "apps/v1/Deployment/extension-runtime-gvisor-k45f5/gardener-extension-runtime-gvisor":
      namespaces "extension-runtime-gvisor-k45f5" not found]'
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
```

So it seems that the Namespace was deleted by the old ControllerInstallation deletion. Then gardenlet didn't wait until the Namespace is removed from the store, and removed the finalizer of the ControllerInstallation. A new ControllerInstallation with the same name was created by GCM -> gardenlet created a new ManagedResource for it but the Namespace was meanwhile removed from the store and the new ManagedResource was not able to get ready.

**Environment**:

- Gardener version: v1.31.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
