### ISSUE TITLE
Allow to Switch On Alpha/Beta Features

### ISSUE THREAD

**Issue by gardener-robot-ci-1** [gardener/gardener#47]
**Issue by [vlerenc](https://github.com/vlerenc)**
_Monday Nov 13, 2017 at 03:53 GMT_
_Originally opened as https://git.removed/kubernetes-attic/garden-operator/issues/198_

----

We knew time would come that users want to tweak the control plane (configure authentication, switch on alpha or beta features). Now Frank was the first to request that (`apiVersion: admissionregistration.k8s.io/v1alpha1`).

How can we enable him and similar use cases, both in operator and in UI?

**Comment by gardener-robot-ci-1** [comment]
**Comment by [rfranzke](https://github.com/rfranzke)**
_Tuesday Nov 14, 2017 at 19:42 GMT_

----

We already got a [second request](https://jam.removed/questions/WmxygrQ8CVIsC1F0i5DjCm) for that.

Alpha APIs are enabled by providing the `--runtime-config` flag to the `kube-apiserver`; official documentation:
```
--runtime-config mapStringString                          A set of key=value pairs that describe runtime configuration that may be passed to apiserver. apis/<groupVersion> key can be used to turn on/off specific api versions. apis/<groupVersion>/<resource> can be used to turn on/off specific resources. api/all and api/legacy are special keys to control all and legacy api versions respectively.
```

Feature gates are enabled by providing flags to the `kube-apiserver`, `kube-controller-manager`, `kube-scheduler`, `kube-proxy` and `kubelet`; official documentation:
```
--feature-gates mapStringBool                             A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
APIListChunking=true|false (ALPHA - default=false)
APIResponseCompression=true|false (ALPHA - default=false)
[...]
TaintBasedEvictions=true|false (ALPHA - default=false)
TaintNodesByCondition=true|false (ALPHA - default=false)
```

[Kops](https://github.com/kubernetes/kops) allows specifying these flags in its `Cluster` resource, see [this](https://github.com/kubernetes/kops/blob/1.8.0-beta.1/pkg/apis/kops/v1alpha2/componentconfig.go#L216-L217) and [this](https://github.com/kubernetes/kops/blob/1.8.0-beta.1/pkg/apis/kops/v1alpha2/componentconfig.go#L135-L136).
I suggest doing it similar (having a `map[string]string` value in the Shoot specification) - the inputs are directly transferred to the respective flags (without further validation whether the values are valid/exist).

What do you think of doing it like Kops?
```
apiVersion: garden.sapcloud.io/v1
kind: Shoot
metadata:
  name: d012345-1
  namespace: d012345
  finalizers:
  - garden.sapcloud.io/operator
spec:
  seedName: seed-aws-dev
  componentConfig:
    kubeAPIServer:
      featureGates:
        TaintNodesByCondition: "true"
        [...]
      runtimeConfig:
        autoscaling/v2alpha1: "true"
        [...]
    kubeControllerManager:
      featureGates:
        TaintNodesByCondition: "true"
    [...]
  [...]
```

Another option could be not using `componentConfig`, but creating `kubernetes` section and moving the `.spec.kubernetesVersion` field into it:
```
apiVersion: garden.sapcloud.io/v1
kind: Shoot
metadata:
  name: d012345-1
  namespace: d012345
  finalizers:
  - garden.sapcloud.io/operator
spec:
  seedName: seed-aws-dev
  kubernetes:
    version: 1.8.3
    allowPrivilegedContainers: true
    kubeAPIServer:
      featureGates:
        TaintNodesByCondition: "true"
        [...]
      runtimeConfig:
        autoscaling/v2alpha1: "true"
        [...]
    kubeControllerManager:
      featureGates:
        TaintNodesByCondition: "true"
    [...]
  [...]
```
