### ISSUE TITLE
Consider machine-controller-manager settings on worker pool when performing worker health checks

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4726]
**How to categorize this issue?**

/area quality
/kind enhancement
/priority 3

**What would you like to be added**:
Each worker pool can have custom values for machine-controller-manager settings such as:

```yaml
    machineControllerManager: # optional, it allows to configure the machine-controller settings.
      machineDrainTimeout: 2h
      machineHealthTimeout: 10m
      machineCreationTimeout: 20m
```

On the other side, the default worker health checker does not consider these settings and can report a failing health check when for example the worker pool is configured with a high timeout.

**Why is this needed**:
For example one can configure a worker pool the following config:

```yaml
        machineControllerManager:
          machineDrainTimeout: 36h0m0s
```

When there is a Pod that cannot be evicted because of some reason, then the worker health checker will report a failing health check for a very long period of time (until the Node is finally drained after the timeout):

```
Worker extension (shoot--foo--bar/bar) reports failing health check: 1 machine is waiting to be completely drained from pods. If this persists, check your pod disruption budgets and pending finalizers. Please note, that nodes that fail to be drained will be deleted automatically.
```

The same applies for the `machineHealthTimeout` (for the case when Machine is unhealthy) and `machineCreationTimeout` (for the case when a new Machine is about to join the cluster) settings.
