### ISSUE TITLE
Do not allow creating a Shoot with `.spec.provider.infrastructureConfig` using an internal API version

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4874]
**How to categorize this issue?**

/area ops-productivity
/kind bug
/priority 3

**What happened**:

Currently it is possible to create a Shoot for example with `.spec.provider.infrastructureConfig` that is using internal API version of the corresponding provider-specific InfrastructureConfig:

```yaml
spec:
  provider:
    type: azure
    infrastructureConfig:
      kind: InfrastructureConfig
      apiVersion: azure.provider.extensions.gardener.cloud/__internal
      ResourceGroup: null
      Networks:
        VNet:
          Name: null
          ResourceGroup: null
          CIDR: 10.250.0.0/16
        Workers: 10.250.0.0/16
        NatGateway: null
        ServiceEndpoints: null
      Identity: null
      Zoned: false
```

Unfortunately, today it is possible to create such Shoot and it even gets created successfully.
We should not allow end users to use internal API version because:
- the internal API version is not designed to be used by end users
- the internal API version can change anytime and does not guarantee backwards compatibility 

(Most probably the extension components have to be adapted and nothing has to be on Gardener side, but let's keep this issue for now in gardener/gardener - we don't want to create the same issue for each and every extension)

**What you expected to happen**:
Using the internal API version of InfrastructureConfig to be disallowed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot with the above partial spec

2. Make sure that it is even getting created successfully.

**Environment**:

- Gardener version: e77a0606aee264a703d2bc2727104c2db0d60951
- provider-azure version: v1.22.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
