### ISSUE TITLE
gardener-seed-admission-controller RBAC has to be adapted for Etcd deletion protection

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4923]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
After https://github.com/gardener/gardener/pull/4861, deletion of Etcd fails with:

```yaml
  - lastTransitionTime: "2021-10-27T14:17:47Z"
    message: 'Failed to delete all resource types, 1 remaining: admission webhook
      "crs.seed.admission.core.gardener.cloud" denied the request: etcds.druid.gardener.cloud
      is forbidden: User "system:serviceaccount:garden:gardener-seed-admission-controller"
      cannot list resource "etcds" in API group "druid.gardener.cloud" in the namespace
      "shoot--foo--bar"'
    reason: ContentDeletionFailed
    status: "True"
    type: NamespaceDeletionContentFailure
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 951167b
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
