### ISSUE TITLE
Existing Shoot fails to be reconciled because of exhausted Secrets quota

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#4946]
**How to categorize this issue?**

/area quality ops-productivity
/kind bug

**What happened**:
Existing Shoot cluster already has its Secrets created/synced in the Project namespace in the Garden cluster. Hence. gardenlet does not need to create any new secrets. But if the Secrets quota for the given Project is exhausted reconciliation of the existing Shoot fails with:

```yaml
  lastErrors:
    - description: "task \"Syncing shoot access credentials to project namespace in Garden\" failed: retry failed with context deadline exceeded, last error: 4 errors occurred:\n\t* secrets \"foo.monitoring\" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=23, limited: count/secrets=23\n\t* secrets \"foo.ssh-keypair\" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=23, limited: count/secrets=23\n\t* secrets \"foo.kubeconfig\" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=23, limited: count/secrets=23\n\t* secrets \"foo.ssh-keypair.old\" is forbidden: exceeded quota: gardener, requested: count/secrets=1, used: count/secrets=23, limited: count/secrets=23\n\n"
      taskID: Syncing shoot access credentials to project namespace in Garden
      codes:
        - ERR_INFRA_QUOTA_EXCEEDED
```

```
$ k -n garden-bar get secrets | grep foo
foo.kubeconfig          Opaque                                3      647d
foo.monitoring          Opaque                                3      647d
foo.ssh-keypair         Opaque                                2      647d
foo.ssh-keypair.old     Opaque                                2      104d
```

**What you expected to happen**:
Reconciliation of existing Shoot to succeed even if the Secrets quota is exhausted (the reconciliation does not need to create any new Secrets).

**How to reproduce it (as minimally and precisely as possible)**:
1. Adapt the Secrets quota of existing project to match the current usage

2. Reconcile existing Shoot

3. Make sure that the reconciliation wrongly fails because of Secrets quota

**Anything else we need to know?**:
This behaviour is caused by usage of `CreateOrGetAndStrategicMergePatch`:

https://github.com/gardener/gardener/blob/ed298c256038023f2d248007cd5a1a647b153c66/pkg/operation/botanist/secrets.go#L437-L446

We always try to create the Secret (no matter it exists or not) and this create Secret call is denied by the quota admission.

**Environment**:

- Gardener version: v1.34.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
