### ISSUE TITLE
Shoot can't be deleted with `UseDNSRecords=true` if it was never reconciled with `UseDNSRecords=false`

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5132]
**How to categorize this issue?**

/area control-plane-migration
/kind regression

**What happened**:

After upgrading to `gardener@v1.37.0`, Shoots fail to be deleted with `UseDNSRecords=true` if they were never reconciled with `UseDNSRecords=false` during the step `Waiting until main and event etcd report readiness`.

**What you expected to happen**:

Shoots should not fail to be deleted regardless of the `UseDNSRecords` feature gate enablement.

**How to reproduce it (as minimally and precisely as possible)**:

1. Turn off the `UseDNSRecords` feature gate in all relevant components (apiserver, controller-manager, gardenlet)
2. Create a shoot
3. Turn on the `UseDNSRecords` feature gate in all relevant components (apiserver, controller-manager, gardenlet)
4. Delete the shoot
5. Observe, that the shoot deletion fails in step `Waiting until main and event etcd report readiness`:
```yaml
  lastErrors:
  - description: "task \"Waiting until main and event etcd report readiness\" failed:
      1 error occurred:\n\t* Error while waiting for Etcd shoot--d067603--local-9wj75/etcd-main
      to become ready: retry failed with context deadline exceeded, last error: not
      enough ready replicas (0/1)\n\n"
    lastUpdateTime: "2021-12-08T08:33:41Z"
    taskID: Waiting until main and event etcd report readiness
  lastOperation:
    description: Waiting until main and event etcd report readiness
    lastUpdateTime: "2021-12-08T08:33:47Z"
    progress: 26
    state: Processing
    type: Delete
```
  This is because, backuprestore in etcd-main is failing to resolve the owner dns record:
```
$ k logs -f etcd-main-0 backup-restore
...
time="2021-12-08T08:26:39Z" level=error msg="Could not resolve owner domain name owner.local-9wj75.d067603.internal.te.dev.k8s.ondemand.com: lookup owner.local-9wj75.d067603.internal.te.dev.k8s.ondemand.com on 10.241.0.10:53: no such host" actor=backup-restore-server
time="2021-12-08T08:26:39Z" level=info msg="Setting status to : 503" actor=backup-restore-server
time="2021-12-08T08:26:39Z" level=info msg="Waiting for 30s..." actor=backup-restore-server
time="2021-12-08T08:27:09Z" level=info msg="Probing etcd..." actor=backup-restore-server
time="2021-12-08T08:27:09Z" level=error msg="Could not resolve owner domain name owner.local-9wj75.d067603.internal.te.dev.k8s.ondemand.com: lookup owner.local-9wj75.d067603.internal.te.dev.k8s.ondemand.com on 10.241.0.10:53: no such host" actor=backup-restore-server
time="2021-12-08T08:27:09Z" level=info msg="Setting status to : 503" actor=backup-restore-server
time="2021-12-08T08:27:09Z" level=info msg="Waiting for 30s..." actor=backup-restore-server

$ k get dnsrecord,dnsentry
NAME                                                       TYPE    DOMAIN NAME                             RECORD TYPE   STATUS      AGE
dnsrecord.extensions.gardener.cloud/local-internal   aws-route53   api.local.timebertt.internal.gardener   A             Succeeded   10m

NAME                                   DNS                                  TYPE          PROVIDER                           STATUS   AGE   TARGETS            OWNERID
dnsentry.dns.gardener.cloud/external   api.local.timebertt.shoot.gardener   aws-route53   shoot--timebertt--local/external   Ready    31m   ["35.240.24.12"]   shoot--timebertt--local-dc1712dc-5939-49d0-856a-8e7a84b2dc96-gardener-local-timebertt-external
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v1.37.0`
