### ISSUE TITLE
Automatically restart kube-apiserver deployment rollout when it is stalled 

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#5176]
**How to categorize this issue?**

/area robustness quality ops-productivity
/kind enhancement

**What would you like to be added**:
Automatically restart kube-apiserver deployment rollout when it is stalled.

We have seen a shoot which reconciliation was failing on the step deploying the kube-apiserver.
```
description: 'Flow "Shoot cluster reconciliation" encountered task errors: [task "Waiting
  until Kubernetes API server reports readiness" failed: failure to read the logs:
  previous terminated container "kube-apiserver" in pod "kube-apiserver-8664d7888f-tmvvj"
  not found: retry failed with context deadline exceeded, last error: kube-apiserver
  deployment has outdated replicas] Operation will be retried.'
```

The shoot was in this state for more than 12 hours. When we checked the controlplane, the deployment had 3 replicas, 2 from the old replicaset and 1 from the new one, but there were not attempts the rollout to be proceeding. 

```bash
$ k get po -l role=apiserver
NAME                              READY   STATUS    RESTARTS   AGE
kube-apiserver-845fb8b7-ddx4f     3/3     Running   0          10h
kube-apiserver-845fb8b7-jvf9h     3/3     Running   0          10h
kube-apiserver-8664d7888f-tmvvj   3/3     Running   0          10h
```

Looking the deployment status, we saw
```yaml
$ k get deploy/kube-apiserver -o json | jq .status
{
  "availableReplicas": 2,
  "conditions": [
    {
      "lastTransitionTime": "2021-12-15T23:53:24Z",
      "lastUpdateTime": "2021-12-15T23:53:24Z",
      "message": "Deployment has minimum availability.",
      "reason": "MinimumReplicasAvailable",
      "status": "True",
      "type": "Available"
    },
    {
      "lastTransitionTime": "2021-12-16T00:03:25Z",
      "lastUpdateTime": "2021-12-16T00:03:25Z",
      "message": "ReplicaSet \"kube-apiserver-8664d7888f\" has timed out progressing.",
      "reason": "ProgressDeadlineExceeded",
      "status": "False",
      "type": "Progressing"
    }
  ],
  "observedGeneration": 110,
  "readyReplicas": 3,
  "replicas": 3,
  "unavailableReplicas": 1,
  "updatedReplicas": 1
}
```

So the KCM of the seed has gave up and stopped the roll out.
We tried to find  in the KCM  logs the reason, but it seems there is nothing helpful
```json
{"time":"2021-12-15T23:53:00.032759550Z","log":"ReplicaSet \"kube-apiserver-8664d7888f\" will be enqueued after 30s for availability check"}
{"time":"2021-12-15T23:52:54.617760300Z","log":"ReplicaSet \"kube-apiserver-845fb8b7\" will be enqueued after 30s for availability check"}
{"time":"2021-12-15T23:52:52.988926494Z","log":"ReplicaSet \"kube-apiserver-845fb8b7\" will be enqueued after 30s for availability check"}
{"time":"2021-12-15T23:52:41.232788329Z","log":"\"Event occurred\" object=\"shoot--foo--bar/kube-apiserver-845fb8b7\" kind=\"ReplicaSet\" apiVersion=\"apps/v1\" type=\"Normal\" reason=\"SuccessfulCreate\" message=\"Created pod: kube-apiserver-845fb8b7-jvf9h\""}
{"time":"2021-12-15T23:52:41.017192208Z","log":"\"Too few replicas\" replicaSet=\"shoot--foo--bar/kube-apiserver-845fb8b7\" need=2 creating=1"}
{"time":"2021-12-15T23:52:39.851665677Z","log":"\"Event occurred\" object=\"shoot--foo--bar/kube-apiserver-8664d7888f\" kind=\"ReplicaSet\" apiVersion=\"apps/v1\" type=\"Normal\" reason=\"SuccessfulCreate\" message=\"Created pod: kube-apiserver-8664d7888f-tmvvj\""}
{"time":"2021-12-15T23:52:39.634743685Z","log":"\"Too few replicas\" replicaSet=\"shoot--foo--bar/kube-apiserver-8664d7888f\" need=1 creating=1"}
{"time":"2021-12-15T23:52:39.634424905Z","log":"\"Event occurred\" object=\"shoot--foo--bar/kube-apiserver\" kind=\"Deployment\" apiVersion=\"apps/v1\" type=\"Normal\" reason=\"ScalingReplicaSet\" message=\"Scaled up replica set kube-apiserver-8664d7888f to 1\""}
{"time":"2021-12-15T23:52:27.105600732Z","log":"\"Event occurred\" object=\"shoot--foo--bar/kube-apiserver-845fb8b7\" kind=\"ReplicaSet\" apiVersion=\"apps/v1\" type=\"Normal\" reason=\"SuccessfulCreate\" message=\"Created pod: kube-apiserver-845fb8b7-ddx4f\""}
{"time":"2021-12-15T23:52:26.810363436Z","log":"\"Too few replicas\" replicaSet=\"shoot--foo--bar/kube-apiserver-845fb8b7\" need=2 creating=1"}
{"time":"2021-12-15T23:15:39.733212296Z","log":"ReplicaSet \"kube-apiserver-845fb8b7\" will be enqueued after 30s for availability check"}
{"time":"2021-12-15T23:15:25.751193990Z","log":"ReplicaSet \"kube-apiserver-845fb8b7\" will be enqueued after 30s for availability check"}
``` 

**Why is this needed**:
To avoid manual operation that requires landscape operator to restart the deployment. Note, simple scale-up/down just increase/decrease the replicas, but does not restart the rollout.

/cc @Kristian-ZH
