### ISSUE TITLE
Add a check for intersection between nodes and pods CIDRs

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/gardener#5180]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
Currently it is possible the create a shoot cluster with the same IP ranges for nodes and pods, but this is not a correct configuration and the creation of the cluster will fail: [ref](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network)
```
7m51s       Warning   FailedToCreateRoute       node/shoot--foo--podnodecidr-worker-nyvbm-z1-54d97-s5fkw   Could not create route 629b5c95-5070-4420-9d16-4369cc95cf9a 10.250.0.0/24 for node shoot--foo--podnodecidr-worker-nyvbm-z1-54d97-s5fkw after 3.477036508s: googleapi: Error 400: UNSUPPORTED_OPERATION - 10.250.0.0/24 hides the address space of the network (10.250.0.0/16). Cannot change the routing of packets destined for the network.
```

Also there will be pods and nodes with the same IP addresses:
```bash
$ k get node -o wide; k -n kube-system get pod vpn-shoot-6cb79d779d-vf64p -o wide
NAME                                                      STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION         CONTAINER-RUNTIME
shoot--foo--podnodecidr-worker-nyvbm-z1-54d97-s5fkw   Ready    <none>   9m16s   v1.22.3   10.250.0.2    <none>        Garden Linux 576.1   5.10.0-9-cloud-amd64   containerd://1.5.7
NAME                         READY   STATUS    RESTARTS   AGE   IP           NODE                                                      NOMINATED NODE   READINESS GATES
vpn-shoot-6cb79d779d-vf64p   1/1     Running   0          10m   10.250.0.2   shoot--foo--podnodecidr-worker-nyvbm-z1-54d97-s5fkw   <none>           <none>
```

**What you expected to happen**:
Gardener should have a check for that and should inform the user that such a configuration is not a possible.

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot cluster with the following configuration:
```
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 100.96.0.0/11
...
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 100.96.0.0/11
```
