### ISSUE TITLE
gardenlet failed to reconcile a Shoot with reason `could not parse renew timestamp`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5181]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
See below.

**What you expected to happen**:
Reconciliation to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. I had a Shoot created with v1.38.0-dev and hibernated afterwards.

2. Updated to last master branch.
 
3. gardenlet fails to reconcile the Shoot with:

```yaml
  lastErrors:
  - description: 'task "Deploying gardener-resource-manager" failed: retry failed
      with context deadline exceeded, last error: could not parse renew timestamp:
      parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"'
    lastUpdateTime: "2021-12-17T14:55:27Z"
    taskID: Deploying gardener-resource-manager
```

**Environment**:

- Gardener version: 3b03c4dc12aeeb2a7ac79fb07107b1472ee951ec
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
