### ISSUE TITLE
cluster-autoscaler cannot handle scale-to-zero worker groups

### ISSUE THREAD

**Issue by jkmw** [gardener/gardener#5212]
**How to categorize this issue?**

/area auto-scaling
/kind bug

**What happened**:

The cluster-autoscaler reports the following error as soon as there is a _scale-to-zero_ worker group (`.spec.provider.workers[0].minimum: 0`) in the shootspec:

```
E0103 14:48:57.382966       1 static_autoscaler.go:428] Failed to scale up: Could not compute total resources: No node info for: shoot--<projectname>--<clustername>-<scale-to-zero-workername>-z1
```

**What you expected to happen**:

The cluster-autoscaler should recognise the scale-to-zero worker groups and ignore them or scale them up if necessary.

**How to reproduce it (as minimally and precisely as possible)**:

Add a scale-to-zero worker group to a shoot cluster:

```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
spec:
  provider:
    workers:
    - name: scale-to-zero
      minimum: 0 # here is the problem
      maximum: 2
```

Afterwards, one can observe the above-mentioned error message from the cluster-autoscaler.

**Environment**:

- Gardener version: `v1.37.2`
- Kubernetes version (use `kubectl version`): `v1.21.3`
- Cloud provider or hardware configuration: `OpenStack`

**Comment by ialidzhikov** [comment]
> Cloud provider or hardware configuration: `OpenStack`

To my knowledge for a long time scale-(from/to)-zero was supported only for AWS and Azure.
From https://github.com/gardener/autoscaler/issues/27:
> Currently, this is logic for fetching instance details is harder coded for AWS and Azure as seen here.

@AxiomSamarth @himanshu-kun can you provider details to the end user how generic scale-to-zero can be used for provider openstack?

**Comment by AxiomSamarth** [comment]
@ialidzhikov @jkmw 

As of today, as Ismail mentioned, the scale to or from zero is supported on AWS & Azure. Soon, generic scale to/from zero will be made available on Gardener for all providers. As of today, in order to facilitate scaling by autoscaler on other cloud providers (except AWS & Azure) you need to have minimum number of machines in the worker pool to be greater than or equal to the number of zones the worker pool is spanning across. 

```
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
spec:
  provider:
    workers:
    - name: scale-to-zero
      minimum: 0 # this value should be >= number of zones this worker pool is spanning across
      maximum: 2
```
