### ISSUE TITLE
Move `DNSProvider` capabilities out of g/g

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#5270]
**How to categorize this issue?**

/area open-source
/kind enhancement

**What would you like to be added**:
Managing `DNSProviders` should be moved from [gardener/gardener](https://github.com/gardener/gardener) to [gardener/gardener-extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service). The following approach was discussed:

- [x] Introduce a new feature gate to disable any handling of `DNSProviders` in g/g. Turning off `DNSProviders` should only work if `UseDNSRecords` is enabled. -> https://github.com/gardener/gardener/pull/5349
- [x] Enhance `DNSConfig.service.dns.extensions.gardener.cloud/v1alpha1` by `providers`.
~Add `RawExtension` field to `shoot.spec.dns.providers` in order to support options that are specific to a DNS extension (e.g. rate limit #5207).~
- [x] Add mutating webhook to [gardener/gardener-extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service) which replicates provider from `shoot.spec.dns.providers` to the `DNSConfig` as well as `shoot.spec.dns.providers[].secretName` to `shoot.resources`.
- [x] The DNS extension creates a shoot domain based `DNSProvider` based on the external `DNSRecord` object.
- [x] For additional DNS providers (non default-domain providers) the DNS extension is supposed to continue working with the `managed-dns-provider` role label ([ref](https://github.com/gardener/gardener/blob/0f631393bda799f92d0c404bd5d3556a975a522d/pkg/operation/botanist/dns.go#L309)) to avoid orphaned providers when the switch happens.
- [x] Verify whether above changes work as expected on large landscapes
- [x] https://github.com/gardener/gardener/pull/6142
- [x] Promote `DisableDNSProviderManagement` feature gate to GA (ref https://github.com/gardener/gardener/pull/6341)
- [x] Drop remaining left-overs of `dns.gardener.cloud` related coding from g/g: https://github.com/gardener/gardener/pull/6479
- [x] Drop `DNSProvider` kind from list of supported extension kinds after giving operators time to delete `external-dns-management` `ControllerRegistrations`: https://github.com/gardener/gardener/pull/6840

**Why is this needed**:
Gardener has been transitioned from using the DNS APIs of [gardener/external-dns-management](https://github.com/gardener/external-dns-management/) to a slimmed down API `dnsrecords.extensions.gardener.cloud` which will eventually become the only option to create infrastructure related DNS records (e.g. internal, external, owner domains) once the corresponding feature graduates to GA (today beta #5219) and the feature gate is removed.

To accomplish this plan we need to move the `DNSProvider` handling from [gardener/gardener](https://github.com/gardener/gardener) to [gardener/gardener-extension-shoot-dns-service](https://github.com/gardener/gardener-extension-shoot-dns-service), so that end-users can still use the DNS providers that are configured in their shoot clusters.

**Comment by rfranzke** [comment]
Hi @timuthy,
thanks for opening the issue and the summary! I have only one question:

>  Add RawExtension field to shoot.spec.dns.providers in order to support options that are specific to a DNS extension (e.g. rate limit Support configuration of rate limits for external and additional DNSProviders #5207).

Do we really need this? Can't the `.spec.extensions[].providerConfig` field be used for this?

**Comment by timuthy** [comment]
@rfranzke the point about "advanced" configuration (2nd point in list) is a little bit different from what you proposed [here](https://github.com/gardener/gardener/pull/5207#issuecomment-999573417). Any strong objections to not add a RawExtension field to `shoot.spec.dns.providers`? I know that your proposal more matches the general approach we took with extensions. However, I think due to historical reasons `DNSProviders` are a bit different and duplicating advanced configuration options in `shoot.spec.extensions` is not very user friendly.

**Comment by rfranzke** [comment]
@timuthy I think we should rather go back to exactly one provider in the `.spec.dns` section since gardenlet uses exactly one domain/provider for a shoot cluster. Any additional providers and any additional metadata information is solely related to `shoot-dns-service`. I think something like this would be a proper target picture:

```yaml
spec:
  dns:
    domain: <shoot-domain>
#   provider: # specify only when no default domain
#     type: aws-route53
#     secretName: <secretName>
  extensions:
  - type: shoot-dns-service
    providerConfig:
      apiVersion: shoot-dns-service.extensions.config.gardener.cloud/v1alpha1
      kind: Configuration
      providers:
      - type: azure-dns
        primary: false
        zones:
          include:
          - zone-id-1
          exclude:
          - zone-id-2
      - primary: true # primary=true allows additional configuration for the same provider like in `.spec.dns`, there is no type field needed (only if it's not the default domain, i.e., only if `.spec.dns.provider` is provided)
        domains:
          include:
          - my-custom-domain.com
          - my-other-custom-domain.com
          exclude:
          - yet-another-custom-domain.com
        ...
```

Does this make sense? I understand that it's "a little inconvenient" to not have the configuration right at the same place like `.spec.dns`, though, I guess this is acceptable since the impact is quite low (you'd have to go to `.spec.extensions.providerConfig` anyways when configuring additional providers).

Keeping `.spec.dns.providers` and allowing a `providerConfig` encodes information that there is a DNS extension (different from the "native" `DNSRecord` extensions) that MIGHT make use of this into the core API. This still makes DNS extensions special although they are "just" regular `Extension`-based extensions. This doesn't seem right to me.
