### ISSUE TITLE
Shoot wrongly marked with error codes when MachineDeployment is unhealthy

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5283]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:

Shoot had the following condition:

```yaml
    - type: EveryNodeReady
      status: Progressing
      lastTransitionTime: '2022-01-17T14:10:55Z'
      lastUpdateTime: '2022-01-17T14:10:55Z'
      reason: WorkerUnhealthyReport
      message: >-
        Worker extension (shoot--foo--bar/bar) reports failing health
        check: machine deployment "shoot--foo--bar-cpu-worker-z1" in
        namespace "shoot--foo--bar" is unhealthy: Deployment does not have
        minimum availability (MinimumReplicasUnavailable).
      codes:
        - ERR_INFRA_INSUFFICIENT_PRIVILEGES
        - ERR_INFRA_QUOTA_EXCEEDED
```

The Shoot/condition is wrongly marked with error codes `ERR_INFRA_INSUFFICIENT_PRIVILEGES` and `ERR_INFRA_QUOTA_EXCEEDED`.

The MachineDeployment status (the unhealthy one):

```yaml
status:
  availableReplicas: 13
  conditions:
  - lastTransitionTime: "2022-01-17T14:10:20Z"
    lastUpdateTime: "2022-01-17T14:10:20Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1001
  readyReplicas: 13
  replicas: 14
  unavailableReplicas: 1
  updatedReplicas: 14
```

After some time the status of the Worker transitioned to:
```yaml
  status:
    conditions:
    - codes:
      - ERR_INFRA_INSUFFICIENT_PRIVILEGES
      - ERR_INFRA_QUOTA_EXCEEDED
      lastTransitionTime: "2022-01-17T14:24:47Z"
      lastUpdateTime: "2022-01-17T14:25:48Z"
      message: All health checks successful
      reason: HealthCheckSuccessful
      status: "True"
      type: EveryNodeReady
```

Note that error codes are not cleaned up.

**What you expected to happen**:
Wrong error codes to don't be added to the Shoot condition

**How to reproduce it (as minimally and precisely as possible)**:
Not clear for now.

**Environment**:

- Gardener version: v1.37.3
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: provider-azure@v1.22.0
- Others:
