### ISSUE TITLE
Creation of hibernated Shoot fails

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5296]
**How to categorize this issue?**

/area quality dev-productivity ops-productivity
/kind bug

**What happened**:
Creation of hibernated Shoot failed.

**What you expected to happen**:
Creation of hibernated Shoot to succeed as before.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Shoot with `spec.hibernation.enabled=true`

```yaml
spec:
  hibernation:
    enabled: true
```

2. Make sure that the creation fails with:

```yaml
  lastOperation:
    description: >-
      Flow "Shoot cluster reconciliation" encountered task errors: [task
      "Deploying gardener-resource-manager" failed: retry failed with context
      deadline exceeded, last error: retry failed with context deadline
      exceeded, last error: token not yet generated] Operation will be retried.
    lastUpdateTime: '2022-01-19T09:54:11Z'
    progress: 51
    state: Error
    type: Create
```

**Environment**:

- Gardener version: 4dde96a5994f181a998e59831aacdcaab8246b48
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
