### ISSUE TITLE
Validate workers max count vs max Nodes count allowed by the Pods CIDR

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5298]
**How to categorize this issue?**

/area networking ops-productivity
/kind enhancement

**What would you like to be added**:
Validation whether the configured worker pools max Nodes count does not exceed max Nodes count allowed by the Pods CIDR. The Pod network calculations that has to be considered are described in https://github.com/gardener/gardener/blob/v1.38.3/docs/usage/shoot_networking.md.

**Steps to reproduce**:
1. Create a faulty Shoot cluster.

```yaml
spec:
  provider:
    workers:
      - name: worker-bvl3g
        maximum: 3
        minimum: 3
  networking:
    pods: 100.96.0.0/23
```

According to https://github.com/gardener/gardener/blob/v1.38.3/docs/usage/shoot_networking.md, we have:
```
Pod network: 100.96.0.0/23 (this is `.spec.networking.pods`)
nodeCIDRMaskSize: /24
-------------------------

Number of podCIDRs: 2 (2 ^ 1, where 1 = /24 - /23) --> max. Node count 
Number of IPs per podCIDRs: 256
```

> Note: `nodeCIDRMaskSize` can be customized with the field `spec.kubernetes.kubeControllerManager.nodeCIDRMaskSize`.

2. Make sure that the 3rd Node is unhealthy

kube-controller-manager:
```
2022-01-18 08:21:01 {"log":"Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range","pid":"1","severity":"ERR","source":"controller_utils.go:260"}
```

Node condition:
```yaml
    - lastHeartbeatTime: "2022-01-18T15:25:42Z"
      lastTransitionTime: "2022-01-18T15:25:42Z"
      message: RouteController failed to create a route
      reason: NoRouteCreated
      status: "True"
      type: NetworkUnavailable
```

**Why is this needed**:
To prevent users to configure a high Nodes count that actually cannot be supported/provider because of the network config.
It also worths mentioning that `spec.networking.{pods.services.nodes}` fields are immutable -> when user hits similar issue, there is no other option than recreating the Shoot cluster with updated spec.
