### ISSUE TITLE
`shootHasBastions` check is wrong - it checks for a random Bastion in the Project namespace

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5323]
**How to categorize this issue?**

/area quality ops-productivity
/kind bug

**What happened**:
Currently `shootHasBastions` func checks whether there is any Bastion in the Project namespace.

https://github.com/gardener/gardener/blob/c2276016229f9e49dcc4652e9ad8b652e7d0f64e/pkg/gardenlet/controller/shoot/shoot_control.go#L452-L462

The following check for Bastions associated to Shoots also seems to be wrong (note the  `Limit: 1` part).

https://github.com/gardener/gardener/blob/c2276016229f9e49dcc4652e9ad8b652e7d0f64e/pkg/controllermanager/controller/bastion/bastion_control.go#L56-L82

**What you expected to happen**:
`shootHasBastions` to check whether there is a Bastion with the appropriate `.spec.shootRef.`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot in a Project that has random Bastion

2. Delete the Shoot

4. Make sure the Shoot deletion does not start/progress. 

Shoot status is:

```yaml
  lastOperation:
    description: Shoot cluster has been successfully reconciled.
    lastUpdateTime: '2022-01-26T08:38:25Z'
    progress: 100
    state: Succeeded
    type: Create
```

Shoot metadata and generations:
```yaml
metadata:
  generation: 3
  creationTimestamp: '2022-01-26T08:26:48Z'
  deletionTimestamp: '2022-01-26T08:52:15Z'
  
status:
 observedGeneration: 2
```

gardenlet logs:
```
{"level":"info","msg":"Error syncing Shoot garden-core/delete-test2: shoot has still Bastions","ts":"2022-01-26T13:20:50.604Z"}
{"level":"info","msg":"Error syncing Shoot garden-core/delete-test2: shoot has still Bastions","ts":"2022-01-26T13:20:50.855Z"}
{"level":"info","msg":"Error syncing Shoot garden-core/delete-test2: shoot has still Bastions","ts":"2022-01-26T13:22:32.805Z"}
```

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
