### ISSUE TITLE
Failing system components are not reported in `ManagedResource` and `Shoot` conditions

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#5357]
**How to categorize this issue?**

/area robustness ops-productivity monitoring
/kind bug

**What happened**:
We saw failing `kube-proxy` `Pod`s in a `Shoot`'s `kube-system` namespace. Their `status`es were as follows:

```yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-27T22:27:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-31T14:44:56Z"
    message: 'containers with unready status: [kube-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-31T14:44:56Z"
    message: 'containers with unready status: [kube-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-01-27T22:27:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://0837dd14c071a6b57cb12ceb9c61a9fbb29e3c43e584103f6caaf2830e604879
    image: k8s.gcr.io/kube-proxy:v1.21.7
    lastState:
      terminated:
        containerID: containerd://0837dd14c071a6b57cb12ceb9c61a9fbb29e3c43e584103f6caaf2830e604879
        exitCode: 1
        finishedAt: "2022-01-31T15:00:15Z"
        reason: Error
        startedAt: "2022-01-31T15:00:15Z"
    name: kube-proxy
    ready: false
    restartCount: 1046
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=kube-proxy pod=kube-proxy-operator-v1.21.7-7djlq_kube-system(95d839a3-85f6-4c7f-a7f4-e8b719a1e88e)
        reason: CrashLoopBackOff
[...]
```

The `DaemonSet`s `status`es were as follows:

```yaml
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 3
  numberMisscheduled: 0
  numberReady: 3
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 4
```

However, the `shoot-core` `ManagedResource` in the shoot's namespace in the seed was not reporting any issues:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-01-27T22:33:17Z"
    lastUpdateTime: "2022-01-27T22:33:17Z"
    message: All resources are healthy.
    reason: ResourcesHealthy
    status: "True"
    type: ResourcesHealthy
  - lastTransitionTime: "2022-01-27T22:33:17Z"
    lastUpdateTime: "2022-01-27T22:33:17Z"
    message: All resources are applied.
    reason: ApplySucceeded
    status: "True"
    type: ResourcesApplied
```

Consequently, the `Shoot`'s `SystemComponentsHealthy` condition had status `True`.

**What you expected to happen**:
The `ResourcesHealthy` condition part of the `ManagedResource` should evaluate to `False`, eventually causing the `Shoot's `SystemComponentsHealthy` condition evaluating to `False`.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot
2. Manipulate the `gardener-resource-manager` deployment in the control plane: set `--sync-period=10m` and `--health-sync-period=10s`. This makes it easier to reproduce and observe the issue.
```bash
k -n shoot--local--local edit deploy gardener-resource-manager
```
3. Break some system component, e.g. kube-proxy, with the following command:
```bash
k -n kube-system set image daemonset kube-proxy-local-v1.23.1 kube-proxy=nginx
```
4. Observe that neither the respective ManagedResource nor the Shoot itself turn to an unhealthy status.

**Anything else we need to know?**:
~~It seems that the [`health.CheckDaemonSet`](https://github.com/gardener/gardener/blob/ca661c0502eb1f885a2ac3793913025788d5102d/pkg/utils/kubernetes/health/daemonset.go#L45-L67) function is not precise enough to cover such situations.~~ not true, see https://github.com/gardener/gardener/issues/5357#issuecomment-1040150204

**Environment**:

- Gardener version: v1.38.4
- Kubernetes version (use `kubectl version`): v1.21.7

**Comment by shafeeqes** [comment]
Shouldn't 
https://github.com/gardener/gardener/blob/ca661c0502eb1f885a2ac3793913025788d5102d/pkg/utils/kubernetes/health/daemonset.go#L58
return an error, since daemonSet.Spec.UpdateStrategy.RollingUpdate = nil (in the kube-proxy charts) and therefore maxUnavailable is 0 ?

**Comment by rfranzke** [comment]
@shafeeqes I think this is defaulted to 

```yaml
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

(at least this is was I see in the `kube-proxy` `DaemonSet` in a system).
