### ISSUE TITLE
controller-manager triggers high number of shoot reconciliations on restart

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5391]
**How to categorize this issue?**

/area scalability usability
/kind bug

**What happened**:

On a restart of controller-manager, a lot of shoot reconciliations are triggered.

This can cause significant problems in large gardener installations, e.g.
- high load on apiserver because of high number of update calls by gardenlet
- hitting DNS rate limits for default and internal domains because of high number of parallel shoot reconciliations

Analysis: this problem occurs for shoots that reference an audit policy configmap, when the configmap's `resourceVersion` changed (without a `data` update).

The shoot configmap controller only reacts on updates to the `data` section of referenced auditpolicy configmaps:
https://github.com/gardener/gardener/blob/5baac06c204771e1adabcc039a2222b037f9f8e0/pkg/controllermanager/controller/shoot/configmap_control.go#L47-L51
With this, the reconciler does not update the `Shoot.Spec.Kubernetes.KubeAPIServer.AuditConfig.AuditPolicy.ConfigMapRef.ResourceVersion` field.
After a restart of controller-manager, all configmaps are enqueued and all referencing shoots are updated with the new `resourceVersion`, leading to immediate reconciliations of affected shoots.

Meaning: there is an inconsistency between this controller's event handler ("predicate" only evaluates to true on `data change`) and the reconciler's logic that triggers a shoot reconciliation (on `resourceVersion` change).

**What you expected to happen**:

Gardener should either
- a) use consistent logic across the controller and either trigger a shoot reconciliation immediately or
- b) not trigger reconciliations on configmap updates at all
- In either case, pending shoot reconciliations should not "pile up" until the next restart.

**How to reproduce it (as minimally and precisely as possible)**:

(controller-manager log level set to `debug`)

1. create a shoot and an auditpolicy configmap:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: local
  namespace: garden-local
  annotations:
    shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds: "0"
spec:
  seedName: local
  cloudProfileName: local
  secretBindingName: local
  region: local
  networking:
    type: local
  provider:
    type: local
    workers:
    - name: local
      machine:
        type: local
      cri:
        name: containerd
      minimum: 1
      maximum: 1
      maxSurge: 1
      maxUnavailable: 0
  kubernetes:
    version: 1.23.1
    kubeAPIServer:
      auditConfig:
        auditPolicy:
          configMapRef:
            name: auditpolicy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auditpolicy
  namespace: garden-local
data:
  policy: |-
    apiVersion: audit.k8s.io/v1beta1
    kind: Policy
    rules:
      - level: Metadata
        omitStages:
          - "RequestReceived"
```
2. restart controller-manager to observe that shoot is not automatically reconciled by a "simple restart"
3. label the configmap to bump the `resourceVersion`
```bash
k -n garden-local label cm auditpolicy foo=bar
```
4. observe that the shoot is not automatically reconciled (controller-manager logs should contain this line):
```text
ts="2022-02-03T13:04:20.151+0100" level=debug msg="[SHOOT CONFIGMAP controller] No update of the `.data` field of cm garden-local/auditpolicy. Do not requeue the ConfigMap"
```
5. restart controller-manager and observe that shoot is now reconciled (controller-manager logs should contain this line):
```text
ts="2022-02-03T13:05:20.234+0100" level=info msg="[SHOOT CONFIGMAP controller] schedule for reconciliation shoot garden-local/local"
```

**Environment**:

- Gardener version: 5baac06c204771e1adabcc039a2222b037f9f8e0
