### ISSUE TITLE
Shoot cannot be deleted with invalid providerConfiguration in shoot.spec.provider.workers.providerConfig

### ISSUE THREAD

**Issue by MrBatschner** [gardener/gardener#5435]
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:

I created a shoot and put a custom `providerConfig` into `shoot.spec.provider.workers.providerConfig` which looked like this:

```yaml
apiVersion: gardenlinux.os.extensions.gardener.cloud
kind: OperatingSystemConfig
linuxSecurityModule: AppArmor
```

The shoot could not get created because `could not decode provider config: no kind "OperatingSystemConfig" is registered for version "gardenlinux.os.extensions.gardener.cloud" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:72"` - this was pretty much to be expected.

Deleting the shoot now fails with the very same error message:

> task "Waiting until shoot worker nodes have been terminated" failed: Failed to delete Worker shoot--k8s-train--test/test: Error deleting worker: failed to deploy the machine classes: could not decode provider config: no kind "OperatingSystemConfig" is registered for version "gardenlinux.os.extensions.gardener.cloud" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:72"

**What you expected to happen**:

I am not expecting a shoot with an invalid or unregistered `providerConfiguration` to get created but if I do such a mistake, deleting the shoot should be possible. Since anyone can put anything into the `providerConfiguration` fields, invalid values here should not lead to zombie shoots that cannot come up but also cannot be deleted anymore.

**How to reproduce it (as minimally and precisely as possible)**:

Create a shoot with this as `.spec.provider`:

```yaml
  provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-c
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.250.0.0/16
    type: gcp
    workers:
    - cri:
        name: containerd
      machine:
        image:
          name: gardenlinux
          version: 576.3.0
        type: n1-standard-2
      maxSurge: 1
      maxUnavailable: 0
      maximum: 2
      minimum: 1
      name: worker-frq0k
      providerConfig:
        apiVersion: gardenlinux.os.extensions.gardener.cloud
        kind: OperatingSystemConfig
        linuxSecurityModule: AppArmor
      systemComponents:
        allow: true
      volume:
        size: 50Gi
        type: pd-standard
      zones:
      - europe-west1-c
```

The shoot will not come up as `gardenlinux.os.extensions.gardener.cloud/OperatingSystemConfig` is not a registered kind but it also cannot get deleted because of that same error.

**Environment**:

- Gardener version: v1.39.3
- Kubernetes version (use `kubectl version`): v1.22.4
- Cloud provider or hardware configuration: gcp
- Others: Garden Linux
