### ISSUE TITLE
GRM: cronjob unknown conversion

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardener#5443]
**How to categorize this issue?**

/kind bug

**What happened**:
Cronjobs switched from `apiVersion: batch/v1beta1` to `apiVersion: batch/v1` with k8s version 1.21.
For a k8s/shoot cluster with version 1.20 the managed resource fails with 
```
    message: 'Could not apply all new resources: 1 error occurred: error during apply
      of object "batch/v1beta1/CronJob/kube-system/hubble-generate-certs": converting
      (v1beta1.CronJob) to (v1.CronJob): unknown conversion'
```
when the follwing cronjob is trying to be created.

```
# Source: cilium/charts/hubble-relay/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hubble-generate-certs
  namespace: kube-system
  labels:
    k8s-app: hubble-generate-certs
    gardener.cloud/role: system-component
spec:
  schedule: "0 0 1 */4 *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            k8s-app: hubble-generate-certs
        spec:
          containers:
            - name: certgen
              image: quay.io/cilium/certgen:v0.1.5
              imagePullPolicy: IfNotPresent
              command:
                - "/usr/bin/cilium-certgen"
              # Because this is executed as a job, we pass the values as command
              # line args instead of via config map. This allows users to inspect
              # the values used in past runs by inspecting the completed pod.
              args:
                - "--cilium-namespace=kube-system"
                - "--hubble-ca-generate"
                - "--hubble-ca-reuse-secret"
                - "--hubble-server-cert-generate"
                - "--hubble-server-cert-common-name=*.default.hubble-grpc.cilium.io"
                - "--hubble-server-cert-validity-duration=94608000s"
                - "--hubble-relay-client-cert-generate"
                - "--hubble-relay-client-cert-validity-duration=94608000s"
          hostNetwork: true
          serviceAccount: hubble-generate-certs
          serviceAccountName: hubble-generate-certs
          restartPolicy: OnFailure
      ttlSecondsAfterFinished: 1800
```

**What you expected to happen**:
That the managed resource with the cronjob can be successfully applied.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.39
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
