### ISSUE TITLE
Introduce "Progressing" state for shoot conditions

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#545]
The current shoot conditions reflect the most recently observed state of a shoot. Users often misinterpret the status and get the impression that their cluster is somewhat broken. A good example for this is e.g., when the cluster-autoscaler decides to scale up. It increases the `.spec.replicas` field of the `MachineDeployment`, however, the `EveryNodeReady` condition shows `False` with the message `Not enough nodes (x/y) are registered to the cluster.`
While we could "fix/improve" this issue with special handling in our code we can't do it generally for all cases.
Consequently, we decided to rather introduce a new state `Progressing` (next to `True`, `False`, `Unknown`) in a condition's spec.

Let's please adapt the shoot care controller in the following way:
1. The core logic is untouched, i.e. it keeps evaluating the shoot state as it is today.
1. If it detects something is wrong it does not write `.status.conditions[*].status=False` like today but `.status.conditions[*].status=Progressing`.
1. If the status is `Progressing` longer than a certain threshold it sets the status to `False`.

Example:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
...
status:
  ...
  conditions:
  - type: EveryNodeReady
    status: 'Progressing'
    lastTransitionTime: '2018-11-22T00:20:52Z'
    reason: EveryNodeReady
    message: Not enough nodes (20/21) are registered to the cluster.
```

Please extend the controller-manager's componentconfig with four new configuration values where we can define the thresholds per condition, e.g.

```yaml
apiVersion: componentconfig/v1alpha1
kind: ControllerManagerConfiguration
...
conditionThreholds:
- type: EveryNodeReady
  duration: 5m
...
```

Moreover, the shoot care controller does label shoots with `shoot.garden.sapcloud.io/unhealthy=true` if at least one condition's status is `False` ([code](https://github.com/gardener/gardener/blob/master/pkg/controller/shoot/shoot_utils.go#L58-L95)). Let's label shoots with `shoot.garden.sapcloud.io/unhealthy=progressing` in case at least one condition's status is `Progressing` and no other condition's status is `False`.

/cc @gardener/dashboard-maintainers
