### ISSUE TITLE
Cannot disable nginx-ingress addon

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5480]
/area quality
/kind bug
/kind regression

**What happened**:
After https://github.com/gardener/gardener/pull/5375 it is not possible to disable the nginx-ingress addon successfully. Currently the SecretData is not passed to the component and the component updates the DNSRecord Secret with empty data on Destroy.

**What you expected to happen**:
To successfully disable nginx-ingress addon.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with `spec.addons.nginxIngress.enabled=true`.

2. Set `spec.addons.nginxIngress.enabled=false`.

3. Make sure that the ingress DNSRecord fails to be destroyed with 
```yaml
  lastError:
    description: 'Error deleting dnsrecord: could not get AWS credentials: secret
      does not contain any data'
    lastUpdateTime: "2022-02-23T10:38:01Z"
```

**Environment**:

- Gardener version: v1.40.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
