### ISSUE TITLE
Remote write configuration in ManagedSeed doesn't trigger Prometheus config change

### ISSUE THREAD

**Issue by maresac** [gardener/gardener#5496]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
I added a remote write configuration for the Shoot Prometheus to the ManagedSeed. The ManagedSeed resource was updated but didn't trigger a restart of the Gardenlet or a config change in the Gardenlet and Shoot Prometheus.

**What you expected to happen**:
Shoot Prometheus picks up remote write configuration.

**How to reproduce it (as minimally and precisely as possible)**:
I added the following monitoring config to the ManagedSeed:
```
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: ManagedSeed
metadata:
[...]
spec:
  gardenlet:
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      monitoring:
        shoot:
          externalLabels:
            cluster: mycluster
          remoteWrite:
            queueConfig: |-
              max_shards: 100
              batch_send_deadline: 20s
              min_backoff: 500ms
              max_backoff: 60s
            url: https://myurl
[...]
```
**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.37.4
- Kubernetes version (use `kubectl version`): 1.20.15
- Cloud provider or hardware configuration: AWS
- Others:
