### ISSUE TITLE
[Flaky Test] E2E Test Suite: [It] Shoot Tests Create, Hibernate, Wake up and Delete Shoot [Shoot]

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5576]
**How to categorize this issue?**

/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:

`E2E Test Suite: [It] Shoot Tests Create, Hibernate, Wake up and Delete Shoot [Shoot]`: https://github.com/gardener/gardener/blob/49427df9174f995daf8a782168b1ed84212f00f9/test/e2e/shoot/create_hibernate_wakeup_delete.go#L29

**CI link**:

- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1503527318235123712#1:build-log.txt%3A1656
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1503587717034807296#1:build-log.txt%3A1725
- https://prow.gardener.cloud/view/gs/gardener-prow/logs/ci-gardener-e2e-kind/1503587717034807296#1:build-log.txt%3A1725

**Reason for failure**:

Tests are failing in step `Wake up Shoot` with errors related to a broken worker health check, errors similar to:
```
    {"level":"info","msg":"Shoot wake-up-7cccz not yet reconciled successfully (condition type EveryNodeReady is not true yet, had message Worker extension (shoot--local--wake-up-7cccz/wake-up-7cccz) reports failing health check: failed to execute 1 health check: unable to check nodes. Failed to list shoot nodes: Get \"https://kube-apiserver.shoot--local--wake-up-7cccz.svc/api/v1/nodes\": dial tcp 10.2.119.43:443: connect: connection refused. with reason WorkerUnhealthyReport)","ts":"2022-03-15T00:40:10.856Z"}
```
or
```
    {"level":"info","msg":"Shoot wake-up-7cccz not yet reconciled successfully (condition type ControlPlaneHealthy is not true yet, had message Worker extension (shoot--local--wake-up-7cccz/wake-up-7cccz) reports an outdated health status (last updated: 9m0s ago at 2022-03-15 00:37:00 +0000 UTC). with reason WorkerOutdatedHealthCheckReport)","ts":"2022-03-15T00:46:10.919Z"}
```

**Anything else we need to know**:

**Comment by timebertt** [comment]
I reproduced this issue locally (first try) by hibernating and waking up a shoot. 
The worker status was in the following state after the wakeup operation had been completed:
```yaml
status:
  conditions:
  - lastTransitionTime: "2022-03-15T16:14:58Z"
    lastUpdateTime: "2022-03-15T16:22:04Z"
    message: Shoot is hibernated
    reason: HealthCheckSuccessful
    status: "True"
    type: SystemComponentsHealthy
  - lastTransitionTime: "2022-03-15T16:15:28Z"
    lastUpdateTime: "2022-03-15T16:22:04Z"
    message: Shoot is hibernated
    reason: HealthCheckSuccessful
    status: "True"
    type: ControlPlaneHealthy
  - lastTransitionTime: "2022-03-15T16:17:20Z"
    lastUpdateTime: "2022-03-15T16:22:04Z"
    message: Shoot is hibernated
    reason: HealthCheckSuccessful
    status: "True"
    type: EveryNodeReady
  - lastTransitionTime: "2022-03-15T16:17:08Z"
    lastUpdateTime: "2022-03-15T16:17:08Z"
    message: No rolling update in progress
    reason: NoRollingUpdate
    status: "False"
    type: RollingUpdate
  lastOperation:
    description: Successfully reconciled worker
    lastUpdateTime: "2022-03-15T16:25:31Z"
    progress: 100
    state: Succeeded
    type: Reconcile
```

So it seems like the health check controller doesn't pick up the checks again after waking up the shoot.

For the `ControlPlane` and the `Network` resources, this was not the case:
```yaml
  status:
    conditions:
    - lastTransitionTime: "2022-03-15T16:13:59Z"
      lastUpdateTime: "2022-03-15T16:41:35Z"
      message: All health checks successful
      reason: HealthCheckSuccessful
      status: "True"
      type: SystemComponentsHealthy
    lastOperation:
      description: Successfully reconciled controlplane
      lastUpdateTime: "2022-03-15T16:23:35Z"
      progress: 100
      state: Succeeded
      type: Reconcile
```

Hence, my suspicion for now is, that this bug is caused by a race condition.
