### ISSUE TITLE
Shoot cluster is hibernated even the hibernation is configured to false

### ISSUE THREAD

**Issue by jan-kuky** [gardener/gardener#5606]
**How to categorize this issue?**

/area shoot cluster
/area hibernation
/area usability
/kind bug

**What happened**: When you want to deploy shoot cluster without hibernation  and you specify hibernation part in shoot cluster definition yaml with shceduling.

```
hibernation:
    enabled: false
    schedules:
    - location: Europe/Bratislava
      start: 00 17 * * 1,2,3,4,5
```
hibernation is disabled only if this part is deleted from yaml or if schedules part is removed.

```
hibernation:
    enabled: false
```
On that case hibernation enabled value is ignored and shoot cluster will be hibernated anyway.  

**What you expected to happen**:
When I specify hibernation  to enabled: false it should not check schedules and should disable hibernation.  

**How to reproduce it (as minimally and precisely as possible)**:
create yaml manifest for shoot cluster where you specify hibernation part following:
```
hibernation:
    enabled: false
    schedules:
    - location: Europe/Bratislava
      start: 00 17 * * 1,2,3,4,5
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.43
- Kubernetes version (use `kubectl version`): 1.21.X
- Cloud provider or hardware configuration: Openstack
