### ISSUE TITLE
Managed Resource `APPLIED` status is false as "apiserver-proxy" service had clusterIP other than "None"

### ISSUE THREAD

**Issue by ary1992** [gardener/gardener#5631]
**How to categorize this issue?**

/kind bug

**What happened**:
While on DOD (CW12), I came across an issue on Canary landscape , where for one of the shoot `SC tile was red` with the following error on dashboard:

```
Could not apply all new resources: 1 error occurred: error during apply of object "v1/Service/kube-system/apiserver-proxy": Service "apiserver-proxy" is invalid: spec.clusterIPs[0]: Invalid value: []string{"None"}: may not change once set
```

On the control plane of shoot , it was found that  managed resource `shoot-core` `Applied` status was `false`.
```
$ k get mr

NAME         CLASS   APPLIED   HEALTHY   AGE
shoot-core           False     True      48d
``` 

`apiserver-proxy` service had following entries under spec section (default value should be "None" for `clusterIP ` and `clusterIPs` )
```
$ k get svc -n kube-system apiserver-proxy -oyaml

...
spec:
  clusterIP: 100.68.73.224
  clusterIPs:
  - 100.68.73.224
...
```

`managedresource-shoot-core` is the `secretRefs` under spec section of `shoot-core` managed resource. It contains `components_charts_apiserver-proxy_templates_apiserver-proxy-service.yaml` in base64 encoded format as one of the data.

```
apiVersion: v1
kind: Service
metadata:
  name: apiserver-proxy
  namespace: kube-system
  labels:
    gardener.cloud/role: system-component
    origin: gardener
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 16910
    protocol: TCP
  selector:
    app: kubernetes
    role: apiserver-proxy
```

Temporary Fix : 
1. Delete the `apiserver-proxy` service.
2. On reconcilation `apiserver-proxy` service will be created with : 
```
spec:
  clusterIP: None
  clusterIPs:
  - None
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Target the shoot of a cluster.
- Delete `kube-proxy` service.
- Create `kube-proxy` service with no clusterIP and clsuterIPs field (those will auto assigned). Something like this :
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    resources.gardener.cloud/description: |-
      DO NOT EDIT - This resource is managed by gardener-resource-manager.
      Any modifications are discarded and the resource is returned to the original state.
    resources.gardener.cloud/origin: 2a540a5c-1b8c-11e8-b291-0a580a2c025a:shoot--i546764--ary-seed-az/shoot-core
  labels:
    gardener.cloud/role: system-component
    origin: gardener
    shoot.gardener.cloud/no-cleanup: "true"
  name: apiserver-proxy
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 16910
    protocol: TCP
    targetPort: 16910
  selector:
    app: kubernetes
    role: apiserver-proxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```  
- After this `shoot-core` managed resource's `APPLIED` status will become false and shoot's SC tile become red.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

cc @vpnachev
