### ISSUE TITLE
Add ERROR_CODE to failed MaintenancePreconditionsSatisfied constraint

### ISSUE THREAD

**Issue by grolu** [gardener/gardener#5778]
**How to categorize this issue?**
/kind enhancement

**What would you like to be added**:
In order to make the user aware of misconfigured webhooks we want to show this as user action error in the dashboard: https://github.com/gardener/dashboard/issues/1144
It would be great, if the reason for the failed constraint could be added as error code, like this:

```yaml
constraints:
  - type: MaintenancePreconditionsSatisfied
    status: 'False'
    codes:
      - ERR_USER_WEBHOOK
    lastTransitionTime: '2022-04-08T03:59:02Z'
    lastUpdateTime: '2022-04-07T15:59:58Z'
    reason: ProblematicWebhooks
    message: >-
      MutatingWebhookConfiguration "fail-webhook" is problematic: webhook
      "my-webhook.example.com" with failurePolicy "Fail" and 5s timeout might
      prevent worker nodes from properly joining the shoot cluster
```

Error codes are already added to conditions in some cases. Adding an error code also to constraints would help us to make the code universal and ready to support future additions.

**Why is this needed**:
The Dashboard is supposed to show this as user error to make the user aware that he needs to take action. However, we can only guess that a webhook is the reason. Gardener should introduce `ERR_USER_WEBHOOK` (or a similar error code) and add it to the failed constraint. Maybe there can be other reasons for this condition to fail which we can introduce at a later point.
