### ISSUE TITLE
Shoot can takeover DNS domains from the default domain

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#5808]
**How to categorize this issue?**

/area ops-productivity security 
/kind bug

**What happened**:
Gardener allows me to use hostname from the default domain that does not belongs to my project.

**What you expected to happen**:
To be disallowed to takeover DNS domains from the default domain

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a gardener project `bar` with namespace `garden-bar`.
2. Create a shoot with similar spec
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: foo
  namespace: garden-bar
spec:
  dns:
    domain: baz.bar.<default-domain> # The only allowed domain from the default domain should be foo.bar.<default-domain>
```

**Anything else we need to know?**:
If the spec.seedName is not set, gardener-scheduler is failing with 
```json
{
  "level": "error",
  "ts": "2022-04-14T10:46:03.313Z",
  "logger": "controller.shoot-scheduler",
  "msg": "Reconciler error",
  "name": "foo",
  "namespace": "garden-foo",
  "error": "Shoot.core.gardener.cloud \"foo\" is invalid: spec.dns: Invalid value: \"foo\": shoot uses a default domain but does not match expected scheme: <shoot-name>.<project-name>.<default-domain>",
  "stacktrace": "sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227"
}
```

**Environment**:

- Gardener version: f5882800d5821bcc18198da96324bbe013bb1afe (but most probably affect released versions, too)
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
