### ISSUE TITLE
Openstack: application credential support

### ISSUE THREAD

**Issue by kayrus** [gardener/gardener#584]
Openstack provides application credential auth method:
https://docs.openstack.org/keystone/queens/user/application_credentials.html

It would be great if Gardener can support them.

**Comment by kayrus** [comment]
I'm not sure whether I understand you. Let me try to clarify my vision for this feature request.

I don't want to put my own user credentials into Gardener to connect it to Openstack, I want to create an application credential and use it to connect Gardener. Application credentials could be revoked at Openstack level if necessary.

**Comment by afritzler** [comment]
Ok, got you (just read up on the diff between application level vs. regular keystone auth :-)). Well that is definitely something worth considering. Since we are not running Queens in production it is kind of hard for us to test. But in general I agree with you here.

We just need to adapt the IaaS secret spec on our side to support both modes. 

Currently it looks like this
```
apiVersion: v1
kind: Secret
metadata:
  name: core-openstack
  namespace: garden-dev
  labels:
    cloudprofile.garden.sapcloud.io/name: openstack
type: Opaque
data:
  domainName: base64(domain-name)
  tenantName: base64(tenant-name)
  username: base64(username)
  password: base64(password)
```

We now need to incorporate those guys
```
[keystone_authtoken]
auth_url = https://keystone.server/identity/v3
auth_type = v3applicationcredential
username = glance
user_domain_name = Default
application_credential_name = glance_cred
application_credential_secret = glance_secret```

Where `auth_url` is part of our `cloudprofile` configuration.
