### ISSUE TITLE
Shoot fails to be reconciled with error `missing DH secret information`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5865]
/area control-plane
/kind bug
/kind regression

**What happened**:
See below.

**What you expected to happen**:
Existing Shoot to be reconciled successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with gardener/gardener@v1.45.0

2. Update to gardener/gardener@v1.46.0-dev-052739856f9f90110d81c97791ee0bf4d9fcf434

3. Reconcile the existing Shoot

4. Make sure that the reconciliation fails with:
```yaml
  lastErrors:
    - description: >-
        task "Deploying vpn-seed-server" failed: retry failed with context
        deadline exceeded, last error: missing DH secret information
      taskID: Deploying vpn-seed-server
      lastUpdateTime: '2022-04-27T14:40:16Z'
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: 052739856f9f90110d81c97791ee0bf4d9fcf434
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
