### ISSUE TITLE
GRM and KCM are not scaled up on reconciliation after a failed hibernation attempt

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5872]
/area control-plane
/kind bug

**What happened**:
After https://github.com/gardener/gardener/issues/5865 got fixed we have bunch of Shoots that fail to reconcile after a failed attempt to hibernate.

**What you expected to happen**:
GRM and KCM to be scaled up on reconciliation when `spec.hibernation.enabled=false`, `status.isHibernated=false`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot

   At this point in time: `spec.hibernation.enabled=false`, `status.isHibernated=false`.

2. Introduce a mock error in the Shoot reconciliation flow to simulate error that occurs after GRM and KCM are scaled down to 0. From example introduce such mock error in step `Deploying vpn-seed-server`.

3. Hibernate the Shoot

   Make sure that GRM and KCM are scaled to 0 and but the Shoot reconciliation cannot complete because of the mock error.
   ```
   $ k -n shoot--foo--bar get deploy
   NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
   cloud-controller-manager     0/0     0            0           9d
   csi-driver-controller        0/0     0            0           9d
   csi-snapshot-controller      0/0     0            0           9d
   gardener-resource-manager    0/0     0            0           9d
   kube-apiserver               0/0     0            0           9d
   kube-controller-manager      0/0     0            0           9d
   kube-scheduler               0/0     0            0           9d
   machine-controller-manager   0/0     0            0           9d
   vpn-seed-server              1/1     1            1           9d
   ```

   At this point in time: `spec.hibernation.enabled=true`, `status.isHibernated=false`.

4. Remove the mock error

5. Wake up the Shoot

   At this point in time: `spec.hibernation.enabled=false`, `status.isHibernated=false`.

6. Make sure that GRM and KCM are not scaled up on reconciliation

   ```
   $ k -n shoot--foo--bar get deploy
   NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
   cloud-controller-manager     1/1     1            1           9d
   csi-driver-controller        1/1     1            1           9d
   csi-snapshot-controller      1/1     1            1           9d
   gardener-resource-manager    0/0     0            0           9d
   kube-apiserver               1/1     1            1           9d
   kube-controller-manager      0/0     0            0           9d
   kube-scheduler               1/1     1            1           9d
   machine-controller-manager   1/1     1            1           9d
   vpn-seed-server              1/1     1            1           9d
   ```

When the error persists for a long time, the tokens in the `gardener` and `gardener-internal` Secrets expire and Shoot fails to wake up:
```yaml
  lastErrors:
    - description: >-
        task "Initializing connection to Shoot" failed: retry failed with
        context deadline exceeded, last error: error creating new ClientSet for
        key "garden-foo/bar": error discovering kubernetes
        version: the server has asked for the client to provide credentials
      taskID: Initializing connection to Shoot
      lastUpdateTime: '2022-04-28T11:48:49Z'
```

**Anything else we need to know?**:

The corresponding part:

https://github.com/gardener/gardener/blob/287b94800fb7c1e0ba2cb21c3464ac18c124a027/pkg/operation/botanist/controlplane.go#L43-L49

Credits to @vpnachev for noticing!

**Environment**:

- Gardener version: v1.46.0-dev-287b94800fb7c1e0ba2cb21c3464ac18c124a027
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
