### ISSUE TITLE
resource-manager fails to apply VerticalPodAutoscaler resource

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#5893]
**How to categorize this issue?**

/area control-plane
/kind bug
/kind regression

**What happened**:
The success rate for Azure tests is awful.

<img width="868" alt="Screenshot 2022-05-02 at 18 27 53" src="https://user-images.githubusercontent.com/9372594/166297622-da37e8e1-ccf6-47c7-8631-06ecb939070e.png">

For K8s 1.23 with @kon-angelo we see the following issue:

CCM fails to start with:
```
E0502 17:44:15.025131       1 controllermanager.go:77] Run: failed to configure cloud controller manager: unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:kube-system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

The CCM RBAC resources are not created in the Shoot.
The corresponding MR fails to be applied with:

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-05-02T16:42:29Z"
    lastUpdateTime: "2022-05-02T16:42:29Z"
    message: The health checks have not yet been executed for the current set of resources.
    reason: HealthChecksPending
    status: Unknown
    type: ResourcesHealthy
  - lastTransitionTime: "2022-05-02T17:39:12Z"
    lastUpdateTime: "2022-05-02T16:42:29Z"
    message: 'error during apply of object "autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler/kube-system/cloud-node-manager":
      no matches for kind "VerticalPodAutoscaler" in version "autoscaling.k8s.io/v1beta2"'
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
```

We suspect that after https://github.com/gardener/gardener/pull/5822 the GRM wrongly tries to first apply the VerticalPodAutoscaler resource and fails because the VPA CRD is not installed yet. So GRM should not first try to apply the VerticalPodAutoscaler, and afterwards blocking creation of all resources.

**What you expected to happen**:
Shoot creation for azure with K8s 1.23 to be successful as before.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create azure Shoot with K8s 1.23.6

2. Verify that the Shoot creation fails as described above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: e0654f04e0c87e87f2f5af7639ebc00e4b24704d
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
