### ISSUE TITLE
Mis-functioning of detection webhooks that are potentially problematic for maintenance activities

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardener#5956]
**How to categorize this issue?**
/area ops-productivity
/kind bug
/priority normal

**What happened**:
In a shoot although shoot owner already configed validatingwebhook to excluded `kube-system` namespace, in dashboard there's still some warning indicating 

```
Maintenance precondition check failed. It may not be safe to start maintenance for your cluster due to the following reason: ValidatingWebhookConfiguration "xxx" is problematic: webhook "xxx" with failurePolicy "Fail" and 3s timeout might prevent worker nodes from properly joining the shoot cluster
```

**What you expected to happen**:

this warning message should not show

**How to reproduce it (as minimally and precisely as possible)**:

1) create a shoot
2) apply a validatingwebhook with following content
```
failurePolicy: Fail
  matchPolicy: Exact
  name: xxx.sh
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
```
3) check the alerts in dashboard
![image](https://user-images.githubusercontent.com/42594392/167872488-dc62a9f2-9fe9-46a1-99c5-54db3ff7b1b3.png)

**Anything else we need to know?**:
I assume it's related to https://github.com/gardener/gardener/issues/3122

**Environment**:

- Gardener version: 1.55.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by timebertt** [comment]
@neo-liang-sap can you add the full webhook config so that one can reproduce this issue?

**Comment by neo-liang-sap** [comment]
@timebertt i will ping you in private

**Comment by timebertt** [comment]
@neo-liang-sap sent me this webhook config right here in private:

```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gatekeeper-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0t...
    service:
      name: gatekeeper-webhook-service
      namespace: gatekeeper-system
      path: /v1/admit
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: validation.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: admission.gatekeeper.sh/ignore
      operator: DoesNotExist
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: '*'
  sideEffects: None
  timeoutSeconds: 3
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0t...
    service:
      name: gatekeeper-webhook-service
      namespace: gatekeeper-system
      path: /v1/admitlabel
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: check-ignore-label.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
    scope: '*'
  sideEffects: None
  timeoutSeconds: 3
```

**Comment by timebertt** [comment]
`check-ignore-label.gatekeeper.sh` is a problematic webhook, as it intercepts `CREATE/UPDATE namespaces` calls with `failurePolicy=Fail`.
This is disallowed by this matcher: https://github.com/gardener/gardener/blob/bc1827317538914af9be133cba42dfe7bb806e24/pkg/operation/botanist/matchers/matcher.go#L80-L83

**Comment by rfranzke** [comment]
We should probably improve our matcher to check whether best-practices are respected. In above case, the `timeoutSeconds` is low enough and there is a correct `namespaceSelector`, so we should not consider it as problematic anymore?

**Comment by timebertt** [comment]
The best-practices don't matter for this case, because Namespaces are cluster-scoped resources, right?
Also, `timeoutSeconds` doesn't matter if `failurePolicy` is set to `Fail`.

**Comment by rfranzke** [comment]
Ah, I missed this. Yeah, in this case an `objectSelector` should be used which excludes `kube-system`. However, I doubt that our check would then no longer consider this webhook as problematic, would it?

**Comment by timebertt** [comment]
Yes, I expect the same.
Maybe we should enhance our matchers to consider this special case for webhooks on `namespaces` and require that an `objectSelector` is present, that excludes all the k8s/gardener managed system namespaces: `kube-system`, `kube-public`, `default`, `kube-node-lease`.

**Comment by ialidzhikov** [comment]
> Yeah, in this case an objectSelector should be used which excludes kube-system. However, I doubt that our check would then no longer consider this webhook as problematic, would it?

Even when you fix the `objectSelector` to be as

```yaml
  name: check-ignore-label.gatekeeper.sh
  namespaceSelector: {}
  objectSelector:
    matchExpressions:
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - namespaces
    scope: '*'
```

gardenlet still considers it as problematic.

I briefly checked the history behind https://github.com/gardener/gardener/blob/bc1827317538914af9be133cba42dfe7bb806e24/pkg/operation/botanist/matchers/matcher.go#L80-L83.

From https://github.com/gardener/gardener/pull/2270#issuecomment-624494880 these rules were added with explanation:

> - `namespaces`, `namespaces/finalize`, `namespaces/status` breaks the cluster once the kube-apiserver is upgraded + woken combo from a version which uses leases as node healthchecks and needs to create the `kube-node-lease` namespace.

The `NodeLease` feature gate is GA since 1.17 (and enabled by default since 1.14), so I think we don't have to worry about this corner case anymore (having in mind that we currently don't support K8s < 1.17).

IIUC we could do a change like
```diff
-		{GVR: corev1.SchemeGroupVersion.WithResource("namespaces"), ClusterScoped: true},
+		{GVR: corev1.SchemeGroupVersion.WithResource("namespaces"), ClusterScoped: true, ObjectLabels: kubeSystemLabels},
```

to stop marking webhooks for namespaces that ignore the kube-system namespace as problematic.

The `default` and `kube-public` namespaces are created by kube-apiserver but I think we can assume that they already exists (how you would create a webhook when the kube-apiserver is not running).

About the ~~`/status`~~, `/finalize` subresources, I am not sure that we need them - cannot think of component or operation that would require to use these subresources on wake up and would fail the wake up if the operation fails.

WDYT?

**Comment by rfranzke** [comment]
Thanks for checking @ialidzhikov, SGTM.

**Comment by timebertt** [comment]
Thank you for checking the details, that sounds promising 👍

**Comment by neo-liang-sap** [comment]
/reopen
some customer reported same error with following webhook with g/g 1.57.0
```
failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating-webhook.openpolicyagent.org
  namespaceSelector:
    matchExpressions:
    - key: openpolicyagent.org/webhook
      operator: NotIn
      values:
      - ignore
    - key: gardener.cloud/purpose
      operator: NotIn
      values:
      - kube-system
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    scope: Namespaced
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10
```
![image](https://user-images.githubusercontent.com/42594392/170605003-e018d497-1eb7-4aab-98b5-d28e91f16c35.png)


Free free ping me in private for more detailed information

**Comment by rfranzke** [comment]
@neo-liang-sap The improvement is not yet released and will only be part of v1.48. @ialidzhikov do you think it makes sense to backport it?

**Comment by ialidzhikov** [comment]
> some customer reported same error with following webhook with g/g 1.57.0

There is no v1.57.0 yet. I assume you mean v1.47.0.
The corresponding PR (https://github.com/gardener/gardener/pull/5991) is not included in v1.47.0 and is about to be included in the upcoming v1.48.0.

>  @ialidzhikov do you think it makes sense to backport it?

Depends on how many affected clusters we have - if it is only several cases I would rather avoid the overhead around new patch release. The issue itself is not a regression. Maybe people just notice it now because of https://github.com/gardener/gardener/pull/5855 and the dashboard showing a warning about it. The only impact should be a misleading warning in the dashboard and gardener-apiserver won't allow hibernation operation.

**Comment by rfranzke** [comment]
Fair enough, thanks!

@neo-liang-sap please check if this still happens with `master` / v1.48 and reopen if necessary

/close

**Comment by vlerenc** [comment]
> Maybe people just notice it now because of https://github.com/gardener/gardener/pull/5855 and the dashboard showing a warning about it.

Seems that had the desired effect. Now so many people started reacting/fixing their web hooks. :-)

cc @holgerkoser @dguendisch @petersutter @grolu

**Comment by dguendisch** [comment]
I have here another legit webhook that Gardener detects as problematic:
<details><summary>webhook spec</summary><p>

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: test-webhook-cfg
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: doesntexist
      namespace: foo
      path: /validate/fail
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: test.foo.bar
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - bar
  # objectSelector:
  #   matchExpressions:
  #   - key: gardener.cloud/purpose
  #     operator: NotIn
  #     values:
  #     - kube-system
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - namespaces
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
```

</p></details>

The important bit is that it's acting on `namespaces` and has a `namespaceSelector` and no `objectSelector`:
```
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - bar
```

I see that @timebertt previously wrote https://github.com/gardener/gardener/issues/5956#issuecomment-1125795187 that `namespaces` are cluster-wide but I don't get the relation.
According to https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-namespaceselector the `namespaceSelector` restricts not only namespaced resources but also namespace objects themselves:
>The namespaceSelector decides whether to run the webhook on a request for a namespaced resource (or a Namespace object)

I verified that with the above webhook in place I can happily `k create ns bar`.
The workaround of applying an additional `objectSelector` works here but would be great if that was not necessary.
