### ISSUE TITLE
Explicitly delete `metrics-server` on Shoot deletion

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#5979]
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:

We could explicitly delete the `metrics-server` including its `APIServices` early on in shoot deletion.

**Why is this needed**:

If there are no nodes to run `metrics-server` pods, the `APIService` is undiscoverable and can therefore block `Namespace` deletion in step `Cleaning shoot namespaces`.

It's not really a bug but an enhancement, because eventually everything works fine. Here are some steps to trigger this though:

1. Create a Shoot
2. Create a new Namespace in the Shoot
3. Hibernate the Shoot
4. Delete the Shoot
5. Observe that the step `Cleaning shoot namespaces` will be unnecessarily prolonged because the namespace is stuck in `Terminating` with 

```yaml
status:
  conditions:
  - lastTransitionTime: "2022-05-16T09:26:24Z"
    message: 'Discovery failed for some groups, 1 failing: unable to retrieve the
      complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently
      unable to handle the request'
    reason: DiscoveryFailed
    status: "True"
    type: NamespaceDeletionDiscoveryFailure
```
