### ISSUE TITLE
After v1.47 gardenlet fails to reconcile ControllerInstallations with helm3 charts

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#6103]
**How to categorize this issue?**

/area robustness usability
/kind bug regression

**What happened**:
After v1.47 gardenlet fails to reconcile ControllerInstallations with [helm3](https://helm.sh/docs/topics/charts/#the-apiversion-field) charts, i.e. `Chart\.yaml.apiVersion=v2`

**What you expected to happen**:
The controller installation to be successfully reconciled

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the following ControllerDeployment (have just a single v1.Service resource)

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: foo
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1X32/bNhDOM/+Ka7uHtpgpS/4F+C1Isi1Y0QZ1YextoKSzxEUiBZJy4hXd376jlCCN284rUCUoyg8GRVHH49HH7+640To6GhhjwmI2656E/WfXjyfTOJkl87kfj8eTyfwIZkMb5tFaJwzAkdHa/Zfcoe/fKTbkf15iVctCaYODrOEdPJ9Ov+j/2WS25/9kupgcwXgQa/bwg/v/GVwI59AoC05DfwjgqkQFaSurXKoCGpFdigItZ8/gXSkt2LZptHHUoYNTQVHpFGrhspKkfwaDlXByizTPlR+NC5WTAoUFfdUKnjcGN/Iac7iSJPfkBYc3qtqBVt1MbxI0aKCSCjnjp6s/V45sIxUnuq5JwfpkBbk0lvFCuqhre/MZT/82UdfeDpRF5JvbV7tV0Z2ilPbXNrCRFVr2kturhtpUXFLrat/XpIe9/IdmrIWRurVwfnpG6zZG/4WZY1zmKKJenIYY39pM5xixx3bu/4Dn/0kpjOM7UVfDrHGI//Fisc//ZDEO/H8IiEau0Vhi5BK2CRNNc/c65jEfj3LcshxtZmTjuvFj+I3yBWT+1MBGG/i9TYmt6Ig+StS4pEHN3K6hHumrZNYxnm0/o/ixt//Dw/M/1xkv9HBrHOL/fL6f/+PpNA78fwhEEawuTv8Y/ULZ70Q3O0p1pXuH124JyThJYHV8AaszIJYL1b2IDSVKKRxCputGqJ1P7PCrMDkqSteZVs7ItKVcbVkUsVv9r2SGyuLonMSc3Eg0FEiosihxlPAxI7lCLwuvwqu2JYwyeMp5RL8tqlybiPJ72aacVo2Km9XuOiXl8Oh2+qgzQlcVmpHBQlpnugjESS2dd+Dw03OKSdCrX5+9XZ2/ef3i5hWvRd1UGH1Jh0+TcHbtaDc+mJG+p956KqO6KukmLKISKZUTcG9TfdnUhcybQV9eudL/lcZQJQF3i8K9RVnzsfZvGTU9/x3SjslCO9BN8Ovvf8lkMg33v4fAff9bNFsiqsgy3apvVhIerP9m+/F/nvj7f4j/w+Ne/RezS6nyJaz6Y3DcHwNWoxO5cGLJAPoC7/174GtRtXQp9AH1wwf6UokUK+tlwEfZzwk99mYDPoHn/7Z30mAXwEP8H8efxP9ZHO5/D4KOqakwj21HQEBAQEBAQEBAQEBAQEBAQMAw+Bfzjb0UACgAAA==
  values:
    image:
      tag: v0.1.0-dev
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: foo
spec:
  deployment:
    deploymentRefs:
    - name: foo
    policy: Always
  resources:
  - kind: Extension
    type: foo
```

and make sure the gardenlet fails to reconcile the ControllerInstallation with
```
ts="2022-06-13T15:48:15.779+0000" level=info msg="Error syncing ControllerInstallation foo-d6kbq: can't create load chart from archive: apiVersion 'v2' is not valid. The value must be \"v1\""
```

If the gardenlet is downgraded to v1.46.2, the ControllerInstallation is successfully reconciled. 

**Anything else we need to know?**:
This was working fine until v1.46.2

**Environment**:

- Gardener version:  >= 1.47
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
