### ISSUE TITLE
#5946 broke ability to update istio if ExposureClasses are used

### ISSUE THREAD

**Issue by ScheererJ** [gardener/gardener#6270]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:
Updating istio does no longer work after https://github.com/gardener/gardener/pull/5946 if `ExposureClasses` are used. There is only one managed resource for the istio resources, but the `istio-ingress` resources should be deployed into several namespaces, one for each exposure class.
Looking into the managed resource, you can see that only one set of `istio-ingress` resources are included. Hence, the other exposure class namespaces are not updated properly.

**What you expected to happen**:
If istio is updated this should be reflected in all exposure class namespaces.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an exposure class, e.g. by adding the following to your gardenlet config:

```
exposureClassHandlers:
  - name: internet-config
    loadBalancerService:
      annotations:
        loadbalancer/network: internet
  - name: internal-config
    loadBalancerService:
      annotations:
        loadbalancer/network: internal
    sni:
      ingress:
        namespace: ingress-internal
        labels:
          network: internal
```

2. Afterwards, simply update istio, e.g. by incrementing the minor version in `charts/images.yaml`.
3. Watch only one `istio-ingress` gateway being updated.

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

/cc @dkistner @acumino @rfranzke
