### ISSUE TITLE
Broken CA-rotation for HA shoots

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#6419]
**How to categorize this issue?**

/area high-availability
/area security
/kind bug

**What happened**:
When testing the CA rotation feature for HA shoot clusters I observed a race condition where the CA `peer` bundle was not completely rolled out to all etcd pods while Gardenlet already continued to distribute the `server/client` certificate singed by the new CA.

- `etcd-main-2` log:

```
2022-07-29 14:40:09.120640 I | embed: rejected connection from "10.1.130.224:35100" (error "remote error: tls: bad certificate", ServerName "etcd-main-2.etcd-main-peer.shoot--local--local.svc")
```

- Pods:
```
etcd-main-0                                     2/2     Running   0          61m    10.1.130.224   gardener-local-control-plane   <none>           <none>
etcd-main-1                                     2/2     Running   0          20m    10.1.130.210   gardener-local-control-plane   <none>           <none>
etcd-main-2                                     1/2     Running   0          20m    10.1.130.229   gardener-local-control-plane   <none>           <none>
```

Hence, the error with Pod IP `10.1.130.224` originates from a `etcd-main-0`.

Checking the Pod definition it's evident that the CA bundle (containing old AND new CA) rollout did not finish completely:

```
etcd-main-0:
  - name: peer-url-ca-etcd
    secret:
      defaultMode: 420
      secretName: ca-etcd-peer-bundle-4e9ba5c3 <-- bundle with old CA only!
  - name: peer-url-etcd-server-tls
    secret:
      defaultMode: 420
      secretName: etcd-peer-server-main-b4fc5d39 <-- old certificated singed by new CA

etcd-main-1:
  - name: peer-url-ca-etcd
    secret:
      defaultMode: 420
      secretName: ca-etcd-peer-bundle-a29057c4 <-- bundle with old and new CA
  - name: peer-url-etcd-server-tls
    secret:
      defaultMode: 420
      secretName: etcd-peer-server-main-b4fc5d39 <-- old certificated singed by new CA


etcd-main-2:
  - name: peer-url-ca-etcd
    secret:
      defaultMode: 420
      secretName: ca-etcd-peer-bundle-a29057c4 <-- bundle with old and new CA
  - name: peer-url-etcd-server-tls
    secret:
      defaultMode: 420
      secretName: etcd-peer-server-main-de8af308 <-- new certificated singed by new CA
```

**What you expected to happen**:
The CA bundle which contains the old and the new CA should successfully be rolled out to every etcd member first before Gardener continues to distribute a newly generated client/server cert.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an HA shoot cluster
2. Execute the CA rotation (multiple times)

**Anything else we need to know?**:
At the moment I assume that this is either a race condition in Gardener when it reads the `etcd` resource (unlikely because `v1beta1constants.GardenerTimestamp` is used to verify the result) or a race condition in Etcd-Druid which sets the `etcd.Status.Ready: true` during the StatefulSet rollout.

I will continue my investigation by adding more logs first and will update this issue as soon as there are more insights.

**Environment**:

- Gardener version: v1.52.0-dev
