### ISSUE TITLE
gardenlet doesn't reconcile `DNSRecords` when changing their spec

### ISSUE THREAD

**Issue by nschad** [gardener/gardener#6463]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
We recently migrated from `dnsentries` to `dnsrecords`. Upon the migration, we noticed that after gardener cleared all `dnsentries` and migrated them to `dnsrecords` it got stuck with the following error message:

> task "Deploying external domain DNS record" failed: Error while waiting for DNSRecord shoot--garden--r-eu01m-0/r-eu01m-0-external to become ready: observed generation outdated (1/2)

We then removed all previously migrated `dnsrecords` and let Gardener re-create the `dnsrecord`. After that the migration went through without a hitch.
```bash
k get dnsrecords.extensions.gardener.cloud -A | tail -n +2 | awk -F ' ' '{print $1, $2}' | xargs -l1 -- sh -c 'kubectl annotate dnsrecord "$2" -n "$1" confirmation.gardener.cloud/deletion=true' --
k get dnsrecords.extensions.gardener.cloud -A | tail -n +2 | awk -F ' ' '{print $1, $2}' | xargs -l1 -- sh -c 'kubectl delete dnsrecord "$2" -n "$1" --wait=false' --
```

**What you expected to happen**:

Migration from `dnsentries` to `dnsrecords` without any manual intervention. Also we can not be sure at the moment that this issue was just a "one time thing" (only once during migration) and if it might happen again.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enabled google gcp extension (provider-gcp)
2. Set `UseDNSRecords` to true

```yaml
# gardener.values.global.apiserver.featureGates
# gardener.values.global.controllers.featureGates
UseDNSRecords: true

# acre.yaml
# landscape.iaas.[].featureGates
UseDNSRecords: true
```
3. Deploy changes
> ./deploy.sh deploy gardener/virtual gardener/runtime gardencontent/seeds/soils
4. Set `UseDNSRecords` to true for Seeds (ManagedSeedSet, ManagedSeed)
```yaml
        config:
          featureGates:
            UseDNSRecords: true
```
5. After Step 4 enable
```yaml
ManagedIstio: true
APIServerSNI: true
````

Step 5 halts the complete reconciliation as Gardener can **not** update the dnsrecord for the shoots/seed/initial.

> task "Deploying internal domain DNS record" failed: Error while waiting for DNSRecord shoot-bla-bla to become ready: observed generation outdated (1/2)

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.43.2
- Kubernetes version (use `kubectl version`): 1.21.11
- Cloud provider or hardware configuration: OpenStack
- Others:
