### ISSUE TITLE
Use federation for creation of various resource in Gardener

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#654]
# Federation-v2 for addon management / extensiblity.

## Overview

Unlike v1, [federation-v2](https://github.com/kubernetes-sigs/federation-v2) providers a generic way to distribute, place, sync and override arbitary Kubernetes resources. From the homepage of the project

<p align="center"><img src="https://raw.githubusercontent.com/kubernetes-sigs/federation-v2/master/docs/images/concepts.png" width="711"></p>

Federation is configured with two types of information:

- **Type configuration** declares which API types federation should handle
- **Cluster configuration** declares which clusters federation should target

**Propagation** refers to the mechanism that distributes resources to federated
clusters.

Type configuration has three fundamental concepts:

- **Template types** define the representation of a resource common across clusters
- **Placement types** define which clusters the resource is intended to appear in
- **Override types** optionally define per-cluster field-level variation to apply to the template

These three abstractions provide a concise representation of a resource intended
to appear in multiple clusters. They encode the minimum information required for
**propagation** and are well-suited to serve as the glue between any given
propagation mechanism and higher-order behaviors like policy-based placement and
dynamic scheduling.

## Federation in the Gardener context

Federation can be used by Gardener in 3 (but not limited to) different ways:

- Replacement for `kube-addon-manager` for a `Seed` cluster to sync and manage all addons in the child `Shoot` clusters.
- Replacement for `seed-reconciler-controller`
- Replacement for `ControllerRegistration` and `ControllerInstallation` as described in the [extensiblity proposal](https://github.com/gardener/gardener/blob/1db44f53ae2b4e11d0cd5e5ed01ed594089afcb5/docs/proposals/01-extensibility.md#registration-of-external-controllers-at-gardener) (where network connectivity `Garden` cluster -> `Seed` cluster is available).

### Replacement for `kube-addon-manager`

`kube-addon-manager` ensures that addons which are installed in the Shoot cluster. There are several fundamental problems with it:

- Every 1 min it manually applies a list of K8S manifests, resulting in a longer downtime when resources are removed.
- Extra API calls are make to the `Shoot` cluster without any benefit 99% of the time.
- Manifests for all addons in a Shoot cluster (stored in `Secrets`) are more or less copied across namespaces with little modification.

In this case in the `Seed` cluster's `kube-system` there will be multiple core resources / addons which must (or optionally not) be created in a `Shoot` cluster. Example for `kube-proxy`' setup (click bellow to expand):

<details>

<summary>kube-proxy-daemonset.yaml</summary>

```yaml
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedDaemonSet
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        garden.sapcloud.io/role: system-component
        origin: gardener
    spec:
      updateStrategy:
        type: RollingUpdate
      selector:
        matchLabels:
          app: kubernetes
          role: proxy
      template:
        metadata:
          labels:
            garden.sapcloud.io/role: system-component
            origin: gardener
            app: kubernetes
            role: proxy
        spec:
          priorityClassName: system-cluster-critical
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          hostNetwork: true
          serviceAccountName: kube-proxy
          # not used - kubeconfig is mounted.
          automountServiceAccountToken: false
          containers:
          - name: kube-proxy
            image: k8s.gcr.io/hyperkube:v1.13.1
            imagePullPolicy: IfNotPresent
            command:
            - /hyperkube
            - proxy
            - --config=/var/lib/kube-proxy-config/config.yaml
            - --v=2
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 20m
                memory: 64Mi
              limits:
                cpu: 900m
                memory: 200Mi
            volumeMounts:
            - name: kubeconfig
              mountPath: /var/lib/kube-proxy
            - name: kube-proxy-config
              mountPath: /var/lib/kube-proxy-config
            - name: ssl-certs-hosts
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: systembussocket
              mountPath: /var/run/dbus/system_bus_socket
          volumes:
          - name: kubeconfig
            secret:
              secretName: kube-proxy
          - name: kube-proxy-config
            configMap:
              name: kube-proxy-config
          - name: ssl-certs-hosts
            hostPath:
              path: /usr/share/ca-certificates
          - name: systembussocket
            hostPath:
              path: /var/run/dbus/system_bus_socket

---

apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedDaemonSetOverride
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  overrides:
  - clusterName: shoot
    clusterOverrides:
    - path: spec.template.metadata.annotations
      value:
        checksum/configmap-componentconfig: fc654c207336c923a0ce270cb2f1241d8f02cbeaa46c1d23c16a8ee77644c023
        checksum/secret-kube-proxy: c7c1888f053843db834b62915ea865a78b7c457b2d4b1ada93c9a0dc523e29e6
    - path: spect.template.spec.containers[0].image
      value: k8s.gcr.io/hyperkube:v1.12.1

---

kind: FederatedDaemonSetPlacement
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  clusterNames:
  - shoot
```
</details>

<details>

<summary>kube-proxy-configmap.yaml</summary>

```yaml
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMap
metadata:
  name: kube-proxy-config
  namespace: kube-system
spec:
  template:
    data:

---

apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapOverride
metadata:
  name: kube-proxy-config
  namespace: kube-system
spec:
  overrides:
  - clusterName: shoot
    clusterOverrides:
    - path: data
      value:
        config.yaml: |-
          ---
          apiVersion: kubeproxy.config.k8s.io/v1alpha1
          kind: KubeProxyConfiguration
          clientConnection:
            kubeconfig: /var/lib/kube-proxy/kubeconfig
          clusterCIDR: 100.96.0.0/11
          conntrack:
            maxPerCore: 524288
---

kind: FederatedConfigMapPlacement
metadata:
  name: kube-proxy-config
  namespace: kube-system
spec:
  clusterNames:
  - shoot
```
</details>

<details>

<summary>kube-proxy-secret.yaml</summary>

```yaml
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedSecret
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  template:
    type: Opaque
    data:

---

apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedSecretOverride
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  overrides:
  - clusterName: shoot
    clusterOverrides:
    - path: data
      value:
        kubeconfig: abcd1234
---

kind: FederatedSecretPlacement
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  clusterNames:
  - shoot
```
</details>

<details>

<summary>kube-proxy-serviceaccount.yaml</summary>

```yaml
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederateServiceAccount
metadata:
  name: kube-proxy
  namespace: kube-system

---

kind: FederateServiceAccountPlacement
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  clusterNames:
  - shoot
```
</details>

### Replacement for `ControllerRegistration` and `ControllerInstallation`

The same method for installation of `Shoot` addons can be applied to install controllers and other components in the `Seed` cluster.

For example on `AWS` `Seed` cluster we might have the following resources in a `Garden` cluster (click bellow to expand):

<details>

<summary>seed-aws-controller-deployment.yaml</summary>

```yaml
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedDeployment
metadata:
  name: aws-controller
  namespace: garden-system
spec:
  template:
    metadata:
      labels:
        app: aws
    spec:
      serviceAccountName: aws-controller
      selector:
        matchLabels:
          app: aws
      template:
        metadata:
          labels:
            app: aws
        spec:
          containers:
          - image: foo/aws-controller:v0.0.1
            name: aws

---

apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedIngressPlacement
metadata:
  name: aws-controller
  namespace: garden-namespace
spec:
  clusterSelector:
    matchLabels:
      gardener.cloud/some-annotation: aws
```
</details>

<details>

<summary>seed-aws-controller-serviceaccount.yaml</summary>

```yaml
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederateServiceAccount
metadata:
  name: aws-controller
  namespace: garden-system

---

kind: FederateServiceAccountPlacement
metadata:
  name: aws-controller
  namespace: garden-system
spec:
  clusterSelector:
    matchLabels:
      gardener.cloud/some-annotation: aws
```
</details>

### Replacement for `seed-reconciler-controller`

Our `seed-reconciler-controller` has the following issues:

- Every `1m` it applies a list of K8S manifests even if there are no changes to those resources.
- Extra API calls are make to the `Seed` cluster without any benefit 99% of the time.

In this case the `federation-controller` can be configured to watch only a specific namespace in the `Garden` cluster and federate in it all of the components in itself. This approach requires only connectivity from the `Seed` to `Garden` cluster.

## Limitations and issues

- Federation v2 is not production-ready.
- In the `kube-addon-manager` replacement context `Federated<RESOURCE-NAME>Override` must be updated for every single cluster. A better approach for this is to add an additional filed like `target` to it point to a `Federated<RESOURCE-NAME>` so an individual `Federated<RESOURCE-NAME>Override` can be created.
- All resources which needs to be federated need to have 3 CRDs generated for each.
- A controller for reconcilation of `Cluster` (`clusterregistry.k8s.io/v1alpha1`) and `FederatedCluster` (`core.federation.k8s.io/v1alpha1`) must be created for our `Seed` and `Shoot` resources.
- There are several bugs which needs to be fixed  [#509 can be overcome by removing/fixing the validation](https://github.com/kubernetes-sigs/federation-v2/issues/509), [#538]((https://github.com/kubernetes-sigs/federation-v2/issues/538))

/cc @vasu1124 @vlerenc @rfranzke
