### ISSUE TITLE
Problematic webhook reported for provider local

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#6562]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
When creating a shoot with `provider-local`, e.g. `example/provider-loca/shoot.yaml`, the following constraints are reported:

```
    constraints:
    - codes:
      - ERR_PROBLEMATIC_WEBHOOK
      lastTransitionTime: "2022-08-22T19:10:36Z"
      lastUpdateTime: "2022-08-22T19:00:05Z"
      message: 'MutatingWebhookConfiguration "gardener-extension-provider-local-shoot"
        is problematic: webhook "node-shoot.local.extensions.gardener.cloud" with
        failurePolicy "Fail" and 1s timeout might prevent worker nodes from properly
        joining the shoot cluster'
      reason: ProblematicWebhooks
      status: Progressing
      type: HibernationPossible
    - codes:
      - ERR_PROBLEMATIC_WEBHOOK
      lastTransitionTime: "2022-08-22T19:10:36Z"
      lastUpdateTime: "2022-08-22T19:00:05Z"
      message: 'MutatingWebhookConfiguration "gardener-extension-provider-local-shoot"
        is problematic: webhook "node-shoot.local.extensions.gardener.cloud" with
        failurePolicy "Fail" and 1s timeout might prevent worker nodes from properly
        joining the shoot cluster'
      reason: ProblematicWebhooks
      status: Progressing
      type: MaintenancePreconditionsSatisfied
```

This unfortunately forbids to hibernate the cluster which is extremely useful when testing locally 😄 

**What you expected to happen**:
The webhook to be skipped (?!) from the checks and not to be reported as problematic.

**How to reproduce it (as minimally and precisely as possible)**:
Follow https://github.com/gardener/gardener/blob/master/docs/deployment/getting_started_locally.md#creating-a-shoot-cluster to create a shoot cluster with provider local.

**Anything else we need to know?**:
It's not yet clear why the [hibernation e2e test](https://github.com/gardener/gardener/blob/master/test/e2e/shoot/create_hibernate_wakeup_delete.go) does not fail.
