### ISSUE TITLE
During a rolling update no new Nodes from the to be rolled worker can join the cluster

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6569]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
It seems that during a rolling update no new Nodes from the to be rolled worker can join the cluster.

**What you expected to happen**:
Such Nodes to be able to join the cluster. Nodes from the to be rolled worker can get unhealthy and can be replaced. But the new replacement Nodes cannot not join the cluster.
For example this can be an issue for large clusters that rollout Nodes 1 by 1 (`maxSurge: 1`).

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot with a worker with min=max=3
2. For each Node setup Deployments with misconfigured PDBs to block the rollout (needed to be able to executed the next steps)

```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb1
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: nginx1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
spec:
  selector:
    matchLabels:
      app: nginx1
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      nodeName: <NODE1>
```

3. Update the Shoot's Kubernetes version to the next minor one to trigger a rolling update

4. During the rolling update delete a Node from the old worker pool

5. Make sure that the new Machine that is supposed to replace the deleted Node from the old worker pool cannot join

**Anything else we need to know?**:

The reason for this seems to be that we always have only the latest cloud-config Secret in the Shoot's kube-system Namespace:
```
$ k -n kube-system get secret -l gardener.cloud/role=cloud-config
NAME                            TYPE     DATA   AGE
cloud-config-cpu-worker-9af6d   Opaque   1      39m
```

While when I check the old MachineClass Secret and its download-cloud-config.sh script in it, I see that it reference the old non-existing Secret:
```bash
SECRET_NAME="cloud-config-cpu-worker-b3bcf"
TOKEN_SECRET_NAME="cloud-config-downloader"
```

Note that there is no longer such cloud-config Secret in the Shoot - `cloud-config-cpu-worker-b3bcf`.

**Environment**:

- Gardener version: v1.53.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
