### ISSUE TITLE
The maintenance controller in GCM to keep track of the last maintenance operation in the shoot status

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#6592]
**How to categorize this issue?**

/area ops-productivity robustness usability
/kind enhancement

**What would you like to be added**:
The maintenance controller in GCM to keep track of the last maintenance operation in the shoot status - it could be either a condition or a new field similar to `lastOperation`. 

**Why is this needed**:
1. To have the timestamp of the last maintenance operation.
2. Any failed maintenance operations to be made visible to the shoot owner and gardener operators with reason/error message.
3. It would be nice to have summary of what was changed in the shoot spec during the last maintenance, e.g. OS/k8s version.

**Comment by rfranzke** [comment]
cross-referencing https://github.com/gardener/gardener/issues/2097

**Comment by ialidzhikov** [comment]
We agreed to add the last maintenance operation in a Shoot status field similar to `lastOperation` - example naming can be `lastMaintenanceOperation`. We also have to check whether https://github.com/gardener/gardener/issues/2097 is still applicable - if it is, we can use the new status field to prevent GCM from performing n maintenance operations if it is in `CrasshloopBackoff`.

**Comment by vpnachev** [comment]
/reopen

as #6862 reverted #6725

**Comment by acumino** [comment]
From suggestion in https://github.com/gardener/gardener/pull/7035.
- API should look like - 
```
status:
  lastMaintenance:
    timestamp: 2022-11-18T10:14:38Z
    description: "Kubernetes version was upgraded to 1.24.5. OS image versioin of worker pool 123 was upgraded to 987.6.5"
    State: <string> it will contain error if last maintenance failed and will not be populated if maintenance succeeds.
```
- Description should be a one-liner and not a list of lines. Though the multiline approach is more readable.
- Description should contain details related to os image changes and Kubernetes version changes.
- Description should contain details of any operation which is scheduled in maintenance time like secret rotation.

- There should be only one last maintenance operation detail in the shoot status.

/cc @rfranzke @timebertt  Can you check if the above changes are right or do we want anything more?

**Comment by rfranzke** [comment]
This is at least what was proposed with https://github.com/gardener/gardener/pull/7035#pullrequestreview-1187711292. The small downside is that this information might get lost quickly when the next relevant maintenance operation runs. Maybe we should go back to reporting the last 3 operations so that this whole field becomes more useful for operators and end-users?

```yaml
status:
  lastMaintenances:
  - timestamp: 2022-11-18T10:14:38Z
    description: "Kubernetes version was upgraded to 1.24.5. OS image versioin of worker pool 123 was upgraded to 987.6.5"
    state: <string> it will contain error if last maintenance failed and will not be populated if maintenance succeeds.
  - timestamp: 2022-11-14T10:26:13Z
    description: "CA rotation start was triggered"
    state: <string> it will contain error if last maintenance failed and will not be populated if maintenance succeeds.
```

Also, we should probably omit "empty maintenances" (which happen in most cases), i.e. those where neither version nor operation annotation was changed. For example, if the controller only triggers a normal reconciliation, we should not augment this `.status.lastMaintenances`. This way, we keep the information in this field is kept free from unneeded information.

WDYT?
