### ISSUE TITLE
Allow controller-manager to specify gardener-apiserver connection

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#66]
`gardener-controller-manager` only supports 1 kubernetes server (`core`) as configuration.
For local development it should be possible to specify the optional `gardener-apiserver` without the need to register it with `APIService`. This will also allow us to specify `application/vnd.kubernetes.protobuf` for the `core` apiserver

I suggest the following changes:

```go
type ControllerManagerConfiguration struct {
	metav1.TypeMeta `json:",inline"`
	// ClientConnection specifies the kubeconfig file and client connection
	// settings for the proxy server to use when communicating with the apiserver.
	ClientConnection ClientConnectionConfiguration `json:"clientConnection"`
+	// GarClientConnection specifies the kubeconfig file and client connection
+	// settings for the gardener-apiserver.
+       GardenerClientConnection ClientConnectionConfiguration `json:"gardenerClientConnection"`
```

If no `GardenerClientConnection` is specified then use `ClientConnection` as fallback.

/cc @rfranzke

**Comment by mvladev** [comment]
This more or less what we want to have:

```yaml
apiVersion: componentconfig.sapcloud.io/v1alpha1
kind: ControllerManagerConfiguration
clientConnection:
  acceptContentTypes: application/vnd.kubernetes.protobuf
  contentType: application/vnd.kubernetes.protobuf
  qps: 100
  burst: 130
  kubeconfig: ~/.kube/config # <- minikube core server
gardenerClientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
  kubeconfig: $GOPATH/github.com/gardener/gardener/dev/kubeconfig # <- local gardener-apiserver kubeconfig. See bellow for example.
...
```

$GOPATH/github.com/gardener/gardener/dev/kubeconfig :

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: $GOPATH/github.com/gardener/gardener/dev/ca.crt
    server: https://localhost:8443
  name: gardener-dev
contexts:
- context:
    cluster: gardener-dev
    user: gardener-dev
  name: gardener-dev
current-context: gardener-dev
kind: Config
- name: gardener-dev
  user:
    client-certificate: $GOPATH/github.com/gardener/gardener/dev/client.crt
    client-key: $GOPATH/github.com/gardener/gardener/dev/client.key
```
