### ISSUE TITLE
Alertmanager running in cluster mode

### ISSUE THREAD

**Issue by eaterm** [gardener/gardener#669]
The alertmanager inside the seed and shoot cluster are running in cluster mode.
If lookup of private IP's fails the alertmanager will terminate with an error, because of this the shoot cluster will never get 100% ready.

Adding `--cluster.listen-address=""'` would solve the issue.

Created ticket for discuss if this is an option.

Ticket created after talking to @dkistner

**Comment by eaterm** [comment]
Seed network config. Because the pod network is niet RFC1918 the pod will fail.
```
  networks: 
    nodes: 172.20.32.0/19
    pods: 100.0.0.0/10
    services: 100.80.0.0/13
```
