### ISSUE TITLE
Webhook constraint matcher does not consider well-know k8s label on namespaces

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#6747]
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
Since https://github.com/kubernetes/kubernetes/pull/96968 all namespace in k8s get the label `kubernetes.io/metadata.name=<namespace-name>`. The webhook constrain matcher here https://github.com/gardener/gardener/blob/24dc519d70c664bb64ebe46808320ae9595d3cfc/pkg/operation/botanist/matchers/matcher.go#L50-L52
does not consider this well-known label and wrongly classify webhooks as problematic.

**What you expected to happen**:
Webhooks with namespace selector like
```yaml
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
```
to not be detected as problematic.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: latest
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
