### ISSUE TITLE
Local Registry pods are only accessible by accident from local shoot clusters

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#6777]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
We are using `172.19.0.0/16` as node CIDR for the local `Seed`s at two places:

https://github.com/gardener/gardener/blob/3f57fd0f415117075724d94b6aa051cee558200d/example/provider-local/seed-kind/local/seed.yaml#L29

https://github.com/gardener/gardener/blob/3f57fd0f415117075724d94b6aa051cee558200d/example/gardener-local/gardenlet/values.yaml#L83

However, in reality the default CIDR for the `kind` Docker network is `172.18.0.0/16`. Generally, the CIDR can be retrieved with the following command:

```shell
docker network inspect kind | jq -r '.[0].IPAM.Config[0].Subnet'
```

The concrete CIDR obviously depends on the target machine. If there are other Docker networks manually created before the `kind` network got created then those have probably already claimed `172.18.0.0/16`, however in "fresh environments", the `kind` network gets the `172.18.0.0/16` range. For example, in Prow pods we have such fresh environments.

Now that we were using the wrong CIDR, the registry was only accessible by accident from local shoot clusters. This is because Gardener deploys a the `NetworkPolicy/allow-to-private-networks` into the shoot namespaces as follows:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-private-networks
  namespace: shoot--local--local
spec:
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/8
        except:
        - <POD-SUBNET-CIDR-OF-SEED>
        - <SERVICE-SUBNET-CIDR-OF-SEED>
    - ipBlock:
        cidr: 172.16.0.0/12
        except:
        - <NODE-SUBNET-CIDR-OF-SEED>
    - ipBlock:
        cidr: 192.168.0.0/16
    - ipBlock:
        cidr: 100.64.0.0/10
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-private-networks: allowed
  policyTypes:
  - Egress
status: {}
```

Since the machine pods have the `networking.gardener.cloud/to-private-networks=allowed` label, this policy actively prevents them from talking to the registry pods running in the `kind` cluster's host network because IP blocks belonging to the seed's nodes CIDR are explicitly excepted.
Previously, it only worked by accident because we were using the wrong nodes CIDR (hence, `172.19.0.0/16` was excepted while the registry pods had IPs out of the `172.18.0.0/16` subnet).

**What you expected to happen**:
Generally, this `NetworkPolicy` makes sense from Gardener's PoV because we usually don't want pods in the shoot control plane namespaces to talk to pods in the seed cluster's host network.
However, the local setup is different and here we explicitly want to allow it.
We should definitely configure the correct nodes CIDR in the `SeedSpec`.
Consequently, `provider-local` has to modify this `NetworkPolicy` and prevent the exception of the seed cluster's node subnet CIDR.

**How to reproduce it (as minimally and precisely as possible)**:
```
make kind-up
make gardener-up
kubectl apply -f example/provider-local/shoot.yaml
```

See the shoot worker nodes successfully pulling images from the registry pods.
