### ISSUE TITLE
pods "vpn-seed-server-867cd9dbcf-" is forbidden: no PriorityClass with name gardener-shoot-controlplane was found

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6798]
**How to categorize this issue?**

/area control-plane
/kind bug
/kind regression

**What happened**:
After the rollout of gardener/gardener@v1.57.0 Shoots are unhealthy with:
```
Deployment "vpn-seed-server" is unhealthy: condition "Available" has invalid status False (expected True) due to MinimumReplicasUnavailable: Deployment does not have minimum availability.
```

```yaml
  - lastTransitionTime: "2022-10-10T19:43:52Z"
    lastUpdateTime: "2022-10-10T19:43:52Z"
    message: 'pods "vpn-seed-server-867cd9dbcf-" is forbidden: no PriorityClass with
      name gardener-shoot-controlplane was found'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
```

Possible related to https://github.com/gardener/gardener/pull/6738.

**What you expected to happen**:
No such issue after the rollout of gardener/gardener@v1.57.0.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.57.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
