### ISSUE TITLE
Cannot create containers with gRPC probes on Gardener 1.57.0 with k8s 1.24

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardener#6818]
**How to categorize this issue?**
/kind bug
/area open-source

**What happened**:
gRPC readiness/liveness probes are not working on Gardener 1.57.0 with k8s 1.24. According to the documentation they should be available on this version: [link](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe). I enabled the GRPCContainerProbe feature gate on kubelet level.

**What you expected to happen**:
be able to create containers with gRPC readiness/liveness probes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Gardener 1.57.0 cluster with k8s version 1.24.3
2. Enable the `GRPCContainerProbe` feature gate
3. Try to create a pod with a gRPC probe. Example from the documentation:
```
apiVersion: v1
kind: Pod
metadata:
  name: etcd-with-grpc
spec:
  containers:
  - name: etcd
    image: registry.k8s.io/etcd:3.5.1-0
    command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", "--listen-client-urls", "http://0.0.0.0:2379/", "--advertise-client-urls", "http://127.0.0.1:2379/", "--log-level", "debug"]
    ports:
    - containerPort: 2379
    livenessProbe:
      grpc:
        port: 2379
      initialDelaySeconds: 10
```
4. Observe that the creation fails with: `The Pod "etcd-with-grpc" is invalid: spec.containers[0].livenessProbe: Required value: must specify a handler type` 

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.57.0
- Kubernetes version (use `kubectl version`): 1.24
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
I think this is caused by the `apiserver-proxy.networking.gardener.cloud` mutating webhook. After looking for several hours into the source of kubernetes/kubernetes and comparing kube-apiserver flags for kind vs gardeer, finally the following was enough to prove that the apiserver-proxy webhook is doing something wrong:
```
# To disable the webhook for the default namespace
$ k label ns default apiserver-proxy.networking.gardener.cloud/inject=disable

$ k create -f ~/pod.yaml
pod/test-grpc created
```

The Pod spec:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-grpc
spec:
  containers:
  - name: agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.35
    command: ["/agnhost", "grpc-health-checking"]
    ports:
    - containerPort: 5000
    - containerPort: 8080
    readinessProbe:
      grpc:
        port: 5000
```
