### ISSUE TITLE
Error code is no longer added for the `Waiting until managed resources have been deleted` step

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#6855]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
Shoot fails to be deleted with:
```yaml
  lastOperation:
    description: "Flow \"Shoot cluster deletion\" encountered task errors: [task \"Waiting until managed resources have been deleted\" failed: error while waiting for all resources to be deleted: : 1 error occurred: retry failed with context deadline exceeded, last error: resource(s) [shoot-core] still exists:\nCould not clean all old resources: 1 error occurred: deletion of old resource \"v1/Service/kube-system/vpn-shoot\" is still pending\n\n-> Events:\n* ipallocator-repair-controller reported 111s ago (x846 over 42h): Cluster IP 100.69.17.139 is not allocated; repairing\n* portallocator-repair-controller reported 111s ago (x846 over 42h): Port 31748 is not allocated; repairing\n* service-controller reported 74s ago (x5572 over 42h): (combined from similar events): Error syncing load balancer: failed to check if load balancer exists before cleanup: InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: <omitted>]"
    lastUpdateTime: '2022-10-14T03:39:54Z'
    progress: 66
    state: Failed
    type: Delete
  lastErrors:
    - description: "task \"Waiting until managed resources have been deleted\" failed: error while waiting for all resources to be deleted: : 1 error occurred: retry failed with context deadline exceeded, last error: resource(s) [shoot-core] still exists:\nCould not clean all old resources: 1 error occurred: deletion of old resource \"v1/Service/kube-system/vpn-shoot\" is still pending\n\n-> Events:\n* ipallocator-repair-controller reported 111s ago (x846 over 42h): Cluster IP 100.69.17.139 is not allocated; repairing\n* portallocator-repair-controller reported 111s ago (x846 over 42h): Port 31748 is not allocated; repairing\n* service-controller reported 74s ago (x5572 over 42h): (combined from similar events): Error syncing load balancer: failed to check if load balancer exists before cleanup: InvalidClientTokenId: The security token included in the request is invalid.\n\tstatus code: 403, request id: <omitted>"
      taskID: Waiting until managed resources have been deleted
      lastUpdateTime: '2022-10-14T03:39:54Z'
```

As you can see the error message contains `InvalidClientTokenId`, which should be matched by the `ERR_INFRA_UNAUTHORIZED` regex https://github.com/gardener/gardener/blob/0a7a79299833ebb78fc6196c1861d271013fc727/pkg/apis/core/v1beta1/helper/errors.go#L61

But as you can see, there is no error code that is added to the `lastErrors`.

**What you expected to happen**:
Similar failure from the  `Waiting until managed resources have been deleted` step to be properly classified with error code as before.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.57.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
