### ISSUE TITLE
Allow extensions to be reconciled at different stages of the shoot control flow

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#6885]
**How to categorize this issue?**

/area usability robustness
/kind enhancement

### Proposal
Right now the `gardenlet` deploys all extension resources after the shoot's `kube-apiserver` is deployed and ready. This behaviour enables most of the use cases regarding extensions but fails to cover cases where the extension should be deployed before the `kube-apiserver`. For example if we want to deploy an auditlogging service this deployment should be up before the `kube-apiserver` and be ready to accept auditlog events. The same is true for the shoot deletion flow - in some cases the extension should be deleted after the `kube-apiserver` is destroyed. I propose that we extend the extensions by adding a lifecycle strategy(see below). This will allow the gardenlet to call different operations on extensions depending on where the specified lifecycle configuration.

#### Goals
 - Extend the extension lifecycle management by adding different "hook points" on which the extension controllers can act
 - Preserve the current functionality and do not introduce breaking changes for existing extensions

### Sample implementation

Extend the [controller resources](https://github.com/gardener/gardener/blob/a36dbb178c844a28904af4570eaaa485bcc4299e/pkg/apis/core/types_controllerregistration.go#L57) so that they contain a `Lifecycle` structure. A sample configuration will look like this:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: my-extension
spec:
  resources:
  - kind: Extension
    type: my-extension
    lifecycle: # only valid for kind Extension
      reconcile: ["before-kube-apiserver", "after-kube-apiserver"]
      hibernate: ["before-kube-apiserver", "after-kube-apiserver"]
      delete: ["before-kube-apiserver", "after-kube-apiserver"]
      migrate: ["before-kube-apiserver", "after-kube-apiserver"]
  deployment:
    deploymentRefs:
    - name: my-extension 
```

An empty `lifecycle` will mean that the current logic is preserved for this extension and it is only reconciled after the `kube-apiserver`. If for example only the `reconcile` flow is specified then we will honour it but will stick to the current logic and default behaviour regarding the `hibernate`, `delete` and `migrate` flows. The `lifecycle` configuration will also be included in the [extension](https://github.com/gardener/gardener/blob/a36dbb178c844a28904af4570eaaa485bcc4299e/pkg/operation/botanist/component/extensions/extension/extension.go#L61) struct.

**P.S.** As far as I can tell right now on hibernation the `reconcile` of extensions is not strictly executed before the scale-down of the controlplane. We can change this in order to satisfy the API proposed above. I am not sure if implications around this can occur but it does not look like a breaking change to me.

cc @rfranzke @plkokanov
