### ISSUE TITLE
Gardenlet might fail to delete seed when runs in a combined garden/seed clusters

### ISSUE THREAD

**Issue by oliver-goetz** [gardener/gardener#6896]
**How to categorize this issue?**

/area robustness
/kind bug

**What happened**:
Deleting the seed cluster in `garden-local` setup failed ([test ref](https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener/6865/pull-gardener-e2e-kind/1584815215726301184)), because gardenlet panicked ([ref](https://storage.googleapis.com/gardener-prow/pr-logs/pull/gardener_gardener/6865/pull-gardener-e2e-kind/1584815215726301184/artifacts/gardener-local-control-plane/pods/garden_gardenlet-9844b75fc-qc85r_1b0fbd55-2f50-4e93-8715-9cb5de39c476/gardenlet/4.log)).

`gardenlet` panicked because `cluster-identity` configmap was not found, when it was restarting during the deletion process.
It might have been restarted by VPA when `cluster-identity` was already deleted.

There is a migration scenario which includes three steps.
- [x] 1. Annotate the content of `cluster-identity`  managed resource of the seed with `resources.gardener.cloud/mode: Ignore` if `cluster-identity` config map is already existing. Switch `cluster-identity` config maps originated by the shoots to immutable. https://github.com/gardener/gardener/pull/7436
- [x] 2. Delete `cluster-identity` config map in the same case. Switch `cluster-identity` config maps originated by gardener-apiserver and the seeds to immutable. https://github.com/gardener/gardener/pull/7569
- [x] 3. https://github.com/gardener/gardener/pull/7851

**What you expected to happen**:
Seed deletion to work robustly in combined garden/seed clusters too.
On seed creation `cluster-identity` configmap could be created only, if it is not existing yet. This should prevent it from being deleted too early. 

**How to reproduce it (as minimally and precisely as possible)**:
Could be reproduced in `garden-local` setup.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.59-dev
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
I woke up a Shoot that was hibernated since longtime. It reports the following error:
```yaml
    - type: SystemComponentsHealthy
      status: 'False'
      lastTransitionTime: '2023-03-13T13:19:17Z'
      lastUpdateTime: '2023-03-13T13:18:17Z'
      reason: ApplyFailed
      message: >-
        deleted object "v1/ConfigMap/kube-system/cluster-identity" because of
        'invalid' update error, and 'delete-on-invalid-update' annotation on
        object or the resource is an immutable ConfigMap/Secret: ConfigMap
        "cluster-identity" is invalid: data: Forbidden: field is immutable when
        `immutable` is set
```
