### ISSUE TITLE
Webhook with `failurePolicy=Ignore` can be problematic

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7013]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What happened**:
Currently we don't consider a webhook with `failurePolicy=Ignore` and `timeoutSeconds < 15s` as problematic:
https://github.com/gardener/gardener/blob/9444417324f2843d3389a28a918239558bd69fb7/pkg/operation/care/constraints.go#L333-L366

However in https://kubernetes.slack.com/archives/C0EG7JC6T/p1650375336872579 it is explained that `failurePolicy: Ignore` does not have effect if the webhook is working and denying the request with a 2XX response code:
> failure policy controls what happens when the webhook fails (times out, or the webhook returns a non-2xx response, or returns invalid content that can't be interpreted as an AdmissionReview, or returns an invalid AdmissionReview response) (edited) 
> not when the webhook successfully returns an AdmissionReview rejecting the API request

Hence, a webhook with `failurePolicy: Ignore` can still deny requests.

Example:

gardener-resource-manager fails to apply the kube-system namespace:
```
{"level":"error","ts":"2022-11-15T08:12:51.224Z","msg":"Reconciler error","controller":"managedresource","controllerGroup":"resources.gardener.cloud","controllerKind":"ManagedResource","ManagedResource":{"name":"shoot-core-namespaces","namespace":"shoot--foo--bar"},"namespace":"shoot--foo--bar","name":"shoot-core-namespaces","reconcileID":"7e780c1c-8d1e-457f-8c1e-2d39b9418005","error":"could not apply all new resources: error during apply of object \"v1/Namespace//kube-system\": admission webhook \"validation.gatekeeper.sh\" denied the request: [constraint-label] This resource must have a label `owner=xxxx`","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/gardener/gardener/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:234"}
```

The webhook spec is:
```yaml
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: # omitted
    service:
      name: gatekeeper-webhook-service
      namespace: gatekeeper
      path: /v1/admit
      port: 443
  failurePolicy: Ignore
  matchPolicy: Exact
  name: validation.gatekeeper.sh
  namespaceSelector:
    matchExpressions:
    - key: admission.gatekeeper.sh/ignore
      operator: DoesNotExist
  objectSelector: {}
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - '*'
    - pods/ephemeralcontainers
    - pods/exec
    - pods/log
    - pods/eviction
    - pods/portforward
    - pods/proxy
    - pods/attach
    - pods/binding
    - deployments/scale
    - replicasets/scale
    - statefulsets/scale
    - replicationcontrollers/scale
    - services/proxy
    - nodes/proxy
    - services/status
    scope: '*'
  sideEffects: None
  timeoutSeconds: 3
```

The corresponding webhook is not marked as problematic.

**What you expected to happen**:
The corresponding webhook to be marked as problematic.

**How to reproduce it (as minimally and precisely as possible)**:
To confirm that a webhook with `failurePolicy=Ignore` can still deny requests:
1. Set the failureMode of webhook `validate-resource-size.gardener.cloud` to Ignore.

2. Prepare a Secret that exceeds the allowed limit for resource size.

3. Try to create the Secret and make sure that the webhook still rejects the requests (even with `failurePolicy=Ignore`)

**Anything else we need to know?**:
```
$ curl -k -XPOST --silent \
 -H "Content-Type: application/json" \
 -d "@admission.json" \
 -H "Accept: application/json" \
https://localhost:2721/webhooks/validate-resource-size -vvv

* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
* We are completely uploaded and fine
< HTTP/2 200
< content-type: text/plain; charset=utf-8
< content-length: 376
< date: Tue, 15 Nov 2022 10:59:53 GMT
<
{"kind":"AdmissionReview","apiVersion":"admission.k8s.io/v1","response":{"uid":"705ab4f5-6393-11e8-b7cc-42010a800002","allowed":false,"status":{"metadata":{},"status":"Failure","message":"secrets \"foo\" is forbidden: maximum resource size exceeded! Size in request: 173282 bytes, max allowed: 50k","reason":"Forbidden","details":{"name":"foo","kind":"secrets"},"code":403}}}
* Connection #0 to host localhost left intact
```

**Environment**:

- Gardener version: v1.59.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
