### ISSUE TITLE
Unify and improve shoot system components handling

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener#7103]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What would you like to be added**:
Whenever users specify a worker pool with `shoot.spec.provider.pools[].systemComponents.allow: true`, related components should be scheduled onto these nodes even when custom and additional taints are specified. Earlier, system components generally tolerated all `NoSchedule` and `NoExecute` taints which has certain drawbacks, e.g. it doesn't work well with [taint based evictions](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions).

Therefore, user defined taints need to be read by Gardener and appropriate tolerations should be added to all relevant system component pods. This can be achieved by adding a new webhook to _Gardener-Resource-Manager_ `SystemComponentsConfig` which holds the desired tolerations in its configuration and adds them to the system component `deployment`s and `statefulset`s.

In addition, the webhook can take care to add the well known nodeSelector `worker.gardener.cloud/system-components: true` which currently must be added by each system component separately ([example](https://github.com/gardener/gardener/blob/7c55e6cd5f5258998d9f3963b2ecc60f541955c8/pkg/operation/botanist/component/metricsserver/metrics_server.go#L304)).

Please note, `DaemonSet`s are excluded by this handling because they must not get the mentioned `nodeSelector`. For them it is still fine and desired to generally tolerate `NoSchedule` and `NoExecute` taints, see [this comment](https://github.com/gardener/gardener/issues/7117#issuecomment-1333870216).

**Example webhook configuration:**

```
apiVersion: resourcemanager.config.gardener.cloud/v1alpha1
kind: ResourceManagerConfiguration
...
webhooks:
  systemComponentsConfig:
    nodeSelector:
      worker.gardener.cloud/system-components: "true"
    tolerations:
    - key: foo
      operator: Equal
      value: bar
      effect: NoExecute
```

**Steps for implementation:**
- Add `SystemComponentsConfig` webhook with above shown configuration
- Configure GRM to enable webhook for shoots and add required tolerations
- Let Gardenlet wait for GRM deployment to be ready before proceeding with Worker deployment to ensure required tolerations are added to components before nodes are rolled out
- Handle special case when tolerations are altered in worker configuration

**Task List:**
- [x] #7204
- [x] #7304
- [x] https://github.com/gardener/gardener-extension-networking-calico/pull/231
