### ISSUE TITLE
Can't see logs from kube-system namespace of shoot cluster

### ISSUE THREAD

**Issue by shaoyongfeng** [gardener/gardener#7114]
**How to categorize this issue?**
/area logging
/kind bug

**What happened**:
I create a shoot on Alicloud and try to get the logs from kube-system namespace of my shoot from operator grafana, 
The logs are not available. 
**What you expected to happen**:
we should be able to see the logs from Loki in grafana
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by vlvasilev** [comment]
This behavior is observed on Alicloud infrastructure only.
The logs from `systemd` are present.
The log agent (Promtail) which scrapes logs from `systemd` and `kube-system` namespace is the same.
It uses the following configuration for scraping pod logs:
```yaml
- job_name: kubernetes-pods-name
  pipeline_stages:
  - cri: {}
  - labeldrop:
    - filename
    - stream
    - pod_uid
  kubernetes_sd_configs:
  - role: pod
    api_server: https://api.shootname.projectname.internal.dev.k8s.ondemand.com
    tls_config:
      server_name: api.shootname.projectname.internal.dev.k8s.ondemand.com
      ca_file: /var/lib/promtail/ca.crt
    bearer_token_file: /var/lib/promtail/auth-token
    namespaces:
      names: ['kube-system']
  relabel_configs:
  - action: replace
    regex: '.+'
    replacement: "gardener"
    source_labels: ['__meta_kubernetes_pod_label_gardener_cloud_role']
    target_label: __meta_kubernetes_pod_label_origin
  - action: replace
    regex: 'gardener'
    replacement: "gardener"
    source_labels: ['__meta_kubernetes_pod_label_resources_gardener_cloud_managed_by']
    target_label: __meta_kubernetes_pod_label_origin
  - action: keep
    regex: 'gardener'
    source_labels: ['__meta_kubernetes_pod_label_origin']
  - action: replace
    regex: ''
    replacement: 'default'
    source_labels: ['__meta_kubernetes_pod_label_gardener_cloud_role']
    target_label: __meta_kubernetes_pod_label_gardener_cloud_role
  - source_labels: ['__meta_kubernetes_pod_node_name']
    target_label: '__host__'
  - source_labels: ['__meta_kubernetes_pod_node_name']
    target_label: 'nodename'
  - action: replace
    source_labels: ['__meta_kubernetes_namespace']
    target_label: namespace_name
  - action: replace
    source_labels: ['__meta_kubernetes_pod_name']
    target_label: pod_name
  - action: replace
    source_labels: ['__meta_kubernetes_pod_uid']
    target_label: pod_uid
  - action: replace
    source_labels: ['__meta_kubernetes_pod_container_name']
    target_label: container_name
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
  - source_labels: ['__meta_kubernetes_pod_label_gardener_cloud_role']
    target_label: gardener_cloud_role
  - source_labels: ['__meta_kubernetes_pod_label_origin']
    replacement: 'shoot_system'
    target_label: origin
```
If I add additional static configuration like this one:
```yaml
 - job_name: static_pod_logs
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      job: static_pod_logs
      host: yourhost
      __path__: /var/log/containers/*.log
``` 
the logs from the containers starts to arrive in Loki.
This means that the pod Kubernetes service discovery(`kubernetes_sd_configs:role:pod`) is not working and the Promtail can't retrieve any metadata for any pod.

After removing the `systemd` part from the configuration and increasing the log vebosity via `-log.level=debug` flag there is no useful logs.
```text
Nov 30 09:05:47 iZgw8469pijl227ykcuvigZ systemd[1]: Starting promtail daemon...
Nov 30 09:05:48 iZgw8469pijl227ykcuvigZ systemd[1]: Started promtail daemon.
Nov 30 09:05:50 iZgw8469pijl227ykcuvigZ promtail[1058890]: level=debug ts=2022-11-30T09:05:50.935539046Z caller=manager.go:195 component=discovery msg="Starting provider" provider=kubernetes/0 subs=[kubernetes-pods-name]
Nov 30 09:05:50 iZgw8469pijl227ykcuvigZ promtail[1058890]: level=info ts=2022-11-30T09:05:50.935626785Z caller=main.go:112 msg="Starting Promtail" version="(version=2.2.1, branch=HEAD, revision=babea82ef)
```
If I made an Alicloud shoot on a GCP seed the logs are missing, too. 

Invalidation of the auth-token result in the following error:
```text
github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:451: Failed to watch *v1.Pod: failed to list *v1.Pod: Unauthorized
```
Giving a false auth-token path gives:
```text
"https://api.ustjpy0xnx.i330716.internal.dev.k8s.ondemand.com/api/v1/namespaces/kube-system/pods?fieldSelector=spec.nodeName%3DiZgw8e9pef55s56prrp9ygZ&limit=500&resourceVersion=0": unable to read bearer token file /var/lib/promtail/auth-token
```

Running a curl command inside the node gives an empty result:
```console
curl -H "Authorization: Bearer ${TOKEN}" -k "https://api.ustjpy0xnx.i330716.internal.dev.k8s.ondemand.com/api/v1/namespaces/kube-system/pods?fieldSelector=spec.nodeName%3DiZgw8e9pef55s56prrp9ygZ&limit=500&resourceVersion=0"{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "577478"
  },
  "items": []
}
```

Interesting, here both `z` characters are capitalized and the node name does not consist of a capital letter!
If I change the `iZgw8e9pef55s56prrp9ygZ` with `izgw8e9pef55s56prrp9ygz` in the above URL it returns a non-empty result. Now the question is how Promtail gets the hostname with capitalized `z` letters.
```console
echo $HOSTNAME
iZgw8e9pef55s56prrp9ygZ
```
```console
hostname
iZgw8e9pef55s56prrp9ygZ
```
```console
uname -n
iZgw8e9pef55s56prrp9ygZ
```

To fix the issue we must set the env `HOSTNAME`  to lower case.
For this purpose, lets change the line from the Promtail service
```text
ExecStartPre=/bin/sh -c systemctl set-environment HOSTNAME=$(hostname)
```
with
```text
ExecStartPre=/bin/sh -c systemctl set-environment HOSTNAME=$(echo -n $(hostname) | tr '[:upper:]' '[:lower:]')
```
Now the logs from `kube-system` star to arrive in the Loki
