### ISSUE TITLE
Set image tags in new releases

### ISSUE THREAD

**Issue by fynluk** [gardener/gardener#7177]
**How to categorize this issue?**
  
  /area dev-productivity
  /area quality
  /area usability
  /kind enhancement
  
  **What would you like to be added**:
  At the moment many chart values contain the image tag latest. For example `charts/gardener/gardenlet/values.yaml` contains:
  ```yaml
  image:
    repository: eu.gcr.io/gardener-project/gardener/gardenlet
    tag: latest
    pullPolicy: IfNotPresent
  ```
  Wouldn't it be better, if we set the image tag corresponding to the real release 
  
  
  **Why is this needed**:
  I had the problem, that I used the gardenlet charts with my own values. After the `v1.59` upgrade I run into issues because I got the latest image (I missed to update my values). 
  
  I think in the future we could avoid these mistakes by pinning the correct image tag and not latest.
