### ISSUE TITLE
provider-local: failed to create snapstore from configured storage provider: mkdir <omitted>: operation not permitted

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7236]
**How to categorize this issue?**

/area dev-productivity
/kind bug

**What happened**:
I am following https://github.com/gardener/gardener/blob/master/docs/development/getting_started_locally.md.
I created a local Shoot:
```
% kubectl create -f example/provider-local/shoot.yaml
```

The creation is stuck waiting etcd-main pod to come up:
```yaml
    lastErrors:
    - description: "task \"Waiting until main and event etcd report readiness\" failed:
        1 error occurred:\n\t* Error while waiting for Etcd shoot--local--local/etcd-main
        to become ready: retry failed with context deadline exceeded, last error:
        not enough ready replicas (0/1)\n\n"
      lastUpdateTime: "2022-12-19T12:43:08Z"
      taskID: Waiting until main and event etcd report readines
```

```
% k -n shoot--local--local get po
NAME            READY   STATUS    RESTARTS   AGE
etcd-events-0   2/2     Running   0          27m
etcd-main-0     1/2     Running   0          6m8s
```

```
% k -n shoot--local--local logs etcd-main-0 backup-restore

time="2022-12-19T12:46:39Z" level=error msg="Failed initialization: error while restoring corrupt data: failed to create snapstore from configured storage provider: mkdir 59eb917e-0551-4654-ac02-69c3086be3c7/shoot--local--local--29262d84-5dd4-426b-aa9a-e97fee14dbe9: operation not permitted" actor=backup-restore-server
time="2022-12-19T12:46:39Z" level=info msg="Responding to status request with: Failed" actor=backup-restore-server
time="2022-12-19T12:46:39Z" level=info msg="Updating status from Failed to New" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Responding to status request with: New" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Received start initialization request." actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Updating status from New to Progress" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Setting status to : 503" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Validation failBelowRevision: " actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Validation mode: full" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=error msg="Failed initialization: error while restoring corrupt data: failed to create snapstore from configured storage provider: mkdir 59eb917e-0551-4654-ac02-69c3086be3c7/shoot--local--local--29262d84-5dd4-426b-aa9a-e97fee14dbe9: operation not permitted" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Responding to status request with: Failed" actor=backup-restore-server
time="2022-12-19T12:46:40Z" level=info msg="Updating status from Failed to New" actor=backup-restore-server
```

**What you expected to happen**:
No such issues.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
@plkokanov reported that he also hits this issue and it appeared after https://github.com/gardener/gardener/pull/6939 for him (cc @vpnachev).

**Environment**:

- Gardener version: 44c7c5613ed79a618900a5bfacd3d812224fb3e1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
