### ISSUE TITLE
`make start-gardenlet` fails for a new Seed

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7272]
**How to categorize this issue?**

/area dev-productivity
/kind bug
/kind regression

**What happened**:
I created a new Seed in my local setup. `make start-gardenlet` failed for it with:
```
% make start-gardenlet SEED_NAME=foo

priorityclass.scheduling.k8s.io/gardener-system-critical created
error: failed to create token: serviceaccounts "gardenlet" not found
make: *** [start-gardenlet] Error 1
```

The script tries to find the garden/gardenlet ServiceAccount:
https://github.com/gardener/gardener/blob/6d18b043a3852034e571ccc9f5e265db1923fd45/hack/local-development/start-gardenlet#L172

https://github.com/gardener/gardener/pull/7108 modified the ServiceAccount, Role and RoleBinding resource to do no longer hard-code the namespace but to use `{{ .Release.Namespace }}`. 
Current the `helm template` invocations in the start-gardenlet script do not pass a namespace, hence all gardenlet resources are created in the default namespace:
```yaml
---
# Source: gardenlet/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardenlet
  namespace: default
  labels:
    app: gardener
    role: gardenlet
    chart: "gardenlet-0.1.0"
    release: "gardenlet"
    heritage: "Helm"
```

**What you expected to happen**:
`make start-gardenlet` to work for a new Seed as before.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 6d18b043a3852034e571ccc9f5e265db1923fd45
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
