### ISSUE TITLE
Implement `Extension` extension resource (+ Cert-Service extension)

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#730]
Part of #308.

As we have proposed in [GEP-1](https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md) we want to have an `Extension` extension resource that is reconciled by an external controller running in the seed. The `Extension` resources does not have any dependent tasks in the shoot flow, however, it's successful reconciliation is required for the whole shoot flow to terminate successfully. It should create the necessary networks, security groups, <iaas resources>, ... needed for a shoot cluster.

# Implementation Proposal

For now, let's begin with the recently added `cert-manager`/`cert-broker` deployments (#509), move them out into an extension controller (named `cert-service`?!), and implement the `Extension` resources for this example.

As discussed, let's go ahead with this first version of the `Extension` resource:

```yaml
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: <some-name>
  namespace: shoot--dev--shoot1
spec:
  type: <some-type>
  providerConfig:
    <some-type-specific-blob>
```

Probably, we also need to extend the `ControllerRegistration` resource: We need to allow to specify for `Extension` resources whether specific configuration is required in the shoot manifest, or whether it should be created for all shoots even when not configured there.

What about:

```yaml
apiVersion: core.gardener.cloud/v1alpha1
kind: ControllerRegistration
metadata:
  name: cert-service
spec:
  resources:
  - kind: Extension
    type: <some-type>
    global: true
```

The `.spec.resources[].global` field is only allowed if `kind==Extension`. If `global= true` then the `Extension` resource of type `<some-type>` will be always written in the shoot flow. If `global=false` then Gardener requires configuration for the `<some-type>` extension in the shoot specification in order to write the `Extension` resource.

# Definition of Done

- [x] Have a `cert-service` extension controller ready that deploys the `cert-manager` once into the seed, and the `cert-broker` next to every shoot control plane [https://github.com/gardener/gardener-extensions/pull/47, ✅]
- [ ] The `certificate-management` secret in the garden cluster is no longer needed because its content are passed to the `cert-service` extension directly.
- [ ] All the cert-manager related charts in https://github.com/gardener/gardener/tree/master/charts/seed-bootstrap/charts/cert-manager are moved out of the `gardener` repository.
- [ ] The cert-broker related chart in https://github.com/gardener/gardener/tree/master/charts/seed-controlplane/charts/cert-broker is moved out of the `gardener` repository.
- [ ] The needed RBAC roles for cert-broker (deployed in https://github.com/gardener/gardener/tree/master/charts/shoot-core/charts/cert-broker) are continuously reconciled by the `cert-service` component itself.
- [ ] The `CertManagement` feature gate has been removed.
- [ ] The `ControllerRegistration` resources has been extended as described above.
- [ ] The shoot reconciliation/deletion flow has been adapted to write `Extension` resources (probably after the control plane has been created).
- [ ] Documentation has been added to the `docs/extensions` folder that describes the contract between Gardener and the `Extension` resource.
