### ISSUE TITLE
Extend Shoot specification to expose created DNS records

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#731]
Right now, Gardener creates one DNS record for the API server of a Shoot: `api.<shoot-domain>`.
In case the `nginx-ingress` addon is enabled, it also creates a second wildcard DNS record for the ingress controller: `*.ingress.<shoot-domain>`.

Some users want to change `*.ingress` to something else, others just want to programmatically identify their API server/ingress domain.

Let's extend the shoot specification to support both scenarios:

1. Add `apiserverRecord` to `.spec.dns`:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-aws
  namespace: garden-dev
spec:
  ...
  dns:
    provider: aws-route53
    domain: johndoe-aws.garden-dev.example.com
    apiserverRecord: api.johndoe-aws.garden-dev.example.com
```

It should be optional and defaulted to `api.<shoot-domain>` if not specified.

2. Add `wildcardDNSRecords` to `.spec.addons.nginx-ingress`:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-aws
  namespace: garden-dev
spec:
  ...
  addons:
    nginx-ingress:
      enabled: true
      loadBalancerSourceRanges: []
      wildcardDNSRecords:
        standard: ingress.johndoe-aws.garden-dev.example.com
```

It should be optional and defaulted to `ingress.<shoot-domain>` if not specified.

Both new fields should be validated to be proper DNS subdomains.

**Comment by timuthy** [comment]
We might still need to expose the API dns entry / entries for a Shoot cluster when it comes to extensibility. Some extension controllers need to generate a Kubeconfig for Shoot clusters for which they need to know the API endpoint url.

Additionally, is the `standard` dns entry enough or is an extension controller also supposed to know the `internal` domain?

```yaml
...
dns:
    provider: aws-route53
    domain: johndoe-aws.garden-dev.example.com
    apiServer:
    - record: api.johndoe-aws.garden-dev.example.com
      type: external
    - record: api.internal.johndoe-aws.garden-dev.example.com
      type: internal
```

What is your opinion?
