### ISSUE TITLE
`ManagedResource`s with a failing `ResourcesApplied` condition produce a confusing `SystemComponentsHealthy` condition in `Shoot`s

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#7451]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:

A `Shoot` for which the `ResourcesApplied` condition of a `ManagedResource` is `False` can produce a confusing `SystemComponentsHealthy` condition in the `Shoot`:

```yaml
    - type: SystemComponentsHealthy
      status: 'False'
      lastTransitionTime: '2023-02-06T09:29:55Z'
      lastUpdateTime: '2023-02-05T09:31:04Z'
      reason: ChecksPending
      message: >-
        The health checks have not yet been executed for the current set of
        resources.
```

Instead, the message should be more clear indicating what the problem with the system components is.

**Details**:

When looking at the `ManagedResource`s, we can see the following conditions:

```yaml
  conditions:
  - lastTransitionTime: "2023-02-01T17:32:08Z"
    lastUpdateTime: "2023-02-01T17:32:08Z"
    message: The health checks have not yet been executed for the current set of resources.
    reason: ChecksPending
    status: Unknown
    type: ResourcesHealthy
  - lastTransitionTime: "2023-02-01T17:32:08Z"
    lastUpdateTime: "2023-02-01T17:32:08Z"
    message: Checks have not yet been executed for the current set of resources.
    reason: ChecksPending
    status: Unknown
    type: ResourcesProgressing
  - lastTransitionTime: "2023-02-06T12:30:41Z"
    lastUpdateTime: "2023-02-01T17:32:08Z"
    message: 'error during apply of object "networking.k8s.io/v1/IngressClass/default/nginx":
      IngressClass.networking.k8s.io "nginx" is invalid: spec.controller: Invalid
      value: "k8s.io/nginx": field is immutable'
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
```

`gardenlet` could consider the message of `ResourcesApplied` when computing the result of the `SystemComponentsHealthy` condition.

**Why is this needed**:
Improve ops productivity.
