### ISSUE TITLE
CRDs with a conversion webhook and a history of multiple stored versions can break reconciliation flow

### ISSUE THREAD

**Issue by hendrikKahl** [gardener/gardener#7471]
**How to categorize this issue?**

/area robustness
/kind enhancement

**What would you like to be added**:

Add a (generic) constraint or any other suitable mechanism to inform operators as well as end-users of a cluster about potentially problematic CRDs with conversion webhooks.

Maybe it would also be possible, to suggest a solution to the end-user based on the [official documentation](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version).

**Why is this needed**:

In a scenario where a CRD adds support for a new version and switches `spec.versions.storage` field to it (i.e. `v1beta1` to `v1`)  existing objects are not migrated in etcd ([ref](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#previous-storage-versions)). 

This creates a mismatch between the requested and stored version for all clients (kubectl, KCM, ...). When the CRD also declares the usage of a conversion webhook, it gets called whenever a client requests information about a resource that still exists in the old version.

If the CRD is created by an end-user, the webhook runs on the shoot-side whereas controllers / kapi-server run separated as part of the control-plane. For the webhook to be reachable a working VPN connection seed -> shoot is essential. 

In scenarios where the VPN connection is broken, KCM eventually stops its garbage collection as that requires to list `v1. PartialObjectMetadata` for everything to build a dependency graph. Without KCM GC, managed resources get stuck during update/rollout. 

A simple example is when a user upgrades the failure tolerance of a shoot to node or zone. That will cause the VPN deployments to be replaced by statefulsets. However, as the VPN connection is broken upon teardown of the deployment, garbage collection will fail leading to a situation that is stuck until an operator manually tackles it.

I'm not sure, if there is a better solution other than raising awareness based on a CRDs `status.storedVersions` and recommending to upgrade existing objects to the current stored version.

<details>
<summary>CRD samples for testing</summary>

Based on the CRD examples used within the K8s documentation. Deploy the CRD with `storage: true` for `v1beta1` along with a dummy webhook service and a corresponding resource.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.example.com
spec:
  group: example.com
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          hostPort:
            type: string
  - name: v1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          host:
            type: string
          port:
            type: string
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1","v1beta1"]
      clientConfig:
        service:
          namespace: default
          name: demo-converter
          path: /crdconvert
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
    - ct
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: demo-converter
spec:
  selector:
    app: does-not-exist
  ports:
  - port: 443
    targetPort: 443
---
apiVersion: example.com/v1beta1
kind: CronTab
metadata:
  name: demo-crontab
  namespace: default
hostPort: demo:443
```

Then, switch `storage` to `v1` version and try querying the `crontab` resource.

When restarting KCM, garbage collection will no longer work. Deleting a deployment for example will orphan the replicaset and pods.

</details>
