### ISSUE TITLE
Enable CMEK Encrypted Shoot Worker Node Boot Disks

### ISSUE THREAD

**Issue by aabond** [gardener/gardener#7496]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
We need the ability to deploy Gardener Shoot Clusters to GCP where the shoot worker node root volumes (node boot disk) are encrypted using Customer Managed Encryption Keys (CMEK).  It appears that we can configure additional PVCs to use CMEK by configuring an appropriate storage class.  This is our primary feature request.  

Additionally, once shoot clusters can be configured to be deployed with CMEK on the node boot disks, we'd like to also be able to deploy managed seeds that are also deployed with CMEK encrypted node boot disks.  

**Why is this needed**:
Customer requirements.

**Comment by himanshu-kun** [comment]
Current proposal (Subject to changes after testing)

############ *Existing worker section* ##############

```yaml
workers:
  - name: worker-xoluy
    machine:
      type: n1-standard-4
    minimum: 2
    maximum: 2
    volume:
      size: 50Gi
      type: pd-standard
      encrypted: true
    dataVolumes:
    - name: kubelet-dir1
        type: SCRATCH 
        size: 25Gi
        encrypted: false
    -   name: kubelet-dir2
        type: SCRATCH 
        size: 25Gi
        encrypted: false
    - name: kubelet-dir3
        type: pd-ssd
        size: 25Gi
        encrypted: false
    - name: kubelet-dir4
        type: pd-ssd
        size: 25Gi
        encrypted: false
    providerConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: WorkerConfig
      volume:
        interface: NVME
      serviceAccount:
        email: foo@bar.com
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
    zones:
      - europe-west1-b

```

############ *New proposed worker section* ##############

```yaml
workers:
  - name: worker-xoluy
    machine:
      type: n1-standard-4
    minimum: 2
    maximum: 2
    volume:
      size: 50Gi
      type: pd-standard
      encrypted: true
    dataVolumes:
      - name: scratch-dir1
        type: SCRATCH
        size: 25Gi
        encrypted: true
      - name: scratch-dir2
        type: SCRATCH
        size: 25Gi
        encrypted: false
      - name: pd-dir1
        type: pd-ssd
        size: 25Gi
        encrypted: true
      - name: pd-dir2
        type: pd-ssd
        size: 25Gi
        encrypted: false
    providerConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: WorkerConfig
      volume: # deprecated because currently it decides the parameters
      # for data volumes but not root volume

      bootVolume: #(for root volume)
         encryption:
            kmsKeyName: abc1
            kmsKeyServiceAccount: efg1

      dataVolumes: #(for data volumes)
        - name: scratch-dir1
          encryption:
            kmsKeyName: abc1
            kmsKeyServiceAccount: efg1 #(optional)
          interface: NVME
        - name: pd-dir1
          encryption:
            kmsKeyName: abc2
            kmsKeyServiceAccount: efg2 #(optional)
          interface: SCSI

      serviceAccount:
        email: foo@bar.com
        scopes:
          - https://www.googleapis.com/auth/cloud-platform
    zones:
      - europe-west1-b
```
