### ISSUE TITLE
provide "real" user in the kubeconfig.yaml instead of the technical user "admin"

### ISSUE THREAD

**Issue by freegroup** [gardener/gardener#75]
The user can download the `kubeconfig.yaml` in the gardener UI to access the cluster
via the `kubectl` CLI. One problem with the downloaded kubeconfig is that the user inside
is always a generic `admin`user and not the user which has logged in to the Gardener.

```yaml
---
apiVersion: v1
kind: Config
current-context: shoot-garden-core-cpet
clusters:
- name: shoot-garden-core-cpet
  cluster:
    certificate-authority-data: LS0tLS......tLS0tLQo=
    server: https://api.....sapcloud.io
contexts:
- name: shoot-garden-core-cpet
  context:
    cluster: shoot-garden-core-cpet
    user: shoot-garden-core-cpet
users:
- name: shoot-garden-core-cpet
  user:
    client-certificate-data: LS0tLS1CRU........0tCg==
    client-key-data: LS0tLS1C........S0tLQo=
- name: shoot-garden-core-cpet-basic-auth
  user:
    username: admin
    password: XEO.......uEqO3
 ```

In this case, it is not possible to track changes of deployments via **audit-logging**.
How to get the user which has initiated the deployment?

I want use the official https://cloud.google.com/kubernetes-engine/docs/how-to/audit-logging
