### ISSUE TITLE
Unable to establish vpn tunnel

### ISSUE THREAD

**Issue by acumino** [gardener/gardener#7583]
**How to categorize this issue?**

/area control-plane
/kind regression

**What happened**:
For OpenStack shoots, reconciliation fails because vpn-shoot tunnel connection can't get established. In older version of gardener netpol for vpn-seed-server was like this:
```
spec:
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: kubernetes
          gardener.cloud/role: controlplane
          role: apiserver
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kubernetes
          gardener.cloud/role: controlplane
          role: apiserver
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
          gardener.cloud/role: monitoring
          role: monitoring
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: istio-ingressgateway
          istio: ingressgateway
  podSelector:
    matchLabels:
      app: vpn-seed-server
      gardener.cloud/role: controlplane
  policyTypes:
  - Ingress
  - Egress
```

Ingress traffic was allowed to vpn-seed-server pods from all namespace having labels :
```
app: istio-ingressgateway
istio: ingressgateway
```

In gardener version 1.65 network policy for ingress from `istio` to `vpn-seed-server` look something like this :
```
 ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-ingress
      podSelector:
        matchLabels:
          networking.resources.gardener.cloud/to-all-shoots-vpn-seed-server-tcp-1194: allowed
    ports:
    - port: 1194
      protocol: TCP
  podSelector:
    matchLabels:
      app: vpn-seed-server
  policyTypes:
  - Ingress
```
In the above case, ingress from only ` istio-ingress` namespace is allowed. But in OpenStack system ingress should be allowed from `istio-ingress-handler-converged-cloud-internet` namespace also. 
Because ingress is not possible from `istio-ingress-handler-converged-cloud-internet` tunnel connection can't get established

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: `v.1.65`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
