### ISSUE TITLE
Misleading error message when shoot tries to use unconfigured OS

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#7595]
**How to categorize this issue?**

/area ops-productivity usability
/kind bug

**What happened**:
When I try to create a shoot cluster with operating system that is not specified in the cloud profile, the error message is misleading. It says that the selected OS/version does not support the CPU architecture, the kubelet version constraint or the image is expired, but how it could be when there is no such image. 

**What you expected to happen**:
The error message should be more clear in this case and it just have to reject the shoot create/update request with error message that there is no such OS image.

**How to reproduce it (as minimally and precisely as possible)**:
1. Try to create a shoot cluster with the following config
```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-foo
  name: bar
spec:
  provider:
    workers:
      - machine:
          image:
            name: foobar
            version: 1.2.3
          architecture: amd64
```
2. Check the create request fails with
```
shoots.core.gardener.cloud "bar" is forbidden: [spec.provider.workers[0].machine.image: Invalid value: core.ShootMachineImage{Name:"foobar", ProviderConfig:(*runtime.RawExtension)(nil), Version:"1.2.3"}: machine image '&{foobar nil 1.2.3}' does not support CPU architecture 'amd64', is expired or does not match kubelet version constraint; valid machine images are: []]
```

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.65.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
