### ISSUE TITLE
Shoot hibernation fails when there is webhook working on `delete pods` requests

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#7614]
**How to categorize this issue?**

/area cost ops-productivity quality usability
/kind bug

**What happened**:
Shoot hibernation is failing on the step `Hibernating control plane` as there are still running pods.
In general, this should not be a problem, but in this case the KCM is always failing to delete the pods due to webhook working on `delete pods` (does not matter if the kube-system namespace is excluded or not) and the pods backing the webhook are already deleted. 

**What you expected to happen**:
One or more of the following
- shoot owners to be provided with option the pods backing the webhooks to be deleted last
- gardener to not wait all running pods in the cluster to be deleted
- shoot hibernation constraints to be enhanced and detect webhooks catching `delete pods` requests as problematic

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a shoot cluster
2. Deploy a pod, e.g. `k -n default run alpine --image=alpine`
3. Deploy the following webhook
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: block-hibernation
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lVS0RhRkp0Ym5lWmFZcGVURzdFamVscURuRS9Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF4TVVZMkV0WW14dlkyc3RhR2xpWlhKdVlYUnBiMjR3SGhjTk1qTXdNekE0TURnMApOekF3V2hjTk1qZ3dNekEyTURnME56QXdXakFmTVIwd0d3WURWUVFERXhSallTMWliRzlqYXkxb2FXSmxjbTVoCmRHbHZiakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNbWtWS2ZEUTVrdVZBcy8KbnB3Z21CUDgydVVrZTVwMjUzUzBDUGlsVllYcExkTjdaTzRyQ1Y0WGU2c2tFOS91RnlNNS84eUdBckYvNlZwdgplcG9LTUswbzJKdWplNDJhWWF4N0pMbFlDV0RNK0pSamc5eWZhTjhvQU1hNXlrR3ZXQ0JwTW5PWXZwY1QrL2xoCmxkblFZd3pXUi90WWJRbW81b2tLNmhheER4M21RbU1Bb0hISHZiQXdZRlpMTHMyY1dyc01jcHNzb2loVHhpWnQKUUYvSFFlb2YwRERFcEpUMHRWUWpwNEhJQnArQVFtVHZiODVaUGczLytuZ2FGclAxWGFlWVg3UkxXcUpkL0hjNwpvQjRMZi9FeFRxbVBWYzdQQkNhc3VXOGF1SCsxbUIxendMR0lSTGNuM2pUQVRBR3IwWHJvNWQ1ajNFODVMcGc0CmMyUkZoNWtDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKSFFZRFZSME9CQllFRkw4REZ5UGQ4Vm0vQ0Y1aTd4b2dST1FzQmE1a01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUJlSERRSHZHREdCTlAxTE9JaFZnTDFZT1NYQWdPWWUxVFAyNUZwZzdsbGJuWTA1YWhaRzkwbTI3cFJNdHBECkU1Z3N0cXhsUE9LM1Q2Z0xEUmhHVVhPT05CQ2gveU1kVDFhZ3IxMTZrQ216aUcwNDFicFpNTWNNOU5uKzdDMWoKM1NWQ0dnQXdBemtwekNTSmRsbDBZNzluWlpua2lJakZOcHhBRTczRnltQkZLRGtLRG5zZVZhckNHa1dMWndyQgo5aklZc0k3SGlrenVYd3o5THJlVC8xYW5GdVd5b21JTDUyeDBiRldabmovVXVVYkZhYU00RW5jZm54d3ZGUzlJCjk4L0R4Y1VPT1ovbDZaWENTWmFsY3h2UkhFb3lQWHhvQ21hYks3ZDlQZFNHWXZKYzNtUHA5SVhkeG1Ca01KZFEKYWVreDM3bnV2RVBiSitlVVdWajlkKzdWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: block-hibernation
      path: /validate/fail
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate.block.hibernation
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - block-hibernation
  objectSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - pods
    scope: '*'
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10
```
4. Trigger shoot hibernation
5. Make sure it fails on the step `Hibernating control plane` due to still existing running pods.

**Anything else we need to know?**:
The step waiting all pods to be deleted was introduced with #1638, maybe it can be also improved to not wait pods, but just the nodes to be deleted, which might also fail if it is done gracefully as node draining also tries to delete pods. 

**Environment**:

- Gardener version: v1.65.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
