### ISSUE TITLE
Shoot hibernate/wake-up is blocked by admission controller working on `leases` even when failurePolicy=Ignore and timeout=10s

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#7625]
**How to categorize this issue?**

/area ops-productivity
/kind bug

**What happened**:
Gardener has not disallowed hibernation for a shoot cluster configured with admission webhook affecting `leases` with failurePolicy=Ignore and timeout=10s.

Some controllers, like KCM, are doing their leader election on leases in the kube-system namespace. As a client, KCM acquire the leader election with longer timeout, however it maintains it with timeout of 5s and this is not enough, when there is such webhook and it is not available. In this case, KCM just logs

```
E0312 14:57:22.228821       1 leaderelection.go:367] Failed to update lock: Put "https://kube-apiserver/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Sometimes the hibernation might fail, depending on how quickly prerequisites for the hibernation will be executed (like all pods to be deleted). If the endpoints for the webhook were not removed from the cluster, waking up the cluster also fails because KCM cannot start and without running KCM:
- no machine can join the cluster
- no pods for the webhook backend are created

**What you expected to happen**:
The hibernation to not be allowed when there is a webhook affecting `leases` in the kube-system namespace even when the failurePolicy=Ignore and timeout=10s.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot cluster.
2. Create a dummy webhook backend
```bash
kubeclt create namespace block-hibernation
kubectl -n block-hibernation create deployment webhook --image=nginx
kubectl -n block-hibernation expose deployment webhook --port 10443 --target-port 10443
```
3. Create the following webhook
```yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: block-hibernation
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lVS0RhRkp0Ym5lWmFZcGVURzdFamVscURuRS9Nd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF4TVVZMkV0WW14dlkyc3RhR2xpWlhKdVlYUnBiMjR3SGhjTk1qTXdNekE0TURnMApOekF3V2hjTk1qZ3dNekEyTURnME56QXdXakFmTVIwd0d3WURWUVFERXhSallTMWliRzlqYXkxb2FXSmxjbTVoCmRHbHZiakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNbWtWS2ZEUTVrdVZBcy8KbnB3Z21CUDgydVVrZTVwMjUzUzBDUGlsVllYcExkTjdaTzRyQ1Y0WGU2c2tFOS91RnlNNS84eUdBckYvNlZwdgplcG9LTUswbzJKdWplNDJhWWF4N0pMbFlDV0RNK0pSamc5eWZhTjhvQU1hNXlrR3ZXQ0JwTW5PWXZwY1QrL2xoCmxkblFZd3pXUi90WWJRbW81b2tLNmhheER4M21RbU1Bb0hISHZiQXdZRlpMTHMyY1dyc01jcHNzb2loVHhpWnQKUUYvSFFlb2YwRERFcEpUMHRWUWpwNEhJQnArQVFtVHZiODVaUGczLytuZ2FGclAxWGFlWVg3UkxXcUpkL0hjNwpvQjRMZi9FeFRxbVBWYzdQQkNhc3VXOGF1SCsxbUIxendMR0lSTGNuM2pUQVRBR3IwWHJvNWQ1ajNFODVMcGc0CmMyUkZoNWtDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcKSFFZRFZSME9CQllFRkw4REZ5UGQ4Vm0vQ0Y1aTd4b2dST1FzQmE1a01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUJlSERRSHZHREdCTlAxTE9JaFZnTDFZT1NYQWdPWWUxVFAyNUZwZzdsbGJuWTA1YWhaRzkwbTI3cFJNdHBECkU1Z3N0cXhsUE9LM1Q2Z0xEUmhHVVhPT05CQ2gveU1kVDFhZ3IxMTZrQ216aUcwNDFicFpNTWNNOU5uKzdDMWoKM1NWQ0dnQXdBemtwekNTSmRsbDBZNzluWlpua2lJakZOcHhBRTczRnltQkZLRGtLRG5zZVZhckNHa1dMWndyQgo5aklZc0k3SGlrenVYd3o5THJlVC8xYW5GdVd5b21JTDUyeDBiRldabmovVXVVYkZhYU00RW5jZm54d3ZGUzlJCjk4L0R4Y1VPT1ovbDZaWENTWmFsY3h2UkhFb3lQWHhvQ21hYks3ZDlQZFNHWXZKYzNtUHA5SVhkeG1Ca01KZFEKYWVreDM3bnV2RVBiSitlVVdWajlkKzdWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook
      namespace: block-hibernation
      path: /validate/fail
      port: 10443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: validate.block.hibernation
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - coordination.k8s.io
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - leases
    scope: '*'
  sideEffects: NoneOnDryRun
  timeoutSeconds: 10
```
5. See that the shoot constraint `HibernationPossible` is not set to `False`.
6. Hibernate the cluster and see it eventually fails to hibernate (for example, there are still `Running` pods and KCM already lost its leadership).
7. Wake-up the cluster and see it eventually fails to wake-up (the Endpoint for the webhook backend need to have some pod IPs, otherwise API server fails early and the 5s timeout does not occur).

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.66.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
