### ISSUE TITLE
Cannot set https scheme for external alertmanager in mutual TLS setup

### ISSUE THREAD

**Issue by namsral** [gardener/gardener#7653]
My best guess is that the monitoring bootstrap implementation is missing the option to change the default `scheme` from _http_ to _https_. This is required for mutual TLS to work and is preferable when using basic auth when configuring an external alertmanager.

/area monitoring
/kind bug

**What happened**: Alerts sent to an external Alertmanager using a mutual TLS setup fail because Prometheus is bootstrapped with the default http scheme thus prefixing the alertmanager endpoint with the wrong scheme, namely `http://<host>:<port>`.

Example alerting-auth secret used from [docs][1]:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    gardener.cloud/role: alerting
  name: alerting-auth
  namespace: garden
data:
  auth_type: base64(certificate)
  url: base64(external.alertmanager.foo)
  ca.crt: base64(ca)
  tls.crt: base64(certificate)
  tls.key: base64(key)
```

The above secret is used to bootstrap a configuration file for Prometheus in shoot clusters, resulting in the following errornous Alertmanagers endpoint: `http://external.alertmanager.foo:9093/api/v2/alerts`

**What you expected to happen**: For the scheme in the endpoint to be _https_ instead of _http_.

**How to reproduce it (as minimally and precisely as possible)**:

Create the alerting-auth secret from the example [docs][1] with a standard mTLS setup.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.61.6
- Kubernetes version (use `kubectl version`): v1.23.6
- Cloud provider or hardware configuration: OpenStack
- Others: Deployed with [gardener-community/gardener-charts][2]

[1]: https://github.com/gardener/gardener/blob/cf02f5dd454ea63e8389939f3eedc45bc8760844/docs/monitoring/alerting.md#remote-alertmanager-examples
[2]: http://github.com/gardener-community/gardener-charts/
