### ISSUE TITLE
gardenlet: VolumeSnapshot cleanup mechanism does no longer work

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7750]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
https://github.com/gardener/gardener/pull/5104 introduced deletion of VolumeSnapshots and VolumeSnapshotContents explicitly in gardenlet.
Currently this mechanism does no longer work as the provider-extension upgraded to external-snapshotter@v6 and the VolumeSnapshot and VolumeSnapshotContent resource are no longer served by in `v1beta1`. They are no served in `v1` only. Ref https://github.com/gardener/gardener-extension-provider-aws/pull/666

```
 % k get volumesnapshots.v1.snapshot.storage.k8s.io
No resources found in default namespace.
% k get volumesnapshots.v1beta1.snapshot.storage.k8s.io
error: the server doesn't have a resource type "volumesnapshots"
```

**What you expected to happen**:
gardenlet to clean up VolumeSnapshots in `v1`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an aws Shoot

2. Create a VolumeSnapshot

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: gardener-extension-admission-aws
  namespace: default
  annotations:
  labels:
    app.kubernetes.io/name: gardener-extension-admission-aws
    app.kubernetes.io/instance: release-name
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gardener-extension-admission-aws
    app.kubernetes.io/instance: release-name
  ports:
  - port: 443
    protocol: TCP
    targetPort: 10250
```

3. Make sure the VolumeSnapshot won't be deleted by gardenlet

In https://github.com/gardener/gardener/blob/5abed1bfedd6f2188e5dcec9af161d1b5c286236/pkg/utils/kubernetes/client/client.go#L394-L399 if you remove `meta.IsNoMatchError(err) || `, then you will see that gardenlet is failing with

```yaml
lastErrors:
  - description: "task \"Cleaning Kubernetes resources\" failed: 2 errors occurred:\n\t*
      no matches for kind \"VolumeSnapshot\" in version \"snapshot.storage.k8s.io/v1beta1\"\n\t*
      no matches for kind \"VolumeSnapshotContent\" in version \"snapshot.storage.k8s.io/v1beta1\"\n\n"
    lastUpdateTime: "2023-04-04T15:15:23Z"
    taskID: Cleaning Kubernetes resources
```

Hence, currently gardenlet cannot delete VolumeSnapshots and as the no match error is ignored, it is failing silently.

**Anything else we need to know?**:
We should update our code to use `v1` to delete the VolumeSnapshots.

**Environment**:

- Gardener version: v1.67.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
