### ISSUE TITLE
Shoot deletion can occasionally fail with: task "Cleaning Kubernetes resources" failed: namespaces "<some-ns>" not found

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#7762]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
We noticed several Shoot deletions failed with:
```yaml
  lastErrors:
    - description: "task \"Cleaning Kubernetes resources\" failed: 1 error occurred:\n\t* namespaces \"<some-ns>\" not found\n\n"
      taskID: Cleaning Kubernetes resources
      lastUpdateTime: '2023-04-06T07:09:20Z'
```

The issue is described in the steps to reproduce. In short, in the `Cleaning Kubernetes resources` step, gardenlet cleans up and finalizes (if needed) the most common K8s resources. But this step it can be the case that while it waits a resource to be gone (for example Service) a new resource (for example Pod) to be created while the `Cleaning Kubernetes resources` step already cleaned up this resource kind (Pods, the step ensured already that all Pods are gone). In such case, the `Cleaning Kubernetes resources` step can succeed but a resource with finalizer to still exist in a Namespace (just created). Next, the `Cleaning shoot namespaces` step finalizes the Namespace. If the Shoot deletion fails at later point and start again, the  `Cleaning Kubernetes resources` will always fail with error `namespaces "<some-ns>" not found`.

**What you expected to happen**:
gardenlet to be resilient somehow against such scenarios

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot

2. Create a dummy ns `foo`

3. Create Service and a finalizer to it

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
```

Add a finalizer `foo.bar/baz` to the Service.

4. Trigger Shoot deletion

5. The `Cleaning Kubernetes resources` step will wait 5 minutes before it finalizes the Service.

6. For example at the 2nd minute of the execution of the `Cleaning Kubernetes resources` create a Pod a add a finalizer to it
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

7. Make sure that the Service will be finalized by the `Cleaning Kubernetes resources` step and then the `Cleaning shoot namespaces` step will finalize the Namespace after 5mins.

8. After the completion of step `Cleaning shoot namespaces`, abort the deletion flow (for example restart gardenlet) and trigger it again

9. Make sure that the deletion flow will fail with:
```yaml
  lastErrors:
    - description: "task \"Cleaning Kubernetes resources\" failed: 1 error occurred:\n\t* namespaces \"foo\" not found\n\n"
      taskID: Cleaning Kubernetes resources
      lastUpdateTime: '2023-04-06T07:09:20Z'
```

and won't succeed without any operator's manual intervention.

The `Cleaning shoot namespaces` step finalized the namespace but the Namespace was not empty as a new resource (with a finalizer) was created in it.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.66.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
