### ISSUE TITLE
Add `Plant` resource to Garden API

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#779]
Gardener is able to provision and to manage Kubernetes cluster across multiple cloud providers. It enables end-users to manage their clusters with a single pane of class.
However, some end-users have created clusters by other means, e.g., by other providers or other provisioning tools.
Let's enable them to also register these clusters into the Gardener system, so that they can see them in the Dashboard, and get easy access and quick insights into their health status.

Please extend the Garden API with the following resource:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: my-external-cluster
  namespace: garden-my-project
type: Opaque
data:
  kubeconfig: base64(kubeconfig-for-external-cluster)

---
apiVersion: core.gardener.cloud/v1alpha1
kind: Plant
metadata:
  name: my-external-cluster
  namespace: garden-my-project
spec:
  secretRef:
    name: my-external-cluster
  # optional fields
  monitoring:
    endpoints:
    - name: Kubernetes Dashboard
      url: https://...
    - name: Prometheus
      url: https://...
  logging:
    endpoints:
    - name: Kibana
      url: https://...
```

Also, please implement a small control loop that acts on `Plant` resources and does produce the following `status`:

```yaml
status:
  conditions:
    - type: APIServerAvailable
      status: 'True'
      lastTransitionTime: '2019-03-02T13:00:52Z'
      lastUpdateTime: '2019-03-02T14:45:28Z'
      reason: HealthzRequestSucceeded
      message: >-
        API server /healthz endpoint responded with success status code. [response_time:92ms]
    - type: EveryNodeReady
      status: 'True'
      lastTransitionTime: '2019-03-02T13:35:32Z'
      lastUpdateTime: '2019-03-02T14:45:28Z'
      reason: EveryNodeReady
      message: Every node registered to the cluster is ready
  observedGeneration: 4
  clusterInfo:
    cloud:
      type: aws|azure|gcp|openstack|alicloud|unknown
      region: eu-central-1
    kubernetes:
      version: 1.12.3
```

**Comment by vlerenc** [comment]
Thank you @rfranzke (cc @petersutter @holgerkoser @grolu).

A few (dirty) questions:
* How about having also these annotations?
```
  annotations:
    garden.sapcloud.io/registeredBy: john.doe@foo.bar.com
    garden.sapcloud.io/purpose: production
```
* "Dirty plant" question: Would we use `createdBy` instead of `registeredBy` (or even `plantedBy`?) like for `shoots`, it would be easier for tools working with `shoot` and `plant` resources like for instance the Dashboard.
* You use `cloud.type`. Wouldn't `cloud.provider` be actually better?
* "Dirty plant" question: Would we use `cloud.profile` (misuse as a `profile` carries different meaning for us) like for `shoots`, it would again be easier for tools working with `shoot` and `plant` resources like for instance the Dashboard.
* You have the Kubernetes version in the status, because we identify it. "Dirty plant" question: Would we use `spec.kubernetes` (technically not a spec) like for `shoots`, again it would be easier for tools working with `shoot` and `plant` resources like for instance the Dashboard.

I guess, you went for the clean way, because `shoots` and `plants` are anyways different and doing these few things "dirty" really isn't worth it?

**Comment by rfranzke** [comment]
> I guess, you went for the clean way, because shoots and plants are anyways different and doing these few things "dirty" really isn't worth it?

I understand the motivation, but I would probably try to go the cleaner way as this is a new API and "just because things look better/similar" we shouldn't mix it semantically up with shoots.

Consequently:

> How about having also these annotations?

OK, no strong opinion, probably `registeredBy` is better.

> You use `cloud.type`. Wouldn't `cloud.provider` be actually better?

`provider` is also OK. I used `type` because it was in the proposal for the new `Shoot` resource: https://github.com/gardener/gardener/blob/master/docs/proposals/01-extensibility.md#shoots (and, all extension CRDs also have `.spec.type`). However, we can in our core API use `.cloud.provider`, that's fine.

> "Dirty plant" question: Would we use `cloud.profile` (misuse as a `profile` carries different meaning for us) like for `shoots`, it would again be easier for tools working with `shoot` and `plant` resources like for instance the Dashboard.

Rather not imho, a `CloudProfile` is completely unrelated to `Plant`s.

> You have the Kubernetes version in the status, because we identify it. "Dirty plant" question: Would we use `spec.kubernetes` (technically not a spec) like for `shoots`, again it would be easier for tools working with `shoot` and `plant` resources like for instance the Dashboard.

That means the user has to maintain the version in the Gardener system manually if he/she upgrades the external cluster. Or do you suggest that the plant-controller writes this into the spec? Well, I don't like both approaches very well. Too dirty ;-)

**Comment by vlerenc** [comment]
OK, great, then let's only add the two annotations and that's it (let's also keep `cloud.type` if the new `shoot` resource will also call it `type`, of course).

**Comment by mvladev** [comment]
What about [cluster-registry](https://github.com/kubernetes/cluster-registry )? The API surface seems very similar.

About our resource - the cloud part can be moved to the status:

```yaml
  cloud:
    type: aws|azure|gcp|openstack|alicloud|unknown
    region: eu-central-1
```

Region / Zone can be discovered automatically when the cluster is added. See how it's done in [federation-v2](https://github.com/kubernetes-sigs/federation-v2/blob/b128bbd0b95a84d89bccdd707987c4f17a21e35c/pkg/controller/federatedcluster/clusterclient.go#L118-L163).

Type can be discovered from the Node's [providerID](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#nodespec-v1-core) as it follows `<ProviderName>://<ProviderSpecificNodeID>` schema.

Except for the obvious _see if my cluster is healthy_ scenario, I think that the most viable use-case would be federation.

`kube-dashboard`, `kibana`, `elastic` and co. are normally exposed by `kube-apiserver`'s proxy functionality, which for browser users would require basic auth.
