### ISSUE TITLE
Prometheus job "tunnel-probe-apiserver-proxy" not work for HA 

### ISSUE THREAD

**Issue by Sallyan** [gardener/gardener#7941]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
Prometheus job `tunnel-probe-apiserver-proxy` is defined to probe the kube-apiserver to the tunnel pod (vpn-shoot)
```
- job_name: tunnel-probe-apiserver-proxy
      honor_labels: false
      metrics_path: /probe
      params:
        module:
        - http_apiserver
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [ kube-system ]
        api_server: https://kube-apiserver:443
{{ include "prometheus.kube-auth" . | indent 8 }}
      relabel_configs:
      - target_label: type
        replacement: seed
      - source_labels: [ __meta_kubernetes_pod_name ]
        action: keep
        regex: vpn-shoot-(.+)
      - source_labels: [ __meta_kubernetes_pod_name ]
        target_label: __param_target
        regex: (.+)
        replacement: https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/${1}/log?tailLines=1
        action: replace
```
The probe target is `https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/${1}/log?tailLines=1` which works well for non-HA cluster as pod has one container. But for HA cluster it will also can have High Availability Reversed VPN, it will have two `vpn-shoot` pod which has two containers. At this situation the probe of target fails. 

<img width="1067" alt="Screenshot 2023-05-16 at 16 52 24" src="https://github.com/gardener/gardener/assets/50126000/3ef9237f-c65d-461b-8aee-e024db330fa5">

```
Logs for the probe:
ts=2023-05-16T08:49:56.079171872Z caller=main.go:181 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Beginning probe" probe=http timeout_seconds=10
ts=2023-05-16T08:49:56.079277684Z caller=http.go:327 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Resolving target address" target=kube-apiserver ip_protocol=ip4
ts=2023-05-16T08:49:56.079982753Z caller=http.go:327 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Resolved target address" target=kube-apiserver ip=10.243.85.49
ts=2023-05-16T08:49:56.08016129Z caller=client.go:251 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Making HTTP request" url=https://10.243.85.49:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? host=kube-apiserver:443
ts=2023-05-16T08:49:56.087753079Z caller=handler.go:117 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Received HTTP response" status_code=400
ts=2023-05-16T08:49:56.087781029Z caller=handler.go:117 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=400
ts=2023-05-16T08:49:56.087836446Z caller=handler.go:117 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=info msg="Response timings for roundtrip" roundtrip=0 start=2023-05-16T08:49:56.080261056Z dnsDone=2023-05-16T08:49:56.080261056Z connectDone=2023-05-16T08:49:56.080542707Z gotConn=2023-05-16T08:49:56.084717566Z responseStart=2023-05-16T08:49:56.087720852Z tlsStart=2023-05-16T08:49:56.080565167Z tlsDone=2023-05-16T08:49:56.084646564Z end=2023-05-16T08:49:56.087829552Z
ts=2023-05-16T08:49:56.087903628Z caller=main.go:181 module=http_apiserver target=https://kube-apiserver:443/api/v1/namespaces/kube-system/pods/vpn-shoot-1/log? level=error msg="Probe failed" duration_seconds=0.008706348
```

And as a result, the `VPN Connection` of grafana dashboard VPN will always show vpn connection failure of HA Shoot 
<img width="1414" alt="Screenshot 2023-05-16 at 16 54 43" src="https://github.com/gardener/gardener/assets/50126000/6eae769c-b1ba-4454-94dd-4350b6645815">

**What you expected to happen**:
`VPN Connection` shows the correct vpn connection status. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.68.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
