### ISSUE TITLE
Issue to deploy  shoot   with HA control-plane.

### ISSUE THREAD

**Issue by krafcima** [gardener/gardener#8066]
**How to categorize this issue?**
/area control-plane
/area high-availability
/kind bug

**What happened**:
When deploying a new shoot we are facing issue that all of the shoot control-plane  pods in the `shoot-*` namespace on the seed cluster are pinned to a single Availability Zone, resulting in overuse of resources of the seed's worker node in that Availability Zone. We have 3 Availability Zones.  

When we tried to manually add below snippet into shoot.yaml manifest (before deployment and also after shoot has been created) we ended up with `controlPlane: {}`. 

```YAML
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
spec:
  controlPlane:
    highAvailability:
      failureTolerance:
        type: zone
```
Currently there is only one randomly picked AZ mentioned in annotation  `high-availability-config.resources.gardener.cloud/zones: AZX` of shoot namespace in the seed cluster. Our workaround currently is that we manually edit annotation to contain all 3 AZs.

**What you expected to happen**:

If we deploy shoot in HA mode with shoot manifest containing  below snippet:

```YAML
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
spec:
  controlPlane:
    highAvailability:
      failureTolerance:
        type: zone
```

then we expect shoot control-plane pods to be scheduled over all  of our 3 Availability Zones and we expect  the shoot namespace on the seed cluster contain annotation  `high-availability-config.resources.gardener.cloud/zones: AZ1,AZ2,AZ3` .

**How to reproduce it (as minimally and precisely as possible)**:
Deploy shoot with HA shoot control-plane.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.70.1
- Kubernetes version: 1.25.9 (occurs on other versions)
- Cloud provider or hardware configuration: Onmetal, (Also on other providers)
- Others:

**Comment by timuthy** [comment]
Can you please check if all of the intended zones are configured in the seed resource?

https://github.com/gardener/gardener/blob/0f62246189813cc25088fd65a23b2d6d1a5262ce/example/50-seed.yaml#L11

Gardener randomly picks zone(s) from the list configured in the seed ([ref](https://github.com/gardener/gardener/blob/0f62246189813cc25088fd65a23b2d6d1a5262ce/pkg/operation/botanist/namespaces.go#L134C4-L141)).

**Comment by jan-kuky** [comment]
Yes we have configured zones in seed object as mentioned bellow:
```yaml
provider:
        region: ffm
        type: onmetal
        zones:
          - AZ1
          - AZ2
          - AZ3
```
But despite that still not configuring HA control pane through the AZ as planned.
