### ISSUE TITLE
Custom Audit Policy for Shoot Cluster is Not Working

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener#816]
With veriosn `0.18.0` of Gardener GCM cannot render an audit policy provided via ConfigMap.

The is the error message 
```
Flow "Shoot cluster reconciliation" encountered task errors: [task "Deploying Kubernetes API server" failed: timed out after 30.396971319s, last error: yaml: line 5: mapping values are not allowed in this context]
```

When the custom audit policy is not set, e.g.
```
      auditConfig:
        auditPolicy:
          configMapRef:
            name: <cm-name>
``` 
is missing for the shoot cluster, the GCM successfully reconciles the cluster.

Currently, it looks like to be related to the chart renderer.
