### ISSUE TITLE
Fluentbit CRD is deleted from managedSeed before controller instalation is removed

### ISSUE THREAD

**Issue by mimiteto** [gardener/gardener#8163]
**How to categorize this issue?**

/area logging
/kind bug

**What happened**:
I deleted a managed seed with:
```
kubectl delete managedseed SEED_NAME
```
But deletion is failing with errors that a controller `aws-provider-xxx` can't be removed.
Upon inspecting the controller it seems like there is a failing managed resource for that controller. Managed resource fails with a status :
```
status:
  conditions:
  - lastTransitionTime: "2023-06-26T08:04:46Z"
    lastUpdateTime: "2023-06-26T08:04:46Z"
    message: Required ClusterFilter "cloud-controller-manager-aws-cloud-controller-manager"
      in namespace "" is missing
    reason: ClusterFilterMissing
    status: "False"
    type: ResourcesHealthy
  - lastTransitionTime: "2023-06-26T08:04:47Z"
    lastUpdateTime: "2023-06-26T08:04:47Z"
    message: 'error during apply of object "fluentbit.fluent.io/v1alpha2/ClusterFilter/default/cloud-controller-manager-aws-cloud-controller-manager":
      the server could not find the requested resource (post clusterfilters.fluentbit.fluent.io)'
    reason: ApplyFailed
    status: "False"
    type: ResourcesApplied
  - lastTransitionTime: "2023-06-23T06:30:44Z"
    lastUpdateTime: "2023-06-23T06:30:44Z"
    message: All resources have been fully rolled out.
    reason: ResourcesRolledOut
    status: "False"
    type: ResourcesProgressing
```
When checked for that crd it seems that it's cleared (` k get crds clusterfilters.fluentbit.fluent.io clusterparsers.fluentbit.fluent.io` returns nothing).
Together with @vlvasilev we've seen that [in this line](https://github.com/gardener/gardener/blob/055a780432c621bd4be4c08d8d41983ddf70bf3a/pkg/gardenlet/controller/seed/seed/reconciler_delete.go#L273) CRDs for Fluent Operator are being deleted and are not waiting for controller installation that are using them to be deleted.
In that case CRDs can possibly be removed before the controller that is using them - hence current error message.

**What you expected to happen**:
Managed seed components to be cleared

**How to reproduce it (as minimally and precisely as possible)**:
Execute:
```
kubectl delete managedseed SEED_NAME
```
Don't know if it occurs every time or I've hit a race condition.

**Anything else we need to know?**:

**Environment**:

- Gardener version: 1.72.2
- Kubernetes version (use `kubectl version`):
```
k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.10", GitCommit:"e770bdbb87cccdc2daa790ecd69f40cf4df3cc9d", GitTreeState:"clean", BuildDate:"2023-05-17T14:06:35Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS, I expect it can happen on others as well
- Others:
