### ISSUE TITLE
Maintenance Time Window

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener#84]
# Story
- As user I want maintenance to occur only in specified time windows, so that the impact is minimal on my business/development.
- As provider I want cluster maintenance to occur not all at once, so that I don't overload the infrastructures.

# Acceptance Criteria
- [x] Maintenance time window can be defined in the shoot resource
  - [x] Whether or not Kubernetes patch versions should be applied automatically
- [x] Controller that updates the shoot resources according to the specification above:
  - [x] Optionally: Kubernetes version
  - [x] Mandatory: Machine image

# Definition of Done
- [ ] Knowledge is distributed: Have you spread your knowledge in pair programming/code review?
- [ ] Unit Tests are provided: Have you written automated unit tests or added manual NGPTT tickets?
- [ ] Integration Tests are provided: Have you written automated integration tests?
- [ ] Minimum API exposure: If you have added public API, was it really necessary/is it minimal?
- [ ] Operations guide: Have you updated the [operations guide](https://github.wdf.sap.corp/kubernetes/kube-docs/wiki/Operations%20Guide)?
#

**Comment by rfranzke** [comment]
With c6153a88d444f07fc44f017aabecd73299141081 we can define the maintenance settings in the Shoot manifest. It looks like that:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Shoot
metadata:
  name: johndoe-az
  namespace: garden-development
spec:
  ...
  maintenance:
    timeWindow:
      begin: 220000+0100
      end: 230000+0100
    autoUpdate:
      kubernetesVersion: true
```

If it is not provided when creating the Shoot, the Gardener will randomly compute the time window. The default for updating the patch kubernetes versions is `true`.

Next task is to write the machine image inside the Shoot manifest (to be discussed how).
After that we can write the controller which updates the Shoot according to the update settings and maintenance window.
