### ISSUE TITLE
☂️ Proposal for implementing OIDC authentication for the observability applications on gardener seeds clusters

### ISSUE THREAD

**Issue by nickytd** [gardener/gardener#8416]
/area logging
/area monitoring
/kind enhancement

## Proposal

In addition to the current authentication mechanism for the observability applications on the seed clusters, we shall introduce a new authentication mechanism based on OIDC. This improves the user experience for gardener cluster operators and shoot owners when accessing those applications.

Here is a high level design:
![oauth2-rbac-proxy](https://github.com/gardener/gardener/assets/3019431/3848df10-ab18-47ad-952a-66336cdb065f)

### Components

- [Oauth2 Proxy](<https://github.com/oauth2-proxy/oauth2-proxy>): implements standard oidc authentication of user requests. Upon successfull authentication with an external ODIC provider the proxy associates a valid OIDC token with the user session and propagates it to the upstream RBAC proxy for authorization check.
- [Kube Rbac Proxy](https://github.com/brancz/kube-rbac-proxy): validates OIDC token against the issuer and performs SubjectAccessReviews for users accessing the observability applications. Upon successful SubjectAccessReview a user session is established and the authenticated and authorized request is propagated to the final application.

There are two major scenarios in the context of authorization:

1. Gardener operators shall have cluster-wide access to all shoot observability applications hosted on a given seed including those in the garden namespace.
2. Shoot owners shall have namespaced access only to the observability applicaitons on the shoots they own. Access to the seed observability applications and other shoot owners apps shall be denied.

There are two major implementation requirements:

1. Lifecycle management of the proxies for each shoot hosted on the given seed.
2. RBAC role management for the shoot observability applications.

#### OIDC configurations

Since all applications on a given seed share the same domain name we can benefit from a simple OIDC configuration shared among the all oauth2 proxies. Example:

```text
scope                                 = "openid email" # shared-among-all-apps-on-a-seed
client_id                             = "b1d2009f-60f6-4ab3-8ddc-4d13e95cd96c" # shared-among-all-apps-on-a-seed
redirect_url                          = "https://pl-local--local.ingress.local.seed.local.gardener.cloud:8448/oauth2/callback"
oidc_issuer_url                       = "https://dex:5556" # shared-among-all-apps-on-a-seed
```

That configuration snippet shall carried in the a seed resource definition since there is 1 to 1 relationship between an OIDC Application Configuration and a Seed cluster. As a consequence a creation or deletion of a seed shall be reflected eventually in the OIDC provider configuration as well. This activity is not part of the gardener seed/shoot reconcilation process. To simplify further the configuration we may use [PKCE](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce) authentication flow.

#### Authenticaiton & Authorization Proxies deployment

For each applicaiton there shall be a deployment comprising the oauth2 and kube-rbac proxies in addition to an ingress definition. It is a rather standard deployment. Each deployment shall have access to the oidc provider configurattion. In addition, the kube-rbac proxy shall also be supplied with OIDC CA public certificates and a shoot specific configuration facilitating the SubjectAccessReviews. Both can be dynamically fetched/created during the seed/shoot reconcilation processes.

#### RBAC Role Management

To facilitate namespaced access to the observability applcations we need to introduce a namespeced spec-less custom resource.
For example:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: observabilityapps.core.gardener.cloud
spec:
  group: core.gardener.cloud
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties: {}
  scope: Namespaced
  names:
    plural: observabilityapps
    singular: observabilityapp
    kind: ObservabilityApp
    categories:
      - all
```

And the followling ClusterRole:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:system:observabilityapps
rules:
  - apiGroups: ["core.gardener.cloud"]
    resources: ["observabilityapps/plutono"]
    verbs: ["get", "create"]
  - apiGroups: ["core.gardener.cloud"]
    resources: ["observabilityapps/prometheus"]
    verbs: ["get", "create"]
  - apiGroups: ["core.gardener.cloud"]
    resources: ["observabilityapps/vali"]
    verbs: ["get", "create"]
  # Any other application in the future shall be added here
  # The proposal here is based on a resource/subresource relation.
```

Which later allows us to create a ClusterRoleBinding granting access to all observebility apps for Gardener operators or Namespaced access to the observability apps only for the shoot owners. Examples:

```yaml
# kubectl auth can-i request observabilityapps.core.gardener.cloud  --subresource plutono --as-group k8s-dev-garden-view --as some-user
# shall return yes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:system:observabilityapps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:system:observabilityapps
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: k8s-dev-garden-view
```

```yaml
# kubectl auth can-i request observabilityapps --subresource plutono -n shoot--local--local  --as project-viewer@gardener.local
# shall return yes
# kubectl auth can-i request observabilityapps --subresource plutono -n other-shoot-namespace  --as project-viewer@gardener.local
# shall return no
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gardener.cloud:system:observabilityapps
  # the namespace of the project resource in the runtime gardener cluster
  namespace: shoot--local--local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gardener.cloud:system:observabilityapps
subjects:
  # reflects the members list in the project resource
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: project-viewer@gardener.local
```

As of today the only origin of the users list belonging to a shoot is the Members field in the [ProjectSpec](<https://pkg.go.dev/github.com/gardener/gardener@v1.78.1/pkg/apis/core/v1beta1#ProjectSpec>) which contains a rbacv1.Subject. Hence in all shoot namespaces we shall create corresponding RoleBindings for the shoots belonging to a given project. The requirement is that users used in the projects and gardener operators shall be authenticated by the same OIDC provider.

Note: Current username & password authentication will also remain for two reasons:
1. Backward compatibility and fail save approach for accessing the observability apps. 
2. Prometheus Federation does not yet support OIDC authentication on the client side. 

Once respective implementation PRs are ready for review those will be linked to this umbrella issue. 
Meanwhile any comments and feedback are appreciated.
<img width="1565" alt="OIDC for the Observability Apps" src="https://github.com/gardener/gardener/assets/3019431/3937f14b-afc2-4930-8bd0-da3d263e1a51">

Note: Adding an OIDC provider (dexidp+openldap) to the gardener provider local setup is trivial if the kind cluster external port mapping template is enhanced with the OIDC provider port mapping.
