### ISSUE TITLE
`kube-apiserver` fails to start due to duplicate `service-account-issuer`

### ISSUE THREAD

**Issue by dimitar-kostadinov** [gardener/gardener#8420]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:
The `kube-apiserver` pod fails to start if default service account issuer is configured in accepted issuers in the `Shoot` manifest
```
% k -n shoot--local--local get po -l role=apiserver
NAME                              READY   STATUS             RESTARTS      AGE
kube-apiserver-68c77898f4-klrl4   1/1     Running            0             66m
kube-apiserver-68c77898f4-qgcwj   1/1     Running            0             65m
kube-apiserver-7fdc8d9db-ww6mc    0/1     CrashLoopBackOff   5 (44s ago)   3m44s
```
```
% k -n shoot--local--local logs kube-apiserver-7fdc8d9db-ww6mc
I0904 13:31:32.553284       1 flags.go:64] FLAG: --admission-control="[]"
...
I0904 13:31:32.553835       1 flags.go:64] FLAG: --watch-cache="true"
I0904 13:31:32.553836       1 flags.go:64] FLAG: --watch-cache-sizes="[]"
E0904 13:31:32.554683       1 run.go:74] "command failed" err="service-account-issuer \"https://api.local.local.internal.local.gardener.cloud\" is already specified"
```
`Shoot` reconciliation fails:
```
% k -n garden-local get shoots local
NAME    CLOUDPROFILE   PROVIDER   REGION   K8S VERSION   HIBERNATION   LAST OPERATION               STATUS      AGE
local   local          local      local    1.27.1        Awake         Reconcile Processing (25%)   unhealthy   90m
```
and `Shoot` manifest contains the following `acceptedIssuers`: 
```
% k -n garden-local get shoots local -o yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  ...
  name: local
  namespace: garden-local
spec:
  cloudProfileName: local
  dns:
    domain: local.local.external.local.gardener.cloud
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      defaultNotReadyTolerationSeconds: 300
      ...
      requests:
        maxMutatingInflight: 200
        maxNonMutatingInflight: 400
      serviceAccountConfig:
        acceptedIssuers:
        - https://api.local.local.internal.local.gardener.cloud
    kubeControllerManager:
      nodeCIDRMaskSize: 24
      nodeMonitorGracePeriod: 40s
   ...
```

**What you expected to happen**:
It should not be possible to set default service account issuer in `acceptedIssuers`

**How to reproduce it (as minimally and precisely as possible)**:
Create a shoot in local setup and configure default service account issuer `https://api.local.local.internal.local.gardener.cloud` as accepted issuers in the shoot manifest.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version: v1.78.1
- Kubernetes version (use `kubectl version`):
  Client Version: v1.28.1
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.27.1
- Cloud provider or hardware configuration:
- Others:
