### ISSUE TITLE
gardener-apiserver: Consider forbidding specifying more than 1 extension from the same type for a Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#8446]
**How to categorize this issue?**

/area quality
/kind bug

**What happened**:
Currently the gardener-apiserver allows to specify 2 extensions from the same type:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot

spec:
  extensions:
  - type: registry-cache
    providerConfig:
      apiVersion: registry.extensions.gardener.cloud/v1alpha1
      kind: RegistryConfig
      caches:
      - upstream: docker.io
        size: 500Mi
  - type: registry-cache
    providerConfig:
      apiVersion: registry.extensions.gardener.cloud/v1alpha1
      kind: RegistryConfig
      caches:
      - upstream: quay.io
        garbageCollectionEnabled: false
```

gardenlet set the Extension name to the extension type. See https://github.com/gardener/gardener/blob/2e4617c3de1a4491a6287788266d45a7fc8044e2/pkg/operation/botanist/extension.go#L90-L104

The above Shoot spec actually was created successfully. It deployed a single Extension to the Seed with the providerConfig of the 2nd extension from the Shoot spec:

```
% k -n shoot--local--local get extensions.extensions.gardener.cloud registry-cache -o yaml

spec:
  providerConfig:
    apiVersion: registry.extensions.gardener.cloud/v1alpha1
    caches:
    - garbageCollectionEnabled: false
      upstream: quay.io
    kind: RegistryConfig
  type: registry-cache
```

The part that makes possible the 2nd extension to overwrite the 1st one:
https://github.com/gardener/gardener/blob/809fd994e01455eb9f67af35f195bab76ebade2f/pkg/component/extensions/extension/extension.go#L396-L426

**What you expected to happen**:
I would say that we should rather forbid specifying the same extension more than once instead of having one of the configs overwriting the other one.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.79.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
