### ISSUE TITLE
cluster shows issues with webhook, despite webhook excluding sensitive resources

### ISSUE THREAD

**Issue by rubofelipe** [gardener/gardener#8508]
**How to categorize this issue?**

/area monitoring
/kind bug

**What happened**:
We see in the dashboard, status errors that webhook configurations are wrong/impacting hibernation/lifecycle operations.
```yaml
  constraints:
  - codes:
    - ERR_PROBLEMATIC_WEBHOOK
    lastTransitionTime: "2023-09-08T21:45:10Z"
    lastUpdateTime: "2023-09-05T15:46:04Z"
    message: 'ValidatingWebhookConfiguration "opa-validating-webhook" is problematic:
      webhook "validating-webhook.openpolicyagent.org" with failurePolicy "Fail" and
      5s timeout might prevent worker nodes from properly joining the shoot cluster'
    reason: ProblematicWebhooks
    status: "False"
    type: HibernationPossible
  - codes:
    - ERR_PROBLEMATIC_WEBHOOK
    lastTransitionTime: "2023-09-08T21:45:10Z"
    lastUpdateTime: "2023-09-05T15:46:04Z"
    message: 'ValidatingWebhookConfiguration "opa-validating-webhook" is problematic:
      webhook "validating-webhook.openpolicyagent.org" with failurePolicy "Fail" and
      5s timeout might prevent worker nodes from properly joining the shoot cluster'
    reason: ProblematicWebhooks
    status: "False"
    type: MaintenancePreconditionsSatisfied
```
**What you expected to happen**:

These warnings should not show, the webhook has a namespace selector, the selector is sensitive about excluding specific namespaces:
```yaml
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - default
    - key: openpolicyagent.org/webhook
      operator: NotIn
      values:
      - ignore
  ```
  
 Besides that, the webhook has `scope: Namespaced` in its rule:
 ```
 % kubectl get validatingwebhookconfiguration opa-validating-webhook -o json | jq '.webhooks[0].rules'
 ```
 ```json
[
  {
    "apiGroups": [
      ""
    ],
    "apiVersions": [
      "*"
    ],
    "operations": [
      "CREATE",
      "UPDATE"
    ],
    "resources": [
      "*"
    ],
    "scope": "Namespaced"
  }
]
 ```

**How to reproduce it (as minimally and precisely as possible)**:
See dashboard/status of the shoot.

**Anything else we need to know?**:
Please see the original issue: issues-canary#4134

**Environment**:
- Gardener version:
- Kubernetes version (use `kubectl version`): v1.25.10
- Cloud provider or hardware configuration: GCP
- Others:
