### ISSUE TITLE
Run kube-proxy in non-privileged mode for Kubernetes >= 1.29

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener#8700]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
When I worked on the topic about running Pods in non-privileged mode, for kube-proxy I created https://github.com/kubernetes/kubernetes/issues/112171. https://github.com/kubernetes/kubernetes/issues/112171 is fixed by https://github.com/kubernetes/kubernetes/pull/120864. Starting Kubernetes 1.29 it will be possible to run the long-running kube-proxy container as non-privileged.
For more details, see https://github.com/kubernetes/contributor-site/pull/452.

The kube-proxy logic that requires to run in a privileged container is moved to an init container. From https://github.com/kubernetes/kubernetes/pull/120864:
```yaml
initContainers:
  - name: kube-proxy-init
    command:
    - /usr/local/bin/kube-proxy
    - --config=/var/lib/kube-proxy/config.conf
    - --init-only
    image: registry.k8s.io/kube-proxy:local
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/kube-proxy
      name: kube-proxy
```

And the main kube-proxy container runs with:
```yaml
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_RESOURCE"]
```

**Why is this needed**:
To run kube-proxy in non-privileged mode.

cc @dimityrmirchev @AleksandarSavchev
