### ISSUE TITLE
Isolate control planes from each other and isolate components inside the control plane

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener#873]
This issue supersedes issue #631.

For security reasons we need to isolate control planes from each other as well as to ensure that components of a control plane can only see each other on a need-to-communicate basis. Everything else shall be protected by firewalls.

## Acceptance criteria

* there are fine grained security polices that deny all traffic within a control plane namespace and to other namespaces and only selectively allows traffic where required.
* There are automated tests to check that the most critical communication channels that are supposed to be blocked are really blocked. Those should especially include the components that are accessible via an ingress (Grafana, Kibana, Prometheus).

## Notes

* We already have several tests that can be re-used.
* @wyb1 has started working on network policies for Prometheus

**Comment by mvladev** [comment]
I'll create network policies for all components except for Prometheus

**Comment by mvladev** [comment]
Here is what I plan to do:

## Goals

- All existing network policies must be purged as they are too broad.
- Lots of components should use labels in their `Pods` to controll common `Ingress`, `Egress` network policies (more on this bellow).
- A new controller watching the Seed cluster's `kubernetes` endpoint must be implemeneted (more on this bellow).

## New policies

Bellow you can find a list of all new policies which must be added to each Shoot namespace in the Seed cluster:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Disables all Ingress and Egress traffic in this namespace.
  name: deny-all
spec:
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
  egress: []
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-dns=allowed'
      to DNS running in 'kube-system'.

      In practice, most of the Pods are going to need this label.
  name: allow-to-dns
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-dns: allowed
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchExpressions:
        - {key: k8s-app, operator: In, values: [kube-dns,coredns]}
   # TODO: discover this ports on every Seed cluster dynamically
   # THOSE ARE NOT Service Ports!
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 8053
    - protocol: UDP
      port: 8053
  policyTypes:
  - Egress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-seed-apiserver=allowed'
      to Seed's Kubernetes API Server.
  name: allow-to-seed-apiserver
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-seed-apiserver: allowed
  egress:
  - to:
    # TODO: write a controller for this specific policy
    - ipBlock:
        cidr: 35.234.81.111/32
   # TODO: discover this ports on every Seed cluster dynamically
   # THOSE ARE NOT Service Ports!
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Egress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-shoot-apiserver=allowed'
      to Shoot's Kubernetes API Server.
  name: allow-to-shoot-apiserver
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-shoot-apiserver: allowed
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: kubernetes
          garden.sapcloud.io/role: controlplane
          role: apiserver
    ports:
    - protocol: TCP
      port: 443
  policyTypes:
  - Egress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-public-except-private-medatadata=allowed'
      to all IPs which except for the Private networks (RFC1918), Carrier-grade NAT (RFC 6598) and CloudProvider's
      specific metadata service IP.

      In practice, this blocks Egress traffic to all networks in the Seed cluster and only only allows traffic to
      public IPv4 addresses.
  name: allow-to-public-except-private-and-metadata
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-public-except-private-medatadata: allowed
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 100.64.0.0/10
        - 169.254.169.254/32
  policyTypes:
  - Egress
  ingress: []

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-metadata=allowed'
      to CloudProvider's specific metadata service IP.
  name: allow-to-metadata
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-metadata: allowed
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32
  policyTypes:
  - Egress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-shoot-networks=allowed'
      to IPv4 blocks belonging to the Shoot network.

      In practice, this should be used by components which use 'vpn-seed' to comunicate to Pods
      in the Shoot cluster.
  name: allow-to-shoot-networks
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-shoot-networks: allowed
  egress:
  - to:
    # Nodes CIDR
    - ipBlock:
        cidr: 10.250.0.0/16
    # Pods CIDR
    - ipBlock:
        cidr: 100.96.0.0/11
    # Services CIDR
    - ipBlock:
        cidr: 100.64.0.0/13
  policyTypes:
  - Egress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Egress from pods labeled with 'networking.gardener.cloud/to-elasticsearch=allowed'
      to the EleasticSearch API.
  name: allow-to-elasticsearch
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/to-elasticsearch: allowed
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: elasticsearch-logging
          garden.sapcloud.io/role: logging
          role: logging
    ports:
    - protocol: TCP
      port: http # TODO: check this port
  policyTypes:
  - Egress
  ingress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress from pods labeled with 'networking.gardener.cloud/from-prometheus=allowed'
      to ports named 'metrics' in the PodSpecification.
  name: allow-from-prometheus
spec:
  podSelector:
    matchLabels:
      networking.gardener.cloud/from-prometheus: allowed
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
          garden.sapcloud.io/role: monitoring
          role: monitoring
    ports:
    - port: metrics
      protocol: TCP
  policyTypes:
  - Ingress
  egress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to the ElasticSearch API pods labeled with 'networking.gardener.cloud/to-elasticsearch=allowed',
      nginx controller in 'kube-system' namespace and fleuntd in the 'gardner' namespace.
  name: allow-elasticsearch
spec:
  podSelector:
    matchLabels:
      app: elasticsearch-logging
      garden.sapcloud.io/role: logging
      role: logging
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
      namespaceSelector:
        matchLabels:
          role: kube-system
    - podSelector:
        matchLabels:
          app: fluentd-es
          garden.sapcloud.io/role: logging
          role: logging
      namespaceSelector:
        matchLabels:
          role: garden
    - podSelector:
        matchLabels:
          networking.gardener.cloud/to-elasticsearch: allowed
    ports:
    - protocol: TCP
      port: http # TODO: check this port
  policyTypes:
  - Ingress
  egress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to etcd pods from the Shoot's Kubernetes API Server.
  name: allow-from-apiserver-to-etcd
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      garden.sapcloud.io/role: controlplane
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: kubernetes
          garden.sapcloud.io/role: controlplane
          role: apiserver
    ports:
    - protocol: TCP
      port: clientport # TODO: check this port
  policyTypes:
  - Ingress
  egress: []

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress and Egress between etcd-main peers.
  name: allow-etcd-main-peering
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      garden.sapcloud.io/role: controlplane
      role: main
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
          role: main
    ports:
    - protocol: TCP
      port: serverport # TODO: which is the peering port?
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
          role: main
    ports:
    - protocol: TCP
      port: serverport # TODO: which is the peering port
  policyTypes:
  - Egress
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-etcd-events-peering
  annotations:
    gardener.cloud/description: |
      Allows Ingress and Egress between etcd-events peers.
spec:
  podSelector:
    matchLabels:
      app: etcd-statefulset
      garden.sapcloud.io/role: controlplane
      role: events
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
          role: events
    ports:
    - protocol: TCP
      port: serverport # TODO: which is the peering port
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
          role: events
    ports:
    - protocol: TCP
      port: serverport # TODO: which is the peering port
  policyTypes:
  - Egress
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to the Grafana from the nginx controller in 'kube-system' namespace,
      and Egress to Prometheus.
  name: allow-grafana
spec:
  podSelector:
    matchLabels:
      component: grafana
      garden.sapcloud.io/role: monitoring
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: prometheus
          garden.sapcloud.io/role: monitoring
          role: monitoring
    ports:
    - protocol: TCP
      port: 9090 # TODO: name this port
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
    ports:
    - protocol: TCP
      port: web
  policyTypes:
  - Egress
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to the Kibana from the nginx controller in 'kube-system' namespace,
      and Egress to ElasticSearch API.
  name: allow-kibana
spec:
  podSelector:
    matchLabels:
      app: kibana-logging
      garden.sapcloud.io/role: logging
      role: logging
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: elasticsearch-logging
          garden.sapcloud.io/role: logging
          role: logging
    ports:
    - protocol: TCP
      port: http # TODO: check this port
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
    ports:
    - protocol: TCP
      port: 5601 # TODO: name this port
  policyTypes:
  - Egress
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to the Shoot's Kuberntes API Server from pods labeled with 'networking.gardener.cloud/to-shoot-apiserver=allowed'
      and Prometheus, and Egress to etcd pods.
  name: allow-kube-apiserver
spec:
  podSelector:
    matchLabels:
      app: kubernetes
      garden.sapcloud.io/role: controlplane
      role: apiserver
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: etcd-statefulset
          garden.sapcloud.io/role: controlplane
    ports:
    - protocol: TCP
      port: clientport # TODO: check this port
  ingress:
  - from:
    - podSelector:
        matchLabels:
          networking.gardener.cloud/to-shoot-apiserver: allowed
    # kube-apiserver listens on https port
    - podSelector:
        matchLabels:
          app: prometheus
          garden.sapcloud.io/role: monitoring
          role: monitoring
    ports:
    - protocol: TCP
      port: https # 443
  policyTypes:
  - Egress
  - Ingress
```

## Labels to components

Bellow you can find a list of new labels that needs to be added to every component present in AWS Shoot cluster.
Those extra labels add additional white-listed rules to every one of those Pods.

### aws-lb-readvertiser

It needs to talk to the Shoot's Kubernetes API Server and do IP address lookup on a public IP.
It needs to be scraped by Prometheus.

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
networking.gardener.cloud/to-public-except-private-medatadata: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### cert-broker


It needs to talk to the Shoot's Kubernetes API Server and Seed's Kubernetes API Server.
It needs to be scraped by Prometheus.

@timuthy can you confirm this?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
networking.gardener.cloud/to-seed: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### cloud-controlelr-manager

Cloud-specific, and CloudProviders should handle those annotations:

It needs to talk to the Shoot's Kubernetes API Server, CloudProvider's Metadata service and Public IPs (cloud APIs).
It needs to be scraped by prometheus

@jia-jerry this should apply for `alicoud`, right?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-public-except-private-medatadata: allowed
networking.gardener.cloud/to-metadata: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
networking.gardener.cloud/from-prometheus: allowed
```

>
> Note: On AWS you can use PrivateLink to connect to the AWS APIs and not go to the public network.
>

### curator cron jobs

It only needs to talk to the ElasticSearch API.

@vlvasilev @ialidzhikov @KristianZH you confirm this?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-elasticsearch: allowed
```

### elasticsearch

Elastic search should not require any specific annotations. Even DNS is not required.
It needs to be scraped by Prometheus.

@vlvasilev @ialidzhikov @KristianZH you confirm this?

```yaml
networking.gardener.cloud/from-prometheus: allowed
```

### etcd

Etcd's backup-sidecar needs to connect to the public internet for backup.
It needs to be scraped by Prometheus.

@shreyas-s-rao can you confirm?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-public-except-private-medatadata: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### grafana

It needs only DNS.
It needs to be scraped by Prometheus.

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### kibana

Kibana needs to talk to ElasticSearch API.
It needs to be scraped by Prometheus.

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-elasticsearch: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### kube-addon-manager

It needs to talk to the Shoot's Kubernetes API Server

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
```

### kube-apiserver

It needs to talk to everything in Shoot network and everything in the Public network (Webhooks).
It should not talk to the Cloud Provider's metadata service.
It needs to be scraped by Prometheus.

@marwinski @rfranzke can you confirm this?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-public-except-private-medatadata: allowed
networking.gardener.cloud/to-shoot-networks: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### kube-controller-manager

It needs to talk to the Shoot's Kubernetes API Server.
It should not talk to the Cloud Provider's metadata service.
It needs to be scraped by Prometheus.

@marwinski @rfranzke can you confirm this?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### kube-scheduler

It needs to talk to the Shoot's Kubernetes API Server.
It needs to be scraped by Prometheus.


```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### kube-state-metrics

It needs to talk to the Shoot's Kubernetes API Server.
It needs to be scraped by Prometheus.


```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
```

### kube-state-metrics-seed

It needs to talk to the Seed's Kubernetes API Server.
It needs to be scraped by Prometheus.


```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-seed-apiserver: allowed
```

### machine-controller-manager

It needs to talk to the Seed's and Shoot's Kubernetes API Server.
It needs to talk to Cloud APIs in public networks.
It needs to be scraped by Prometheus.

@prashanth26 @hardikdr can you confirm this?

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-public-except-private-medatadata: allowed
networking.gardener.cloud/to-seed-apiserver: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
networking.gardener.cloud/from-prometheus: allowed
```

### terraformer jobs

It needs to talk to the Seed's API Server and CloudProvider's API.

```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-public-except-private-medatadata: allowed
networking.gardener.cloud/to-seed-apiserver: allowed
```

### prometheus

TBD

## new controller for seed-apiserver access

A new controller for the Seed cluster must be created which will watch for changes to `defaut/kubernetes` `Endpoints` and reconcile `NetworkPolicy` `allow-to-seed-apiserver` in each `Shoot` namespace.

**Comment by mvladev** [comment]
P.S. I've tested some of those policies, but not everything. 
This is just the idea on how organize and structure them.

**Comment by marwinski** [comment]
Just one comment regarding DNS. Only DNS need to see each other via the TCP port, TCP port should be blocked from all other pods.

**Comment by mvladev** [comment]
> Just one comment regarding DNS. Only DNS need to see each other via the TCP port, TCP port should be blocked from all other pods.

I don't get it. Can you explain it in more detail?

**Comment by marwinski** [comment]
DNS nodes apparently sync each other using TCP. The open TCP port was of some concern to our pen testers as they can be used to manipulate the DNS configuration.

**Comment by mvladev** [comment]
From [rfc1035](https://tools.ietf.org/html/):

>  Messages carried by UDP are restricted to 512 bytes (not counting the IP
or UDP headers).  Longer messages are truncated and the TC bit is set in
the header.

After 512 bytes `TCP` is used.`DNSSEC` responses might be larger than the maximum `UDP` size and for this `TCP` is required.

I don't think that we can safely disable it.

**Comment by vpnachev** [comment]
> ```yaml
> apiVersion: networking.k8s.io/v1
> kind: NetworkPolicy
> metadata:
>   annotations:
>     gardener.cloud/description: |
>       Allows Ingress to the ElasticSearch API pods labeled with 'networking.gardener.cloud/to-elasticsearch=allowed',
>       nginx controller in 'kube-system' namespace and fleuntd in the 'gardner' namespace.
>   name: allow-elasticsearch
> spec:
>   podSelector:
>     matchLabels:
>       app: elasticsearch-logging
>       garden.sapcloud.io/role: logging
>       role: logging
>   ingress:
>   - from:
>     - podSelector:
>         matchLabels:
>           app: nginx-ingress
>           component: controller
>       namespaceSelector:
>         matchLabels:
>           role: kube-system
>     - podSelector:
>         matchLabels:
>           app: fluentd-es
>           garden.sapcloud.io/role: logging
>           role: logging
>       namespaceSelector:
>         matchLabels:
>           role: garden
>     - podSelector:
>         matchLabels:
>           networking.gardener.cloud/to-elasticsearch: allowed
>     ports:
>     - protocol: TCP
>       port: http # TODO: check this port
>   policyTypes:
>   - Ingress
>   egress: []
> ```

The elasticsearch does not need to be exposed via the nginx ingress service.

Most of the policies are addressing the `shoot--` namespaces, while some pods are living in the `garden` or `kube-system` ns. Shall you add policies for non shoot namespaces ? For example fluent[d|bit] are living in the `garden` ns and they are talking each other. I think that FluentBit is even talking with the kube API server of the seed cluster.

Generally, I would not block every component to talk to the DNS, but keep it open, because it is a [core component](https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services) of a k8s cluster.

**Comment by mvladev** [comment]
Gardener-created pods in other namespaces will get their own network policies in a separate PR.

DNS is optional addon. It's not required. Also `elasticsearch` should not use any DNS as it's should not have any Egress traffic.

**Comment by wyb1** [comment]
Using the network policies that @mvladev suggested, the network policy for prometheus should look like:
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Ingress to Prometheus from Grafana and Egress to Prometheus targets.
  name: allow-prometheus
spec:
  podSelector:
    matchLabels:
      app: prometheus
      garden.sapcloud.io/role: monitoring
      role: monitoring
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: grafana
          garden.sapcloud.io/role: monitoring
    - podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
      namespaceSelector:
        matchLabels:
          role: kube-system
  egress:
  - to:
    - podSelector:
        matchLabels:
          networking.gardener.cloud/from-prometheus: allowed
  - to:
    - namespaceSelector:
        matchLabels:
          role: garden
      podSelector:
        matchLabels:
          networking.gardener.cloud/from-prometheus: allowed
  policyTypes:
  - Ingress
  - Egress
```

Additionally, prometheus will need the following labels:
```yaml
networking.gardener.cloud/to-dns: allowed
networking.gardener.cloud/to-seed-apiserver: allowed
networking.gardener.cloud/to-shoot-networks: allowed
networking.gardener.cloud/to-shoot-apiserver: allowed
```

**Comment by mvladev** [comment]
I think that this should be used

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    gardener.cloud/description: |
      Allows Prometheus to talk to various components in the Seed cluster
  name: allow-prometheus
spec:
  podSelector:
    matchLabels:
      app: prometheus
      garden.sapcloud.io/role: monitoring
      role: monitoring
  egress:
  - to:
    - podSelector:
        matchLabels:
          networking.gardener.cloud/from-prometheus: allowed
    - podSelector:
        matchLabels:
          app: prometheus
          role: monitoring
      namespaceSelector:
        matchLabels:
          role: garden
    - podSelector:
        matchLabels:
          component: alertmanager
          role: monitoring
          garden.sapcloud.io/role: monitoring
      namespaceSelector:
        matchLabels:
          role: garden
  ingress:
  - from:
    - podSelector:
        matchLabels:
          component: grafana
          garden.sapcloud.io/role: monitoring
    - podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
      namespaceSelector:
        matchLabels:
          role: kube-system
  policyTypes:
  - Egress
  - Ingress
```

We need to explicitly specify which components you want to talk in the `gardener` namespace otherwise you'll give too much permission.
