### ISSUE TITLE
Wrong `istio-ingress` is used if `ExposureClassName`and `ExposureClassHandler` is not the same

### ISSUE THREAD

**Issue by dergeberl** [gardener/gardener#8794]
**How to categorize this issue?**

/area networking
/kind bug

**What happened**:

After a local-setup with `ExposureClasses` (while following the documentation
 https://github.com/gardener/gardener/blob/master/docs/usage/exposureclasses.md), I found a bug in the `ExposureClassName`and `ExposureClassHandler` handling. 

Currently it only works if the `ExposureClassesName`and `ExposureClassesHandler` are the same value.

**What you expected to happen**:

`ExposureClassesName` and `ExposureClassesHandler` should not have to be the same value.

**How to reproduce it (as minimally and precisely as possible)**:

Create a `ExposureClass` with a different name than handler like this: 
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: ExposureClass
metadata:
  name: internet
handler: internet-config
```

Add `exposureClassHandlers` in `GardenletConfiguration`:
```yaml
exposureClassHandlers:
- name: internet-config
  loadBalancerService:
    annotations:
      loadbalancer/network: internet
```

If now a `shoot` will get created by setting `spec.exposureClassName` to `internet-1`, the shoot will be placed in the "normal" `istio-ingress` namespace.

**Anything else we need to know?**:

In the function `exposureClassHandler()` the `exposureClassName` is wrongly compared with the `handler.Name`:
https://github.com/gardener/gardener/blob/8abf4350e290ac7e18cc97eaeef3cca73f98c531/pkg/operation/istio_config.go#L63-L72

**Environment**:

- Gardener version: latest (local-setup)
- Cloud provider or hardware configuration: provider-local
