### ISSUE TITLE
🧑🏼‍🌾 Deploy `gardenlet`s Through Custom Resource Via `gardener-operator`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#8802]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
`gardener-operator` should also be able to deploy `gardenlet`s to target seed clusters (unmanaged seeds, sometimes also known as "soils"). Today, human operators have to manually deploy the `gardenlet` Helm chart there. Instead, we could add a new `Gardenlet` CRD to the `operator.gardener.cloud/v1alpha1` API:

```yaml
apiVersion: operator.gardener.cloud/v1alpha1
kind: Gardenlet
metadata:
  name: local
spec:
# kubeconfigSecretRef:
#   name: kubeconfig-to-target-cluster
#   namespace: garden
  gardenlet:
    bootstrap: BootstrapToken
    config:
      apiVersion: gardenlet.config.gardener.cloud/v1alpha1
      kind: GardenletConfiguration
      seedConfig:
        spec:
          # insert seed specification here
```

`gardener-operator` obviously needs a kubeconfig for the target seed cluster, and all of this only works when it can reach it network-wise. The `.spec.kubeconfigSecretRef` is optional, and when not provided, `gardenlet` is getting deployed into the runtime cluster of `gardener-operator`.

We already have the needed code in [`gardenlet'`s `ManagedSeed` controller](https://github.com/gardener/gardener/tree/master/pkg/gardenlet/controller/managedseed) and just need to make it reusable.

PoC code is in https://github.com/metal-stack/gardener/tree/hackathon-operator-gardenlet

**Why is this needed**:
`gardener-operator` can only deploy the Gardener control plane components (API server, controller-manager, etc.). `gardenlet`s must be deployed manually to target seed clusters (typically, via the Helm chart). When the `gardener-operator` can reach such seed clusters network-wise, it should be possible to make it easily deploy `gardenlet`s via a new `operator.gardener.cloud/v1alpha1.Gardenlet` custom resource.

**Tasks:**

- [x] https://github.com/gardener/gardener/pull/10161
- [x] https://github.com/gardener/gardener/pull/10218
