### ISSUE TITLE
Improve naming of referenced resources in Seed

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener#8807]
**How to categorize this issue?**

/area usability
/kind enhancement

**What would you like to be added**:

Referenced resources that are copied over to the Seed should be named `ref-<resource-name>` instead of `ref-<original-name>`.

For example:
Creating a shoot with `spec.resources` like this:
```yaml
spec:
  resources:
  - name: foo # <- resource-name
    resourceRef:
      apiVersion: v1
      kind: Secret
      name: bar # <- original-name
```

results in a Seed secret named `ref-bar`:
```bash
$ k get secret ref-bar
NAME              TYPE     DATA   AGE
ref-bar   Opaque   1      48m
```

However, it should be named `ref-foo` instead.

ref https://github.com/gardener/gardener/issues/2321
ref https://github.com/gardener/gardener/issues/2327

**Why is this needed**:

In some extensions, users can reference a resource in the project namespace in the `providerConfig`.
With the current naming scheme, extensions need to fetch the `ShootSpec` from the `Cluster` object, find the referenced resource, and prepend the original resource name with `ref-` to determine the name of the resource in the seed cluster.

Naming the resources `ref-<resource-name>` is more intuitive and simplifies the required code in extensions for handling referenced resources, as they can simply prepend `ref-` to some value in the `providerConfig`.
