### ISSUE TITLE
Default shoot networks should be configured on seed side

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#895]
Currently, the default pod/service networks for shoots are hard-coded in the Garden API: https://github.com/gardener/gardener/blob/master/pkg/apis/core/v1alpha1/types_utils.go#L91-L96

This means that every shoot that does not specify a pod/service network will get these values. However, due to the VPN we install between seed and shoot the shoot networks must be disjunct from the pod/service network of the seed. That means we can't have these static defaults for all shoots. Instead, we should enable the possibility to maintain the defaults on the seed resource itself:

```yaml
apiVersion: garden.sapcloud.io/v1beta1
kind: Seed
...
spec:
  networks: # Seed and Shoot networks must be disjunct
    nodes: 10.240.0.0/16
    pods: 10.241.128.0/17
    services: 10.241.0.0/17
    shootDefaults: # or similar
      pods: 100.96.0.0/11
      services: 100.64.0.0/13
```

The static defaulting [here](https://github.com/gardener/gardener/blob/master/pkg/apis/garden/v1beta1/defaults.go#L40-L43) should be replaced by a dynamic defaulting via admission, preferably the `SeedManager` admission controller takes over.

Reported by @mandelsoft and @MartinWeindel.
