### ISSUE TITLE
shoot's status.observedGeneration not updated (in time)

### ISSUE THREAD

**Issue by cbarbian-sap** [gardener/gardener#8995]
**How to categorize this issue?**

  /area control-plane
/kind bug

**What happened**:
In the past the field `status.observedGeneration` was timely updated by the shoot controller as soon as it recognised a `metadata.generation` update (as it should be the case for any decent K8s controller).
But now (maybe a while ago?) this behaviour changed for some reason. Although the controller sees and processes a new `metadata.generation`, the `status.observedGeneration` stays behind for a long time. It looks like it is getting synchronised only at the end, when all conditions are in a ready state. Until then, it looks as follows:

```yaml
metadata:
  ...
  generation: 3
...
status:
  ...
  lastOperation:
    description: Waiting until all shoot worker nodes have updated the operating system
      config
    lastUpdateTime: "2023-12-30T21:17:11Z"
    progress: 98
    state: Processing
    type: Create
  observedGeneration: 2
```

This is very inconvenient for programmatic observers that want to poll the status of a shoot (because they have to check that the `status.observedGeneration` has been synchronised by the controller).

**What you expected to happen**:

That the observed generation gets updated timely by the controller (i.e. as soon as it sees a new `metadata.generation`, and starts to reconcile it).

**How to reproduce it (as minimally and precisely as possible)**:

Provision a shoot.

**Anything else we need to know?**:

No.

**Environment**:

- Gardener version:  1.71.1
- Kubernetes version (use `kubectl version`): probably not relevant (1.27 in that case)
- Cloud provider or hardware configuration: probably not relevant (AWS in that case)
- Others:
