### ISSUE TITLE
Use dnsmasq to cache Shoot's DNS in the Seed cluster

### ISSUE THREAD

**Issue by mvladev** [gardener/gardener#90]
In our setup end-users should be able to use an extension apiserver, `ExternalAdmissionHookConfiguration`, `ValidatingWebhookConfiguration` ...

Imagine the following configuration that the user adds to it's Shoot cluster via `kubectl`:

```yaml
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ExternalAdmissionHookConfiguration
metadata:
  name: example-config
externalAdmissionHooks:
- name: pod-image.k8s.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Ignore
  clientConfig:
    caBundle: <pem encoded ca cert that signs the server cert used by the webhook>
    service:
      name: foo
      namespace: bar
```

This will fail, because the API server is in the Seed cluster and it'll try to do a call against `https://foo.bar` and when trying to resolve `foo.bar` the Seed's DNS will not find this record.
Even worse - this can be used to call some existing services in the Seed cluster.

# Solution 1

To solve this issue and to smooth Seed -> Shoot NS lookups the following should be added to the Shoot cluster for every Shoot namespace:

- `kube-dnsmasq` pod with `kube-dnsmasq` and `vpn-seed` as containers. `kube-dnsmasq` will be configured with:
    
    ```
    [...]
    --server=/<SHOOT-CLUSTER-DOMAIN>/<SHOOT-KUBE-DNS-SERVICE>-#53
    --server=/<SEED-CLUSTER-DOMAIN>/<SEED-KUBE-DNS-SERVICE>-#53
    [...]
   ```

- Kubernetes service for `kube-dnsmasq` called `kube-dnsmasq` it's ClusterIP we call `<KUBE-DNSMASQ-CLUSTER-IP>`
- `kube-apiserver` should have the following [dns configuration](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods-dns-config) (alpha in 1.9):

    ```yaml
    [....]
    dnsPolicy: "None"
    dnsConfig:
      nameservers:
        - <KUBE-DNSMASQ-CLUSTER-IP>
      searches:
        - kube-system.svc.<SHOOT-CLUSTER-DOMAIN>
        - svc.<SHOOT-CLUSTER-DOMAIN>
        - <SHOOT-CLUSTER-DOMAIN>
        - <SEED-NAMESPACE>.svc.<SEED-CLUSTER-DOMAIN>
      options:
        - name: ndots
          value: "5"
        - name: edns0
    [....]
    ```

This requires 2 things - both Shoot and Seed to have different DNS domains - not `cluster.local`. 

# Solution 2

This also can be simplified by simply putting the `kube-dnsmasq` container in the `kube-apiserver` pod, but if multiple pods in the Seed cluster needs to have the same DNS resolve, then they should add it to theirs as well.
