### ISSUE TITLE
wrong error message for missing min/max count in shoot worker spec

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener#9030]
**How to categorize this issue?**

/area usability
/kind bug

**What happened**:
I was experimenting with programmatic generation of minimal shoot manifests and my manifest
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: my-shoot
  namespace: my-project
spec:
  cloudProfileName: gcp
  kubernetes:
    version: '1.27'
  networking:
    nodes: 10.180.0.0/16
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-b
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.180.0.0/16
    type: gcp
    workers:
    - machine:
        image:
          name: gardenlinux
        type: n1-standard-2
      name: my-worker
      volume:
        size: 50Gi
        type: pd-balanced
      zones:
      - europe-west1-b
  purpose: evaluation
  region: europe-west1
  secretBindingName: my-secret
```
gave me this validation error when trying to apply it:
```
The Shoot "my-shoot" is invalid: spec.provider.workers: Forbidden: at least one active worker pool with allowSystemComponents=true needed
```

Adding
```yaml
allowSystemComponents: true
```
to the worker's spec leads to
```
Shoot in version "v1beta1" cannot be handled as a Shoot: strict decoding error: unknown field "spec.provider.workers[0].allowSystemComponents"
```

I checked an existing shoot and found that the actual syntax looks like this:
```yaml
systemComponents:
  allow: true
```

However, with that added to the worker's spec, I still got the original error message.
I then noticed that my shoot spec was missing the `minimum`, `maximum`, and `maxSurge` fields of the worker spec. With these added, it worked (even without the `systemComponents` part).

**What you expected to happen**:
I would expect the error message to hint to the missing `minimum`, `maximum`, and `maxSurge` fields instead of the `systemComponents` field (which seems to not be a problem if missing).
If the missing `systemComponents` field was a problem, I would expect the error message to use `systemComponents.allow=true` instead of `allowSystemComponents=true`.

**How to reproduce it (as minimally and precisely as possible)**:
Adapt name, namespace, and secret binding name and apply the above manifest.

**Environment**:

- Gardener version: v1.86.0
- Kubernetes version (use `kubectl version`):
  - Client Version: v1.27.3
  - Server Version: v1.26.10
