### ISSUE TITLE
hyperkube download fails for new kubernetes patches ,and older kubernetes versions will fail with new gardener

### ISSUE THREAD

**Issue by lotharbach** [gardener/gardener#9059]
**How to categorize this issue?**

/area delivery
/kind bug

**What happened**:
#8968 changes the default hyperkube image registry to europe-docker.pkg.dev

The last round of kubernetes/hyperkube patches was only uploaded to europe-docker.pkg.dev, so those won't work with gardener 1.86.1 or any older versions that still try to pull from eu.gcr.io

Most older kubernetes/hyperkube versions are not yet uploaded to europe-docker.pkg.dev, so those won't work with main or gardener 1.87.0

**What you expected to happen**:
All still supported kubernetes/hyperkube versions to be available in both registries, or an default imageVector that deals with this temporary dualism and points different versions to different registries.

**How to reproduce it (as minimally and precisely as possible)**:
Add kubernetes 1.28.6 to cloudprofile with gardener 1.86.1

Or

Use kubernetes 1.28.5 in cloudprofile with gardener main (Not tested that myself, but you get the idea)

**Anything else we need to know?**:

**Environment**:

- Gardener version: v1.85.1

**Comment by majst01** [comment]
Can confirm, this prevents us from updating clusters to newer patch version of kubernetes v1.26 and v1.27.

The old hyperkube versions are not populated to the new registry, and the new hyperkube versions are not in the old registry. Modifying the imagevector is not possible in a way to make it work, at least for us.

**Comment by lotharbach** [comment]
This imageVector worked for us but we would of course rather not maintain that. I guess you could do <= as well, but I've not tested that yet.
```
    imageVectorOverwrite: |
      images:
        - name: hyperkube
          sourceRepository: github.com/gardener/hyperkube
          repository: europe-docker.pkg.dev/gardener-project/releases/hyperkube
          targetVersion: "1.28.6"
        - name: hyperkube
          sourceRepository: github.com/gardener/hyperkube
          repository: europe-docker.pkg.dev/gardener-project/releases/hyperkube
          targetVersion: "1.27.10"
        - name: hyperkube
          sourceRepository: github.com/gardener/hyperkube
          repository: europe-docker.pkg.dev/gardener-project/releases/hyperkube
          targetVersion: "1.26.13"
```
