### ISSUE TITLE
Control Plane: Transitions between HA modes not well documented

### ISSUE THREAD

**Issue by mpw96** [gardener/gardener#9356]
Documentation issue at https://pages.github.tools.sap/kubernetes/gardener/docs/guides/high-availability/control-plane/

The page describes "Allowed Transitions" and "Disallowed Transitions". This is not complete. All transitions between the three states `none`, `node`, `zone` should be described as either allowed or disallowed.

The transition from `zone` to `none` is not allowed:

Removing these 4 lines from an existing shoot:
```
  controlPlane:
    highAvailability:
      failureTolerance:
        type: zone
```

results in
```

shoot.core.gardener.cloud "my-test" is invalid: spec.controlPlane.highAvailability.failureTolerance.type: Invalid value: "": field is immutable
```
