### ISSUE TITLE
AWS persistence volume creation for "ReadWriteMany" stays in pending

### ISSUE THREAD

**Issue by gabel** [gardener/gardener#98]
When trying to create the following resource it stays in pending and never finishes. There is no volume created in AWS EC2. As soon as I switch back to "ReadWriteOnce" the creation works like a charm.

Infrastructure: AWS
Region: eu-central-1
Server version: 1.8.5

persistencevolumeclaim.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dynadata
  name: dynadata
spec:
  accessModes:
  # This should be "ReadWriteMany" to bind multiple app pods to it but creation of that type fails in k8s @ AWS
  # Maybe related to https://github.com/terraform-providers/terraform-provider-kubernetes/issues/74
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
status: {}
```
