### ISSUE TITLE
`gardenlet` Self-Upgrades For Unmanaged `Seed`s

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener#9830]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement

**What would you like to be added**:
Let's introduce a new `seedmanagement.gardener.cloud/v1alpha1.Gardenlet` resource whose specification is similar to the `seedmanagement.gardener.cloud/v1alpha1.ManagedSeed` resource:

```yaml
apiVersion: seedmanagement.gardener.cloud/v1alpha1
kind: Gardenlet
metadata:
  name: local
  namespace: garden
spec:
  deployment:
    replicaCount: 1
    revisionHistoryLimit: 2
    helm:
      ociRepository:
        ref: <some-ref-to-the-chart>
  config:
    apiVersion: gardenlet.config.gardener.cloud/v1alpha1
    kind: GardenletConfiguration
    gardenClientConnection:
      kubeconfigSecret:
        name: gardenlet-kubeconfig
        namespace: garden
    controllers:
      shoot:
        reconcileInMaintenanceOnly: true
        respectSyncPeriodOverwrite: true
      shootState:
        concurrentSyncs: 0
    featureGates:
      CoreDNSQueryRewriting: true
      DefaultSeccompProfile: true
      HVPA: true
      HVPAForShootedSeed: true
      IPv6SingleStack: true
      ShootManagedIssuer: true
    etcdConfig:
      featureGates:
        UseEtcdWrapper: true
    logging:
      enabled: true
      vali:
        enabled: true
      shootNodeLogging:
        shootPurposes:
        - infrastructure
        - production
        - development
        - evaluation
    seedConfig:
      apiVersion: core.gardener.cloud/v1beta1
      kind: Seed
      metadata:
        labels:
          base: kind
      spec:
        backup:
          provider: local
          region: local
          secretRef:
            name: backup-local
            namespace: garden
        dns:
          provider:
            secretRef:
              name: internal-domain-internal-local-gardener-cloud
              namespace: garden
            type: local
        ingress:
          controller:
            kind: nginx
          domain: ingress.local.seed.local.gardener.cloud
        networks:
          nodes: 172.18.0.0/16
          pods: 10.1.0.0/16
          services: 10.2.0.0/16
          shootDefaults:
            pods: 10.3.0.0/16
            services: 10.4.0.0/16
        provider:
          region: local
          type: local
          zones:
          - "0"
        settings:
          excessCapacityReservation:
            enabled: false
          scheduling:
            visible: true
          verticalPodAutoscaler:
            enabled: true
```

It allows specifying deployment values (replica count, resource requests, etc.) as well as the `gardenlet`'s component configuration (feature gates, seed spec, etc.). In addition, the `Gardenlet` resource must contain a ref to an OCI registry storing `gardenlet`'s Helm chart. With a new controller part of `gardenlet` which watches such resources, it will be possible to download the Helm chart and apply it with the provided configuration to its own cluster.

This way, it is no longer necessary to manually deploy the Helm chart into unmanaged seed clusters but to only conveniently maintain the respective configuration within the central garden cluster.

> [!NOTE]
> This topic was explored at the [05/2024 Hackathon](https://github.com/gardener-community/hackathon/blob/main/2024-05_Schelklingen/README.md#-gardenlet-self-upgrades-for-unmanaged-seeds).

**Why is this needed**:
In order to keep `gardenlet`s in unmanaged seeds up-to-date (i.e., in seeds which are no shoot clusters, like the "root cluster"), its Helm chart must be regularly deployed to it. This requires network connectivity to such clusters which can be challenging if they reside behind a firewall or in restricted environments. Similar challenges might arise for the to-be-developed [autonomous shoot clusters](https://github.com/gardener/gardener/issues/2906) (see also the [topic summary](https://github.com/gardener-community/hackathon/blob/main/2023-05_Leverkusen/README.md#-bootstrapping-masterful-clusters-aka-autonomous-shoots) from one of the previous Hackathons). It would be much simpler if `gardenlet` could keep itself up-to-date, based on configuration read from the garden cluster.

**Tasks:**

- [x] https://github.com/gardener/gardener/pull/9874
