### ISSUE TITLE
Support for Structured Authentication for `Shoot`s >= Kubernetes v1.30

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/gardener#9858]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
Since Kubernetes 1.30 Structured Authentication has moved to beta. Gardener managed `kube-apiservers` should support this feature. Although for the time being this feature is [limited to 64 authenticators](https://github.com/kubernetes/kubernetes/issues/122809), for most users this is sufficient and an in-tree alternative to https://github.com/gardener/oidc-webhook-authenticator and https://github.com/gardener/gardener-extension-shoot-oidc-service.

I propose that we support this feature for clusters with k8s version >= 1.30.

Please read the [Structured Authentication Blog](https://kubernetes.io/blog/2024/04/25/structured-authentication-moves-to-beta) for more details.

**Why is this needed**:
Support multiple JWT Authenticators without a Gardener extension.

<hr>

- https://github.com/gardener/gardener/pull/10244

**Comment by rfranzke** [comment]
Similar to https://github.com/gardener/gardener/issues/9740

**Comment by dimityrmirchev** [comment]
> Important
> 
> `.spec.virtualCluster.kubernetes.kubeAPIServer.authentication.webhook` should be deprecated and removed in a future.

I think that we should hold of with the deprecation and removal of the authentication webhook support. As of now there is a limit of 64 JWT authenticators in structured authentication. Even if that limitation is removed in the future (which I think is the goal) we cannot be sure if registering hundreds or thousands JWT authenticators will scale well in the `kube-apiserver`. My gut feeling is that this load will be better of being handled by another server. See https://github.com/gardener/gardener/issues/8937 where I also mention a use case for registering shoot clusters as trusted in the Virtual Garden Cluster.

**Comment by rfranzke** [comment]
Deprecating `.spec.virtualCluster.kubernetes.kubeAPIServer.authentication.webhook` is about removing the option to go for only exactly one authn webhook in favor of the new structured authn approach which supports 64 authenticators. It seems I'm missing something - can you explain how this relates? Also, isn't it an option to still use [OWA](https://github.com/gardener/oidc-webhook-authenticator/) with structured authn when one want to go beyond 64 authenticators?

**Comment by dimityrmirchev** [comment]
Structured authentication is about a set of JWT authenticators to replace the current one authenticator that is configured with the `--oidc-*` flags of the `kube-apiserver`. This means that the `kube-apiserver` will fetch the public keys of this set of issuers and then internally check if a given token is signed by one of these issuers. It is still a perfectly valid case to configure an external authentication webhook through the `--authentication-token-webhook-*` flags.

Please, see this [code snippet](https://github.com/kubernetes/kubernetes/blob/5bf1e95541d90e37f6c6637b5b45d8783e7907aa/pkg/kubeapiserver/authenticator/config.go#L156-L185). If the token is not signed by any of these issuers and there is an authentication webhook configured then the `kube-apiserver` will make a [TokenReview](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/) request to that authentication webhook in order to check if that token can be recognized.

> Also, isn't it an option to still use [OWA](https://github.com/gardener/oidc-webhook-authenticator/) with structured authn when one want to go beyond 64 authenticators?

Yes, you can do that, but you cannot configure an external authentication webhook through the structured authentication config file. For that you still need to use the `--authentication-token-webhook-*` flags. Ideally one should use only one of the solutions in order to mitigate the chance for misconfigurations.

**Comment by rfranzke** [comment]
Got it, thanks for the explanation. I indeed missed this part: Structured authn is "just" about JWT auth, but one might still want to have another, maybe generic authn webhook. Will update above description accordingly. :)

**Comment by dimityrmirchev** [comment]
With the introduction of this new authentication configuration mechanism we might consider deprecating `OpenIDConnectPreset` & `ClusterOpenIDConnectPreset`. The latter can still provide benefits when working with multiple projects if redesigned. However, I am not sure if the additional complexity is worth it, since users will be able to define a single (or a few) `StructuredAuthentication` configs and directly refer to them in the shoot spec without messing with multiple configuration values (which is the current state). WDYT?

One more thing to note is that with this proposal implemented, users (both human and technical) with write access for `configmap`s will be able to configure authentication mechanisms for shoots that already reference a certain `configmap`. Previously a user would either need write access for `Shoot` or write access for `OpenIDConnectPreset`/`ClusterOpenIDConnectPreset`.

cc @petersutter @donistz

**Comment by AleksandarSavchev** [comment]
We cannot allow the user to configure `JWTAuthenticator`s fully, since they cannot set the [Issuer](https://github.com/kubernetes/kubernetes/blob/8565e375251450a291f0af3c6195c7a5bf890292/staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1beta1/types.go#L184)'s [CertificateAuthority](https://github.com/kubernetes/kubernetes/blob/8565e375251450a291f0af3c6195c7a5bf890292/staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1beta1/types.go#L222-L227) correctly.
To avoid this problem we can extend the APIs as follows:
``` yaml
kubernetes:
  kubeAPIServer:
    authentication:
      structured:
        configMapName: name-of-configmap-containing-jwt-authenticators
        caBundles:
        - isser: https://issuer1.example.com
          configMapName: name-of-configmap-containing-the-ca-bundle-used-for-discovery
```
The referenced `caBundles.configMapName` configMap will contain the `ca.crt` file
``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: name-of-configmap-containing-the-ca-bundle-used-for-discovery
  namespace: garden-my-project
data:
  ca.crt: <PEM-encoded certificate authority certificates>
 ```
 We would also have an admission webhook to validate the referenced `authentication.structured.configMapName` that it does not have `issuer.certificateAuthority` set.
 `gardenlet` would read all referenced `caBundle` configMaps and create a single new `configMap` (in the shoot namespace in the seed cluster if needed) with all certificates:
``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: name-of-configmap-containing-the-ca-bundle-used-for-discovery
  namespace: garden-my-project
data:
  issuer0.crt: <PEM-encoded certificate authority certificates>
  issuer1.crt: ...
  issuer4.crt: ...
 ```
This new `configMap` will be mounted by the `kube-apiserver` and the `AuthenticationConfiguration` will be set to use the paths to the specific `.crt` files. Both the `caBundles` and `AuthenticationConfiguration` `configMap`s can be created in the `Deploying Kubernetes API server` `gardenlet` step

Another implementation details is about setting `.kubernetes.kubeAPIServer.oidcConfig`. We cannot simply follow the suggested structure:
``` yaml
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
- issuer:
    url: <value of `.kubernetes.kubeAPIServer.oidcConfig.issuerURL`>
    certificateAuthority: <path to file containing value of `.kubernetes.kubeAPIServer.oidcConfig.caBundle`>
  claimMappings:
    username:
      claim: <value of `.kubernetes.kubeAPIServer.oidcConfig.usernameClaim`>
      prefix: <value of `.kubernetes.kubeAPIServer.oidcConfig.usernamePrefix`>
    groups:
      claim: <value of `.kubernetes.kubeAPIServer.oidcConfig.groupsClaim`>
      prefix: <value of `.kubernetes.kubeAPIServer.oidcConfig.groupsPrefix`>
  claimValidationRules: <value of `.kubernetes.kubeAPIServer.oidcConfig.requiredClaims`>
```
Since for the authentication config, there is no defaulting for claim or prefix [ref](https://github.com/kubernetes/kubernetes/blob/a2106b5f73fe9352f7bc0520788855d57fc301e1/staging/src/k8s.io/apiserver/pkg/apis/apiserver/v1alpha1/types.go#L357-L366). The described defaulting in the linked comment can be done by`gardenlet`.

WDYT? cc @rfranzke
