### ISSUE TITLE
Add (Basic Auth) Monitoring URLs to `.monitoring` secret

### ISSUE THREAD

**Issue by petersutter** [gardener/gardener#9867]
**How to categorize this issue?**

/area monitoring
/kind enhancement

**What would you like to be added**:
Currently, the `<shootname>.monitoring` secret contains the basic auth credentials for accessing the monitoring stack.
In addition, it also contains the URL for Plutono.

Current Secret:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    url: https://gu-myproject--myshoot.ingress.myseed.seed.example.com
  labels:
    gardener.cloud/role: monitoring
  name: myshoot.monitoring
  namespace: garden-myproject
stringData:
  auth: admin:{SHA}hash
  password: password
  username: admin
```

- Introduce new annotations to store the Plutono, Prometheus and (optionally) the Alertmanager URLs. Deprecate, but keep for now, the `url` annotation.
- Update the documentation under https://github.com/gardener/gardener/blob/master/docs/usage/logging.md#how-to-access-the-logs and no longer refer to the gardener dashboard.

**Why is this needed**:
End-users can obtain the URLs without requiring access to the gardener dashboard. In addition, these URLs (and credentials) will soon no longer be shown in the dashboard in case the OIDC observability URLs are shown ([ref](https://github.com/gardener/dashboard/issues/1893)).
